### ISSUE TITLE
Agent disconnect, only HP laptops

### ISSUE THREAD

**Issue by cbaptista** [Ylianst/MeshCentral#2326] opened 2021-02-26 13:45 UTC
Hi,
I have a strange problem.
We have a server with about 300 clients without problems.
Now we start adding some HP 640 and HP 650 laptops and the client disconnects after a few seconds, it rarely stays longer than a minute. This problem only happens with HP laptops.
Installation is done with clonezilla, using a standard image for everyone.

Does anyone have suggestions or had an identical problem?

The server version is 0.7.59

Thanks
Carlos Baptista

**Comment by petervanv** [comment] 2021-02-26 15:51
thinking about updating your server to higher version could help probaly. Maybe adding the no agent update in your config, and then try to update 1 or 2 clients with the latest version of the agent in the settings part:     "noagentupdate": true,
restart the server and try again.

**Comment by cbaptista** [comment] 2021-02-26 16:48
Thanks for the reply, but I found the solution. 
I still dont know what happend and why, but if I delete meshagent.db file and restart the service, it seems that everything goes well.
The question is, why only with HP laptops?
Strange... :-P

Thanks
Carlos Baptista

**Comment by Ylianst** [comment] 2021-02-26 19:01
The problem is likely the Clonezilla installation. The MeshAgent generates a certificate which it will use as it's identity. When cloning, now all devices have the same identity and so, the MeshCentral server will think that all your HP laptops are the same computer and only allow 1 connection. When one HP laptop connects, the server will disconnect the previous connection and only one of your laptops will how up on the site.

If you delete the meshagent.db, it forces the MeshAgent to re-generate a new identity and fixes the problem. If you can delete the meshagent.db just before you generate the master image, that will work.

Hope that helps,
Ylian

**Comment by Ylianst** [comment] 2021-03-03 00:39
Going to close this one, but if there is more info. Don't hesitate to report back.

**Closed by Ylianst** 2021-03-03 00:39 UTC
Labels: Fixed - Confirm & Close, question
