### ISSUE TITLE
Malwarebytes flagging as malware ...

### ISSUE THREAD

**Issue by hs6666** [Ylianst/MeshCentral#3537] opened 2022-01-25 16:10 UTC
Hi,

today malwarebytes has started flagging mescentral as malware (happened when i tried to open the desktop on the remote windows 10 pc)

Message came up saying file has been quarantined and message to user forcing them to reboot

when i tried to restore it.... it said i had to reboot first so it could do the quarantine first

anybody else having the same issue?

**Comment by khaosnmt** [comment] 2022-01-25 17:19
Yep. This started happening to me this morning. Connections to the MeshCentral subdomain on my server have been getting blocked by VIPRE as well

**Comment by Ylianst** [comment] 2022-01-25 18:21
Sadly, people use the MeshAgent to do bad things and so, this is what happens. Nothing much I can do except to put exceptions.

**Comment by openncomp** [comment] 2022-01-25 19:19
About the same thing used to happen with VNC, TeamViewer, etc.
But with the growth of popularity, this software has moved from the category of malware to the category of remote control software.
I think the same thing should happen with MeshCentral over time.
Perhaps there is a way to digitally sign, can we raise community funds for this?

**Comment by JSuenram** [comment] 2022-01-25 19:40
> About the same thing used to happen with VNC, TeamViewer, etc.
> But with the growth of popularity, this software has moved from the category of malware to the category of remote control software.
> I think the same thing should happen with MeshCentral over time.
> Perhaps there is a way to digitally sign, can we raise community funds for this?

You can sign with your own public cert. It is not "that" expensive and get your reputation for your personalized Agent/Client save. Not sure if signing directly here is a good idea as people can still do bad things with this public versions....

**Comment by openncomp** [comment] 2022-01-25 19:44
> You can sign with your own public cert. It is not "that" expensive and get your reputation for your personalized Agent/Client save. Not sure if signing directly here is a good idea as people can still do bad things with this public versions....

Oh, thank you, I will have to study this question in more detail.

**Comment by JSuenram** [comment] 2022-01-25 19:46
> > You can sign with your own public cert. It is not "that" expensive and get your reputation for your personalized Agent/Client save. Not sure if signing directly here is a good idea as people can still do bad things with this public versions....
> 
> Oh, thank you, I will have to study this question in more detail.

This thread might be of some help.... https://github.com/Ylianst/MeshCentral/issues/2947

**Comment by JSuenram** [comment] 2022-01-25 19:49
> Yep. This started happening to me this morning. Connections to the MeshCentral subdomain on my server have been getting blocked by VIPRE as well

Even if it is a bit more work than should be necessary, most AV vendors allow to report "false positives" or have possibility to report correct "reputation".

**Comment by krayon007** [comment] 2022-01-25 20:58
We used to sign the agent binary, but one time one of the av vendors had our signing cert revoked because their automated servers reported that we used our signing cert to sign malware.

**Comment by hs6666** [comment] 2022-01-26 10:24
I think unfortunantly it's only a question of time before other av progs also start flagging meshcentral as "riskware"

In prep I'm already adding c:\program files\mesh agent\ folder to each clients av config.... windows defender should be easier via a quick batch file to add the exclusion via registry :)

**Comment by JSuenram** [comment] 2022-01-26 20:33
Maybe in the MeshCentral-Setup-Guide there should be a hint, that because of the nature of the Software/Agent Malware-flagging might be possible. And recommend to exclude installation-folder from realtime and on demand scanners but also make sure to only use validated and secured versions of Agent/Software....

**Comment by catalinchertes** [comment] 2022-01-27 15:29
Antivirus detects meshagent as Trj/GdSda.A, is there something to worry about here guys??

**Comment by JSuenram** [comment] 2022-01-27 15:35
> Antivirus detects meshagent as Trj/GdSda.A, is there something to worry about here guys??

You can always check against up to 50 AVs with https://www.virustotal.com
But there is no Malware-Code in MeshCentral-Source that I am aware of. But it is a Remote-Control-Software which is open source, so anyone can fork and make some not so funny "shit" with it. That's why keep your Agent with your own Config and Filenames and Signing as secured and uncommon as possible.

Maybe if more users start using MC the more the Autobots for detecting Malware will treat it comparable to AnyDesk, TeamViewer etc etc....

**Comment by catalinchertes** [comment] 2022-01-27 15:41
Damn... knowing this makes me think twice about using mesh... if anyone can just fork whatever they want, there must be some kind of control, no? I had this deployed and after updating the version my antivirus started detecting a lot of windows machines as malware (trojans) so Im rather concerned here...

**Comment by JSuenram** [comment] 2022-01-27 15:50
> 

I just started reporting False Positive to the current detecting AV-Vendors.
I told them something like, if you detect this as Malware or PUA, please also do it vor TeamViewer, AnyDesk, etc etc or let all of them including MeshCentral alone. I am excited what will come back if ever.....

![image](https://user-images.githubusercontent.com/68963439/151393710-1757e7a0-cef0-486d-b989-7680a582c226.png)

**Comment by krayon007** [comment] 2022-01-27 16:40
> Damn... knowing this makes me think twice about using mesh... if anyone can just fork whatever they want, there must be some kind of control, no? I had this deployed and after updating the version my antivirus started detecting a lot of windows machines as malware (trojans) so Im rather concerned here...

Anyone can "fork" it, but they wouldn't be able to deploy it your systems. The server checks the hash of each agent that connects to it. They would have to control your server to be able to control the deployed agents.  Someone with sufficient permissions to change the agent, would have sufficient permissions to cause you other/bigger worries on your systems.

**Comment by krayon007** [comment] 2022-01-27 16:42
On a side note, I have a few ideas to try and see what/how the AV detects the agent as a threat... I'll take a look at that after I free up some cycles...

**Comment by FrankSanabria** [comment] 2022-01-28 02:53
Same error here, Panda detect a Trojan Trj/GdSda.A

**Comment by LPJon** [comment] 2022-01-28 05:41
I have not had this issue yet but I have custom named my agents. Simply meshagent is easily identified by antivirus software and generic because it's default. The other thing I do is install the certificates from the installer into each windows machine's certificate store. I have seen some make comments about teamviewer and such. That is one company and one software. This software can be deployed many times and by anyone who wants to. That makes MeshCentral "different" to the antivirus companies. Even signed agents would not change this fact and would most likely only get you past windows smart screen. The best way to handle this is to manage your clients antivirus/malware software. We generally white list the agent directory in those softwares.

I will say that it is quite a process to have a general customer requesting remote assistance install the agent on their machine sometimes. I wish that process could be simpler but that is the nature of open source software like MeshCentral because anyone can use it and anyone can do bad things with it if they want to.

**Comment by JSuenram** [comment] 2022-01-28 10:50
> Hi,
> 
> today malwarebytes has started flagging mescentral as malware (happened when i tried to open the desktop on the remote windows 10 pc)
> 
> Message came up saying file has been quarantined and message to user forcing them to reboot
> 
> when i tried to restore it.... it said i had to reboot first so it could do the quarantine first
> 
> anybody else having the same issue?

From Malwarebytes-Support:
I couldn't reproduce the detection, do you have a detection name or detection report available?

**Comment by robina80** [comment] 2022-02-01 19:18
Sophos central also detecting it as a virus and it cleans it up straight away ie deletes the exe

**Comment by hs6666** [comment] 2022-02-01 19:44
> Sophos central also detecting it as a virus and it cleans it up straight away ie deletes the exe

... easy thing about sophos is the central web console, makes it a lot easier to login to the web console and remove it from quarantine and whitelist it :)

interestingly i tried adding the agent today to a brand new install of windows 10... a message popped up saying it was examining it during install .... but it then let it install ok

**Comment by FrankSanabria** [comment] 2022-02-02 13:54
> > Antivirus detects meshagent as Trj/GdSda.A, is there something to worry about here guys??
> 
> You can always check against up to 50 AVs with https://www.virustotal.com (https://www.virustotal.com/gui/file/f2bc88a1627903900264786ee945594304fe23de2734e77696bb231ca6db3623?nocache=1) But there is no Malware-Code in MeshCentral-Source that I am aware of. But it is a Remote-Control-Software which is open source, so anyone can fork and make some not so funny "shit" with it. That's why keep your Agent with your own Config and Filenames and Signing as secured and uncommon as possible.
> 
> Maybe if more users start using MC the more the Autobots for detecting Malware will treat it comparable to AnyDesk, TeamViewer etc etc....

Review this, into analisys result, can view: https://pentestlaboratories.com/2021/12/08/process-ghosting/

**Comment by FrankSanabria** [comment] 2022-02-02 13:55
title: Stop Windows Service
id: eb87818d-db5d-49cc-a987-d5da331fbd90
description: Detects a windows service to be stopped
status: experimental
author: Jakob Weinzettl, oscd.community
date: 2019/10/23
modified: 2021/11/30
tags:
    - attack.impact
    - attack.t1489
logsource:
    category: process_creation
    product: windows
detection:
    selection:
        Image|endswith:
            - '\sc.exe'
            - '\net.exe'
            - '\net1.exe'
        CommandLine|contains: 'stop'
    filter:
        CommandLine: 'sc  stop KSCWebConsoleMessageQueue' # kaspersky Security Center Web Console double space between sc and stop
        User|startswith: 
            - 'NT AUTHORITY\SYSTEM'
            - 'AUTORITE NT\Sys' # French language settings
    condition: selection and not filter
fields:
    - ComputerName
    - User
    - CommandLine
falsepositives:
    - Administrator shutting down the service due to upgrade or removal purposes
level: low

**Comment by JSuenram** [comment] 2022-02-02 14:13
> title: Stop Windows Service
> id: eb87818d-db5d-49cc-a987-d5da331fbd90
> description: Detects a windows service to be stopped
> status: experimental
> author: Jakob Weinzettl, oscd.community
> date: 2019/10/23
> modified: 2021/11/30
> tags:
> - attack.impact
> - attack.t1489
> logsource:
> category: process_creation
> product: windows
> detection:
> selection:
> Image|endswith:
> - '\sc.exe'
> - '\net.exe'
> - '\net1.exe'
> CommandLine|contains: 'stop'
> filter:
> CommandLine: 'sc stop KSCWebConsoleMessageQueue' # kaspersky Security Center Web Console double space between sc and stop
> User|startswith:
> - 'NT AUTHORITY\SYSTEM'
> - 'AUTORITE NT\Sys' # French language settings
> condition: selection and not filter
> fields:
> - ComputerName
> - User
> - CommandLine
> falsepositives:
> - Administrator shutting down the service due to upgrade or removal purposes
> level: low

And?

**Comment by FrankSanabria** [comment] 2022-02-02 16:22
> And? Any suggestions or what should this report say?

Maybe is a false positive for error on meshagent code (maybe, i don't know the meshagent code), in special this lines:

1. 'AUTORITE NT\Sys' # French language settings
2. CommandLine: 'sc stop KSCWebConsoleMessageQueue' # kaspersky Security Center Web Console double space between sc and stop

Where?, I don't know

**Comment by dinger1986** [comment] 2023-11-13 00:12
@si458 can close

**Comment by si458** [comment] 2023-11-13 00:18
closing as agreed, all AV ones will point to a discussion going forward, me thinks

**Closed by si458** 2023-11-13 00:18 UTC
Labels: question, Fixed - Please Verify & Close
