### ISSUE TITLE
SmartScreen of Windows Defender 

### ISSUE THREAD

**Issue by sdlopexvidri** [Ylianst/MeshCentral#294] opened 2019-06-10 16:14 UTC
Hi, I noticed one litle detail on windows 10, when I install or reinstall our enterprise application, Windows 10 activate SmartScreen and lock the screen, so Meshcentral can't see the smartscreen advertisin and I can't click on install button even not show this one, and if I reconect to desktop get a black screen.

**Comment by Ylianst** [comment] 2019-06-11 17:11
Please send a screen shot of the problem. If the meshagent.exe is signed with a revoked certificate, update your MeshCentral server. It will update all the agents to a self-signed executable.

**Comment by sdlopexvidri** [comment] 2019-06-12 13:53
Ok, I'm going to check the certificate

**Comment by Ylianst** [comment] 2019-06-13 07:10
FYI. Just published MeshCentral v0.3.6-m with a new 32bit MeshAgent that passes all virustotal.com tests. So now, both 32bit and 64bit MeshCentral agents should not have a problem anymore.

This is probably a duplicate of #279. In any case, I will close it since I am sure after this server update, everything should be fine. Feel free to re-open if needed.

**Closed by Ylianst** 2019-06-13 07:10 UTC

**Comment by sdlopexvidri** [comment] 2019-06-13 13:46
Thanks alot for, your Support Ylianst
