### ISSUE TITLE
groups and devices disappeared after upgrade to 1.35 

### ISSUE THREAD

**Issue by arditm** [Ylianst/MeshCentral#6593] opened 2024-12-08 23:51 UTC
**Describe the bug**
Hi, 
After updating to 1.35 from 1.33 I am able to login with ldap credentials but I don't have access to all my existing groups devices etc. I promoted my user to Admin through node node_modules/meshcentral --adminaccount user\\ldapuserid ,but nothing changed. In the login page it appeared the "create user account" which was not there before, and no other users are available on the users/ groups list.

**To Reproduce**
1. Update from 1.33 to 1.35 via web browser interface
2. Login with ldap credentials. 
3. Open groups or my devices. 
5. No groups and devices available.

**Expected behavior**
Expect to see all my groups, devices and users.

**Screenshots**
![image](https://github.com/user-attachments/assets/d25a32ee-733f-4b3a-ba20-8869e019f6cc)

**Server Software (please complete the following information):**
 - OS: Debian GNU/Linux 11 (bullseye) Release: 11 / bullseye
 - Virtualization: LXC
 - Network: LAN/WAN, reverse proxy Nginx proxy manager]
 - Version: 1.0.35
 - Node: node -v     v16.20.2

**Your config.json file**
 cat config.json
```
{
        "$schema": "https://raw.githubusercontent.com/Ylianst/MeshCentral/master/meshcentral-config-schema.json",
        "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
        "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
        "settings": {
                "postgres": {
                        "user": "user",
                        "password": "password",
                        "port": "5432",
                        "host": "172.29.2.11"
                },
                "Cert": "my.domain.net",
                "_WANonly": true,
                "_LANonly": true,
                "WebRTC": true,
                "_sessionKey": "MyReallySecretPassword1",
                "cookieIpCheck": false,
                "tlsOffload": "172.29.3.228, 127.0.0.1 ",
                "_trustedProxy": "172.29.3.228, 127.0.0.1, ::1",
                "port": 444,
                "aliasPort": 443,
                "redirPort": 800,
                "RelayPort": 453,
                "AgentPing": 120,
                "agentpong": 55,
                "BrowserPing": 50,
                "BrowserPong": 50,
                "MpsPort": 44330,
                "MpsAliasPort": 4433,
                "MpsTlsOffload": false,
                "_redirAliasPort": 80
        },
        "domains": {
                "": {
                        "auth": "ldap",
                        "ldapOptions": {
                                "url": "ldap://172.29.2.59/",
                                "bindDN": "CN=ldap,OU=Service_Accounts,DC=domain,DC=net",
                                "bindCredentials": "password",
                                "searchBase": "DC=domain,DC=net",
                                "searchFilter": "(&(objectclass=user)(mail={{username}}))",
                                "reconnect": "true",
                                "nightMode": 1,
                                "hide": 5
                        },
                        "ldapUserBinaryKey": "objectSid",
                        "ldapUserName": "{{{mail}}} {{{sn}}}",
                        "ldapUserMail": "mail",
                        "_ldapUserRealName": "name",
                        "ldapUserPhoneNumber": "telephoneNumber",
                        "_ldapUserImage": "thumbnailPhoto",
                        "_siteStyle": 2,
                        "title": "Domain Remote Access",
                        "title2": "Spaghetti da PINO",
                        "_loginPicture": "logo2.png",
                        "_titlePicture": "logo2.png",
                        "_minify": true,
                        "_newAccounts": true,
                        "_userNameIsEmail": true,
                        "certUrl": "https://my.domain.net:443/"
                }
        },
        "_letsencrypt": {
                "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
                "email": "myemail@mydomain.com",
                "names": "myserver.mydomain.com",
                "production": false
        }
}
```

**Comment by si458** [comment] 2024-12-09 00:00
If u see the `create a user account` on the login page, then this generally means the is no admin account
I noticed your config.json is setup with postgres
Have you checked your postgres database and checked the is data inside the meshcentral database?

**Comment by arditm** [comment] 2024-12-09 00:10
![image](https://github.com/user-attachments/assets/c4ba157d-2d4c-4f80-ae46-6b430411978c)

**Comment by si458** [comment] 2024-12-09 07:50
Ok so the is data there, how do u run/start meshcentral? What's the command? Have u checked its output?

**Comment by arditm** [comment] 2024-12-09 09:55
it runs as a service. When running it in debug mode with node node_modules/meshcentral --debug > meshcentral-debug.log 2>&1
[meshcentral-debug.log](https://github.com/user-attachments/files/18059548/meshcentral-debug.log)

**Comment by si458** [comment] 2024-12-09 10:18
something is wrong with your setup/install
`AGENT: Agent connected with invalid domain/mesh, holding connection (172.29.0.90:55446, mesh//cFfuOaI5T92dUGZ7aVSpKwxYaV@mM0Z79h3$LVgUnbR4I1HP73rR7g1OEdqIds03).`
its like meshcentral has completely lost all its groups etc,
are you sure your config.json is setup to talk to the correct postgres database?
have you deleted the groups by mistake maybe?
if you email myself i can connect into ur environment and help u out if needs be

**Comment by arditm** [comment] 2024-12-09 12:04
Not really a bug, though a very unsuspicious feature :) . Thank you very much for your help  @si458 

**it's necessary to explicitly specify the database name in config.json**
"settings": {
              "postgres": {
                        "user": "user",
                        "password": "password",
                        **"database" : "meshcentral",**
                        "port": "5432",
                        "host": "ip.address"
                },

**Comment by si458** [comment] 2024-12-09 12:04
this is a duplicate of this issue https://github.com/Ylianst/MeshCentral/issues/6574
the problem is due to an improvement we made to autobackups,
but in the process broke the default database name for postgres!
so it thinks the default database name for postgres if you dont specify one is actually the same as your username
so to fix the issue you MUST specify a database name if you havent specifed one!
```
"postgres": {
  "host": "127.0.0.1",
  "user": "username",
  "database": "meshcentral",
  "port": 5432,
  "password": "password"
}
```

**Closed by si458** 2024-12-09 12:04 UTC
Labels: bug
