### ISSUE TITLE
Agent install on CENTOS 6

### ISSUE THREAD

**Issue by rightvision** [Ylianst/MeshCentral#121] opened 2019-03-09 15:09 UTC
Tried to install agent in CENTOS 6

meshagent startup does not go to /etc/rc.d/init.d
copied manualy, but meshagent startup-script points to /usr/local/mesh_services/meshagent/meshagent 

WRONG 
SCRIPT=/usr/local/mesh_services/meshagent/meshagent
RIGHT 
SCRIPT=/usr/local/mesh/meshagent

**Comment by Ylianst** [comment] 2019-03-09 20:17
You right, Bryan confirmed that is a problem. Fix is in the next version.

**Comment by Ylianst** [comment] 2019-03-09 22:30
Published MeshCentral v0.3.0-a with this fix.

**Comment by rightvision** [comment] 2019-03-11 14:30
Still during install
meshagent: unrecognized service
meshagent installed as upstart/init.d service.

there's no startscript in /etc/init.d

**Comment by krayon007** [comment] 2019-03-11 14:50
Upstsrt services are installed and /etc/init

So it should be at /etc/init/meshagent.conf
It could be that your platform was detected as upstart when it isn't. I tested with CentOS 7 and 9 but not 6. I can setup a CentOS 6 image and see...

**Comment by krayon007** [comment] 2019-03-11 20:31
Ok, I just tested with CentOS 6. It actually works fine, it because service wasn't mapped to initctl on CentOS 6..

So to start/stop the service on CentOS 6, use the command:

initctl start meshagent
initctl stop meshagent

I'll have Ylian update the script, so the directions reference initctl instead of service on upstart platforms.

**Comment by rightvision** [comment] 2019-03-12 17:44
great - will check when new version is there.

Another small issue - we do not run graphical interface on the LINUX servers. Connect terminal is fine, but does not echo the prompt - so only output is visible.

**Comment by krayon007** [comment] 2019-03-14 17:03
@rightvision, what distro are you using for your Linux server? I'll see if I can reproduce the terminal issue you are seeing, and if I can I'll see if I can fix it.

**Comment by rightvision** [comment] 2019-03-15 08:23
This is still the CENTOS 6 and also tested now with CENTOS 7. When connecting, there's shortly some screen, but it disappears immediatly and then just the output of the commands is displayed.

**Comment by TitovLab** [comment] 2019-04-08 17:23
Replacement of two lines in MeshCentral v0.3.1-y in the meshcentral/agents/meshinstall-linux.sh file solved the problem with the fact that in CentOS 6 the agent did not start after installation.
Then, just in case, I checked the script on CentOS 7 - it also works, it does not affect this change, because there is a systemd. For convenience, in the attachment patch.
[meshinstall-linux.sh.txt](https://github.com/Ylianst/MeshCentral/files/3055557/meshinstall-linux.sh.txt)
Thank you!

**Comment by Ylianst** [comment] 2019-05-09 21:46
This fix to "meshinstall-linux.sh" was applied to the latest versions of MeshCentral and should work. I will close this issue but feel free to re-open if needed.

**Closed by Ylianst** 2019-05-09 21:46 UTC

**Comment by rightvision** [comment] 2019-05-10 14:26
Output of the console shortly comes up - but then disapears.
