### ISSUE TITLE
MeshCentral does not start after Update

### ISSUE THREAD

**Issue by rightvision** [Ylianst/MeshCentral#407] opened 2019-08-07 11:33 UTC
Latest version installed from GUI - server did not restart
npm update meshcentral from CLI

node /data/meshcentral/node_modules/meshcentral/
Installing cbor...
ERROR: Unable to install required module "cbor". MeshCentral may not have access to npm, or npm may not have suffisent rights to load the new module. Try "npm install cbor" to manualy install this module.

npm install cbor worked fine, but during start the "Installing cbor..." message and error comes again.

**Comment by Ylianst** [comment] 2019-08-07 17:35
This is weird. Can you run your command shell "as administrator" and try again?

**Comment by pananix** [comment] 2019-08-07 17:53
I believe this may be what's going on (tried as a regular user and root):

-------- 8/7/2019, 12:49:48 PM ---- 0.3.9-h --------

/home/dab11/MeshCentral/node_modules/cbor/lib/utils.js:21
const td = new TD('utf8', {fatal: true, ignoreBOM: true})
           ^

TypeError: TD is not a constructor
    at Object.<anonymous> (/home/dab11/MeshCentral/node_modules/cbor/lib/utils.js:21:12)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/dab11/MeshCentral/node_modules/cbor/lib/commented.js:5:15)
    at Module._compile (module.js:577:32)

**Comment by Ylianst** [comment] 2019-08-07 18:13
What version of node are you using? Type "node -v". Hopefully I can make this happen too.

**Comment by rightvision** [comment] 2019-08-07 19:41
node v6.17.1, running on CentOS 7 as root.

**Comment by pananix** [comment] 2019-08-07 20:26
v6.17.1 on RHEL7.7

**Comment by Ylianst** [comment] 2019-08-07 21:04
Both node 6, I do all my development on Node 6.0.0. I will update and check...

**Comment by Ylianst** [comment] 2019-08-07 21:16
Ok, I just checked and "cbor" no longer supports Node 6.x. [I filed an issue](https://github.com/hildjj/node-cbor/issues/94). I am going to fix the MeshCentral package.json to not load the latest "cbor" and find a work around.

**Comment by pananix** [comment] 2019-08-07 21:20
Unfortunately, my $DAYJOB is a RedHat shop.  I can run meshcentral on my Ubuntu workstation (node v8.10.0)

**Comment by Ylianst** [comment] 2019-08-07 21:26
Published MeshCentral v0.3.9-j with a fix for this. cbor 4.1.5 will now be used.

**Comment by pananix** [comment] 2019-08-07 21:34
that works -- thanx for the quick response (and the great software)

**Comment by Ylianst** [comment] 2019-08-07 22:44
Perfect. Much appreciated. We are two on it full time, many more features to come. Thank you for posting and reporting issues, it helps a lot.

**Closed** 2019-08-07 22:44 UTC
Labels: Fixed - Please Confirm, bug

**Comment by rightvision** [comment] 2019-08-07 23:33
yes - works - thank you for the quick respnse

**Comment by hildjj** [comment] 2021-01-04 21:30
WARNING @Ylianst: the cbor package is about to deprecate support for Node 6 and Node 8.  Please pin to version 5.2; I'll do sec fixes there if absolutely necessary, but nothing else.  Since the `engines` entry in package.json didn't work the last time I did this, I'm taking aggressive measures to make sure that cbor v6+ fails quickly at install time on old Node versions, to prevent a regression for you.  See https://github.com/hildjj/node-cbor/pull/124/files#diff-c58a3e2ae73b57ad2cda290bf6508b39bfcc54d031e8d71e360f1a5367ce28ed

I'll wait a few days to hear from you before I merge that pull request.

**Comment by Ylianst** [comment] 2021-01-04 23:07
@hildjj Thanks. Check into GitHub cbor pinning to `cbor@~5.2.0`. It will be published later today or tomorrow.
