### ISSUE TITLE
No Desktop Display, Meshcentral 0.4.5-u

### ISSUE THREAD

**Issue by routerino** [Ylianst/MeshCentral#733] opened 2019-12-14 12:52 UTC
Hi,

I have just updated to 0.4.5-u (the system I use auto updates, which in hindsight is a terrible idea and will be turned off). Host OS is alpine linux via docker, which I have also destroyed and recreated from scratch to see if it fixed the problem (no go).

All clients seem to connect, and the terminal section of the client seems to work. However, the desktop display does not work. For linux clients, it will "connect" (IE: You hit the connect button, it then appears to be connected with the disconnect option) but only shows a black screen. Windows clients won't even connect, hitting the connect button seems to do nothing.

I have tried both firefox and chrome, and tried both through traefik proxy and without traefik proxy.

Other features (online activity, status display, etc.) seem unaffected.

**Comment by asasin114** [comment] 2019-12-14 15:13
Same issue with my Windows install. I don't have any error logs on my system pointing to a particular issue. Windows devices will not allow me to connect at all and Linux devices act as if they connect but I get no screen feedback. I am able to access the terminal on Windows and Linux systems and can also access the Files but that's it.

**Comment by Barborica-Alexandru** [comment] 2019-12-14 16:07
Same issue linux install. No errors no issues other than Desktop.

**Comment by krayon007** [comment] 2019-12-14 16:29
Interesting about the linux issue, as the last several server versions do not include linux updates. For the windows users, what version of Windows are you running? Do you have multiple users logged in? I know Ylian was working on UI changes for for Windows KVM around that, but I'm not sure if that's part of this server update.

**Comment by Barborica-Alexandru** [comment] 2019-12-14 16:36
Interestingly it works in the Desktops display mode. So the issue isn't anywhere in the backed I believe. Its just the actual webpage that is broken.

**Comment by krayon007** [comment] 2019-12-14 16:37
What distro of linux are you guys running? I just quickly tested on Ubuntu 14, 18, and Fedora 29, and it seems to work fine... By any chance are you machines joined to an active directory domain?

**Comment by asasin114** [comment] 2019-12-14 17:38
I'm running on Server 2019

**Comment by Ylianst** [comment] 2019-12-14 19:34
Ok, pulled MeshCentral 0.4.5-u for further testing. The web application clearly has a problem.

**Comment by asasin114** [comment] 2019-12-14 19:39
Switched to 0.4.5-q and everything is working again. Thank you!

**Comment by asasin114** [comment] 2019-12-14 19:40
> What distro of linux are you guys running? I just quickly tested on Ubuntu 14, 18, and Fedora 29, and it seems to work fine... By any chance are you machines joined to an active directory domain?

No AD here at this point.

**Comment by Barborica-Alexandru** [comment] 2019-12-14 19:48
I am confirming that the update seems to have fixed the problem.

**Comment by routerino** [comment] 2019-12-14 20:46
I can also confirm, issue appears to be resolved now by reverting.

**Comment by Ylianst** [comment] 2019-12-16 19:26
Just published MeshCentral v0.4.5-v with fixes for this. Hopefully it will works for everyone.

**Comment by asasin114** [comment] 2019-12-16 22:44
> Just published MeshCentral v0.4.5-v with fixes for this. Hopefully it will works for everyone.

Can confirm this is working now!

**Comment by Ylianst** [comment] 2019-12-16 23:08
Perfect, thanks for confirming. I can't possibly test all cases, so it's nice to get feedback.

**Comment by asasin114** [comment] 2019-12-17 04:10
> Perfect, thanks for confirming. I can't possibly test all cases, so it's nice to get feedback.

Thank you for your continued efforts on this project! It has been an amazing project to work with!

**Comment by Ylianst** [comment] 2019-12-17 18:48
Thanks. Closing this issue since I am pretty sure it's fixed. Please open a new issue if needed.

**Closed by Ylianst** 2019-12-17 18:48 UTC
Labels: Fixed - Please Confirm, bug
