### ISSUE TITLE
Regular MeshCentral Users can´t use RDP option via MeshCentral Router

### ISSUE THREAD

**Issue by mcallisaya79** [Ylianst/MeshCentral#6375] opened 2024-09-11 16:46 UTC
**Describe the bug**
• Regular MeshCentral Users can´t use RDP option via MeshCentral Router
• Admin users have no problems and works fine.

**To Reproduce**
1. Open MCRouter
2. Login 
3. Select a device, right click, chose RDP...
4. Nothing happens

**Expected behavior**
It should open Microsoft Remote Desktop Windows

**Screenshots**

**Server Software (please complete the following information):**
 - OS: Ubuntu
 - Virtualization: n/a
 - Network: LAN/WAN
 - Version: 1.1.29

**Client Device (please complete the following information):**
 - Device: Workstations
 - OS: Windows
 - Network: Remote over WAN
 - Browser: n/a
 - MeshCentralRouter Version: 1.8.8680

**Remote Device (please complete the following information):**
 - Device: workstations
 - OS: Windows 11 21H2
 - Network: Remote over WAN]
 - Current Core Version (if known): Dec 9 2022, 300248521

**Additional context**
No issues with previous server version

Debug file:
ExceptionSink: System.NullReferenceException: Object reference not set to an instance of an object.
   at MeshCentralRouter.MainForm.QuickMap(Int32 protocol, Int32 port, Int32 appId, NodeClass node)
   at MeshCentralRouter.MainForm.rdpToolStripMenuItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by si458** [comment] 2024-09-11 17:03
Have u downloaded the latest version from the website?
If it asks to update after u login say no.

**Comment by mcallisaya79** [comment] 2024-09-11 17:06
Yes I tried different versions, same result: nothing happens when RDP option is used for regular MeshCentral user,  with MeshCentral Administrator user, all works fine Microsoft RDP opens and connects fine.

**Comment by si458** [comment] 2024-09-11 17:09
Can u clarify what a regular user is?
What permissions do the user have?
Do they have access to only some devuce or some groups?
What are the permissions of the devices/groups?

**Comment by rodrigo-hissam** [comment] 2024-09-11 17:16
I am seeing the same issue in my install. For me any non meshcentral administrator user account cant use the quickmap RDP mapping on meshrouter.

**Comment by mcallisaya79** [comment] 2024-09-11 17:18
For our MeshCentral we have ADministrator accounts (those who handle all the server setup/configuration), those have full admin rights.  Those accounts can login and use Microsoft RDP without problems.

User accounts, are regular accounts we opened to access specific devices or groups of devices (depending of each situation), but those were working fine before the last update.   Nothing specific on groups, no special permission were set for any group/user, we just have regular users (standard access) and Administrator accounts (full privileges)

**Comment by si458** [comment] 2024-09-11 17:21
Can u please share screenshots of a users permissions tho?
Also what permissions a device or group the user has

**Comment by mcallisaya79** [comment] 2024-09-11 17:45
![image](https://github.com/user-attachments/assets/49ea914e-19b9-4a4a-92f1-e473de3fad9d)

![image](https://github.com/user-attachments/assets/1988b3df-91fd-4d3e-87bc-808211e72a79)

**Comment by mcallisaya79** [comment] 2024-09-11 17:54
![image](https://github.com/user-attachments/assets/ccc9525b-d90a-4ffc-91af-4bbb43025060)

![image](https://github.com/user-attachments/assets/e45f9170-849e-4db7-b157-712bd1fc6203)
![image](https://github.com/user-attachments/assets/5c1fd485-1be2-4e20-8ae2-e1e2d21a41ad)
![image](https://github.com/user-attachments/assets/de1b06fd-6887-47d2-b96d-b3a8de171d48)

We have all our regular standard users with the same issue, not only this one.  This is just an example (we have several users) dealing with this issue, all the users are set with no server rights.  As mentioned above this was not happening before the update.

**Comment by mcallisaya79** [comment] 2024-09-11 18:03
![image](https://github.com/user-attachments/assets/9bbf5695-b834-456a-8dbe-6e9c41ba973e)

FYI This is where all stuck, no action, nothing happens.   With an Administrator user, all works fine and Microsoft RDP windows opens as it should be.

**Comment by si458** [comment] 2024-09-11 18:34
OK I will try have a look tomorrow as we didn't change anything that I'm aware?

You should always make sure `selfUpdate: false` to stop ur meshcentral auto upgrading itself

**Comment by si458** [comment] 2024-09-12 14:59
right so the issue is to do with meshcentralrouter itself!
if you click the RDP option in the web ui and let it open up meshcentralrouter it works no problem

**Comment by si458** [comment] 2024-09-12 16:03
linking issue in meshcentralrepo https://github.com/Ylianst/MeshCentralRouter/issues/100
will close this issue, 
please follow in the other repo

**Closed by si458** 2024-09-12 16:03 UTC
Labels: bug
