### ISSUE TITLE
Created a user to only access one device, keyboard typing not working

### ISSUE THREAD

**Issue by formanjackj** [Ylianst/MeshCentral#2001] opened 2020-11-19 01:08 UTC
Possibly a bug or I'm doing it wrong. 
I created a user to access only their own computer and the network. Only gave them access to remote control, wake, and chat.

The user can see one computer and can connect to it.
The user can also remotely use the mouse, click on objects and icons, and move them around the screen.
However, that can not type any text keyboard, no text is passed to the remote computer. however, I can type on the physical keyboard.

If I change the user to have access to the full realm through a common device group, with permissions set to remote control, wake device, and chat & notify.
Then they can connect to the device and control it and type text.

**Comment by Ylianst** [comment] 2020-11-19 01:13
Is the remote computer Windows and what version of the server are you using? Note that starting with MeshCentral v0.6.93 with have changed how the keyboard works to support international key mappings. So if you update the server, agents also need to be updated to work with the new keyboard system.

**Comment by Ylianst** [comment] 2020-11-19 04:52
Not that MeshAgent will auto-update when you update the server. However if you are using a custom agent that you compiled yourself, you need a new version. Bryan just tested key input on Windows 7 and Windows 10 and it worked, so any more data on what OS you have would be appreciated. Thanks.

**Comment by Ylianst** [comment] 2020-11-19 18:41
I am working on a new setting to disable the international keyboard support. That way, I will give everyone a workaround until we root cause the problem. I will have a new version shortly.

**Comment by Ylianst** [comment] 2020-11-19 19:08
Just published MeshCentral v0.6.96 with a new option to work around this problem. If you can take a look at #2002, we are trying to root cause the problem.

![image](https://user-images.githubusercontent.com/1319013/99712074-6a5e0500-2a57-11eb-8e0a-c4424b67ae4e.png)

**Comment by Ylianst** [comment] 2020-11-19 20:19
Just published MeshCentral v0.6.97 with a keyboard fix. You would not see any keys when you have this option turned on in config.json:

```
"DesktopMultiplex": true
```

Should work perfectly with v0.6.97. Let me know if it works.

**Comment by Ylianst** [comment] 2020-11-19 20:32
Ok, looks like #2002 fixed the issue. I am also closing this one. If it's still a problem, please re-open. Thanks.

**Closed by Ylianst** 2020-11-19 20:32 UTC
Labels: Fixed - Confirm & Close, High Priority, bug
