### ISSUE TITLE
Meshcentral agents across differents VLANs

### ISSUE THREAD

**Issue by lavoieequipement** [Ylianst/MeshCentral#2696] opened 2021-05-26 17:22 UTC
Hi, 

First of all, thank you so much for MeshCentral! Awesome software!

I would like to know if MeshCentral allows agent management across different Vlans. 
I have a MeshCentral installed on the subnet 192.168.50.x and all agents work fine there but I have another location (Site to Site VPN) where PC are on the subnet 192.168.40.x and those won't connect.
All subnets are accessible from both side.
Do I need to have all my agents within the same subnet  or am I missing something ? (192.168.50.x for instance)
Thank you for your help

**Comment by AntonAndreevichMoroz** [comment] 2021-05-26 17:27
what server mode are you using?  LAN, WAN, Hybrid?

**Comment by lavoieequipement** [comment] 2021-05-26 17:28
Hi, 
I use the LAN mode

**Comment by Ylianst** [comment] 2021-05-26 17:51
In LAN mode, the agents will multicast to try to find the server. Then you install a MeshAgent, you should see a "meshagent.msh" file which is text file that tells the agent how to find and authenticate the server. It often looks like this:

```
MeshName=Lab Computers
MeshType=2
MeshID=0xEDBE1BE3771D69DF39D35DF97F7E9A6F7D75DB86F9D9EE3B735EBB7DB6B4E7971EF34D36EBB6B875CF3D7DED1EE7CD5C
ServerID=D99362D5ED8BAEA8BF9E743B34B242256370C460FD66CB62373C6CFCB204D6D707403E396CF0EF6DC2B3A42F735135FD
MeshServer=wss://central.mesh.meshcentral.com:443/agent.ashx
webSocketMaskOverride=1
```

Note the "MeshServer" line indicating the URL to connect to the server. If your .msh has this:

```
MeshServer=local
```

Then the agent will multicast to find the server. The problem is that if multicast does not travel thru your different local networks or thru the VPN, the agent will not find the server.

The easy fix it to set a DNS name for your server in the settings section of the config.json:

```
"cert": "myserver.domain.com"
```

Then, new agents will resolve the DNS name and connect to the given URL. Even if your server is internal with no public access, it's still going to solve the issue.

Hope that helps.

**Comment by lavoieequipement** [comment] 2021-05-26 17:55
Thank you very much! I will try this!

**Comment by Ylianst** [comment] 2021-05-26 18:17
Ok, please close this issue once it's resolved.

**Closed** 2021-05-27 13:13 UTC
Labels: Fixed - Confirm & Close, question

**Comment by TvT73** [comment] 2024-07-26 12:38
Hello togehter,
I am trying to test this also, but without success. I don´t know how to identify the issue.
My meshcentral is internal with 192.168.10.x and the server on a different vlan is running on 192.168.20.x 

`{
  "$schema": "https://raw.githubusercontent.com/Ylianst/MeshCentral/master/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "cert": "meshcentral",
    "_WANonly": true,
    "_LANonly": true,
    "_sessionKey": "MyReallySecretPassword1",
    "_port": 443,
    "_aliasPort": 443,
    "_redirPort": 80,
    "_redirAliasPort": 80
  },`

I edit the config.json, rebootet the meshcentral server, edit hosts for the server 2019 and in browser and cmd the meshcentral is resolving to the right adresse, but the agent won´t connect to the meshcentral server.

The Agent is running in local mode.

**Comment by TvT73** [comment] 2024-07-26 21:11
You are right, it´s still in lan mode. So I guess something is missing, that I am not in hybrid mode. Is this the right mode when only using it local? Port 443 is used for another application on the wan, so I cant use it for meshcentral.

**Comment by si458** [comment] 2024-07-26 21:13
If I remember, the cert value must be a valid dns name! 
So, for example, meshcentral.myserver.com, meshcentral.local, meshcentral.ad.local, etc...
It can not just be a single name

**Comment by TvT73** [comment] 2024-07-26 21:15
Here is an Unifi DNS und Router on a larger Camp Ground site. The meshcentral is not part of the AD

**Comment by si458** [comment] 2024-07-26 21:18
@TvT73 No, that's just an example, 
In ur config.json, u gave ur cert value and its set as `meshcentral` which won't be valid. It needs to be a valid dns name, e.g, meshcentral.example.com, myserver.com, meshcentral.ad.local, something like that

**Comment by TvT73** [comment] 2024-07-26 21:25
Okay, I understand. It doesn´t matter what I choose, but it must be resolvable in the hosts file from the agent of server.
Am I right, that I must activate both wan and lan options for getting hybrid mode?

**Comment by si458** [comment] 2024-07-26 21:28
All u need to do is set `cert` to a valid dns name that all ur agents can resolve one way or another.

Even if u purchase a domain and create an A record and it points to ur internal ip address!

Then restart meshcentral and it will recreate it certificates with that dns name and switch into hybrid mode

Don't set the wanonly or lanonly values! Leave them alone

**Comment by TvT73** [comment] 2024-07-26 21:44
I´ve got it :-) Thanks a lot 🥇
