### ISSUE TITLE
issue with windows installer

### ISSUE THREAD

**Issue by seekermate** [Ylianst/MeshCentral#334] opened 2019-07-02 13:08 UTC
i have downloaded meshcentral windows installer and run it , but after install the requirements
and start configuration, an has show up with this title "cant install meshcentral service(3#) and "unable to parse c://.../config.json"
please guide me tnx.

**Comment by esembeit** [comment] 2019-07-03 13:50
I can confirm i am having the same issue as well, i attached the file for your review. Hope this helps thanks.
[config.zip](https://github.com/Ylianst/MeshCentral/files/3355267/config.zip)

**Comment by luquer2** [comment] 2019-07-03 15:58
I am also experiencing the same exact issue. It looks like the config.json file generated during installation process is tailing an extra comma character after last settings object property:
{
  "settings": {
    "cert": "example.domain.es",
  }
}
This extra comma is causing .net installer to throw a parse error when the installer wants to read config.json file at MeshCentralInstaller.MainForm.loadConfiguration(String configFilePath) method.

This happens on 1.6 version of the installer.

Thank you

**Comment by Ylianst** [comment] 2019-07-03 20:26
Ha! Yes, you are right. Thank you for reporting this. I just uploaded a new .exe (still labeled 1.6) with a fix. If it works, let me know. Again, many thanks.

**Comment by Ylianst** [comment] 2019-07-03 20:36
I just took advantage of being in this area of the code to updated the installer a bit more. Replaced the older "mongojs" to the new "mongodb" module installation.

**Comment by luquer2** [comment] 2019-07-03 22:33
I am sorry, link from installers guide 0.0.7 with url **http://info.meshcentral.com/downloads/meshcentral2/MeshCentralInstaller.exe** redirects to a 404.
The alternative way to download installer, from http://info.meshcentral.com/downloads/MeshCentral2/MeshCentralInstaller-1.6.exe gives me the same binary I downloaded before your fix,  wich has the following hashes:
CRC32: B8961D9D
CRC64: 5CA3A0CAC7A9D2BF
SHA256: FF70DA2702C0D098B3643E6C1086A3A5B83BA6238410E95BA5D6DDAA207D4C75
SHA1: 3B7FA3CCC527D58AD0E2E2A0C2BA46B2CAD7FA64

Does the installer download from any dynamic content that will produce different results in the installation process if executed again?

Anyway I have been able to install in a different host, Win10Pro version 1809, using MeshCentralInstaller-1.6.exe after your fix without any issue. So i think i can confirm that the fix worked for me.

Thank you.

**Comment by Ylianst** [comment] 2019-07-04 00:51
Hi. My server must be caching the files in memory and so, when I replace them on disk the new version is not served. I just bumped up the version number to 1.7 ([link here](http://info.meshcentral.com/downloads/MeshCentral2/MeshCentralInstaller-1.7.exe)). I also noticed the 404 link has a problem, the "MeshCentral2" is not capitalized:

[http://info.meshcentral.com/downloads/MeshCentral2/MeshCentralInstaller.exe ](http://info.meshcentral.com/downloads/MeshCentral2/MeshCentralInstaller.exe )

This works better, I am going to fix the documentation now.

**Comment by Ylianst** [comment] 2019-07-04 00:56
Just fixed the 404 link in the Installer's Guide v0.0.7. Thanks for the report.

**Comment by luquer2** [comment] 2019-07-05 14:16
I have successfully installed MeshCentral with installer version 1.7. I only had an issue at the step when the installer shows "Service Started". It may be waiting for some kind of response from the process that starts the service, but in my case, a single core, single thread VPS, was so busy that it did not start the process indeed. Starting it manually, resumed the installer and ended successfully. 
For me #334 should be marked as fixed and closed.

Thank you very much Ylian.

**Comment by Ylianst** [comment] 2019-07-05 22:31
Thanks. I will close this one, but feel free to open a new issue if needed.

**Closed by Ylianst** 2019-07-05 22:31 UTC
Labels: Fixed - Please Confirm, bug
