### ISSUE TITLE
MeshCentral Version

### ISSUE THREAD

**Issue by motapek** [Ylianst/MeshCentral#206] opened 2019-04-26 21:06 UTC
On my on-premise server when I try to check Server version I get Current version  - 0.3.3-a but the latest version is unknown.

**Comment by Ylianst** [comment] 2019-04-26 22:23
Internally, MeshCentral calls npm to check the version number. If the server is low on RAM or can't find or call the npm binary, it will return "unknown". Check "mesherror.txt" in "meshcentral-data" to run MeshCentral manually and try again, may be able to see what the problem is.

**Comment by motapek** [comment] 2019-04-29 20:22
I upgraded to 0.3.3-i and it is this same.
I tried stop - start server but without effect.
I didn't get any server logs and mesherror.txt file.
On the server I have 3 GB free memory. 
Server work normaly but maybe this is problem with mechcentral upgrade.
When I check outdated  packages (sudo npm outdated) I get for example:
Package      Current   Wanted   Latest  Location
meshcentral  0.3.3-a  0.3.3-i  0.3.3-i  zonoit_meshcentral
But after (sudo npm install) and check again and I get this same.
Only if I change version meshcentral in package.json file to Latest version and try again (sudo npm install) this in effect gives the latest version of meshcentral.
I'm not a npm/node specialist. Maybe this is normal.

**Comment by Ylianst** [comment] 2019-05-04 00:20
Ok. I find the issue and was able to fix this on my servers. When running the server using systemd, the paths to Node and NPM are not set. So, the server can't call NPM correctly. Go in your config.json and add this line in the "Settings" section

`"NpmPath": "/home/ec2-user/.nvm/versions/node/v10.15.1/bin/node /home/ec2-user/.nvm/versions/node/v10.15.1/bin/npm"`

You need to add "npmpath" with the full path of NodeJS a space and the full path of NPM. You can use "whereis node" and "whereis npm" and use that. Above is the line I use for Amazon Linux2. Also, make sure you add the line with project JSON formatting, you add a comma at the end of the line if needed.

This should fix it. Let me know if it does, I will add to the server installation documentation. - Thanks.

**Comment by Kodangi** [comment] 2019-05-05 09:53
Verified

**Comment by Ylianst** [comment] 2019-05-05 16:28
Thanks. I will close this once since I am pretty sure it's a fix. However, I may in the future look for a way for MeshCentral to automatically figure out the Node/NPM paths.

**Closed by Ylianst** 2019-05-05 16:28 UTC
Labels: help wanted
