### ISSUE TITLE
Disable Novnc

### ISSUE THREAD

**Issue by coolwormgit** [Ylianst/MeshCentral#1467] opened 2020-06-09 06:14 UTC
hello, is there any way to disable novnc from the menu?? because i dont need it... 

thanks

**Comment by Ylianst** [comment] 2020-06-09 19:05
Ok, in next version of MeshCentral v0.5.56, you can add this line in the domain section of the config.json:

```
"novnc": false
```

That will remove the "noVNC" link.

**Comment by Ylianst** [comment] 2020-06-10 23:11
Published MeshCentral v0.5.56, you can turn turn off "noVNC" using `"novnc":false` in the domain section of config.json.

For people wondering, you can find "noVNC" and the new "Web-RDP" clients here. Right now, "noVNC" is enabled by default, the web RDP is not, you need to add `"mstsc":true` in the domain section of config.json to enable the web RDP.

![image](https://user-images.githubusercontent.com/1319013/84327716-ed884000-ab34-11ea-8459-6c2df15dfa7c.png)

**Comment by Ylianst** [comment] 2020-06-10 23:13
Additional notes on the new Web RDP, it's not enabled by default. If someones gives it a try, please open a new issue and let me know what you think.

![MC2-RDP1](https://user-images.githubusercontent.com/1319013/84327845-435ce800-ab35-11ea-814a-c4b735b2d5d2.png)

![MC2-RDP2](https://user-images.githubusercontent.com/1319013/84327850-4526ab80-ab35-11ea-9205-dad76e9676d0.png)

**Comment by uldiseihenbergs** [comment] 2020-06-11 06:22
Hi @Ylianst , i just tried a new WebRDP, and performance is very poor in my case - i see squares when i move some windows - screen is just repainting and so on. when i use the same RDP with Remmina on Linux, it performs very well.
and i just tested the same RDP in browser with Apache Guacamole - with this one RDP works very well..

**Comment by Ylianst** [comment] 2020-06-11 06:47
Thanks for trying it out and the feedback. I never tried Apache Guacamole and this is a very early version (this is why I have it disabled by default). Can I know what browser you used for testing? Also, would it be a feature you would generally use if it worked well? - Thanks.

**Comment by uldiseihenbergs** [comment] 2020-06-11 06:52
i'm using Firefox browser. and yes, if this feature will work near builtin RDP, then i will use it. as i wrote, i'm using Remmina on my Ubuntu to connect Windows RDP and it just works :)

**Comment by amenolo** [comment] 2020-06-11 06:58
Oh boy...what a juicy features! 

I'm going to try them and I'll give you feedback as well, since I would use them for sure!

**Comment by Ylianst** [comment] 2020-06-11 07:05
Oh dear, remember, it's just a first version, but feedback appreciated. I wish I could add the Apache Guacamole code in MeshCentral, but they use C back-end code and I would like to keep MeshCentral all NodeJS in the back-end.

**Comment by amenolo** [comment] 2020-06-11 07:17
Well...I guess we all know that Guacamole RDP works exceptionally fine...in any case that kind of features seems to me like a mini killer-application....so thumbs up! :+1:

**Comment by amenolo** [comment] 2020-06-11 07:31
BTW AFAUK there are less "invasive" alternatives to RDP Wrapper Library in order to enable RDP loopback connections in Windows OS?

**Comment by amenolo** [comment] 2020-06-11 07:31
BTW AFAYK there are less "invasive" alternatives to RDP Wrapper Library in order to enable RDP loopback connections in Windows OS?

**Comment by Ylianst** [comment] 2020-06-11 07:46
Maybe RDP does work on loopback by default, I need to get myself fresh machine and see if it works or not. For testing, I setup a computer with allows RDP sessions without a password (I changed a registry key for this) but I can't remember if I had to do anything for loopback, maybe not.

**Comment by uldiseihenbergs** [comment] 2020-06-11 07:49
i goggled about RDP loopback and there was nothing obvious in results - then i just tried on one of my widows and it just works. so i think it's enabled by default.

**Comment by Ylianst** [comment] 2020-06-11 07:51
Nice, my mistake. I will edit my little graphics.

**Comment by amenolo** [comment] 2020-06-11 08:01
> 
> 
> i goggled about RDP loopback and there was nothing obvious in results - then i just tried on one of my widows and it just works. so i think it's enabled by default.

AFAIK RDP loopback is not enabled by default in Windows OS, RDP Wrapper Library comes in handy for that (and other stuffs too), in theory ( see for example https://arnav.jain.se/2017/windows-10-rdp-to-local-user/ )...anyway I'm not able to web-RDP in to any of my Windows guests...uhm...

**Comment by uldiseihenbergs** [comment] 2020-06-11 08:07
huh, i just tried another win machines in my mesh - another two Win10 wont work, one win2008 R2 works..
how to check for RDP loopback in Win?

**Comment by amenolo** [comment] 2020-06-11 08:12
Coincidentally my RDP Windows tests are limited to non-server versions...uhm...

**Comment by Ylianst** [comment] 2020-06-11 23:58
FYI. Just published MeshCentral v0.5.58 with improved RDP flow control, fix for mouse wheel.

**Comment by uldiseihenbergs** [comment] 2020-06-12 06:26
Hi @Ylianst , i just updated to .58, and still bad experience - i'm still seeing screen repainting line bi line.

**Comment by amenolo** [comment] 2020-06-12 12:37
Upgraded to MC v0.5.58, now web-RDP causes a server disconnection.

![rdp](https://user-images.githubusercontent.com/29974944/84503300-403f3480-acba-11ea-858b-ec5526e1086b.gif)

Besides I was still unable to get web-RDP working (with Windows 10 workstation guests at least) with previous MC version.

**Comment by Ylianst** [comment] 2020-06-12 17:23
Can you send over the last error in "meshcentral-data/mesherrors.txt"? i will fix that rights away! Thanks.

**Comment by amenolo** [comment] 2020-06-12 17:26
`-------- 12/6/2020, 19:25:54 ---- 0.5.58 --------

events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: Unexpected server response: 403
    at ClientRequest.<anonymous> (/opt/meshcentral/node_modules/ws/lib/websocket.js:595:7)
    at ClientRequest.emit (events.js:315:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:610:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:17)
    at Socket.socketOnData (_http_client.js:479:22)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:273:9)
    at Socket.Readable.push (_stream_readable.js:214:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
Emitted 'error' event on WebSocket instance at:
    at abortHandshake (/opt/meshcentral/node_modules/ws/lib/websocket.js:718:15)
    at ClientRequest.<anonymous> (/opt/meshcentral/node_modules/ws/lib/websocket.js:595:7)
    [... lines matching original stack trace ...]
    at Socket.Readable.push (_stream_readable.js:214:10)`

Thanks!

**Comment by Ylianst** [comment] 2020-06-12 19:31
I submitted a fix for this. This type of errors will not crash the server anymore, I added support for servers that are not on port 443, you can only trace what is going on using the "relay" trace.

This will all be in v0.5.59.

**Comment by amenolo** [comment] 2020-06-13 09:06
And here we are again: v.0.5.59 solved issue! 👍 

I meanwhile managed to get RDP loopback working in latest Windows 10 versions thanks to updated RDP Wrapper ( https://github.com/asmtron/rdpwrap/blob/master/binary-download.md ) and I can confirm its poor behavior, at least compared to almost flawless noVNC...any chance to get it better? Moreover I was wondering if one can change RDP visual settings (desktop background, window content while dragging, and so on...) maybe via meshcentral config file...

BTW just noticed that Web-RDP right click menu opens noVNC option:

![right menu](https://user-images.githubusercontent.com/29974944/84564937-e09e6300-ad65-11ea-94b7-e475295092cf.gif)

**Comment by Ylianst** [comment] 2020-06-13 12:57
I just pushed the fix for the context menu, thanks for reporting that. It will be in v0.5.61.

As for getting better, I need to chat with the Apache Guacamole team... they are clearly the best in this area. I am using [node-rdpjs](https://github.com/citronneur/node-rdpjs) which has not been updated in years. I need to find another path forward that does not include personally coding RDP protocol.

**Comment by amenolo** [comment] 2020-06-13 13:05
> I need to chat with the Apache Guacamole team...

Very appreciated commitment! 👍 

BTW I get following warning every time I run Web-RDP connection

```
-------- 13/6/2020, 14:58:38 ---- 0.5.60 --------

{"name":"node-rdpjs","hostname":"server","pid":22257,"level":40,"msg":"undefined","time":"2020-06-13T12:58:38.744Z","v":0}
```

Something I have to worry about? Thanks.

**Comment by uldiseihenbergs** [comment] 2020-06-13 18:01
@Ylianst  another RDP implemantation option would be Freerdp? (http://www.freerdp.com/). Remmina in Linux is using it and works very well. but i don't know if this can work in browser - looks like they have subproject for web too - http://freerdp.net/

**Comment by Ylianst** [comment] 2020-06-13 20:13
@amenolo You can ignore the warning messages, I will need to fork the "node-rdpjs" project and change their code to get rid of these messages. It's annoying that they don't have a way to remove them.

@uldiseihenbergs The problem with FreeRDP is that the server component is written in C/C++ and so, it has to be compiled on the server. This said, I did not know about [http://freerdp.net/](http://freerdp.net/), i wonder if there is anything I can do to use that.

**Comment by Ylianst** [comment] 2020-06-13 20:23
Taking a quick look, http://freerdp.net/ was not updated in 5 years.

**Comment by Ylianst** [comment] 2020-06-15 20:18
I will close this one since an options to disable noVNC is now available. Please open a new issue for discussion/feedback/problems with the web RDP client.

**Closed by Ylianst** 2020-06-15 20:18 UTC
Labels: Fixed - Confirm & Close, enhancement
