### ISSUE TITLE
LDAP Support for Multi-Company logins?

### ISSUE THREAD

**Issue by SomeGuru** [Ylianst/MeshCentral#1028] opened 2020-03-16 17:03 UTC
HI @Ylianst,

Any chance that there is support for ldap from different companies on one server? I don't see it in the document and want to attempt to connect LDAP A Company, LDAP B Company, LDAP C Company & LDAP D Company to the server... Of course the companies would have to give some method by which to connect to their specific LDAPs but this could help with growth in regards to administration from my stand point... 

Thanks,
SomeGuru.

**Comment by Ylianst** [comment] 2020-03-16 20:44
You can setup multiple domains in MeshCentral, each with it's own access URL or DNS name. You should be able to configure different LDAP settings for each domain and so, a single server can host different companies at the same time.

This said, there is no support and probably not a good idea to setup many LDAP servers on the domain domain because you may have collisions between users of different organizations. Let me know if that works.

**Comment by MordyT** [comment] 2020-03-17 04:29
Is there anything besides auth:sspi for ldap?

How do I join a MC server to multiple domains?

**Comment by Ylianst** [comment] 2020-03-20 05:32
(This is a duplicate of my instructions for #1020)

You can configure a MeshCentral server to use an LDAP server for user authentication by adding the following to the domain section of the config.json (this is only an example):

```
      "auth": "ldap",
      "ldapUserName": "displayName",
      "ldapUserBinaryKey": "objectSid",
      "ldapOptions": {
        "url": "ldap://127.16.0.1:389",
        "bindDN": "CN=svc_meshcentral,CN=Users,DC=meshcentral,DC=local",
        "bindCredentials": "Password.1",
        "searchBase": "DC=meshcentral,DC=local",
        "searchFilter": "(sAMAccountName={{username}})"
      }
```

Since I have not used LDAP much, I would appreciate feedback on this. MeshCentral uses the "[ldapauth-fork](https://www.npmjs.com/package/ldapauth-fork)" module to do this. Look at that module for the proper options.

**Closed** 2020-07-15 11:37 UTC
Labels: Fixed - Confirm & Close, question
