### ISSUE TITLE
Two and more monitors switching

### ISSUE THREAD

**Issue by motapek** [Ylianst/MeshCentral#205] opened 2019-04-26 20:53 UTC
I have a lot of users with two or three monitors.
I have two problems with this.
First:
When I connect to desktop I get two monitors view.
Generaly always I can switch to second monitor but not to first.
Sometimes it is possible but I does not find a some correlation what it depends on. Additionaly when I can switch to 1 and 2 monitor I can't switch directly from 2 to 1. I must do it by all monitors (2 -> ALL -> 1)
I used all web browsers but without satisfactory effect (Edge, Opera, Firefox, Chrome, Vivaldi)
Second:
(maybe this is not a bug) but when I do something in user computer and must use admin privilages, after get admin right window, meshcommander automaticaly switch me to all monitors view.
I understend it but sometimes this is irritating. 
Maybe you can add some switch in user settings to choice of behavior ?

**Comment by wh1te909** [comment] 2019-04-26 21:50
Are your users on windows 10?
I have the same issue with my users. Windows 10 only. Windows 8.1 no issues.
The pattern I have consistently noticed with dual monitors:

Intel integrated graphics or AMD graphics card: selecting "Display 1" does nothing, selecting "Display 2" will show Display 1.

Nvidia graphics card: switching between display 1 and 2 works as intended.

**Comment by motapek** [comment] 2019-04-26 21:56
Yes. I have only WIndows 10 Pro users. 
All computers use Intel graphic cards.

**Comment by Ylianst** [comment] 2019-04-26 22:26
- For the first issue reported, yes, I need to fix that. The drop down box starts in the wrong position.
- For the second issue, I get a sense of the problem, I will need to discuss with Bryan on how to fix this.

**Comment by Ylianst** [comment] 2019-04-27 17:47
Published MeshCentral v0.3.3-c with a fix for both these issues. Give it a try and let me know if it works.

**Comment by wh1te909** [comment] 2019-04-27 19:29
Display 1 is still not working for me, here is a screen capture of the behavior:
https://gyazo.com/580a8d251a0e855fb4e41254a9164a98

**Comment by krayon007** [comment] 2019-04-27 19:44
Are your monitors set to have a different DPI setting each? if so I have fixed this but it will be released in an upcoming server update that has a new agent update

**Comment by wh1te909** [comment] 2019-04-27 19:58
Nope both on the default 100% scaling. Just tested on a few more pc's same issue.

**Comment by krayon007** [comment] 2019-04-27 20:32
Interesting I'll put together a test system with a different graphics card and see if I can reproduce the problem.

**Comment by Ylianst** [comment] 2019-04-27 20:51
Thanks for the report. I will work on it later today. This is a server side problem related to this morning's work on this. Not agent related.

**Comment by Ylianst** [comment] 2019-04-27 22:37
Published MeshCentral v0.3.3-e. Not sure if it will fix it, but re-wrote the display selection code.

**Comment by wh1te909** [comment] 2019-04-27 23:11
Nope :(
https://gyazo.com/6bbc85ef5cf35f9582f1a72408ba62c6

**Comment by Ylianst** [comment] 2019-04-28 17:41
Published MeshCentral v0.3.3-f with browser console output for the display selector. Can you update your server, open the browser console, connect to remote desktop and select each screen one-by-one? It should look like the screen below. Once you do that, screen shot or cut and paste console and sent it over. Should be easy to see what is going on. Thanks.

![MC2-DebugDisplaySelector](https://user-images.githubusercontent.com/1319013/56868047-19cd1580-69a2-11e9-93b5-348f8e0abbe3.png)

**Comment by Ylianst** [comment] 2019-04-28 17:43
Published MeshCentral v0.3.3-f with browser console output for the display selector. Can you update your server, open the browser console, connect to remote desktop and select each screen one-by-one? It should look like the screen below. Once you do that, screen shot or cut and paste console and sent it over. Should be easy to see what is going on. Thanks.

![MC2-DebugDisplaySelector](https://user-images.githubusercontent.com/1319013/56868067-792b2580-69a2-11e9-97ef-34ea27b9815a.png)

**Comment by wh1te909** [comment] 2019-04-28 18:10
![display1](https://user-images.githubusercontent.com/7434746/56868351-294e5d80-69a6-11e9-8693-9ca08ff4032e.PNG)

**Comment by Ylianst** [comment] 2019-04-28 18:12
Thanks for the quick response! This seems to be a MeshAgent problem. Bryan will need to look into it.

**Comment by krayon007** [comment] 2019-04-28 18:22
Which graphics driver are you using? I might need to track down a specific machine or build because I'm unable to reproduce it on my machines.

**Comment by Ylianst** [comment] 2019-04-28 18:35
I am in the same boat, I can't make this happen on my machine. @wh1te909, could we have a screen shot of selecting "All Displays" and selecting "Display 1" back an forth? Then "Display 2" to "Display 1" than "All to Display 2"? I would like to get a full pattern of all display transitions, just in case it gives us an hint. Thanks.

**Comment by wh1te909** [comment] 2019-04-28 19:18
Here are graphics drivers from 8 different computers with the display issue:

Intel UHD Graphics 630 version 25.20.100.6471 - Win 10 pro 1809

Intel HD Graphics 2500 version 10.18.10.4358 - Win 10 pro v 1803

Intel HD Graphics 630 version 23.20.16.4973 - Win 10 Pro v 1803

Intel HD Graphics 4600 version 20.19.15.4835 - Win 10 Pro v 1809

AMD Radeon HD 5450 version 15.201.1151.1008 - Win 10 Pro v 1803

Intel HD Graphics 630 version 25.20.100.6323 - Win 10 Pro v 1809

Intel® HD Graphics 2000 - version 9.17.10.4459 - Win 10 Pro v 1809

AMD Adrenalin version 18.2.3 - Win 10 Pro v 1809


![pattern](https://user-images.githubusercontent.com/7434746/56869033-b3e78a80-69af-11e9-938b-96793df7a6c9.PNG)

**Comment by Ylianst** [comment] 2019-04-28 19:34
Perfect! Thanks.

**Comment by krayon007** [comment] 2019-04-28 20:02
Thanks, I'll see if I can track down a system with one of those. I have a hunch the problem is caused by the display identifier field I'm using, and how the driver populates it.

**Comment by krayon007** [comment] 2019-04-29 20:39
Can you run the following JavaScript file on one of your machines, and let me know what the output is? You can run it, by simply specifying the javascript file as one of the command line parameters to the agent binary. ie: meshagent MonitorTest

This script will simply enumerate the monitors, and display the identifiers.
[MonitorTest.js](https://drive.google.com/open?id=1NGKyL4Hg44JaBP4vG5wma9fc2G1t3KEJ)

**Comment by motapek** [comment] 2019-04-29 20:40
After upgrade in my system all computer work fine.
Even if one of the monitors is off (black) I can switch to it. ( I view black monitor).

**Comment by motapek** [comment] 2019-04-29 21:34
\\.\DISPLAY1
\\.\DISPLAY2

**Comment by motapek** [comment] 2019-04-29 21:38
Other computer this same:
\.\DISPLAY1
\.\DISPLAY2

**Comment by wh1te909** [comment] 2019-04-29 21:43
I know what's causing it now sorry for driving you guys crazy lol.
The output was
\\.\DISPLAY2
\\.\DISPLAY3
Which made me realize we have LogMeIn installed on all these computers, and in device manager under display adapters there is "Logmein Mirror Driver" which im guessing mesh thinks is DISPLAY1.
After uninstalling LogMeIn and re-installing the mesh agent the output is now what it should be:
\\.\DISPLAY1
\\.\DISPLAY2

**Comment by PathfinderNetworks** [comment] 2019-04-29 21:49
I just updated my server and tested the multi monitor selection option. It seems to be working mostly correctly on my end.  I'm able to select monitors correctly now. But the resolution/DPI issue is still there (although I know Bryan says that's going to be fixed with an agent update down the road).

**Comment by UnP1u9** [comment] 2019-05-07 11:54
getting same issue on windows 10 machines. 1st screen can't be access alone however 2nd display working fine.

**Comment by Ylianst** [comment] 2019-06-15 00:53
Published MeshCentral v0.3.6-n with Bryan's latest MeshAgent which has many fixes including handling multi-monitor with different DPI's. If anyone can test and give feedback for multi-monitor scenarios, that would be great.

**Comment by PathfinderNetworks** [comment] 2019-06-15 01:24
I just updated my server. So far it seems to be working correctly . I connected to a device that has two different size, different resolution monitors and was able to switch back and forth between the two of them without issue.  Tried the same thing on a device with three monitors, two of which are the same resolution and the third is a different.  Worked correctly there as well.  I also notice that the mouse is tracking correctly no matter which monitor I switch to.  
Thanks!!

**Comment by PetieM** [comment] 2020-04-20 16:27
I realize this is quite old but I think the problem I'm seeing now is related very closely to this one. Selecting individual monitors has been working perfectly for me in most cases but on one particular machine, I have three monitors connected but one of them is mirrored. So display 1 and 2 (according to Windows) both show the same image and display 3 is the "second" monitor. With this setup, I can't select my "second" display, selecting display 1 does nothing, and selecting display 2 shows only display 1 (which kind of makes sense given that it is actually labeled display 2 in Windows).

**Comment by krayon007** [comment] 2020-04-23 16:35
What do you mean by mirrored? If you walk me thru setting up your mirrored display, I can try to replicate your use case, and see if I can track down what is going on.

**Comment by PetieM** [comment] 2020-04-23 16:46
It's using the duplicate display feature in Windows. There are three displays connected but numbers 1 and 2 are showing the same content. I attached a couple of screenshots showing how it's set up but if you need more details, please let me know.

![Screen Shot 2020-04-23 at 10 45 20 AM](https://user-images.githubusercontent.com/16453878/80126002-b2fc2100-854f-11ea-8d2f-2a0d66462106.png)
![Screen Shot 2020-04-23 at 10 45 29 AM](https://user-images.githubusercontent.com/16453878/80126007-b42d4e00-854f-11ea-8df3-a260008e46d1.png)

**Comment by krayon007** [comment] 2020-04-24 18:19
I finally got to the bottom of this issue, and fixed it... The issue was caused because the way the KVM protocol works, it assumes the Display IDs are in numerical order. Most of the time this is true, but I found some display drivers, hard code the display IDs based on which physical port the display is connected to... Likewise, virtual displays will screw up that assumption too...  So I fixed the agent so it won't try to use that ID as the actual ID...

This will be live in the next windows agent update...

**Comment by krayon007** [comment] 2020-04-25 03:01
This is fixed in MeshCentral v0.5.14. Give it a whirl, and let me know if it fixes it for you...

**Comment by PetieM** [comment] 2020-04-25 04:18
Thanks for the quick fix! Confirming that this is now working though it's worth adding that it has the displays labeled backwards now (what would logically be display 1 or the "main" display is coming up as 2 in the setup shown in the screenshot from a few posts back). I'm sure this is related to how you're retrieving display IDs now and definitely isn't a big deal but it is slightly unintuitive as is. Based on your description, I'm not sure if this is even fixable and it's certainly better that it works at all than to have the displays numbered "correctly" regardless.

**Comment by krayon007** [comment] 2020-04-25 04:46
Yeah, the reason it may be a little wierd, is that the wire protocol between the agent and the browser, doesn't have a field to specify any ID's in the descriptor, the wire protocol only said how many displays it had... So to get around this without changing the protocol, I made it so that instead of using 1, 2, 3, etc as Display ID 1, 2, and 3, I asked the OS for to give me all the connected displays, and I used the first result as 1, the second result as 2, etc...  So I'm at the mercy of the order that Windows enumerates the displays for me.

**Comment by PetieM** [comment] 2020-04-25 04:50
Makes sense to me. It's not hard to guess and check and I'd rather it work than be labeled "correctly" and have one or more displays entirely unavailable. Again, thanks for the quick turnaround and have a good weekend!

**Closed** 2020-04-25 04:59 UTC
Labels: Fixed - Confirm & Close, bug
