### ISSUE TITLE
Keyboard Mapping Issues with Mismatched Keyboard Layouts

### ISSUE THREAD

**Issue by scottalanmiller** [Ylianst/MeshCentral#896] opened 2020-01-31 16:02 UTC
We have a lot of users with Spanish language keyboards, that need to remote into US keyboards.  But they have found that many symbols and special characters don't work properly.  The key that they type on their local keyboard will come through as a different character in the remote session.  Some keys cannot be found at all.  Like typing @ is often impossible.  Even when using the "Type" feature, they often can't type what they need in there like they used it, it too gets "translated" to a different keyboard mapping.

Ideally what they type, the symbol that they hit locally should be what shows up remotely.

**Comment by TotallyNotElite** [comment] 2020-02-05 20:06
Same issue with german keyboards. @bencat07 and I had this issue today.

**Comment by TotallyNotElite** [comment] 2020-02-05 20:07
Duplicate of https://github.com/Ylianst/MeshCentral/issues/469

**Comment by Ylianst** [comment] 2020-11-18 22:32
MeshCentral v0.6.93 was published with correct keyboard handling on Windows. Bryan is working on doing the same for other platforms (Linux, macOS, FreeBSD). Let us know if it works.

![MC-MultiKeyboards](https://user-images.githubusercontent.com/1319013/99596296-e2babc80-29aa-11eb-9acf-c34bc5c92d3d.png)

**Closed** 2021-01-04 05:18 UTC
Labels: Fixed - Confirm & Close, bug
