### ISSUE TITLE
File transfer causing mesh portal to go unresponsive

### ISSUE THREAD

**Issue by mdshoaibumer** [Ylianst/MeshCentral#5627] opened 2023-12-13 12:10 UTC
Dear @Ylianst sir,

I'm using MeshCentral in my organization with 15000+ agents communicating every day. I observed that meshcentral portal is going unresponsive when we are performing file transfer. I'm trying to figure out why this is happening. There is no error in the logs and once i cancel file transfer the portal works perfectly as expected.

OS : Microsoft Server 2016.
MeshCentral Version : 1.1.0

Kindly help me on this to resolve the issue.

**Comment by si458** [comment] 2023-12-13 12:13
what sorta size files are you copying? as i know the filetransfer doesnt really handle LARGE files correctly

**Comment by brianmillum** [comment] 2023-12-14 20:42
This happens to me as well. Anything over 3 meg hangs...

**Comment by si458** [comment] 2023-12-14 20:59
**you havent really followed the bug template so its missing key info to help fix your issue**
what nodejs version are you using?
have you tried updating to the latest version of meshcentral to see if the issue is fixed?
whats you config.json? (hide sensitive stuff)
whats the local device running the web ui? (OS+BROWSER)
whats the remote device you are trying to send files too? (OS/ARCH)
are you sending files to multiple computers at once? (using the batch file upload method)
are you sending files to only a single computer via the Files tab?

**Comment by mdshoaibumer** [comment] 2023-12-18 13:15
@si458 

Currently iam upgrading my MeshCentral to Latest Stable version 1.1.16. Will ping here if the issue is observed again
are you sending files to multiple computers at once? (using the batch file upload method) - NO
are you sending files to only a single computer via the Files tab? - Yes

**Comment by si458** [comment] 2024-04-09 13:05
do you still have this issue with the latest 1.1.22?
have you also tried upgrading to the latest LTS node version 20 ?

**Comment by si458** [comment] 2024-04-09 14:22
ok i will close the issue them for now,
any problems make sure you use the latest version and node 18 or above.
if still happening do reply back and we can investigate it more

**Closed by si458** 2024-04-09 14:22 UTC
Labels: bug
