### ISSUE TITLE
Question about config issue with port 

### ISSUE THREAD

**Issue by killmasta93** [Ylianst/MeshCentral#4438] opened 2022-08-24 04:22 UTC
**Describe your issue**
Hi Currently trying to install the docker version of meshcentral but im having issue with the ports 
on my docker compose i have published http port 8085 and also on the config but it keeps showing error connection  

**Server Software (please complete the following information):**
 - OS:ubuntu
 - Virtualization: docker
 - Network: LAN only then use reverse proxy to expose 

**Your config.json file**
```
{
   "__comment__":"This is a sample configuration file, edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
   "settings":{
      "Cert":"remoto.domain.com",
      "mongoDb":"mongodb://meshcentral-db:27017",
      "mongoDbName":"meshcentral",
      "dbEncryptKey":"MyReallySecretPassword2",
      "LANonly":true,
      "Port":8086,
      "RedirPort": 8085,
      "AgentPing":60,
      "AgentPong":60,
      "BrowserPong":20,
      "ignoreagenthashcheck":false
   },
   "domains":{
      "":{
         "Title":"Remoto",
         "Title2":"Remoto",
         "CertUrl":"https://remoto.domain.com:443/"
      }
   }
}
```
log outcome

```
meshcentral-db    | 2022-08-23T08:59:09.252-0500 I NETWORK  [conn7] end connection 172.26.0.2:33508 (10 connections now open)
meshcentral-db    | 2022-08-23T08:59:09.253-0500 I NETWORK  [conn9] end connection 172.26.0.2:33512 (9 connections now open)
meshcentral-db    | 2022-08-23T08:59:09.253-0500 I NETWORK  [conn6] end connection 172.26.0.2:33506 (8 connections now open)
meshcentral-db    | 2022-08-23T08:59:09.254-0500 I NETWORK  [conn10] end connection 172.26.0.2:33514 (7 connections now open)
meshcentral-db    | 2022-08-23T08:59:09.255-0500 I NETWORK  [conn8] end connection 172.26.0.2:33510 (6 connections now open)
meshcentral       | MeshCentral HTTP redirection server running on port 8085.
meshcentral       | MeshCentral v1.0.72, LAN mode.
meshcentral       | Code signed agent MeshService64.exe.
meshcentral       | Code signed agent MeshService.exe.
meshcentral       | MeshCentral HTTPS server running on port 8086.
```
thank you

my docker compose

```
version: '2'
# This is example 2 from the documentation
services:
  meshcentral:
    container_name: meshcentral
    image: ghcr.io/gurucomputing/meshcentral-docker:latest
    restart: "always"
    volumes:
      - meshcentral-data:/meshcentral/meshcentral-data
      - meshcentral-files:/meshcentral/meshcentral-files
      - meshcentral-backup:/meshcentral/meshcentral-backup
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MONGODB_URL=mongodb://meshcentral-db:27017
      - MONGODB_NAME=meshcentral
      - DB_ENCRYPT_KEY=${DB_ENCRYPT_KEY}
    ports:
      - 8085:8085
      - 8086:8086
    networks:
      - meshcentral-nw
  meshcentral-db:
    container_name: meshcentral-db
    image: mongo:3.6.3
    restart: "always"
    volumes:
      - mongo-data:/data/db
      - /etc/localtime:/etc/localtime:ro
    networks:
      - meshcentral-nw

networks:
  meshcentral-nw:

volumes:
  mongo-data:
    driver: local-persist
    driver_opts:
      mountpoint: /scsi2/remote/meshcentral/_data/mongo-data
  meshcentral-data:
    driver: local-persist
    driver_opts:
      mountpoint: /scsi2/remote/meshcentral/_data/meshcentral-data
  meshcentral-files:
    driver: local-persist
    driver_opts:
      mountpoint: /scsi2/remote/meshcentral/_data/meshcentral-files
  meshcentral-backup:
    driver: local-persist
    driver_opts:
      mountpoint: /scsi2/remote/meshcentral/_data/meshcentral-backup
```
Thank you

**Comment by Ylianst** [comment] 2022-08-24 07:08
I am not an expert on this, but it looks like the problem is not that MeshCentral is using ports 8085 and 8086, that seems to work ok. The problem is MeshCentral's connection to the MongoDB database.

It looks like you make have a limit on how many connections are allowed to the database and MeshCentral is running into that limit. Again, I have not seen these errors before, but look like it's database related. You can test this theory by removing the "mongodb" line in the config.json and see if the errors go away.

**Comment by killmasta93** [comment] 2022-08-24 14:16
thank you so much for the reply, it seems that the mongodb name i forgot to add meshcentral-db

`"mongoDbName":"meshcentral-db"`

now its loading but it seems to always load https 

is there a way to only load http?

Thank you

**Comment by Ylianst** [comment] 2022-08-24 19:30
I am not sure exactly what you mean by always loading HTTPS. MeshCentral only works on the HTTPS protocol this is because it's secure and that MeshAgent can only connect using HTTPS. If you are concerned about the browser's certificate warning when you connect to HTTPS, MeshCentral has built-in support for Let's Encrypt, [I have a video on this here](https://www.youtube.com/watch?v=a4F1ayu7XWo).

I will close this since the original issue was solved.

**Closed by Ylianst** 2022-08-24 19:30 UTC
Labels: question, Fixed - Please Verify & Close
