### ISSUE TITLE
Self Update FAILED 

### ISSUE THREAD

**Issue by saschawj** [Ylianst/MeshCentral#2291] opened 2021-02-13 18:09 UTC
Hi, 

We are running into a weird issue with the Windows agents of Meshcentral. 
All of them have lost their desktop connectivity option, and can only be resolved by manually reinstalling agent. The problem is of course a lot of machines are remote and not directly reachable. 

While the agent will show online, in the console when trying to force a agentupdate, we will get 
Self Update FAILED because the downloaded agent FAILED hash check (1), URL: http:/xxxxx/meshagents?id=x 
Self Update will try again in 60 seconds...

I have tried the setting in config file of "ignoreagenthashckeck":true on the server, but it doesn't seem to solve this problem. 

The server version running is 0.7.68

Any ideas?
S.

**Comment by Ylianst** [comment] 2021-02-13 21:47
Does the error really say `http://` or does it say https? Also, if you try to download the agent using the link given in the error, does it work? Do you have a reverse proxy or some firewall that is blocking the agent download on the URL? Thanks.

**Comment by saschawj** [comment] 2021-02-13 23:56
It is https:// and i can download the agent via web directly. I can send you URL in a PM if you need.

**Comment by Ylianst** [comment] 2021-02-14 00:13
Sure, my [contact information is here](https://www.meshcommander.com/contact-information). If you can also create a dummy account, I will give it a try. It seems like something is not allowing the agent to download correctly.

**Comment by Ylianst** [comment] 2021-02-14 00:19
As a temporary solution, can probably restore the remote desktop by going in the device "Console" tab, hit "Agent Actions" button and clearing and setting back the "Server Default Core". However, it would be best to fix the agent download.

**Comment by VINISHVV** [comment] 2021-02-14 03:27
@Ylianst - can you speedup the #2285

**Comment by Ylianst** [comment] 2021-02-14 03:52
@VINISHVV That will not fix this issue. If you can't download the update, doing batch update will not change anything.

**Comment by VINISHVV** [comment] 2021-02-14 03:57
@Ylianst - Manual update is working fine... 
Only error with self update.

**Comment by saschawj** [comment] 2021-02-14 16:17
@Ylianst: I have sent you connectivity info in PM.

As per "Server Default Core" it loads recovery core, which gives you terminal, but no desktop.

**Comment by Ylianst** [comment] 2021-02-15 01:42
After investigation I found that having the following line in the settings section of the config.json will cause this exact problem:

```
"agentsInRam": false
```

For now, just remove this line or add a "_" in front of the name, save and restart the server. That should fix it. I am looking into a better fix now.

**Comment by Ylianst** [comment] 2021-02-15 02:19
Found the root cause a have a fix for the for the next version of MeshCentral. When `"agentsInRam": false` is in use, the hash of the signed and unsigned hashes are compared and so, the update fails.

**Comment by Ylianst** [comment] 2021-02-16 22:08
Just published MeshCentral v0.7.69 with a fix for the `"agentsInRam": false` problem. Let me know if it works. Close this issue if it does.

**Closed** 2021-02-23 00:53 UTC
Labels: Fixed - Confirm & Close, bug
