### ISSUE TITLE
display user logged also in columns view

### ISSUE THREAD

**Issue by tradexsrl** [Ylianst/MeshCentral#1129] opened 2020-04-08 15:28 UTC
hi is it possible to see the user logged in also in this view?
![immagine](https://user-images.githubusercontent.com/62424179/78802709-6ac0f880-79be-11ea-8250-d228051fbb9f.png)

**Comment by Ylianst** [comment] 2020-04-09 08:22
So... how would you imagine it would be displayed on that screen? Can you send an example image?

**Comment by tradexsrl** [comment] 2020-04-09 08:51
like this:
![immagine](https://user-images.githubusercontent.com/62424179/78876738-16665900-7a50-11ea-844a-db49051be9a1.png)

**Comment by Ylianst** [comment] 2020-04-09 09:15
Well, that only works if the computer name is short, what happens when the computer name is longer? In addition, the connection state could be "MQTT, CIRA, Agent, Power on". It's not going to fit well. Not sure I can do that.

**Comment by tradexsrl** [comment] 2020-04-09 09:18
other variation could only name without domain
if the name would be very long could be like this name................ so i can understand which computer is which user

**Comment by tradexsrl** [comment] 2020-04-09 09:24
not the computer name...i mean name of the user

**Comment by tradexsrl** [comment] 2020-04-09 09:29
or other variation could be : do not show "agent,powered" but only if you want "agent" because if the pc icon is blue is powered

**Comment by tradexsrl** [comment] 2020-04-09 09:34
when i wrote "if you want" because showing "agent" for me is not relevant

**Comment by si458** [comment] 2024-01-18 18:29
duplicate of #3422
closing this one, please follow the other one as its more 'show extra information' request than just 'show the user'

**Closed by si458** 2024-01-18 18:29 UTC
Labels: enhancement
