### ISSUE TITLE
After updating to 0.3.9-c few agents are not connected

### ISSUE THREAD

**Issue by Ilia1** [Ylianst/MeshCentral#400] opened 2019-08-03 12:02 UTC
_Originally posted by @Ylianst in https://github.com/Ylianst/MeshCentral/issues/373#issuecomment-517807486_

On the computer service Meshagent stopped. Starting the service and reinstalling the agent does not help.

**Comment by PTR-inc** [comment] 2019-08-04 09:41
Have the same issues. Only running a testserver with a 4 windows agents, but all disconnect after a about 2.5 minutes. When I try to restart the agent service, it is unable to stop. Have to kill the meshagent.exe.
Tried a full re-install and a fresh agent install, no luck.

**Comment by PTR-inc** [comment] 2019-08-04 09:56
Tried a win10 client with av disabled and the service stays connected.

**Comment by Ylianst** [comment] 2019-08-05 16:35
Like I mentioned in #401, I just published MeshCentral v0.3.9-d with the AV status removed. If you can try this new version and confirm that version work, would be great. Thanks.

You can also type the "av" command in the agent console to see if it will cause the agent to crash/lockup. Thanks.

![x](https://user-images.githubusercontent.com/1319013/62480298-4b553a00-b764-11e9-8951-46fbe268f11a.png)

**Comment by Ylianst** [comment] 2019-08-05 18:33
I suspect this is a duplicate of #401. Bryan looked at this and patched it correctly. Published MeshCentral v0.3.9-e with the correct fix. If it works, should close this issue.

**Comment by PTR-inc** [comment] 2019-08-05 22:44
My testsubjects are working fine now, the difference was server 2016 (hung) versus win10 LTSC (1809) (working). On a production env where the 0.3.9-c was installed, most of the win10 LTSB (1607) are down and need to be rebooted after the rollback to pre-0.3.9-c.
Windows Pro (1809) seems ok.

**Comment by Ylianst** [comment] 2019-08-07 23:01
Once the "av" fix was pushed in the server, I would expect all Windows agents to work after they are restarted. Agents that are stuck will need a reboot or service restart. I am going to close this one since the fix seems to work, but feel free to re-open this or open a new issue if needed.

**Closed by Ylianst** 2019-08-07 23:01 UTC
Labels: Fixed - Please Confirm, bug
