### ISSUE TITLE
after server upgrade - $ sign wont work - by the remote login...

### ISSUE THREAD

**Issue by wvt-adm** [Ylianst/MeshCentral#541] opened 2019-10-08 12:10 UTC
good morning - i have update to the actual version 041-w - open a mesh - click on desktop - click on connect - put in the username admin - put in the password - my password has a $ sign - lile test$1234 - the $ wont work - mean - when i press this $ sign nothing happens.... any idea? - thanks a lot for help

best regards am

**Comment by penguinthingie** [comment] 2019-10-08 17:07
Have you tried using the "type" option when entering the password?

**Comment by wvt-adm** [comment] 2019-10-08 17:12
yes – of course – but when i put in a $ - i receive a – sorry – this i can only copy paste

[cid:image001.png@01D57E0C.4FC2C710]

it looks like a french sign… ;-)

the type version is not so nice because all people can read what i write…

best regrads and thanks

am

Von: penguinthingie [mailto:notifications@github.com]
Gesendet: Dienstag, 8. Oktober 2019 19:07
An: Ylianst/MeshCentral <MeshCentral@noreply.github.com>
Cc: wvt-adm <fws@wvtnet.ch>; Author <author@noreply.github.com>
Betreff: Re: [Ylianst/MeshCentral] after server upgrade - $ sign wont work - by the remote login... (#541)


Have you tried using the "type" option when entering the password?

**Comment by MailYouLater** [comment] 2019-10-08 21:58
We can't see the image you attached.  Could you log into github and post it directly to https://github.com/Ylianst/MeshCentral/issues/541 instead of sending it by email? That way we should be able to see what you mean.

**Comment by Ylianst** [comment] 2019-10-08 23:32
One test to try is to change the remote keyboard to US English (US-EN) and try again. I think the problem is that the $ key and many other keys are re-mapped my the remote keyboard. So if the remove keyboard is French or German, you send a key and it gets re-mapped.

The solution is for the MeshAgent to be able to send keyboard characters without them being re-mapped by the remote keyboard layout. Bryan will be looking into this.

**Comment by wvt-adm** [comment] 2019-10-09 12:35
![spezial sign - not dollar](https://user-images.githubusercontent.com/56296924/66481767-de328d80-eaa1-11e9-8472-e6ec92bfdf8e.png)

this is the sign that i receive... by using the type function...

**Comment by MailYouLater** [comment] 2019-10-09 19:04
You state in the opening post that you've updated the MeshCentral server. Are you saying that this used to work correctly for you, but doesn't any more? If so, what version were you on previously?

Also, with the new information you've given, I'm fairly certain this is a duplicate of #469.

**Comment by wvt-adm** [comment] 2019-10-10 01:14
very special, 

initial situation: on my computer with win10pro swiss german keyboard - connection to a win10pro also swiss german keyboard 

-> with firefox 69.0.2 64bit the problem $ ect. exists 
-> but if i use internet explorer or the edge on the same computer all characters work exactly as they should... so there should be a firefox problem... so im not really shure with witch browser i have tested by the beginning... sorry.

(i hope that i now post this in the right place...)

ps. also tested with a win8.1pro computer - exactly the same.

Translated with www.DeepL.com/Translator

**Comment by dinger1986** [comment] 2023-11-12 17:04
im sure this is fine now @si458

**Comment by si458** [comment] 2023-11-12 20:33
i believe this is fixed now, you can also use the 'use remote keyboard map' under 'settings' which should help you!

**Closed by si458** 2023-11-12 20:33 UTC
Labels: bug
