### ISSUE TITLE
Assistance with SSH through relay

### ISSUE THREAD

**Issue by takuy** [Ylianst/MeshCentral#5394] opened 2023-10-06 00:53 UTC
**Describe your issue**
Hey, I'm having issues with getting SSH to connect to another device through a relay. The agent itself to the relay is working fine, all features work, but I'm not able to SSH/SFTP through the relay into other linux devices. From those devices themselves, I can connect to the targeted devices via SSH/SFTP fine. 

Looking for help troubleshooting where this is failing. It prompts for a username & password, which I entered, and then it just freezes at "Setup..."

**Server Software (please complete the following information):**
 - OS: alpine:3.15.2
 - Virtualization: Docker
 - Network: LAN/WAN
 - Version: 1.1.11
 - Node: 16.16.0

**Relay Device:**
 - Device: Desktop
 - OS: Windows 10 22H2
 - Network: Different VLAN on same network
 - Current Core Version (if known): Dec 9 2022, 2577413753

**Your config.json file**
```
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "settings": {
    "cert": "example.com",
    "WANonly": true,
    "TlsOffload": "aaaa",
    "_LANonly": true,
    "trustedProxy": ["172.0.0.0/8"],
    "sessionKey": "aaaa",
    "port": 443,
    "redirPort": 80,
    "relayDNS": "relay.example.com",
    "MpsPort": 0,
    "_redirAliasPort": 80,
    "_agentLogDump": true,
    "AgentPong": 300,
    "SelfUpdate": false,
    "AllowFraming": "false",
    "cookieIpCheck": false,
    "WebRTC": "false",
    "debug": true,
    "MariaDB": {
      "host": "example.com",
      "user": "meshcentral",
      "password": "pp",
      "database": "meshcentral"
    }
  },
  "smtp": {
     "host": "smtp.example.com",
     "port": 25,
     "from": "noreply@oexample.com"
  },
  "domains": {
    "mesh": {
      "title": "Org",
      "title2": "My Org",
      "newAccounts": false,
      "footer": "Org",
      "unknownUserRootRedirect": "/mesh/auth-saml",
      "showPasswordLogin": false,
      "ssh": true,
      "novnc": true,
      "ipkvm": true,
      "CertUrl": "https://blah:443/",
      "consentMessages": {
        "consentTimeout": 30,
        "autoAcceptOnTimeout": true
      },
      "ManageAllDeviceGroups": [ "myusers"],
      "deviceMeshRouterLinks": {
        "rdp": false, "ssh": false, "scp": false
      }
  }
}

```

**Comment by takuy** [comment] 2023-10-08 21:15
Actually just noticed this error in the container logs when trying to connect to SSH through a relay:

```
TypeError: Assignment to constant variable.
    at startRelayConnection (/opt/meshcentral/node_modules/meshcentral/apprelays.js:1553:40)
    at WebSocket.<anonymous> (/opt/meshcentral/node_modules/meshcentral/apprelays.js:1675:25)
    at WebSocket.emit (node:events:527:28)
    at Receiver.receiverOnMessage (/opt/meshcentral/node_modules/ws/lib/websocket.js:720:20)
    at Receiver.emit (node:events:527:28)
    at Receiver.dataMessage (/opt/meshcentral/node_modules/ws/lib/receiver.js:414:14)
    at Receiver.getData (/opt/meshcentral/node_modules/ws/lib/receiver.js:346:17)
    at Receiver.startLoop (/opt/meshcentral/node_modules/ws/lib/receiver.js:133:22)
    at Receiver._write (/opt/meshcentral/node_modules/ws/lib/receiver.js:69:10)
    at writeOrBuffer (node:internal/streams/writable:389:12)
```

@si458 @Ylianst should this be considered a bug?

**Comment by si458** [comment] 2023-10-08 22:02
First q, are u using cloudflare? If so, there is still an outstanding issue with cloudflare. It was supposed to be fixed by them like a week ago, but people are still having issues

**Comment by si458** [comment] 2023-10-08 22:11
So you have setup a first device in a group and u can use the ssh connect in the Web ui no problem

But if u setup a relay group and set the relay device as the first device, then add a second device in and try to use the ssh connect in the Web ui, it's not working?

Can u ssh from the first device to the second device, ok?

Is ur first device a lan device to meshcentral or is it remote?

I'll have to test when I'm in the office 2moz

What is the os of the first and second devices?

**Comment by si458** [comment] 2023-10-08 22:35
Hmmm, I'm seeing the same thing, but no error, which is weird?
I'll have a look 2moz when I'm in the office

**Comment by takuy** [comment] 2023-10-08 23:13
> So you have setup a first device in a group and u can use the ssh connect in the Web ui no problem
First device is a Windows device (tried both a Windows Enterprise, as well as Windows Server device), so SSH isn't a thing but Web RDP/Terminal work fine.

> But if u setup a relay group and set the relay device as the first device, then add a second device in and try to use the ssh connect in the Web ui, it's not working?
Yep. 

> Can u ssh from the first device to the second device, ok?
Yep. I'm able to SSH from the first device (from both Putty and Windows shell) to the second device just fine. 

> Is ur first device a lan device to meshcentral or is it remote?
Technically remote. It's in the same network but different VLAN. 

> What is the os of the first and second devices?

First = Windows Server 2019, but have also tried a Windows 10 2019 Enterprise device.
Second = RHEL 7, but have also tried Ubuntu (I think)


Thanks for any help you can provide! It's pretty weird.

**Comment by takuy** [comment] 2023-10-13 14:55
I've updated to the latest version (1.1.13) of MeshCentral since I saw some fixes for SSH were included. Same issue.

**Comment by si458** [comment] 2023-10-13 15:46
@takuy still looking into it for you, im away for the weekend, so will look next week 👍

**Comment by takuy** [comment] 2023-11-15 02:19
> @takuy still looking into it for you, im away for the weekend, so will look next week 👍

Hey, just checking in to see if you had a chance to look at this. I'm happy to test anything!

**Comment by si458** [comment] 2023-11-15 10:08
Sorry been poorly so not been coding much, will have a look when I get chance for you!

**Comment by takuy** [comment] 2024-01-16 06:06
> Sorry been poorly so not been coding much, will have a look when I get chance for you!

Hey, happy new year! Hope things have gone up for you :)
 
I'm still having issues with this, but also with Web Relays... I'm just not sure if this is a code error or if we have things horribly configured. It's almost the same exact error 🤷‍♂️ 

```
HTTPHEADERS: GET /control-redirect.ashx?n=node/mesh/cuY@u77nR59s8FyhuWY1Hg1Abk7TVp9hOoy0JAVOAWQbhxKFrFLo2uha@NEpR0zn&p=443&appid=2&c=xUh7m7wGHAbOuAMnUhUjCZCa5Hh5IFcVs7LvTErBGQKtfwfI38KrD@mr5$1B3Ic$Zcc@ziIT1MaH3aBCImf1kjPC9qPP0YzSM3ThmnIA1wgvSL@oJq4Gx8V$mzRjbIMSluaa&addr=myip&relayid=node/mesh/hEigWZ$UL31jrTczweKbsqzdN8@qBz7EQO7nAQyHscGe3Paj0vfSAg5SlcLyxS7o 

WEB: webRelaySetup

COOKIE: Decoded AESGCM cookie: {"ruserid":"user/mesh/~saml:myusername","x":"N6coreng","time":1705384460000,"dtime":94048}

WEBRELAY: CreateWebRelaySession, userid:user/mesh/~saml:myusername, addr:myip, port:443

WEBRELAY: handleRequest, url:/
WEBRELAY: launchNewTunnel
RELAY: TCP: Request for web relay

COOKIE: Encoded AESGCM cookie: {"userid":"user/mesh/~saml:myusername","domainid":"mesh","nodeid":"node/mesh/hEigWZ$UL31jrTczweKbsqzdN8@qBz7EQO7nAQyHscGe3Paj0vfSAg5SlcLyxS7o","tcpport":443,"tcpaddr":"myip","time":1705384554}

TypeError: Assignment to constant variable.
    at Object.obj.connect (/opt/meshcentral/node_modules/meshcentral/apprelays.js:462:40)
    at launchNewTunnel (/opt/meshcentral/node_modules/meshcentral/apprelays.js:205:16)
    at handleNextRequest (/opt/meshcentral/node_modules/meshcentral/apprelays.js:162:9)
    at Object.obj.handleRequest (/opt/meshcentral/node_modules/meshcentral/apprelays.js:129:9)
    at handleWebRelayRequest (/opt/meshcentral/node_modules/meshcentral/webserver.js:7294:30)
    at /opt/meshcentral/node_modules/meshcentral/webserver.js:6966:74
    at Layer.handle [as handle_request] (/opt/meshcentral/node_modules/express/lib/router/layer.js:95:5)
    at next (/opt/meshcentral/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/opt/meshcentral/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/opt/meshcentral/node_modules/express/lib/router/layer.js:95:5)

```

**Comment by si458** [comment] 2024-01-16 11:39
what version are you currently running?
line 462 seems to only relate to assigning values? nothing special?
what does your config.json look like? (share plz hide sensitive info)
https://github.com/Ylianst/MeshCentral/blob/6e2321b5c65438a4ac079026d6cb411020c3e50f/apprelays.js#L462

**Comment by takuy** [comment] 2024-01-16 15:24
> what version are you currently running? line 462 seems to only relate to assigning values? nothing special? what does your config.json look like? (share plz hide sensitive info)
> 
> https://github.com/Ylianst/MeshCentral/blob/6e2321b5c65438a4ac079026d6cb411020c3e50f/apprelays.js#L462
> 
> EDIT: if your config.json is the same as above, try changing
> 
> ```
>   "domains": {
>     "mesh": {
>       "title": "Org",
> ```
> 
> to
> 
> ```
>   "domains": {
>     "": {
>       "title": "Org",
> ```
> 
> as this is the domain.id and if you only have a single domain then this should be BLANK, it shouldnt have a name in it

Running 1.1.18. Config is the same as above. We're serving the meshcentral frontend through `suborg.myorg.tld/mesh` (per https://github.com/Ylianst/MeshCentral/issues/2323) - so we're ignoring that a parent `/` mesh site technically exists. The relay we have on it's own proper subdomain though (ie `relay.suborg.myorg.tld`)

Though isn't that the problem right there? the `url` var is defined as a const, and then being modified in the next line.

```js
            const url = protocol + '://localhost:' + args.port + '/' + domainadd + (((obj.mtype == 3) && (obj.relaynodeid == null)) ? 'local' : 'mesh') + 'relay.ashx?p=14&auth=' + cookie; // Protocol 14 is Web-TCP
            if (domain.id != '') { url += '&domainid=' + domain.id; } // Since we are using "localhost", we are going to signal what domain we are on using a URL argument.
```

It's the same for the line referenced for the SSH relay issue. 
https://github.com/Ylianst/MeshCentral/blob/6e2321b5c65438a4ac079026d6cb411020c3e50f/apprelays.js#L1552C1-L1554C1

**Comment by si458** [comment] 2024-01-16 15:26
oh, thats a unique use case you have! so you dont use the default `""` you use a SUBDOMAIN instead...
ill have a look when i get chance for you 👍

**Comment by si458** [comment] 2024-01-16 15:42
OK I CAN REPLICATE!!!, created a new subdomain, added a device to agent group, then created relay ground, then tried to use the ssh connect and get the same error
it seems on first looks, the relay doesnt work IF your subdomain doesnt have a DNS name, so will investigate for you 👍

**Comment by takuy** [comment] 2024-01-16 15:52
I tested this on my own instant - replaced the declaration of "const url" with "let url" in these places and it seems to work:

https://github.com/Ylianst/MeshCentral/blob/6e2321b5c65438a4ac079026d6cb411020c3e50f/apprelays.js#L461

https://github.com/Ylianst/MeshCentral/blob/6e2321b5c65438a4ac079026d6cb411020c3e50f/apprelays.js#L1213

https://github.com/Ylianst/MeshCentral/blob/6e2321b5c65438a4ac079026d6cb411020c3e50f/apprelays.js#L1552

https://github.com/Ylianst/MeshCentral/blob/6e2321b5c65438a4ac079026d6cb411020c3e50f/apprelays.js#L1906

**Comment by si458** [comment] 2024-01-16 15:54
@takuy you just beat me too it, was just about to comment saying yeh thats all the problem is haha, do commit soon for you

**Comment by si458** [comment] 2024-01-16 15:58
done commit for you, used `var` instead to keep in style with the coding (dont ask) 👍 
will be in next release or as you found, just replace the `const` with `var` or `let`

**Closed by si458** 2024-01-16 15:58 UTC
Labels: question
