### ISSUE TITLE
black screen

### ISSUE THREAD

**Issue by kylelliott** [Ylianst/MeshCentral#3916] opened 2022-04-25 21:09 UTC
getting black screen when remoting in at home but at work it works prefect

**Comment by krayon007** [comment] 2022-04-25 21:10
Does it say it's connecting with webrtc? I know there is currently an issue with chrome, but I haven't root caused the issue with the recent chromium update that broke webrtc.

**Comment by poiNt3D** [comment] 2022-05-11 05:19
Sometimes black screen appears when you connect to Windows machine with locked screen after unlocking it. Reconnecting helps in this case.

**Comment by krayon007** [comment] 2022-05-11 06:18
I just fixed a webrtc interop issue with Chrome and Edge, that caused a black screen. This will be in the next agent update.

**Closed** 2023-12-31 15:14 UTC
Labels: bug
