### ISSUE TITLE
RPi icon is missing..

### ISSUE THREAD

**Issue by VM-2020** [Ylianst/MeshCentral#1286] opened 2020-05-03 15:58 UTC
We do install RPi or Asus TB/S boards in our integration modules for I/O monitoring and lots of other stuff - when I select the RPi icon it shows the one on the left.

**Comment by Ylianst** [comment] 2020-05-03 16:10
What version of the server are you using and can you send screenshots of where you click to select the RPi icon and what you see? I just did a quick test and works for me.

**Comment by ryanblenis** [comment] 2020-05-03 16:42
A fix for this was implemented for 0.5.14 (since whenever the virtual machine icon was added, I believe around 0.5.10 ish), so I'd imagine you're running an older version.

**Comment by VM-2020** [comment] 2020-05-04 05:44
We're running version 0.5.12 - the icon on the left from the RPi icon comes up.
![image](https://user-images.githubusercontent.com/59306301/80938847-e3a74a80-8dda-11ea-8028-39cd7857239e.png)

**Comment by Ylianst** [comment] 2020-05-04 07:58
Yes, this is a duplicate of #1228 and was fixed in 0.5.14.

**Closed** 2020-05-07 06:58 UTC
Labels: Fixed - Confirm & Close, duplicate
