### ISSUE TITLE
RDP broken

### ISSUE THREAD

**Issue by coolwormgit** [Ylianst/MeshCentral#1149] opened 2020-04-13 12:54 UTC
i have meshcentral in windows 10 as server and after update to 0.5.1-q and RDP is broken now....

thanks

**Comment by uldiseihenbergs** [comment] 2020-04-13 13:38
looks like the same. i can connect with telnet to localhost:<forwarded port>, but connecting with RDP takes forever..

**Comment by Ylianst** [comment] 2020-04-13 16:31
Working on it, will be fixed shortly.

**Comment by Ylianst** [comment] 2020-04-13 16:39
Published MeshCentral v0.5.1-r with a fix for this.

**Comment by ryanblenis** [comment] 2020-04-13 16:43
=P I'll stop my digging then. Thanks!

While you're in there, I was just was noticing though that `rights` both before and after the change is always `undefined` as you're getting them from `rights.rights` whereas the `rights` var, upon inspection, is actually just an integer.

**Comment by uldiseihenbergs** [comment] 2020-04-13 16:43
Confirmed, it's fixed for me.

**Comment by coolwormgit** [comment] 2020-04-13 19:50
fixed :) thanks

**Closed** 2020-04-13 19:52 UTC
Labels: Fixed - Confirm & Close, bug
