### ISSUE TITLE
Feature Request: history and autocomplete terminal on Linux hosts 

### ISSUE THREAD

**Issue by D4V3M0NK** [Ylianst/MeshCentral#250] opened 2019-05-28 19:12 UTC
After prepping for some time, today I finally moved a couple of "live" systems into my MeshCentral system.  I understand that the terminal has improved since inception, but I wonder if I could once more put a couple of really useful abilities into the feature request of the terminal.

1. autocomplete : use of the <TAB> key to complete the rest of the command

1.  history : being able to use the <UP> and <DOWN> keys to reference previous commands

Really liking where this is all heading Ylian, congrats to you and your team again for your continued work on this

**Comment by Ylianst** [comment] 2019-05-29 01:13
Thanks. Your right, the terminal need improvements. Are you asking about the Linux terminal? Or Windows? On Linux, I think the problem is that we shell into a root terminal without VT100 settings and so, some keys are messed up. I need to take a look at this.

**Comment by D4V3M0NK** [comment] 2019-05-29 01:45
At the moment, I'm working exclusively on Linux, so yes, I'm referring to the Linux Terminal. I remember that there was a potential library that was potentially being looked at that might offer an expeditious resolution, although I'm not sure I remember its name ("xterm" perhaps?).  Additionally, if there's a way of invoking the Linux terminal without shell-ing into the root account, that would be totally awesome.

**Comment by Ylianst** [comment] 2019-05-30 03:33
I will fire up my Linux machine and take a look at this. When starting a new root terminal, I write a few commands to get color working, I will check if I can figure out how to get the keys working right so you get bash history and tab auto-complete.

**Comment by Ylianst** [comment] 2019-05-30 16:54
Published MeshCentral v0.3.5-n with correct shell in the terminal on Linux. Tab auto-complete and up/down history now works!

**Comment by D4V3M0NK** [comment] 2019-05-30 16:58
Ylian,
MASSIVE improvement, so much more usable - thank you!!!  ...  However, "vi" seems to hang, irrespective of editing an existing, or new, file.

**Comment by Ylianst** [comment] 2019-05-30 17:00
Ha... your right, I just tried vi and see the same problem, pico seems to work... Looking into it.

**Comment by Ylianst** [comment] 2019-05-30 17:18
I am not a vi user, but it does seem to work. At first I typed "vi" and could not type anything, but the I realized ":quit" works. If I type "vi bob.txt" which is a new file, you have to type capital-I to insert a new line before the cursor and it worked. I hit esc and then ":quit!", that also works. Editing an existing file also works, I just needed to figure out how vi works. Can you confirm you see the same?

**Comment by D4V3M0NK** [comment] 2019-05-30 17:22
I don't see the same. When I connect to Ubuntu 14.04.5 LTS, it just seems to freeze the terminal (screenshot attached)
![viFreezesMeshCentral0 3 5-n](https://user-images.githubusercontent.com/7572742/58650942-dc231b80-82c4-11e9-938c-e8acb0c41a30.png)

**Comment by Ylianst** [comment] 2019-05-30 17:29
Oh... well, that is different indeed. I don't see that on my Raspberry Pi and old Ubuntu 10.04 LTS. I will need to try more Linux variants.

**Comment by D4V3M0NK** [comment] 2019-05-30 17:34
Ubuntu 16 works just fine

**Comment by D4V3M0NK** [comment] 2019-05-30 17:40
Ubuntu 18 works just fine - although when opening up a new file, I see some odd characters at the top of the file
![viOddCharsMeshCentral0 3 5-n](https://user-images.githubusercontent.com/7572742/58651953-59e82680-82c7-11e9-8110-e1555846b13d.png)

**Comment by Ylianst** [comment] 2019-05-30 17:57
I can fix the odd chars. That is an escape sequence I don't handle yet. I will add it.

**Comment by Ylianst** [comment] 2019-06-04 05:50
FYI. I figured out these garbage characters on the terminal and will have a fix tomorrow.

**Comment by Ylianst** [comment] 2019-06-04 20:45
Published MeshCentral v0.3.5-y that now supports some xTerm escape codes and ignores the others. The one I support is to change the windows title. In that case, it will be displayed above the terminal on the web app. Hopefully we can close this issue and start now ones as this one is getting long :)

![MC2-XTermTitle](https://user-images.githubusercontent.com/1319013/58911826-8fc54a80-86cd-11e9-845b-bd42e8674704.png)

**Comment by D4V3M0NK** [comment] 2019-06-04 21:45
I'm still seeing a 'c' when I open a new file - existing files work perfectly.
![meshViTerminalEscapeCode](https://user-images.githubusercontent.com/7572742/58916049-64475d80-86d7-11e9-8207-b4ca4f27e9d4.png)

**Comment by Ylianst** [comment] 2019-06-05 00:22
I don't see the "c" on my ubuntu, but getting close. Can you open the debug console in the browser and see there are any error messages? Especially "unknown terminal code". If so, send over the exact error message.

**Comment by D4V3M0NK** [comment] 2019-06-05 00:53
[MeshCentralUnknownTerminalCodes0.3.5-y.log](https://github.com/Ylianst/MeshCentral/files/3255032/MeshCentralUnknownTerminalCodes0.3.5-y.log)

**Comment by Ylianst** [comment] 2019-06-05 00:55
That is exactly helpful! Thanks!

**Comment by si458** [comment] 2023-10-03 15:25
history and autocompleted implemented already

**Closed by si458** 2023-10-03 15:25 UTC
Labels: enhancement

**Comment by Suncatcher** [comment] 2026-04-25 18:19
>history and autocompleted implemented already

@Ylianst  @si458  for me it doesn't work. The host is Debian 13 Trixie. Any thing I need to check?

**Comment by si458** [comment] 2026-04-25 18:23
@Suncatcher for history to work, you MUST type `exit` in the terminal session and let it exit that way
DONT just click `disconnect` as it then loses what you typed etc

**Comment by Suncatcher** [comment] 2026-04-25 19:12
@si458 thanks, that worked. Any way to automate this? Does MC have any sort of post-disconnect auto-scripts?

**Comment by si458** [comment] 2026-04-25 19:13
@Suncatcher im not 100% sure, its only something ive noticed!
i think it would be better you open up an issue about it (include all details in bug report)
and we can look into why it doesnt save the history etc if you just click `Disconnect`

**Comment by Suncatcher** [comment] 2026-04-25 23:31
@si458 created the bug https://github.com/Ylianst/MeshCentral/issues/7769
