### ISSUE TITLE
The problem of connecting to the terminal in Windows 7 32-bit

### ISSUE THREAD

**Issue by bravery-only** [Ylianst/MeshCentral#4615] opened 2022-10-08 21:50 UTC
![Screenshot_3](https://user-images.githubusercontent.com/42680639/194728903-7160e638-778c-468d-8820-4224a17b1f3b.jpg)
The problem of connecting to the terminal in Windows 7 32-bit
help for solve this problem

**Comment by krayon007** [comment] 2022-10-08 22:37
Please refer to #4435. The root cause was determined to be a change in minification, which ended up deleting the ESC control character in win-terminal. You can refer to that thread for guidance on how to disable minification for now, until I fix the minification tool.

**Comment by si458** [comment] 2022-10-09 06:48
My pr #4595 was merged already so
 if u npm install directly from the git repo, the fix is already implemented too

**Comment by bravery-only** [comment] 2022-10-09 10:54
delete this folder and fixed. folder : modules_meshcore_min

**Comment by si458** [comment] 2022-10-16 21:33
@bravery-only please can you close this issue

**Closed** 2024-11-27 15:04 UTC
Labels: bug
