### ISSUE TITLE
At creating new user, set user/devices groups membership

### ISSUE THREAD

**Issue by hunter-nl** [Ylianst/MeshCentral#380] opened 2019-07-25 11:00 UTC
When creating a new user it would be nice if the new user account in the same creation dialog window can be added as member to user and device groups.

**Comment by hunter-nl** [comment] 2019-07-27 09:49
When the administrator creates a new user and administrator is member of any group, then the administrator can not see the newly created user, because the newly created user is not member of any groups at all.
So now I have to remove all the group membership of the administrator account to see the new user account. Put the new user into the needed (device) groups and set the administrator account back to the required group memberships.

**Comment by Ylianst** [comment] 2019-07-27 17:16
The expected behavior is that when you create a new account, the new account should automatically get all of the groups of the user creating it. If not, this is a bug. I will check and fix this.

On a related topic, this type of user group may need to be renamed to "sub-domain group" or "domain realm" or something. I may create user groups in for assigning permissions on the future, but these groups are for controlling what accounts "sub-administrators" can manage.

**Comment by Ylianst** [comment] 2019-07-28 19:21
Your 100% right, that was bad. Just published MeshCentral v0.3.8-q with a fix for this.

Also, would you (and anything else) be ok if I rename "user groups" to "Domain Realms" or "User Realms"? The current "user groups" and really a way for a sub-administrator to manage a sub-set of users. So maybe these are "Realm Administrators" and some users are part of that "Realm".

I may way to make this change since "Groups" or "User Groups" will be used to groups a bunch of users so you can do batch operations on them like, assign them to a device group to do group chat, etc. in the future. Feedback on this welcome.

**Comment by hunter-nl** [comment] 2019-07-29 10:18
Yes, This has been fixed.

Or just call it "Realms". And when you introduce groups. Make it also possible to add groups as member to a realm.

**Comment by Ylianst** [comment] 2019-07-29 17:51
Thanks. Will close this and look at renaming to Realms.

**Closed by Ylianst** 2019-07-29 17:51 UTC
Labels: Fixed - Please Confirm, bug
