### ISSUE TITLE
Turn off remote display for privacy

### ISSUE THREAD

**Issue by andreapx** [Ylianst/MeshCentral#5038] opened 2023-03-13 10:59 UTC
**Is your feature request related to a problem? Please describe.**
When I connect to my PC remotely, everyone that passes near it can see what I'm doing

**Describe the solution you'd like**
There should be a way to turn the screens black while from remote I can still see them.

**Describe alternatives you've considered**
I can't see any.

**Comment by dinger1986** [comment] 2023-03-13 11:00
this is already open https://github.com/Ylianst/MeshCentral/issues/416

**Comment by andreapx** [comment] 2023-03-13 11:04
Dammit, I've searched, but I couldn't find it.
Thanks!

**Comment by OutbackMatt** [comment] 2023-03-14 05:35
I use RDP if I want privacy (via the MeshRouter)

**Comment by andreapx** [comment] 2023-03-14 08:19
> I use RDP if I want privacy (via the MeshRouter)

We all use 2 displays and RDP only supports one.

**Comment by OutbackMatt** [comment] 2023-03-14 22:19
I know that to be an incorrect statement when talking about Windows 10 or 11 (even via MeshCentral)
How old is that machine that you are connecting to, and what OS is being used,

**Comment by andreapx** [comment] 2023-10-09 16:32
> I know that to be an incorrect statement when talking about Windows 10 or 11 (even via MeshCentral) How old is that machine that you are connecting to, and what OS is being used,

Sorry, I completely missed your reply.
The PC is about 5 years old with the latest version of Windows 10

**Comment by OutbackMatt** [comment] 2023-10-09 20:14
https://techcommunity.microsoft.com/t5/security-compliance-and-identity/using-multiple-monitors-in-remote-desktop-session/ba-p/246840

Multimon has been available as an option for RDP since Windows 7 and Server 2008R2

**Comment by dinger1986** [comment] 2023-11-12 16:43
duplicate of #416 @si458 please close

**Closed** 2023-11-12 17:09 UTC
Labels: enhancement
