### ISSUE TITLE
Don't require user consent if no one is signed in, or allow connection after a timeout

### ISSUE THREAD

**Issue by takuy** [Ylianst/MeshCentral#4154] opened 2022-06-22 04:22 UTC
**Is your feature request related to a problem? Please describe.**
If no one is logged into a computer, there's no way to respond to a connection confirmation prompt or connect to the device. 

**Describe the solution you'd like**
MeshCentral should allow you to automatically connect in cases when no one is signed in. OR, automatically connect within 30 seconds if the prompt is not responded to (in the case a user forgot to sign out). 

Maybe a user permission for like, "connect anyway?" if someone is signed in. Makes the connect consent more of a suggestion, but gives a user at the computer the opportunity to decline.

I support a lot of "public use" PCs where everyone logs in with their domain credentials, and often time users forget to log out. I'd like to use MeshCentral to take control/support even in cases where no one is physically at the device - regardless of login state. RDP is not always suitable for this case, because some features get disabled when connected via RDP. Mesh's native capability is great because it allows you to act as if you're at the PC. 

I'm really giving a few suggestions / requests here:

1. Don't require user consent if no one is signed in
2. A setting to disregard user consent requirement after a timeout period (ie if user doesn't respond to the consent in designated time)
3. A setting to allow specific users a way "override" the user's consent if they do not respond, "connect anyway?" unless they specifically decline

Maybe some of this is already available? Maybe I missed it in the docs. Let me know if that's the case. 

**Describe alternatives you've considered**

**Additional context**
Feature briefly discussed here: https://www.reddit.com/r/MeshCentral/comments/vby6c1/require_user_confirmation_only_if_a_user_is/

**Comment by silversword411** [comment] 2022-06-22 04:38
![2022-06-22_003809 - brave_MeshCentral_Documentation_-_Brave](https://user-images.githubusercontent.com/13395348/174944651-ce73de28-277d-4aa1-a945-ee4366de83fe.png)

Specifically looking for

`"autoAcceptOnTimeout"`

**Comment by takuy** [comment] 2022-06-22 04:51
> ![2022-06-22_003809 - brave_MeshCentral_Documentation_-_Brave](https://user-images.githubusercontent.com/13395348/174944651-ce73de28-277d-4aa1-a945-ee4366de83fe.png)
> 
> Specifically looking for
> 
> `"autoAcceptOnTimeout"`

Totally missed that as an option. That definitely solves one of my use cases. Ideally, consent wouldn't be required if no one is signed into the computer, but hopefully this'll work as a workaround. Thanks for pointing that option out!

**Comment by Ylianst** [comment] 2022-06-22 06:18
Ha yes, I was about to post back the following options to try adding this to the domain section of the config.json:

```
      "consentMessages": {
        "consentTimeout": 30,
        "autoAcceptOnTimeout": true
      },
```

I do agree that an additional option to auto accept on no-one logged in would be great. Bryan would have to see if the agent can detect this.

**Comment by si458** [comment] 2024-02-16 12:35
closing as this is partely completed as explained above but also duplicate of #2969

**Closed by si458** 2024-02-16 12:35 UTC
Labels: enhancement
