### ISSUE TITLE
Writing problem on remote computer

### ISSUE THREAD

**Issue by motapek** [Ylianst/MeshCentral#335] opened 2019-07-02 22:59 UTC
Hi
I have few problem write on remote computer.
My instal is Ubuntu 18.0.4 on Azure and mesh 0.3.6-y
1. When I type "-" (minus) on remote computer I don't get "-". Instead, it is replaced by on / off volume.
2. "+" and "=" don't work. When I type it nothing happens.
3. When I type "space" I get space, but with this I'm switching to Display1/Display2 switch and I can't write on.
4. When I use up and down arrows (attempts to call the last command on cmd) I switch between Display 1 and Dispaly 2
5. If at the time of writing I switch to other Window (alt-tab), after returning I can't continue writing. I need disconnect and connect again. Especially if I type in the password field.

I use Windows 10 with polish (programers) keyboard.
I use Fierefox.

**Comment by PathfinderNetworks** [comment] 2019-07-03 16:37
I think it's something to do with they keyboard being used and it sending different characters/data than what Mesh is expecting.  I have similar issues when remoting in to a device from my Lenovo X1 Carbon (with the US keyboard).  I think it's due to the keys being used for non-standard multiple functions (at least in regards to the Lenovo).

**Comment by MailYouLater** [comment] 2019-07-03 21:19
Your 5th issue is likely because the remote computer thinks you're still holding the the <kbd>Alt</kbd> key, so after having <kbd>Alt</kbd>+<kbd>Tab</kbd>bed out, and then brought the focus back to the remote connection (e.g. by clicking back in the remote control area) it'll act like each key is <kbd>Alt</kbd>+whatever key you're really pushing.  You can mitigate this issue by pressing and releasing the <kbd>Alt</kbd> key after returning to the remote connection.  For future discussion of this issue see #330.

The other issues are likely as @PathfinderNetworks says.  What are the keyboard layouts set to on the machine you're controlling, and the machine you're operating it from? and do either of them have non-standard keyboards? (e.g. laptops with <kbd>fn</kbd> key)

**Comment by motapek** [comment] 2019-07-04 08:40
Hi
I tried different computers to different remote computers. It was always the same.
I tried Asus laptop, HP laptop and my son's normal PC.
All computers was windows 10 with polish (programmers) keybord.
In p.3 when I view two monitors from remote computer in mesh windows "space" work normaly.

**Comment by motapek** [comment] 2019-07-04 10:31
Hi 
I tested few web browser and:
Edge - all work OK
Edge Chrom - all work OK
Opera - all work OK
Chrome - all work OK
Vivaldi - all work OK
All symptoms are only in Firefox !
???

**Comment by MailYouLater** [comment] 2019-07-04 22:20
Is there possibly something non-standard about your Firefox configuration?
I recommend you download Firefox Portable from PortableApps.com, install it to a temporary location (e.g. a folder on your desktop), _fully_ exit your local install of Firefox, and test this in Firefox Portable _without_ making any changes to it's configuration.  This should demonstrate if it's caused by Firefox settings you've set.

**Comment by motapek** [comment] 2019-07-04 22:47
In first I disabled all add-ons in my Firefox - without effect - the same symptoms
After this I downloaded Firefox Portable and run it - symptoms are this same.
On my son's PC in Firefox is this same.
I don't have any idea.

**Comment by MailYouLater** [comment] 2019-07-04 22:51
What language do you have Windows set to? and/or what language did you set during the installation of Firefox Portable?  I'm not sure, but it's possible that would affect it.

**Comment by motapek** [comment] 2019-07-04 22:57
Both computers (my and remote are Polish language with keyboard - polish (programmers).
My installed Firefox is polish language but Firefox portable is English US.

**Comment by MailYouLater** [comment] 2019-07-04 23:34
OK, so your issue is occurring using both a local Firefox install with language set to Polish, and a fresh Firefox Portable with language set to US English on a Windows 10 PC with the language set to Polish and keyboard set to Polish (Programmers) when connecting to another computer.  You are able to connect to the same computer without experiencing the issue if you connect using Edge, Chrome, Opera, or Vivaldi, so we can safely assume that it's an issue occurring in the browser, not in the agent.

Can you also test if you still experience the issue if you switch the keyboard layout from Polish (Programmers) to either Polish (not-programmers) or English? or if it's specific to the Polish (Programmers) keyboard layout.

I had to lookup these keyboard layouts, so for reference:
[Polish](http://kbdlayout.info/00010415/)
[Polish (Programmers)](http://kbdlayout.info/00000415/)
[English (United States)](http://kbdlayout.info/00000409/)

**Comment by Ylianst** [comment] 2019-07-05 22:28
Just published MeshCentral 0.3.7-h with (hopefully) fixes for all of the issues reported in the original mail. 

- The "-" and "=" keys should be fixed in FireFox.
- When shift / alt / ctrl is pressed and the browser window is de-focused, these keys will be released.
- The multi-display up/down arrow should be fixed.

If you can test and confirm this now as expected, would be appreciated.

**Comment by motapek** [comment] 2019-07-08 07:08
Hi
It's working fine
Thanks.

**Comment by Ylianst** [comment] 2019-07-08 23:09
Thanks I will close this one, but please open a new issue if you find other problems.

**Closed by Ylianst** 2019-07-08 23:09 UTC
Labels: Fixed - Please Confirm, bug
