### ISSUE TITLE
Improvment logon on multiple clients

### ISSUE THREAD

**Issue by gally11** [Ylianst/MeshCentral#4604] opened 2022-10-05 13:00 UTC
Hi, 

I love Meshcentral, it's a real benefic for us in our IT service.

I just have a function who isn't exist in Meshcentral but I used with another software , it's maybe a possible improvment: https://veyon.io/en/

The function is the possibility to logon on all selected computers with the same account, exemple connect the administrator account on all computers of a computer room.

If this option could be add on Meshcentral, it's very an excellente idea ;)

Thanks Ylian for all that you do, Mesh is great !

Guillaume
IT tech in a french college.

**Comment by Otsegox** [comment] 2022-10-05 15:55
I asked for the same thing, recently. 
https://github.com/Ylianst/MeshCentral/issues/3557

**Comment by nounours460** [comment] 2022-10-05 17:28
Sorry, I look for "Improvment" only in opened issues.

**Comment by Otsegox** [comment] 2022-10-05 18:01
Don't me. It shows them it isn't only me! I just wanted to share.

**Comment by si458** [comment] 2024-02-17 16:04
duplicate of #3557

**Closed by si458** 2024-02-17 16:04 UTC
