### ISSUE TITLE
Agent mesh macOS Ventura

### ISSUE THREAD

**Issue by dmastero** [Ylianst/MeshCentral#4849] opened 2022-12-12 21:14 UTC
After I updated some mac on Ventura 13.0, mesh agent doesn't start anymore after a reboot. 
Anything that I'm missing ?

**Comment by krayon007** [comment] 2022-12-12 22:06
That's because I'm using the same same for the launch agent and launch daemon, which apparently Ventura doesn't like. I'm fixing the agent to use a different name. It's a bit more involved that I thought because of how agent customization is implemented. But if you delete the plist entry for the launch agent, the agent should start normally.

**Comment by dmastero** [comment] 2023-01-19 13:59
Hello Krayon

Doesn't work ... 
After a reboot, the agent doesn't start automatically

**Comment by dmastero** [comment] 2023-02-08 16:29
Hello Krayon 

Any update about this ?

**Comment by si458** [comment] 2023-02-08 18:35
> I had a small setback when I had to return my MacBook, but I now have a different Mac I can use for development, so I have to put together a new macos dev environment.

Give this a try,  I've used it a few times and it's amazing!!
https://github.com/sickcodes/Docker-OSX

**Comment by RichardBurt65** [comment] 2023-02-17 11:01
Any update to this?

**Comment by kay-kun** [comment] 2023-02-19 16:37
would love to have it working

**Comment by silversword411** [comment] 2023-02-20 19:51
Here's a fix outside of official: https://github.com/amidaware/community-scripts/blob/d1236f9b1309ba66d5938c8eae48c48cb8482a2c/scripts_staging/macos_fix_mesh_install.sh

**Comment by RichardBurt65** [comment] 2023-02-21 05:15
Fixed with a bit of jiggery-pockery.

There is only line in the script that matters. Simply run this in terminal:

`sudo defaults write "meshagent_osx64_LaunchAgent.plist" Label "meshagent-agent"`

I can confirm that meshagent now survives multiple reboots.

Issue finally fixed with a one-line hack.

**Comment by sandneck** [comment] 2023-03-29 18:55
Any progress on this one, updated my endpoint to Ventura now all require manual restart of the agent and no remote input when the agent is started.

**Comment by mrhhats** [comment] 2023-04-04 15:04
> 

Darn! I was so hoping this would fix on my end as well. Sadly no change :(

**Comment by rrmoore64** [comment] 2023-04-05 18:12
well, it happened to me too.  With the latest update to/on Ventura, mesh stops working after reboot.  Looking forward to updates on this critical issue.

**Comment by inzi** [comment] 2023-04-15 18:59
Same here - The command mentioned above didn't work for me either.

(this one: sudo defaults write "meshagent_osx64_LaunchAgent.plist" Label "mesh-agent" )

Best I've been able to do is get it to register and I can connect a remote desktop session, but I only see the mouse pointer. I'm unable to actually see any open windows, etc.

Has anyone else gotten it to work?

**Comment by yodaphone** [comment] 2023-05-06 23:13
the applescript worked for me

https://www.reddit.com/r/MeshCentral/comments/s8gleb/comment/htkwslh/?utm_source=share&utm_medium=web2x&context=3

**Comment by RichardBurt65** [comment] 2023-06-12 11:34
7+ months and no official fix for this??

**Comment by NiceGuyIT** [comment] 2023-06-12 11:44
@RichardBurt65 PRs are welcome. Nothing is stopping you from submitting the PR, or hiring a developer to submit the PR.

**Comment by RichardBurt65** [comment] 2023-06-12 11:58
> @RichardBurt65 PRs are welcome. Nothing is stopping you from submitting the PR, or hiring a developer to submit the PR.

I'm an end user, not a coder and why should I pay to fix their problem? If they're not planning on fixing it then maybe mesh should be considered abandonware for macOS 13 Ventura and all other future versions?

**Comment by dinger1986** [comment] 2023-06-12 12:03
> > @RichardBurt65 PRs are welcome. Nothing is stopping you from submitting the PR, or hiring a developer to submit the PR.
> 
> I'm an end user, not a coder and why should I pay to fix their problem? If they're not planning on fixing it then maybe mesh should be considered abandonware for macOS 13 Ventura and all other future versions?

who are you referring as "their"? Its opensource, you arent charged anything to use it!! Why should "they" give their development time to fix your problem? I am sure it will be fixed but again, its opensource and free, there is a fix sitting as a PR which I think will resolveit but maybe the devs are busy in their own lives and they have less time to give up for free? Im amazed by the sense of entitlement!!

**Comment by NiceGuyIT** [comment] 2023-06-12 12:10
> why should I pay to fix their problem?

conflicts with
> 7+ months and no official fix for this??

In case you didn't know, you might want to read the [MeshCentral news, Sponsorship and Opportunities][]. The funding that was previously provided by Intel by way of 2 full time employees has stopped. The funding now rests on the community. If the software is important to you, consider funding it. I assure you, though, comments like "7+ months and no official fix for this??" will NOT increase the funding or the desire to fix something by someone providing **their time FOR FREE**!

[MeshCentral news, Sponsorship and Opportunities]: https://github.com/Ylianst/MeshCentral/discussions/4795

**Comment by yodaphone** [comment] 2023-06-12 14:50
> > @RichardBurt65 PRs are welcome. Nothing is stopping you from submitting the PR, or hiring a developer to submit the PR.
> 
> 
> 
> I'm an end user, not a coder and why should I pay to fix their problem? If they're not planning on fixing it then maybe mesh should be considered abandonware for macOS 13 Ventura and all other future versions?

Dude.. are you for real?.. this is an open source software. You are more than welcome to stop using the product. No one will miss you

**Comment by Bewo** [comment] 2023-06-25 06:37
There's an easy solution which worked for me:
[](https://github.com/Ylianst/MeshCentral/issues/4822#issuecomment-1542789876)

**Comment by dinger1986** [comment] 2023-11-13 23:43
@si458 fix has been merged I believe

**Comment by si458** [comment] 2023-11-16 22:05
fix has been merged and the is a temporary solution listed above https://github.com/Ylianst/MeshCentral/issues/4849#issuecomment-1605896578

**Closed by si458** 2023-11-16 22:05 UTC
Labels: bug
