### ISSUE TITLE
win10 : remote control impossible when avast ui on screen

### ISSUE THREAD

**Issue by tranbert** [Ylianst/MeshCentral#633] opened 2019-11-05 09:04 UTC
When we launch any avast Ui element, no more remote control is working.

Remote screen is OK but no more interaction is possible. Terminal seems Ok too.

**Comment by PathfinderNetworks** [comment] 2019-11-06 01:22
I brought this up a while back and was hoping it could be resolved.  I also use Avast CloudCare and have the same issue.  Strange thing is that it doesn't happen 100% of the time. More like 75% of the time.  Always happens on devices where I have the Avast UI password protected though.

**Comment by tranbert** [comment] 2019-11-06 12:59
For my case : no password and avast free version french ui.

And it's a 100%...

**Comment by OutbackMatt** [comment] 2020-02-11 00:58
This happen for me too, and where the AVAST secure web browser is set to open on logon, I can do nothing with the machine. Rebooting it brings the secure web browser up straight away.

I've ONLY noticed there where the AVAST Cloudcare is installed. 
A client installed Cloudcare this last week, and suddenly I was faced with this issue on all of their computers

**Comment by MailYouLater** [comment] 2020-02-11 01:14
I don't use Avast so I don't know for sure, but you may still be able to send a <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>Del</kbd>, in which case you _may_ be able to use the Task Manager to close or minimize the offending window so that you can access the machine again.

**Comment by vitko-bg** [comment] 2020-02-11 16:06
Just add MeshAgent.exe and meshaget folder to exclusions. I had same problem - by some reason Avast UI is unbeatable - even with Ctrl+Alt+Del .............

**Comment by MailYouLater** [comment] 2020-02-11 18:01
> ... by some reason Avast UI is unbeatable - even with Ctrl+Alt+Del .............

Strange. Perhaps you could try going into the device's Console tab and running `power 9` to send the <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>Del</kbd>.  I don't know if it'll be any different or not, but it seems to me like it would be worth a try.

**Comment by ryanblenis** [comment] 2020-02-11 18:10
Possibly related for a similar input related issues via remote desktop access #892 #454. Perhaps they're using the same protection mechanism?

**Comment by MailYouLater** [comment] 2020-02-11 19:09
It may be related, but it is at least somewhat different.
The issue when controlling MS Edge is that the keyboard input doesn't seem to reach the page.  You can still use the mouse, and the keyboard still works in the location bar, and sending the <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>Del</kbd> key combo still works too.

Can someone who has this issue with Avast verify what exactly does and doesn't work? @vitko-bg says you can't send a <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>Del</kbd>. Can you still move the mouse? If so, what can/can't you click? Where can/can't you type? Any information may prove helpful.

**Comment by PathfinderNetworks** [comment] 2020-02-12 19:08
I use Avast CloudCare on all of my endpoints. What's very odd about this is that it doesn't seem to happen on every device. Like right now, I have a Server 2019 box I'm doing maintenance on so I figured I'd open up Avast and explain what happens.  But, low and behold, the Avast UI opened and was accessible while I was in remoted in via MeshCentral.  This one is even password protected.  Typically what would happen is that, as soon as the Avast UI would open (or the password screen would appear) the MeshCentral session would be locked from any input- no mouse or keyboard. Although the desktop is still visible and active.  In those cases I would have to go to the Premium Remote tool via Avast CloudCare to remote in to the device and close the UI.  As soon as the UI is closed then Mesh would have input access again.   
Avast just did update their agent to version 4.19.360 and I've been pushing that out to my devices- so maybe they've made some changes that have resolved this?  I'll have to keep testing other devices to confirm though because, as mentioned, it wouldn't always happen.

**Comment by krayon007** [comment] 2020-02-12 19:11
When I get some spare cycles I'll install the free version and see if I can reproduce it.

**Comment by PathfinderNetworks** [comment] 2020-02-12 19:12
I just tried another device- this time it is a Server 2012 box. As soon as the Avast UI opened I no longer have input access from MeshCentral.  Now, that said, it did allow me to send a Ctrl-Alt-Del. I chose Task Manager and that opened and is allowing me mouse and keyboard input.  But, as soon as I click the Avast UI screen I immediately lose keyboard/mouse input to the session.  If I send another Ctlr-Alt-Del and choose Task Manager again I have input.  If I close the Avast UI via Task Manager then I still have full input from Mesh. So there is something in the Avast UI that is blocking Mesh- at least some times.  
Bryan, if you wanted to try the paid version of CloudCare I could send you an installer using one of my NFR licenses.  That way you could test that as well.

**Comment by vitko-bg** [comment] 2020-02-12 23:16
To recreate problem, simply right click on Avast icon in the tray and select disable protection on all shields
 As soon as Avast Yes/No full screen notification is displayed - no actions can be performed... Only way via different soft, i.e RDP, TeamViewer, etc OR local click on Yes or No.....

**Comment by si458** [comment] 2024-11-27 12:01
this wont be fixed as its a security feature built into avast which stops remote agents from controlling there software

**Closed by si458** 2024-11-27 12:01 UTC
Labels: bug
