### ISSUE TITLE
folders transfer

### ISSUE THREAD

**Issue by payon** [Ylianst/MeshCentral#50] opened 2018-12-15 04:35 UTC
1. Can I transfer folders from a remote desktop?

2. Is it possible to paste the copy from the admin screen onto the remote desktop screen?

**Comment by Ylianst** [comment] 2018-12-22 18:21
I certainly need to add batch file transfers. Should not be a problem when uploading to the remote machine. I don't know about folder download however, would need to zip the folder on the remote side before download.

**Comment by Ylianst** [comment] 2018-12-22 18:21
Will check at some point for remote clipboard support.

**Comment by whalehub** [comment] 2019-03-10 20:44
@Ylianst Any update on this?

**Comment by krayon007** [comment] 2019-03-10 20:52
I'm working on getting the agent to tar the folder. There are some other bugs I got distracted with before finishing this. But support will be coming...

**Comment by Ylianst** [comment] 2019-07-14 17:11
Closing as this is a duplicate of #323

**Closed by Ylianst** 2019-07-14 17:11 UTC
Labels: duplicate
