### ISSUE TITLE
win7 client connect terminal then strange content in 1.0.81

### ISSUE THREAD

**Issue by jefflin0902** [Ylianst/MeshCentral#4540] opened 2022-09-12 03:57 UTC
**Describe the bug**
win7 client connect terminal then strange content

**To Reproduce**
1. Go to 'terminal'
2. Click on 'connect'
3.  See error

Screen screencapture

https://user-images.githubusercontent.com/97925204/189571542-fe3b8fae-a085-4f52-aaec-3620c9f4c78b.mp4

**Server Software (please complete the following information):**
 - OS: ubuntu
 - Virtualization: physical machine
 - Network: WAN
 - Version: 1.0.81
 - Node: v16.16.0

**Client Device (please complete the following information):**
 - Device: Desktop
 - OS: win10
 - Network: WAN
 - Browser:Google Chrome

**Remote Device (please complete the following information):**
 - Device: Desktop
 - OS: win7 pro
 - Network: WAN
 - Current Core Version (if known): 
Current Core: Aug 25 2022, 1360394467
Agent Time: 2022-09-12 11:55:50.986+08:00.
User Rights: 0xffffffff.
Platform: win32.
Capabilities: 15.
Server URL: wss://wwremote.winwayglobal.com:443/agent.ashx.
OS: Microsoft Windows 7 專業版  - 7601.
Modules: amt-apfclient, amt-lme, amt-manage, amt-mei, monitor-border, smbios, sysinfo, util-agentlog, wifi-scanner-windows, wifi-scanner, win-console, win-info, win-securitycenter, win-terminal, win-virtual-terminal, win-volumes.
Server Connection: true, State: 1.

**Comment by VINISHVV** [comment] 2022-09-12 06:22
Duplicate #4528 #4435

**Comment by KommunistGangsta** [comment] 2022-09-12 09:57
Restart your Mesh Server. It worked for me

**Comment by jefflin0902** [comment] 2022-09-12 11:42
I try update meshcenter server to 1.0.85 and reboot it, But the issue not be resolve.

**Comment by githubbiswb** [comment] 2022-09-30 16:13
I have this same issue

**Comment by silversword411** [comment] 2022-09-30 16:40
Please don't post to this issue, as vinishvv said this is a duplicate of https://github.com/Ylianst/MeshCentral/issues/4435 and it has been solved there.

**Comment by githubbiswb** [comment] 2022-09-30 17:25
My bad @silversword411 thanks for the heads up!

**Comment by silversword411** [comment] 2022-10-02 15:13
@jefflin0902 can you close this issue

**Closed** 2022-10-03 00:41 UTC
Labels: bug
