### ISSUE TITLE
Can HTTP Direct be added?

### ISSUE THREAD

**Issue by PathfinderNetworks** [Ylianst/MeshCentral#145] opened 2019-03-23 05:49 UTC
I was looking at the MeshCentral Router and was thinking this was going to replace the HTTP Direct tool that is in MeshCentral1.  But it doesn't appear it can do the same thing?  
The HTTP Direct tool in MeshCentral1 is very useful for when I need to connect to a http GUI for devices on a remote network- such as a printer or other devices.  It's nice because I don't need to take over a desktop session to open the GUI on those devices.  I can just open the site directly in a browser on the machine I'm working at.  Granted, not all websites work properly- but it's still handy tool to have.  Or can this actually be done through the MeshCentral2 router and I'm just not understanding how to do it?

**Comment by jsastriawan** [comment] 2019-03-23 05:56
Well, you could use MeshCentral router to tunnel TCP 80 or 443 for HTTPS. Additionally you could check mc2router repo. You could add custom tunnel which opens a browser to connect to local TCP port which will be forwarded to TCP port at device. @merlinweb used it and he said it fits his use case.

I still need to add OTP support mc2router because it does not respond to token request yet.

**Comment by PathfinderNetworks** [comment] 2019-03-23 05:59
But it looks like the MeshCentral router only routes ports to the remote device itself.  The HTTP direct tool in MeshCentral1 lets you route http traffic through a remote agent on to a device on that remote LAN that doesn't have any MeshCentral agent.  So they seem to work almost in the opposite way of each other.  But maybe I'm not fully understanding it.

**Comment by jsastriawan** [comment] 2019-03-23 06:05
It may actually be possible. At the moment the parameter I pass for tunneling is just TCP port. There is nothing from stopping us to add host to it. Which means we could use MeshAgent as a jump point to other host in a network. 

See meshcore.js line 614. If tcpaddr parameter is set, it will use that tcpaddr. Otherwise it will use 127.0.0.1.

**Comment by Ylianst** [comment] 2019-03-23 12:28
Yes, I will look into adding that in. I am not sure I am will adding the same HTTP-Direct on the server as MeshCentral v1 anytime soon since it requires an additional port on the server, but adding it in the MeshCentral Router should not be a problem.

**Comment by merlinweb** [comment] 2019-03-24 13:48
>  @merlinweb used it and he said it fits his use case.

Yes I can confirm, it can work without a mess.
And...I'hope I've read right :
> It may actually be possible. At the moment the parameter I pass for tunneling is just TCP port. There is nothing from stopping us to add host to it. Which means we could use MeshAgent as a jump point to other host in a network.
> See meshcore.js line 614. If tcpaddr parameter is set, it will use that tcpaddr. Otherwise it will use 127.0.0.1.
WOW !! So I can configure a "bridge" to another host in destinaton network, ie a Vnc client, without install agent on every machine
In my case this is an amazing news, start to look at this immediately

Thanks Joko !

Cheers

Merlinweb

**Comment by Ylianst** [comment] 2019-03-24 18:35
That is exactly correct. I will see what I can do to add it to the MeshCentral Router tomorrow. It is really useful.

**Comment by Ylianst** [comment] 2019-03-25 05:40
Just updated [MeshCentral Router](info.meshcentral.com/downloads/MeshCentral2/MeshCentralRouter.exe) to add port mapping using device relay. If anyone can test this and make sure it works ok, that would be great.

![MeshRouter-RelayPortMap2](https://user-images.githubusercontent.com/1319013/54897485-d86ab700-4e85-11e9-8549-5b4d198e6281.png)

**Comment by merlinweb** [comment] 2019-03-25 09:22
IT WORKS !!!!!!!!

Pointing to a test windows pc with agent installed,  behind a router with activated firewall

![image](https://user-images.githubusercontent.com/48550288/54908200-a68a3c80-4ee7-11e9-8d3f-c1c7ca1c1d77.png)

Redirecting 80 port with internal ip pointing to router web management console, I see device logon page !!! GREAT STUFF !!!

![image](https://user-images.githubusercontent.com/48550288/54908318-e51ff700-4ee7-11e9-98fc-b42192730894.png)

**Comment by mschubeck** [comment] 2019-03-25 13:33
I've been patiently waiting for this for a long time, so I downloaded it this morning - 1.0.7022.  However, it doesn't allow me to login, it always returns "Invalid username or password".  Does something else need to be configured to allow the MeshCentral Router to connect to my server?

**Comment by jsastriawan** [comment] 2019-03-25 14:39
I just added checkbox to indicate if you want to relay to other device.

![image](https://user-images.githubusercontent.com/6583218/54928107-a5014a00-4ed0-11e9-91e3-40f2f8aa4841.png)

It will prompt for the destination IP (no FQDN yet).
![image](https://user-images.githubusercontent.com/6583218/54928278-e72a8b80-4ed0-11e9-9998-280a5482b841.png)

@merlinweb, please try.

**Comment by mschubeck** [comment] 2019-03-25 15:32
Updated server from 0.3.0-s to 0.3.0-u and it is working now.

**Comment by PathfinderNetworks** [comment] 2019-03-25 16:52
Outstanding!  Thank you for this.  I just tested it at a couple different sites.  First was to a HTTP GUI on a printer. Another was to a RDP session on a server.  Both worked perfectly and were very fast.  This is going to be an incredibly useful tool.   One other request- and nothing urgent by any means.  Can a link to the MeshCentralRouter.exe be added somewhere in the MeshCentral page?  Like maybe under My Account or somewhere else that makes sense?  That way, if I happen to be on a different device or location and need access to MeshCentralRouter, I'll be able to download the executable quickly and easily.

**Comment by mschubeck** [comment] 2019-03-25 17:05
Yes, I missed this feature since I used both Labtech and Packet Trap.  Being able to securely tunnel into a remote site and use various tools and protocols without needing to take over someone's desktop saves a lot of time in remote management.  Now we can edit switch & router configs, modify firewall and printer settings, run backups using TFTP, etc. at sites without dedicated servers and without having to displace a user from their workstation while we do our work.

**Comment by merlinweb** [comment] 2019-03-25 17:09
> @merlinweb, please try.

Hi Joko
I can confirm your update is working in my modified MC2ROUTER Version, with vnc configured in it. Now I can Use an agent installed PC to connect every computer in the same network with an active vnc server.

Great improvement, thanks

Merlinweb

**Comment by mschubeck** [comment] 2019-03-25 17:15
Sorry, one more request- I have some sites (meshes/groups) that have machines with duplicate hostnames as other sites.  Can there be a way to differentiate the various mesh/groups instead of just the hostname by itself?  That would make the tool more usable.

**Comment by merlinweb** [comment] 2019-03-26 14:49
Hi, finally I've my customized version of MC2Router by Joko 👍 
For my needs, I've changed some buttons, launching different apps (all freeware)
My version is modified as follow:

![image](https://user-images.githubusercontent.com/48550288/55000527-01e52900-4fd3-11e9-82ee-4bb5b91e8393.png)

**Ultravnc**: (Portable client, embedded in the tool)  Connect remote machine with a vncserver installed, with "relay" checked can connect to every computer in the remote network (Unbelievable !) [tip: remember to check allow Loopback connection in vnc server]

**Browser**: (portable Browser K-Meleon, Lightest footprint I've found, embedded in the tool) I have added destination port request, so, in both direct and relay mode, is possible to specify remote port, ie for non standard web management or other needs:

![image](https://user-images.githubusercontent.com/48550288/55002997-ca2cb000-4fd7-11e9-8e94-7cd10e031faa.png)

**Remote Desktop**: Exactly the same of standard version, for me it's perfect as is

**SQL Browser**: (portable software, HeidiSQL, embedded in the tool, it's quite usable, I'm used to work with SSMS but it's ok) Manage a remote sql server installation, query, SP, Triggers etc

everything is zipped in a single file and is available for my tech operators  in meshcentral shared group. They need only a windows pc to be productive in a couple of minutes and give support to my POS network 

Of course all tools have to be pointed correctly in configuration page, plus right switches in custom argument (sql in this case)

This custom MC2Router, associated to meshcentral portal, is a huge improvement in support and problem solving by my technicians, with a "swiss army knife" for remote problem solving 

Thanks to **Joko and Ylianst** for their support, help and patience.

Cheers

Merlinweb

**Comment by Ylianst** [comment] 2019-03-26 21:23
Nice! I will need to review @jsastriawan version of the router for security, note that I have not looked at this code yet.

mschubeck - Let me know what would help differentiate devices. I can display devices by group if that would help.

**Comment by mschubeck** [comment] 2019-03-26 23:28
They seem to be sorted by group now, but if there is a way to show the group name along with the hostname that would be great.

**Comment by PathfinderNetworks** [comment] 2019-03-27 02:30
I agree with mschubeck.  If the group name were also included (and the various devices listed under the corresponding group name) that would be very helpful. I've only got about 40 devices on my MeshCentral2 server and it's already confusing trying to find the correct device in the Router.  Once I get up to hundreds of devices it would be very difficult.  Another option would be a drop down box that shows all the group names.  Then you can select the appropriate group. Then another selection box would be below that showing just the devices that are in that group.  That, for me anyway, would be a better way to filter through all the devices in the MeshCentral Router.

**Comment by Ylianst** [comment] 2019-03-27 05:29
Good suggestion, I will add a group dropdown.

**Comment by merlinweb** [comment] 2019-03-27 07:00
Consider add username in search, too.  It could be very useful to find user that connect to more than one machine, so you can find the right computer using only username (I see in My Device, when a pc is disconnected, user disappear)

**Comment by Ylianst** [comment] 2019-03-27 19:43
Just updated [MeshCentral Router](https://github.com/Ylianst/MeshCentral/issues/info.meshcentral.com/downloads/MeshCentral2/MeshCentralRouter.exe) with group drop down. Feedback appreciated.

![MC2-MeshCounterWithGroups](https://user-images.githubusercontent.com/1319013/55107174-e12dd980-508d-11e9-8ce6-174cf549cea8.png)

**Comment by Ylianst** [comment] 2019-03-28 03:40
I will close this since I think the original request is was completed and works. Anyone please feel free to open a new issue as needed.

**Closed by Ylianst** 2019-03-28 03:40 UTC
