### ISSUE TITLE
Meshagent doesn't install for aarch64 with 32 bit Kodi 

### ISSUE THREAD

**Issue by siliconhippy** [Ylianst/MeshCentral#5172] opened 2023-06-01 02:40 UTC
Tried this install many times. I am not a dev but I have been told that meshagent in any form cannot be installed on aarch64 platform running Kodi 32 bit on top.

Reason for running Kodi 32 bit on aarch64 instead of Kodi 64bit seems to be that Kodi has memory leaks which have not been fixed. 

Such a aarch64 with Kodi 32 bit system for example is Coreelec.org ( fork of Libreelec.tv) or its fork, AlexElec.tv. The root OS is read only, but Kodi itself is read/write.

Luckily meshagent works fine on AlexElec PCx64 version where Kodi 64 bit is available! Again the root OS is r/o but Kodi is r/w.

Meshcentral is such an amazing remote manager that I really want this problem solved...any suggestions?

**Comment by pelwell** [comment] 2023-06-05 07:45
Probably a duplicate of this: https://github.com/Ylianst/MeshAgent/issues/183

**Comment by siliconhippy** [comment] 2023-06-05 08:47
Ok thanks for the reference.
Hopefully @Ylianst will add the patch fix soon.

**Comment by pelwell** [comment] 2023-06-05 10:23
I can turn my example patch into a PR, in case the maintainers just want to hit Merge.

**Comment by pelwell** [comment] 2023-06-05 10:35
See https://github.com/Ylianst/MeshAgent/pull/187.

**Comment by dinger1986** [comment] 2023-11-13 23:22
@si458 fix was merged

**Comment by si458** [comment] 2023-11-16 11:04
correct fix was merged, but no new agent releases yet recently, so keeping open until new agent releases

**Closed** 2023-11-16 11:07 UTC
Labels: question
