### ISSUE TITLE
Capturing mouse pointer

### ISSUE THREAD

**Issue by hchkim** [Ylianst/MeshCentral#28] opened 2018-10-26 04:54 UTC
I can't see mouse pointer of remote side. Do you have any plan to solve these issue?

**Comment by jsastriawan** [comment] 2018-10-26 14:41
What OS is running at the client side?

**Comment by hchkim** [comment] 2018-11-06 11:40
Both viewer side and remote side(MeshAgent) are windows. The mouse on viewer side looks well, but remote mouse cursor can not be synchronized. For example, if you place the mouse at the end to resize the remote window, the mouse cursor will not change, making it difficult to resize the window.

**Comment by marco-vogt** [comment] 2019-02-06 02:37
I have the same behaviour. I dont see the remote mouse cursor. Is this a bug on my side or expected behaviour?

**Comment by marco-vogt** [comment] 2019-02-06 03:05
just tested it again on a different setup and still have no mouse cursor, so i expect this supposed to be like that.

@Ylianst is this feature planned for the future?

**Comment by Ylianst** [comment] 2019-02-06 07:55
This is clearly a bug... but I have never seen it on my test computers. If there is any way to make a short video with a phone and post it, that would be great. The best would be to detail how I can make the same happen on my computers. Any info appreciated.

**Comment by marco-vogt** [comment] 2019-02-06 11:33
Sure, here you go.

https://sendvid.com/dze809mx

On the right monitor, you can see the remote control view from the browser. On the left monitor is the remotely controlled computer. You can see that the controlled computer shows the mouse pointer but the web view does not.

Maybe its because server & agent are running on the same computer here? I havent tested it in another environment but maybe thats the root of the problem?

Anyway, there are not any special really steps to reproduce. I followed your setup tutorial on youtube and everything worked great besides the mouse cursor.

If it matters, im running W10 Pro Version 10.0.17134 Build 17134.

Let me know if you need to know anything else.

**Comment by Ylianst** [comment] 2019-02-06 19:12
Wow! What browser are you using? I will add code to explicitly show the cursor on the HTML canvas now.

**Comment by Ylianst** [comment] 2019-02-06 20:00
Published MeshCentral 0.2.7-k what explicitly sets the cursor to "default" on the browser canvas. Let me know if that worked for you.

**Comment by marco-vogt** [comment] 2019-02-06 22:28
Thanks for the quick update but it unfortunately didnt work.

Im using the newest version of Firefox but also just tested on Edge and it didnt work. Like i said, it cant be due to the fact that im running server & agent on the same machine, right?

**Comment by marco-vogt** [comment] 2019-02-06 22:34
Also, im not sure if thats related but im having another problem. Default Multiscreen shows both of my screens side by side, selecting Display 1 & Display 2 both show Display 1 though.

I dont think the problems are related but who knows. You want me to open another issue for that? Its not super important for me, up to you.

Also, here are my specs, maybe it helps you identify the problem:
I5-6500
AMD Radeon R9 390
W10 Pro Version 10.0.17134

**Comment by marco-vogt** [comment] 2019-02-06 23:31
Forget the last comment and the problem with the displays. I resolved it and it was an error on my part.

Regarding the mouse pointer issue: Im still not sure if we are talking about the same problem here and i think the issue i was talking about is indeed expected behaviour. I just looked at your setup video again (https://www.youtube.com/watch?v=LSiWuu71k_U) and it looks like in the video you were also not able to see the mouse cursor rendered in the html canvas?

**Comment by krayon007** [comment] 2019-02-06 23:54
I think I understand what you are talking about. You are correct that is intended behavior. Rendering the mouse cursor remotely, would send unnecessary traffic across the wire, and it would most likely be jittery resulting in a poor user experience. Many Remote Desktop solutions will instead render the mouse cursor locally.

If you are having issues with the mouse cursor not being synchronized correctly in the 2D desktop space, that is a different problem. I know I ran into issues with this depending on what your monitor DPI settings were set to, as the OS will try to scale the 2D coordinate system, so I set the OS flag for that, so that the mouse coordinates are correct, however I know that method call is only supported on Windows 8 and above I think, but you said you are on Windows 10, so I'm not sure what's going on. Can you change your Monitor Scaling, and see if that makes a difference?

**Comment by marco-vogt** [comment] 2019-02-07 00:09
> I think I understand what you are talking about. You are correct that is intended behavior. Rendering the mouse cursor remotely, would send unnecessary traffic across the wire, and it would most likely be jittery resulting in a poor user experience. Many Remote Desktop solutions will instead render the mouse cursor locally.

Ah, i see. That explains it. I finally got around and tested it on two seperate machines (one running server and one running an agent) and that works as it should. The problem of not seeing your own mousecursor on the screen only happens when server and agent are running on the same machine and youre "accessing" your own computer. Your first paragraph explains why this is happening.

Thanks, issue can be closed i think as im sure the issue creator was having the same problem as i did.

On another note, is there some kind of discussion forum for this software? I am planning to integrate MeshCentral in a big web-app in our company and a place for discussion/questions other than here would be nice.

**Comment by krayon007** [comment] 2019-02-07 00:15
By the way, when we detect that you are remoting yourself like that, we disabled mouse input on the remote canvas, because otherwise we'd have a feedback loop on the mouse input.

**Comment by Ylianst** [comment] 2019-02-07 02:16
No official discussion group on MeshCentral (yet), but [this thread is interesting](https://mangolassi.it/topic/18607/comparing-meshcentral-2-to-screenconnect/121).

**Comment by Ylianst** [comment] 2019-02-12 02:16
Going to close this one. Please reopen if needed.

**Closed by Ylianst** 2019-02-12 02:16 UTC
