### ISSUE TITLE
Linux interactive installer hangs since 0.7.28

### ISSUE THREAD

**Issue by Yvan-Masson** [Ylianst/MeshCentral#2140] opened 2021-01-04 11:11 UTC
Hi,

Starting from MeshCentral 0.7.28, the interactive agent (the one you get from MeshCentral when clicking on "Add an agent -> Linux binary executable -> interactive only" (approximate translation sorry) hangs: process starts but does not display anything, nor in the console nor in a Zenity window, even with `-help` option. Issue is still here with 0.7.37.

I tested the agent on two computers: one running Debian testing, the other running Ubuntu 20.04.

Regards,
Yvan

**Comment by Ylianst** [comment] 2021-01-04 18:28
Yes, this is because of the new agent multi-language support. Working on a fix for that.

**Comment by Ylianst** [comment] 2021-01-04 18:53
Ok, found the problem and fixed it. Will be in MeshCentral v0.7.38. Thanks for reporting that.

**Comment by Ylianst** [comment] 2021-01-04 21:34
Published MeshCentral v0.7.39. Let me know if it works.

**Comment by CHBMB** [comment] 2021-01-04 22:30
Confirmed as working for me.

**Comment by Ylianst** [comment] 2021-01-04 22:34
Excellent! Thanks for reporting back.

**Closed** 2021-01-04 22:34 UTC
Labels: Fixed - Confirm & Close, bug

**Comment by Yvan-Masson** [comment] 2021-01-05 09:37
It also works for me, thanks!
