### ISSUE TITLE
v1.0.87 - Terminal - Connect is not working on non-english pages.

### ISSUE THREAD

**Issue by rapi3** [Ylianst/MeshCentral#4663] opened 2022-10-24 20:22 UTC
**Describe the bug**
Pressing Connect on Terminal - nothing happens ( reverting to v1.0.85 it is working OK ) 

**To Reproduce**
1. Go to 'Agent - Terminal'
2. Click on 'Connect'

**Expected behavior**
Connect to terminal on remote agent.

**Screenshots**
no

**Server Software (please complete the following information):**
 - OS: Ubuntu 22.04.1 LTS
 - Network:  LAN/WAN
 - Version: 1.0.87
 - Node: v16.13.2

**Client Device (please complete the following information):**
 - Device: Laptop/PC
 - OS: Ubuntu
 - Network: Local to Meshcentral
 - Browser: Chrome

**Remote Device (please complete the following information):**
 - Device: Laptop/PC
 - OS: Ubuntu / Linux
 - Network: Local to Meshcentral
 - Current Core Version (if known): Aug 29 2022, 294730201

**Comment by krayon007** [comment] 2022-10-24 20:49
I think xterm.js was updated in that version, so let me do some testing with the updated xterm.

**Comment by si458** [comment] 2022-10-24 21:05
Not having this issue here?
Updated to 1.0.87 and connected to Ubuntu centos and debian no problems
Have you tried ctrl+f5?
Also logging out and back in again?
Also try private browsing?

**Comment by Ylianst** [comment] 2022-10-24 21:53
One possible problem is that old files are cached. Hold the "Shift" key and hit refresh on the browser and try again. My first guess that that the old xterm.js is being served with a new main web site. Let me know if that solves it.

**Comment by nicrame** [comment] 2022-10-24 22:27
I can confirm problem on windows terminal (v 1.0.87 and 1.0.88 - cache cleared from browser, using newest FF).
It looks like that:
![Zrzut ekranu (23)](https://user-images.githubusercontent.com/5872054/197641497-6133c172-582c-4661-b14f-a5b9cb16871b.png)
Same problem with Linux agents.

**Comment by Ylianst** [comment] 2022-10-24 22:40
Ok, looking into it.

**Comment by Ylianst** [comment] 2022-10-24 22:55
Your right! It works in English but not in other languages. Looking for a fix now.

**Comment by Ylianst** [comment] 2022-10-24 23:13
MeshCentral v1.0.89 published with a fix for this. Let me know if it works.

**Comment by rapi3** [comment] 2022-10-25 06:10
It is fixed in v1.0.89.
Thank you.

**Closed** 2022-10-25 06:10 UTC
Labels: bug, Fixed - Please Verify & Close
