### ISSUE TITLE
 MeshCentral Assistant crash latest meshcentral2 server (0.8.49)

### ISSUE THREAD

**Issue by paolor1965** [Ylianst/MeshCentral#2708] opened 2021-05-28 13:05 UTC
hi, I report the behavior of MeshCentral Assistant on two test stations: 
1) crash when I try to acquire remote control on windows 10 ltsc ver 1809 (17763.1971) standalone workstation following a request for help. ( direct connection)
2) windows 10 ltsc 1809 (17763.1879) in AD: crah immediately after execution.
I am attaching the two logs created with -debug option
mesh agent installed work perfectly on both

[debug_crash_immediatly.log](https://github.com/Ylianst/MeshCentral/files/6560986/debug_crash_immediatly.log)
[debug_crash_when_click_desktop_control.log](https://github.com/Ylianst/MeshCentral/files/6560994/debug_crash_when_click_desktop_control.log)

thanks for everything paolo

**Comment by paolor1965** [comment] 2021-05-28 13:12
I specify that only the stand alone client contacts the server through a nat

**Comment by VINISHVV** [comment] 2021-05-28 15:30
This issue is Duplicate of #2694

Please find the below response from ylianst.
----------------------------------------------------------------------------------------

One workaround until I fix it is to run the basic MeshCentralAssistant.exe from /node_modules/meshagent once. Then, stop it and then run the MeshCentralAssistant.exe you downloaded that includes the device group. I will have a fix for this in 2 days then I get back to work.

**Comment by Ylianst** [comment] 2021-05-28 18:32
Yes, this is a duplicate. It will be fixed in the next version of MeshCentral.

**Closed** 2021-05-28 18:32 UTC
Labels: duplicate

**Comment by Ylianst** [comment] 2021-05-31 00:12
FYI. This has been fixed in v0.8.50
