### ISSUE TITLE
No action is taken when clicking on the drives!

### ISSUE THREAD

**Issue by bravery-only** [Ylianst/MeshCentral#4662] opened 2022-10-24 19:04 UTC
After the update of Mesh Central, when the 32-bit agent installed in 64-bit Windows, it does not enter the drives in the file management!!

![Error](https://user-images.githubusercontent.com/42680639/197605317-89cbe0fd-3a43-4818-bf3c-daa7866febe8.jpg)

**Comment by bravery-only** [comment] 2022-10-24 19:05
After the update from version 1.0.85 to 1.0.86 and 1.0.87

**Comment by si458** [comment] 2022-10-24 19:06
**please can you follow the bug report template in the future as it has critical information required to help us with your issue**

what version where you going from and to?
what OS is the remote device?
what browser are you using?

**Comment by bravery-only** [comment] 2022-10-24 19:10
> **please can you follow the bug report template in the future as it has critical information required to help us with your issue**
> 
> what version where you going from and to? what OS is the remote device? what browser are you using?

It is the same in all browsers. When I click on the drive, the content does not appear

**Comment by bravery-only** [comment] 2022-10-24 19:17
I tested it. It is the same in all Windows, even Windows Server!!

**Comment by krayon007** [comment] 2022-10-24 19:29
Which version of windows are you using? A change I made was that it would inject "sysnative" into the results if the folder being enumerated was %windir%

It shouldn't affect entering the drive. I fixed this in two ways depending if the agent was updated or not. Let me check the non updated agent path.

**Comment by bravery-only** [comment] 2022-10-24 19:35
> Which version of windows are you using? A change I made was that it would inject "sysnative" into the results if the folder being enumerated was %windir% if the agent detected was 32 bit running in 64 bit windows
> 
> It shouldn't affect entering the drive. I fixed this in two ways depending if the agent was updated or not. Let me check the non updated agent path.

Windows 64 bit. But the agent is 32-bit. I had no problem, this problem appeared after the update

**Comment by bravery-only** [comment] 2022-10-24 20:23
When I click on it, a # is added to the page address!
![Error2](https://user-images.githubusercontent.com/42680639/197621579-5a0ce422-1ab6-4d41-b104-3c1a1c7c3517.jpg)

**Comment by Ylianst** [comment] 2022-10-24 21:54
This is really bad. Will release an update shortly.

**Comment by Ylianst** [comment] 2022-10-24 22:03
MeshCentral v1.0.88 is out with (hopefully) a fix for this. Please test and let us know if it works.

**Comment by bravery-only** [comment] 2022-10-25 04:30
> MeshCentral v1.0.88 is out with (hopefully) a fix for this. Please test and let us know if it works.
The problem was solved, but after the update, it gave an error unable to update in the last step!! I reinstalled Mesh Central. In the 1.0.87 update, after the update, the Mesh Central service was not installed!!! I reinstalled there yesterday!

**Comment by bravery-only** [comment] 2022-10-25 04:30
> MeshCentral v1.0.88 is out with (hopefully) a fix for this. Please test and let us know if it works.

The problem was solved, but after the update, it gave an error unable to update in the last step!! I reinstalled Mesh Central. In the 1.0.87 update, after the update, the Mesh Central service was not installed!!! I reinstalled there yesterday!

**Comment by Ylianst** [comment] 2022-10-28 16:04
I will close this since the problem is solved. The server update system has not changed in years, but if there is an issue please create a new issue for that.

**Closed by Ylianst** 2022-10-28 16:04 UTC
Labels: bug, Fixed - Please Verify & Close
