### ISSUE TITLE
Feature Request: Terminal Tab in Mobile View Mode

### ISSUE THREAD

**Issue by lulu3000** [Ylianst/MeshCentral#2478] opened 2021-04-06 10:49 UTC
Hello

It would be nice to have the Terminal Tab also in Mobile View. 

MeshCentral ist absolutely amazing!!!!!

**Comment by Ylianst** [comment] 2021-04-07 05:49
Ok, this has been requested before. I just added the terminal is a very basic way, but it's poorly adapted to mobile devices right now. Will need to do some more work on it.

![mobile-term](https://user-images.githubusercontent.com/1319013/113816852-42cbb880-972a-11eb-965f-8afaeae2a1bb.png)

**Comment by Ylianst** [comment] 2021-04-07 23:40
Just published MeshCentral v0.8.5 with terminal support on the mobile site. Let me know if that works.

![MC2-MobileTerminal](https://user-images.githubusercontent.com/1319013/113947646-f59a2600-97bf-11eb-835a-2ee620c86291.png)

**Comment by lulu3000** [comment] 2021-04-08 07:52
Do I have to update also the clients?

**Comment by lulu3000** [comment] 2021-04-08 08:04
Without updating the clients: It works on Ipad, on android only the Return key ist transmitted to the terminal.

**Comment by Ylianst** [comment] 2021-04-08 16:22
So, agents are always automatically updated if needed. In this case, an agent update is not needed. What browser are you using on Android?

**Comment by lulu3000** [comment] 2021-04-09 07:01
Im am using chrome.

**Comment by AntonAndreevichMoroz** [comment] 2021-04-11 06:15
Thank you for your work. This is really cool.
We, too, on Android are experiencing such problems. Chrome browser. Only control keys, Enter, arrows, Ctrl + C are transmitted. But letters and numbers are not entered. Tried on two devices with different keyboard programs.

**Comment by Ylianst** [comment] 2021-04-12 03:04
Just put in a fix for this. Should work on both Chrome and FireFox. Will be in MeshCentral v0.8.7 when it's next published.

**Comment by Ylianst** [comment] 2021-04-12 05:59
Just published MeshCentral v0.8.8 with a fix for this. Let me know if it works.

**Comment by lulu3000** [comment] 2021-04-12 07:33
Hi!
It's getting better, but there are still a couple of issues:
- The browser is regarding the terminal as password input field. That means that when I want to write a command in the terminal, it lets me choose which account to use and will write then the passwort of this accout - visible - as command in the terminal. This happens on windows clients as soon as I type the first character in the terminal. On unix client it's the same, but moreover the conections is lost after the first command. Which means that MeshCentral says the client is off. It comes back later then.

**Comment by lergolas** [comment] 2021-04-28 07:08
> Hi!
> It's getting better, but there are still a couple of issues:
> 
> * The browser is regarding the terminal as password input field. That means that when I want to write a command in the terminal, it lets me choose which account to use and will write then the passwort of this accout - visible - as command in the terminal. This happens on windows clients as soon as I type the first character in the terminal. On unix client it's the same, but moreover the conections is lost after the some commands. Which means that MeshCentral says the client is off. It comes back when restarting the meshagent process.

I have de same issue with the terminal. I use Brave and Chrome in Android. This happens on Windows and Linux clients.

**Comment by TotallyNotElite** [comment] 2021-05-13 10:33
Duplicate of #2204, and yea it's also rather broken on my end too.

**Closed** 2021-08-20 16:14 UTC
Labels: enhancement, Fixed - Please Verify & Close
