### ISSUE TITLE
New agents not connects if Session recording enabled

### ISSUE THREAD

**Issue by Mfinadmin** [Ylianst/MeshCentral#3868] opened 2022-04-11 06:04 UTC
Dear Ylian,

If user session recording enabled in server then it seems newly installed agents are not connecting properly till server restart.

Can you check this issue.

**Comment by Ylianst** [comment] 2022-04-12 04:33
You can provide the exact config.json you are using or any other details to replicate the issue? Thanks.

**Comment by Mfinadmin** [comment] 2022-04-12 05:07
Hi Ylian,

I am running MC in windows server 2019 with latest version of MongoDB.

Please find the below similar issues reported earlier. I have also added my config for your references.

Issues.
#2896
#3111
#3237


**Configuration**

_______________________________________________________________________
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "cert": "XXXX.XXXX.org",
    "certUrl": "XXXX.XXXX:443",
    "mongodb": "mongodb://127.0.0.1:27017/meshcentral",
    "mongodbcol": "meshcentral",
    "MongoDbBulkOperations": true,
    "_WANonly": true,
    "_LANonly": true,
    "PublicPushnotifications": true,
    "_TlsOffload": "192.168.1.69",
    "_syslogtcp" : "localhost:514",
    "_trustedProxy": "127.0.0.1,192.168.1.92,10.10.10.1",
    "_AllowHighQualityDesktop": true,
    "wscompression": true,
    "agentwscompression": true,
    "compression": true,
    "_ignoreAgentHashCheck": true,
    "desktopMultiplex" : true,
    "_agentAllowedIP": "10.91.0.0/24",
    "_sessionKey": "MyReallySecretPassword1",
    "_port": 4430,
    "_aliasPort": 443,
    "_redirPort": 80,
    "_redirAliasPort": 80,
    "_agentIdleTimeout": 5,
    "_agentping": 55,
    "_agentpong": 55,
    "_BrowserPing": 55,
    "_BrowserPong": 55,
    "webPush": { "email": "XXXX@XXXXX" },
    "_WatchDog": { "interval": 200, "timeout": 400 },
    "webRTC": true,
    "authlog" : "c:\\MSAT\\auth.log",
    "_ListEvents" : "c:\\mesh\\event.csv",
    "_noagentupdate": true,
    "AllowLoginToken": true,
    "MaxInvalidLogin": {
    "time": 5,
    "count": 7,
    "_coolofftime": 10
    },
    "dbExpire": {
    "events": 31536000,
    "powerevents": 301400,
    "statsevents": 301400
    },
	"_plugins": {
     "enabled": true
	},
 "AutoBackup": {
      "mongoDumpPath": "c:\\Program Files\\MongoDB\\Tools\\100\\bin\\mongodump.exe",
      "backupIntervalHours": 24,
      "keepLastDaysBackup": 20,
      "backupPath": "E:\\BACKUPS"
    }  
      },
   "domains": {
    "": {
      "title": "System Accessing Tool",
      "WelcomePicture": "welcome66.jpg",
      "minify": true,
      "ssh" : true,
      "newAccounts": false,
      "agentInviteCodes": true,
      "autocomplete": false,
      "_userNameIsEmail": true,
      "mstsc": true,
      "_nightmode": 1,
      "_userallowedip" : "202.191.157.10,49.36.131.141",
	"Limits": {
        "_MaxDevices": 100,
        "_MaxUserAccounts": 100,
        "_MaxUserSessions": 100,
        "_MaxAgentSessions": 100,
        "userSessionIdleTimeout":3,
        "_userSessionIdleTimeout":5, 
        "twoFactorCookieDurationDays":1,
        "MaxSingleUserSessions": 2
},
        "assistantCustomization": {
        "image" : "MSAT.png",
        "filename" : "MSAT-Assist"
},
       "androidCustomization": {
        "image" : "MSAT.png",
        "subtitle" : "Powered By Team-IT"
},
       "sessionRecording": {
       "onlySelectedUsers": true,
      "onlySelectedUserGroups": true,          
        "onlySelectedDeviceGroups": true,
        "filepath": "E:\\RECORDINGS",
        "index": true,
        "maxRecordings": 10000000,
        "maxRecordingDays": 360,
        "_maxRecordingSizeMegabytes": 3,
        "__protocols__": "Is an array: 1 = Terminal, 2 = Desktop, 5 = Files, 100 = Intel AMT WSMAN, 101 = Intel AMT Redirection, 200 Messenger",
        "protocols": [ 2,5,200]
},
  "passwordRequirements": {
        "force2factor": true,
          "twoFactorTimeout":180,
         "oldPasswordBan": 3,
         "reset": 10       
      },
  "_consentMessages": {
        "desktop": "{0} requesting remote desktop access. Grant access ?",
        "terminal": "{0} requesting remote terminal access. Grant access ?",
        "files": "{0} requesting remote files access. Grant access?"
      },
  "agentCustomization": {
        "displayName": "M-SAT",
        "description": "MSAT - Remote monitoring, management and assistance.",
        "serviceName": "MSAT-LIVE",
        "fileName": "MSAT-LIVE",
         "_foregroundcolor" : "000000",
         "_backgroundcolor" : "#cf0626",
        "image" : "MSATS.png"
        
}
    }
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "myemail@mydomain.com",
    "names": "myserver.mydomain.com",
    "production": false
  },
 "smtp": {
    "host": "smtp.gmail.com",
    "port": 587,
    "from": "XXX@XXXXXX",
    "user": "XXX@XXXXXX",
    "pass": "XXX@XXXXXX",
    "tls": false
  },
  "_smtp": {
    "from": "XXX@XXXXXX",
    "auth": {
      "clientid": "161553737295-r9h0icj98j12ugc7jn2nrvdsn79b127e.apps.googleusercontent.com",
      "clientsecret": "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",
      "_refreshtoken": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    }
  },
  "sms": {
    "provider": "twilio",
    "sid": "XXXXXXXXXXXXXXXXXXXXXXXXX",
    "auth": "XXXXXXXXXXXXXXXXXXXXX",
    "from": "XXXXXXXXXXXXXXXXXX"
  }
 }

**Comment by Ylianst** [comment] 2022-04-18 18:42
Thanks to @prononext in issue #3857, I replicate a permissions issue when activating session recording on a user. I put in a fix for this, will be in v1.0.11. Hopefully that will also fix #2896, #3111, #3237, #3868.

**Comment by bajo** [comment] 2022-04-27 14:20
@Ylianst can you clarify if the fix from #3857 was also supposed to fix this problem? 
We are running version 1.0.11 and see the same issue still happening. New agents are not connecting when we have the session recording enabled. 
Also, running meshcmd with and meshaction file to do port forwarding through MC is also happening as long as session recording is enabled. There it basically times out at the Authentication stage and only works for some time (a few hours) after the meshcentral server restart.

If there is any data I can provide to try to find the root cause I'm happy collect and send here. :)

**Comment by VINISHVV** [comment] 2022-04-27 14:30
+1 the issue is still persist.

@Ylianst - is there any trouble shoot /debug option available?.  I tried stop running meshagent service in the new pc and then run the same through cmd.

Some times its shows message like connecting to domain... And stuck there.

Some time its shows error like Unable to open database (1/10)

**Comment by Mfinadmin** [comment] 2022-04-28 05:16
@Ylianst - issue is still persist.

**Comment by bbrendon** [comment] 2022-07-13 01:59
I tried recordings on 1.0.43 and was also unable to add agents.

**Comment by si458** [comment] 2023-10-31 22:22
PLEASE FOLLOW #4449

**Closed by si458** 2023-10-31 22:22 UTC
