### ISSUE TITLE
CloudFlare | Mesh Central

### ISSUE THREAD

**Issue by Altus668** [Ylianst/MeshCentral#3580] opened 2022-02-01 20:51 UTC
So, I am very new here. But I have my DNS managed at CloudFlare.
I stood up a Mesh Central server at our colocation - it is externally available on 443 and 80 currently with a CNAME that points to a DNS name that is tied to the public IP of which the server is NAT'ed to.

Currently if I leave the record as is - everything works **without** the CloudFlare DNS proxy turned on.

As soon as I turn on the DNS proxy option; I can still browse to the login page, but not everything loads, and I get a WebSocket error. 

I am new to this, but I can provide whatever logs necessary to troubleshoot. Really loving the product - just want to get it working through the DNS proxy in CloudFlare.

![image](https://user-images.githubusercontent.com/92278541/152049308-e3bd7536-d849-4984-855b-381e43acf80b.png)

Thanks!
K. LaFleur

**Comment by Ylianst** [comment] 2022-02-01 21:30
CloudFlare should work.

![image](https://user-images.githubusercontent.com/1319013/152054463-52932a21-81d1-4d0e-aca8-b53ec065699c.png)

Can you enable the debug console on your browser and post any errors you see? Thanks.

**Comment by Altus668** [comment] 2022-02-01 21:33
> Can you enable the debug console on your browser and post any errors you see? Thanks.

I am happy to - I am really green to troubleshooting web stuff. Do you know where to enable this for edge or chrome? I am concurrently looking. Thanks!

**Comment by Altus668** [comment] 2022-02-01 21:34
![image](https://user-images.githubusercontent.com/92278541/152055115-1a5f6eff-052e-47af-9ad8-3b6fdca5beb4.png)

**Comment by Ylianst** [comment] 2022-02-01 21:36
That is the right debug console. Can you navigate to the place where the websocket does not connect and post the content of the console window? Thanks.

**Comment by Altus668** [comment] 2022-02-01 21:37
![image](https://user-images.githubusercontent.com/92278541/152055393-06691948-e852-466a-b0f0-97e2d2c18d8f.png)

**Comment by Altus668** [comment] 2022-02-01 21:38
crap this is revealing my freaking domain - so anyways I will change it. But we can use this for tesing lol.

**Comment by Altus668** [comment] 2022-02-01 21:40
![image](https://user-images.githubusercontent.com/92278541/152055948-3b5fa9e6-063c-40e0-b228-c6ae5919e0f9.png)


Kind of even doesn't fully load - now when I bypass Cloudflare. Works like a charm.

**Comment by Ylianst** [comment] 2022-02-01 21:40
Just deleted it :)

**Comment by Altus668** [comment] 2022-02-01 21:44
![image](https://user-images.githubusercontent.com/92278541/152056252-8adb5ba7-2fe6-42d5-a91f-0309e8589c5d.png)

![image](https://user-images.githubusercontent.com/92278541/152056279-8d8dc39f-abe6-467e-a7e5-474b69bec13e.png)

errors like this - like it is having an issue loading thing.

But again, with cloudflare bypassed - at another URL I have it setup on - it works fine.

**Comment by Altus668** [comment] 2022-02-01 21:44
![image](https://user-images.githubusercontent.com/92278541/152056586-994baa6e-993e-43e7-a59b-97efce47f8fb.png)
 this as well

**Comment by ctv99** [comment] 2022-02-23 14:01
Any updates on this I'm having the same issue now with Cloudflare and 500 agents.

**Comment by Altus668** [comment] 2022-02-23 19:57
I am working on it - we just got extremely busy over the last 2 weeks. Basically, I just took us off of Cloudflare for the moment. But if you want to work on it together; I am more than willing to set aside some time. Thanks.

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

------- Original Message -------

**Comment by Altus668** [comment] 2022-02-23 20:01
I have another developer who is kind of heling me troubleshoot this. I promise I will update y'all with the outcome.

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

------- Original Message -------

**Comment by ctv99** [comment] 2022-02-23 21:07
We just went to letsencrypt ssl cert for now i may revisit cloudflare at a
later date.

**Comment by PrplHaz4** [comment] 2022-02-24 22:17
I think the problem is your agent is seeing the CloudFlare SSL cert, but your server is seeing your local SSL cert, so when hashes are checked it doesn't match.

I don't want clients on my local network to have to go out to CF and back, so am also seeing this same problem.

```
External Clients: Agent -> CF Proxy (CF SSL cert) -> Reverse Proxy (Local SSL cert) -> MeshCentral
Internal Clients: Agent -> Reverse Proxy (Local SSL cert) -> MeshCentral
```

I'm guessing it worked for @Ylianst because his server was likely not resolving to an internal IP when pulling the cert at startup, so both server and client fetched the CF SSL cert.

**Comment by jirijanata** [comment] 2022-11-20 22:35
Hello everyone, I didn't found any informations about CIRA and CloudFlare. I've now MeshCentral behind CloudFlare, but CIRA isn't working anymore. I can't access https://mesh.domain.com:4433.

Does anyone tried Intel AMT CIRA from internet to the MeshCentral behind CloudFlare? 

Without CloudFlare works everything fine. Thank you for your replies!

**Comment by ctv99** [comment] 2022-11-20 22:51
You have to pay cloudflare for extra port access.

**Comment by jirijanata** [comment] 2022-11-20 23:46
Awesome! Thank you very much your reply. I changed MPS Port to the 8443. I can now access the MeshCentral MPS server, but the certificate served is one from CloudFlare -> so the Intel CIRA will not connect. But most likely it's not because of certificate.

https://developers.cloudflare.com/fundamentals/get-started/reference/network-ports/ 

As far as I unterstand it, according to this post - CIRA cannot be run throught the proxy. The only solution seems to be to configure some other hostname under mpsAliasHost and then this hostname have to be not proxied through the CloudFlare. Then it should work. The only downside will be, that the IP will be exposed, but I don't think, that we can do anything to prevent it. Maybe some IP limitation etc.
https://github.com/Ylianst/MeshCentral/issues/2203

**Comment by si458** [comment] 2024-03-01 22:43
closing as stale,
please try the latest version 1.1.21 and use node 18 or above,
if issues persist, please reply back

**Closed by si458** 2024-03-01 22:43 UTC
Labels: bug

**Comment by ctv99** [comment] 2024-03-01 22:47
Sorry I should have commented back I'm not having issues any longer.
