### ISSUE TITLE
Mac Agent not staying persistent with latest updates

### ISSUE THREAD

**Issue by Matt-CyberGuy** [Ylianst/MeshCentral#2160] opened 2021-01-11 19:20 UTC
Morning all of you awesome peoples... 

Last week I spun up some Mac VMs to do some in house testing for future Apple clients and put MeshAgent on all of them. I thought it was a glitch when they didn't reconnect on reboot, but I'm finding now after rebooting the MeshAgent service no longer connects to MeshCentral after restart. 

I'm also finding this to be the case on my Macbook Air. I don't recall this being an issue before.

**Comment by krayon007** [comment] 2021-01-11 19:59
That's intersting... My mac VMs, my Apple Silicon mac mini, and macbook Pro all seem to have updated correctly.
Can you open an elevated terminal, and go to the /usr/local/mesh_services/meshagent folder and run:
`./meshagent -state`
and let me know what it says?

**Comment by matt-cylanda** [comment] 2021-01-11 20:09
```
Querying Mesh Agent state...
Mesh Agent connected to: [NOT CONNECTED]
 Chain Timeout: 86400000 milliseconds
 FD[12] (R: 0, W: 0, E: 0) => ILibAsyncSocket
 FD[9] (R: 0, W: 0, E: 0) => Signal_Listener
 FD[14] (R: 0, W: 0, E: 0) => net.ipcServer.ipcSocketConnection
 FD[11] (R: 0, W: 0, E: 0) => net.ipcServer
 FD[15] (R: 0, W: 0, E: 0) => ILibWebRTC_stun_listener_ipv4
```

The only way I can get the agents to reconnect is to run an uninstall and re-install everything

**Comment by matt-cylanda** [comment] 2021-01-11 20:47
I don't know if it could be causing it, but I'm running MeshCentral in a docker instance behind an NGinx reverse proxy. I did find I didn't have the config set right for MeshCentral, causing all of the IPs to report incorrectly. I'm wondering it there's a config setting I'm missing or set incorrectly that's causing the client to not be able to see the server on reboot.

**Comment by krayon007** [comment] 2021-01-11 21:11
does kickstarting the service cause it to connect?
`sudo launchctl kickstart -k system/meshagent`

**Comment by matt-cylanda** [comment] 2021-01-11 21:34
Huh... it looks like that worked. What's the difference between what that command does and what the agent does when it loads on reboot?

**Comment by krayon007** [comment] 2021-01-11 21:52
They should be identical... I haven't been able to reproduce on any of my macs, but I know others have reported that sometimes on reboot, there is this strange scenario where it seems the network stack is nonfunctional. It acts like there is some sort of race or something, where all the network API calls don't work... Normally, if a call fails, it will retry... But on some people's systems it looked like the call just hung without returning an error, and without triggering any descriptors... When it entered this state, it seemed to work, if you restarted the service. I know I added some timers in the connect logic to detect if the network stack was deadlocked, but I can't remember if I triggered a service restart or not. I'll double check. I may have just uninitialized the socket, and reinitialized it, as I haven't heard anyone report back on that particular issue in a while, so I may not have finished what I intended to do....

**Comment by matt-cylanda** [comment] 2021-01-11 22:18
Interesting. Strangely even a re-install doesn't fix the issue, I have to do a complete uninstall before the service reconnects... or run the restart command you just sent over

**Comment by krayon007** [comment] 2021-01-11 23:25
ok, so I checked what it currently does... The timer it sets only causing it uninit and re-init the control channel socket. I remember what I was doing now... I was going to implement code to check what the system uptime was, so that when I add in the code to force restart the agent, it would only do that if it could detect that the system just booted, so that it doesn't get into a situation where it continuously restarts the agent.  But I only ever got as far as the uptime detection, so I never added the service restart to the logic... I'll work on that, and I'll probably post a binary here that you can test to see if it helps your situation

**Comment by matt-cylanda** [comment] 2021-01-11 23:41
Awesome, thank you!

Just curious... off subject, what are you using for your Mac VM Management? I run an Unraid server at home, but eventually when we all start working back in the office, was just wondering what other folks are using to get Mac VMs up and running.

**Comment by matt-cylanda** [comment] 2021-01-13 18:05
Just fyi, I had to go onsite to a clients location for some on site assistance, I noticed when I got back home, my laptop was no longer in the list of online mac systems. It looks like the agent also stops connecting after the endpoint has changed networks.

**Comment by Extcee** [comment] 2021-01-14 14:11
> Awesome, thank you!
> 
> Just curious... off subject, what are you using for your Mac VM Management? I run an Unraid server at home, but eventually when we all start working back in the office, was just wondering what other folks are using to get Mac VMs up and running.

Just to note, I believe its against Apple's EULA to install macOS (virtualised or not) on non-Apple Hardware.

**Comment by krayon007** [comment] 2021-01-14 16:06
> > Awesome, thank you!
> > Just curious... off subject, what are you using for your Mac VM Management? I run an Unraid server at home, but eventually when we all start working back in the office, was just wondering what other folks are using to get Mac VMs up and running.
> 
> Just to note, I believe its against Apple's EULA to install macOS (virtualised or not) on non-Apple Hardware.

I am using an actual mac. The VMs are to run older macos releases.

**Comment by krayon007** [comment] 2021-01-15 08:23
Just a quick update. I found a logic error in the retry logic when the network stack doesn't respond.  When the timeout expired, it didn't clear one of the state flags, so that when it attempted to reconnect, it didn't make the request... This will be corrected in the next agent update. Hopefully this will address your issue.

**Comment by matt-cylanda** [comment] 2021-01-15 19:46
> > > Awesome, thank you!
> > > Just curious... off subject, what are you using for your Mac VM Management? I run an Unraid server at home, but eventually when we all start working back in the office, was just wondering what other folks are using to get Mac VMs up and running.
> > 
> > 
> > Just to note, I believe its against Apple's EULA to install macOS (virtualised or not) on non-Apple Hardware.
> 
> I am using an actual mac. The VMs are to run older macos releases.

Ahh right... I thought about running VM's on my laptop, but we really needed to have a small group of them going to test out some deployments we're rolling out. I am aware of the EULA restrictions, we are not using the installations commercially, and we do own Apple hardware for our production environments, so I don't feel we're circumventing Apple's ability to make money off of us :P 

> Just a quick update. I found a logic error in the retry logic when the network stack doesn't respond. When the timeout expired, it didn't clear one of the state flags, so that when it attempted to reconnect, it didn't make the request... This will be corrected in the next agent update. Hopefully this will address your issue.

Thanks for your assistance, I'm sure you guys are pretty tied up with the Windows 0.7.47 issues right now.

**Comment by honestlai** [comment] 2021-01-21 19:18
I'm having the same issue

**Comment by krayon007** [comment] 2021-01-21 20:13
> I'm having the same issue

What server version are you running?

**Comment by honestlai** [comment] 2021-01-21 20:14
0.7.49... Do the agents need to be removed and re-installed?

**Comment by krayon007** [comment] 2021-01-21 20:39
> 0.7.49... Do the agents need to be removed and re-installed?

No..
When the agent appears to be disconnected, are you able to open a terminal on that machine, and navigate to where the agent is installed, usually `/usr/local/mesh_services/meshagent` and execute the command `sudo ./meshagent -state` and report what it says?

**Comment by honestlai** [comment] 2021-01-21 20:48
Unfortunately no, but I am logged into my laptop that normally shows up in MeshCentral

```
Querying Mesh Agent state...
Mesh Agent connected to: [NOT CONNECTED]
 Chain Timeout: 86400000 milliseconds
 FD[12] (R: 0, W: 0, E: 0) => ILibAsyncSocket
 FD[9] (R: 0, W: 0, E: 0) => Signal_Listener
 FD[14] (R: 0, W: 0, E: 0) => net.ipcServer.ipcSocketConnection
 FD[11] (R: 0, W: 0, E: 0) => net.ipcServer
 FD[15] (R: 0, W: 0, E: 0) => ILibWebRTC_stun_listener_ipv4
```

**Comment by krayon007** [comment] 2021-01-21 21:01
> Unfortunately no, but I am logged into my laptop that normally shows up in MeshCentral
> 
> ```
> Querying Mesh Agent state...
> Mesh Agent connected to: [NOT CONNECTED]
>  Chain Timeout: 86400000 milliseconds
>  FD[12] (R: 0, W: 0, E: 0) => ILibAsyncSocket
>  FD[9] (R: 0, W: 0, E: 0) => Signal_Listener
>  FD[14] (R: 0, W: 0, E: 0) => net.ipcServer.ipcSocketConnection
>  FD[11] (R: 0, W: 0, E: 0) => net.ipcServer
>  FD[15] (R: 0, W: 0, E: 0) => ILibWebRTC_stun_listener_ipv4
> ```

wierd... And if you run the command `./meshagent -info`

does it reports the same data as the following:
```
Compiled on: 10:24:08, Jan 18 2021
   Commit Hash: 949b49257b41332dd3a8e8c5f4ad2825778eac01
   Commit Date: 2021-Jan-17 21:48:07-0800
Using OpenSSL 1.1.1i  8 Dec 2020
```

**Comment by honestlai** [comment] 2021-01-22 01:29
I get the following:

```
Compiled on: 12:56:56, Jan  7 2021
   Commit Hash: e0ec2a405dc422645036963592c5b895db894fc7
   Commit Date: 2020-Dec-31 13:13:23-0800
Using OpenSSL 1.1.1i  8 Dec 2020
```

**Comment by krayon007** [comment] 2021-01-22 05:53
> I get the following:
> 
> ```
> Compiled on: 12:56:56, Jan  7 2021
>    Commit Hash: e0ec2a405dc422645036963592c5b895db894fc7
>    Commit Date: 2020-Dec-31 13:13:23-0800
> Using OpenSSL 1.1.1i  8 Dec 2020
> ```

Are you sure you are running v0.7.49?
The commit date for the macOS agent for v0.7.49 is Jan-17... The particular fix I implemented for this issue, was committed on Jan 13th.

```
Compiled on: 10:23:26, Jan 18 2021
   Commit Hash: 949b49257b41332dd3a8e8c5f4ad2825778eac01
   Commit Date: 2021-Jan-17 21:48:07-0800
Using OpenSSL 1.1.1i  8 Dec 2020
```

**Comment by honestlai** [comment] 2021-01-23 09:05
I think it's fixed now. I did an uninstall from my machine from the command prompt, and then made sure to download and install from the portal. I've rebooted a few times, it looks like it's working now.

Thank you!

**Closed** 2024-02-23 11:33 UTC
Labels: bug
