### ISSUE TITLE
MeshCentral crashes when using the RelayPort 

### ISSUE THREAD

**Issue by vtacquet** [Ylianst/MeshCentral#4196] opened 2022-06-30 08:56 UTC
**Describe the bug**
When you click the HTTPS link of a device the MeshCentral service crashes and restarts
![CleanShot 2022-06-30 at 10 55 20](https://user-images.githubusercontent.com/5128967/176636176-1118da44-57a8-454d-8805-476385779aac.png)

**To Reproduce**
1. enable RelayPort 
2. go to a device
3. click HTTPS
4. check log

**Expected behavior**
Page should open 

**Log**
```
ERR: /meshcentral/node_modules/meshcentral/apprelays.js:184
        for (var i in pendingRequests) { if (pendingRequests[i][2] == true) { pendingRequests[i][1].end(); } else { pendingRequests[i][1].close(); } }
                                                                                                                                          ^

TypeError: pendingRequests[i][1].close is not a function
    at close (/meshcentral/node_modules/meshcentral/apprelays.js:184:139)
    at handleNextRequest (/meshcentral/node_modules/meshcentral/apprelays.js:129:31)
    at Object.tunnel.onclose (/meshcentral/node_modules/meshcentral/apprelays.js:153:13)
    at Object.obj.close (/meshcentral/node_modules/meshcentral/apprelays.js:361:32)
    at WebSocket.<anonymous> (/meshcentral/node_modules/meshcentral/apprelays.js:423:117)
    at WebSocket.emit (node:events:527:28)
    at WebSocket.emitClose (/meshcentral/node_modules/ws/lib/websocket.js:172:10)
    at Socket.socketOnClose (/meshcentral/node_modules/ws/lib/websocket.js:781:15)
    at Socket.emit (node:events:527:28)
    at TCP.<anonymous> (node:net:715:12)

Node.js v17.9.1
Error: Command failed: /usr/local/bin/node /meshcentral/node_modules/meshcentral/meshcentral.js --launch 7
```

**Server Software:**
 - Virtualization: Docker container based on node:17-buster-slim
 - Network: Traefik reverse proxy in front (also proxying the RelayPort)
 - MeshCentral Version: 1.0.43
 - Node: v17.9.1
 - Browser: Google Chrome

**Remote Device (please complete the following information):**
 - Device: macBook Pro M1-Pro
 - OS: macOS Monterey 12.4

**Comment by si458** [comment] 2022-06-30 09:03
i can indeed confirm the same, but only on certain devices, some devices it works no problem?

**Comment by vtacquet** [comment] 2022-06-30 09:12
@si458 nope it does not have one, but if a user clicks by accident on HTTPS in stead of HTTP the server should not crash

**Comment by vtacquet** [comment] 2022-06-30 09:23
or a entry box to allow you to enter the port you want to relay... every device has specific ports...

**Comment by si458** [comment] 2022-06-30 09:24
> or a entry box to allow you to enter the port you want to relay... every device has specific ports...

ill add this to my feature request issue! i was literally just thinking this as i cant access say portainer running on 9000,

this issue is actually a BUG

**Comment by si458** [comment] 2022-06-30 09:49
#4198 should fix it, can u try for me?

**Comment by Ylianst** [comment] 2022-06-30 17:29
PR approved, will be in 1.0.43. I think @si458 found exactly the problem, thank you!

**Comment by si458** [comment] 2022-07-03 16:34
@Ylianst while the PR fixed this issue im still getting another error when it comes to websockets being relayed
```
TypeError: Cannot read properties of null (reading 'connection')
    at processHttpResponse (/opt/meshcentral/meshcentral/apprelays.js:641:32)
    at processHttpData (/opt/meshcentral/meshcentral/apprelays.js:496:21)
    at TLSSocket.emit (node:events:537:28)
    at addChunk (node:internal/streams/readable:324:12)
    at TLSSocket.<anonymous> (/opt/meshcentral/meshcentral/apprelays.js:411:66)
    at readableAddChunk (node:internal/streams/readable:293:11)
    at Readable.push (node:internal/streams/readable:234:10)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)
    at Duplex.ondata (node:internal/js_stream_socket:77:22)
    at Duplex.emit (node:events:537:28)
```

**Comment by lergolas** [comment] 2022-07-05 09:00
I have a similar problem, I assume it will be the same.

When I web relay to a server the Meshcentral service restarts.

The server is a NAS OMV. I have another OMV NAS with the same version and it works fine.

The difference between one and the other is that the one that works is in the same network as the Meshcentral server, the one that causes the error is in another location and accesses from the outside through the reverse proxy.

I comment here the error that gives me:

`-------- 2022-7-5 10:33:06 ---- 1.0.45 --------

_http_outgoing.js:514
    throw new ERR_INVALID_HTTP_TOKEN('Header name', name);
    ^

TypeError [ERR_INVALID_HTTP_TOKEN]: Header name must be a valid HTTP token ["{"response""]
    at ServerResponse.setHeader (_http_outgoing.js:532:3)
    at ServerResponse.header (/home/lergolas/node_modules/express/lib/response.js:771:10)
    at processHttpResponse (/home/lergolas/node_modules/meshcentral/apprelays.js:620:71)
    at processHttpData (/home/lergolas/node_modules/meshcentral/apprelays.js:490:17)
    at processRawHttpData (/home/lergolas/node_modules/meshcentral/apprelays.js:443:13)
    at WebSocket.<anonymous> (/home/lergolas/node_modules/meshcentral/apprelays.js:420:21)
    at WebSocket.emit (events.js:314:20)
    at Receiver.receiverOnMessage (/home/lergolas/node_modules/meshcentral/node_modules/ws/lib/websocket.js:720:20)
    at Receiver.emit (events.js:314:20)
    at Receiver.dataMessage (/home/lergolas/node_modules/meshcentral/node_modules/ws/lib/receiver.js:405:14) {
  code: 'ERR_INVALID_HTTP_TOKEN'
}`

**Comment by si458** [comment] 2022-07-05 09:14
@lergolas thats weird, i have 2 openmediavault server that are at different sites remotely
and i can access them no problem with relaying?
are you trying to access them both at the same?
ive found its best to only access one thing at a time with the web relay
also try clearing the cookies for the website https://(YOURMESHCENTRAL):453

**Comment by lergolas** [comment] 2022-07-05 09:44
@si458 I have tried from several browsers and from 2 different computers and the problem is the same. A NAS OMV and another web server work fine, however this other OMV always restarts the Meshcentral service.
It does not do it when you open the page to enter the credentials, the error occurs once you enter the credentials and load the main page.
The other OMV that works, you can normally access all the configuration of the page.

**Comment by si458** [comment] 2022-07-05 09:46
> @si458 I have tried from several browsers and from 2 different computers and the problem is the same. A NAS OMV and another web server work fine, however this other OMV always restarts the Meshcentral service.
> It does not do it when you open the page to enter the credentials, the error occurs once you enter the credentials and load the main page.
> The other OMV that works, you can normally access all the configuration of the page.

Is the omv using https or http?

**Comment by lergolas** [comment] 2022-07-05 10:05
Both OMV use http.

**Comment by Ylianst** [comment] 2022-07-06 07:57
Looks like MeshCentral is receiving a HTTP header that it can't parse correctly. It would be interesting to see what header is causing the issue. I can add code to deal with this gracefully, and skip and display any headers that cause issue.

**Comment by lergolas** [comment] 2022-07-06 10:49
> Looks like MeshCentral is receiving a HTTP header that it can't parse correctly. It would be interesting to see what header is causing the issue. I can add code to deal with this gracefully, and skip and display any headers that cause issue.

Hi!
I just updated to version 1.0.46 and problem with NAS server has been solved.
Now everything works correctly.

Thank you very much!

**Comment by Ylianst** [comment] 2022-07-06 18:48
Nice! ok, closing this one. Please open a new issue if anything comes up.

**Closed by Ylianst** 2022-07-06 18:48 UTC
Labels: bug, Fixed - Please Verify & Close
