### ISSUE TITLE
Mac Agent doesn't install

### ISSUE THREAD

**Issue by cp1797** [Ylianst/MeshCentral#1092] opened 2020-03-31 14:22 UTC
Hey!

So I've got a mix of client platforms. Mostly Windows and just a handful of Macs. The Windows clients work well (minus the cursor flicker, to which I've raised another issue in the past) but the Mac agent doesn't seem to be getting installed. Correct me if I'm wrong, but I believe the installation location is /usr/local/mesh_services/meshagent. There's absolutely no files that show up. Please assist.

Thanks

**Comment by ryanblenis** [comment] 2020-03-31 15:05
Any chance the mpkg you're using has a [space in the name](https://github.com/Ylianst/MeshAgent/issues/22)?

**Comment by cp1797** [comment] 2020-03-31 15:48
Yes there was! Removed it and it installed. Now there's another issue. When I installed it, it worked fine. I restarted the client and now it shows as Offline on the Dashboard. Am I doing something wrong?

**Comment by krayon007** [comment] 2020-03-31 16:00
I'll take a look at the installer, and see what happens when there's a space in the downloaded name...

**Comment by cp1797** [comment] 2020-03-31 16:05
A follow up to what I posted earlier. I enabled the debug log with the line from [this](https://github.com/Ylianst/MeshCentral/issues/797#issuecomment-572782669). and here's what I get:

```
Unable to open database (1/10)
zsh: segmentation fault  ./meshagent_osx64
```

I'm running macOS Catalina 10.15.4 and MeshCentral 0.5.0-s

**Comment by cp1797** [comment] 2020-03-31 16:17
I was able to resolve the connection issue by adding a `sudo` to my execution statement. How do I make it run as a privileged user by default?

**Comment by krayon007** [comment] 2020-03-31 17:12
What statement were you executing? The package installer is supposed to install the agent as a launch daemon, which should already run as a system service.

**Comment by ryanblenis** [comment] 2020-03-31 17:22
If you ran the executable directly I can see the permissions being an issue and sudo being required, however starting/stopping it can be done as a service via:

`launchctl stop meshagent`

and 

`launchctl start meshagent`

**Comment by cp1797** [comment] 2020-03-31 17:37
> What statement were you executing? The package installer is supposed to install the agent as a launch daemon, which should already run as a system service.

I was trying to directly execute the program to see it's output. I did this from /usr/local/mesh_services/meshagent. I ran the below:
```
cd /usr/local/mesh_services/meshagent
sudo ./meshagent_osx64
```




> If you ran the executable directly I can see the permissions being an issue and sudo being required, however starting/stopping it can be done as a service via:
> 
> `launchctl stop meshagent`
> 
> and
> 
> `launchctl start meshagent`

Yup. I did try to restart the service with `launchctl` but it just wasn't working.

**Comment by cp1797** [comment] 2020-03-31 17:40
Oddly enough I was able to resolve the issue by modifying the LaunchDaemon and LaunchAgent in `/Library/LaunchDaemons` and `/Library/LaunchAgents` respectively. I added the following just above the final closing `</dict>`:

```
<key>StandardOutPath</key>
<string>/var/log/meshagent.log</string>
```

Could someone please look into this? I was able to reproduce the exact same issue and solve it with the exact same method on 2 other macOS machines

**Comment by krayon007** [comment] 2020-03-31 17:51
Interesting... I'll also do some testing between Mojave and Catalina, to see if there's a behavior change with regards to stdout redirection.

**Comment by Ylianst** [comment] 2020-03-31 18:10
Note for Bryan, your latest MeshAgent was updated for MacOS and FreeBSD only a while back. I would have to check the MeshCentral version.

**Comment by krayon007** [comment] 2020-03-31 20:28
OK, I fixed the installer issue if the downloaded filename has a space in it. The postflight script copy operation failed if there was a space in the source file name.

However, I wasn't able to reproduce the issue with stdout redirection in the LaunchDaemon. I tested it on Mojave and Catalina, and it worked without specifying redirection on both.

But anyways, this update should be in the next server update.

**Comment by ryanblenis** [comment] 2020-03-31 20:35
I assume theres more going on with the daemon not running correctly. I've got it on about 20 Macs now and it is constantly dying or not connecting on boot or after waking from sleep. Just trying to build a profile of macOS versions to narrow it down before filing a bug report. Glad the space issue in the installer will be fixed though!

**Comment by jfp2** [comment] 2020-05-03 11:47
Would love to hear how this issue progresses. I'm not able to roll the product out due to this. 😕

**Comment by cp1797** [comment] 2020-05-03 13:28
Really sorry for not replying. Due to medical issues I'm currently in hospital quarantine and am unable to check further. My sincere apologies if this has impacted the roll out

**Comment by jfp2** [comment] 2020-05-13 10:22
Hope you've beaten this thing, and can hug your loved ones.

Best

**Comment by vitko-bg** [comment] 2020-10-05 09:46
Same issue here: 
"Unable to open database (1/10)
Unable to open database (2/10)
.............................................................
Unable to open database (10/10)"

No spaces in the names
Running on Catalina
MC Server: 0.6.56

**Comment by ryanblenis** [comment] 2020-10-05 15:08
Hi @vitko-bg ,

The space in the name issue was for the installer. Typically when you're seeing "Unable to open database" there is a permissions issue or the daemon is already running.

What are the outputs of `sudo ls -alh /usr/local/mesh_services/meshagent/` and `sudo ps aux | grep meshagent` ?

**Comment by vitko-bg** [comment] 2020-10-05 19:23
Result from 1st comand is:
drwxr-xr-x  8 root  wheel   256B  5 Oct 20:16 .
drwxr-xr-x  3 root  wheel    96B  4 Oct 22:00 ..
srwxrwxrwx  1 root  wheel     0B  5 Oct 20:16 DAIPC
srwxr-xr-x  1 root  wheel     0B  5 Oct 20:15 kvm
-rwxr-xr-x@ 1 root  wheel   3.4M  5 Oct 10:38 meshagent_osx64
-rw-r--r--  1 root  wheel    65K  5 Oct 10:57 meshagent_osx64.db
-rw-r--r--  1 root  wheel    63B  4 Oct 22:00 meshagent_osx64.log
-rw-r--r--@ 1 root  wheel   300B  5 Oct 10:38 meshagent_osx64.msh

And from the second one is:
root                96   0.0  0.1  4302988  10780   ??  Ss    8:15pm   0:00.57 /usr/local/mesh_services/meshagent/meshagent_osx64
admin              797   0.0  0.0  4268284    684 s000  S+    8:20pm   0:00.00 grep meshagent


However - it somehow managed to install, but cannot connect to MC server without "ignoreagenthashcheck": true
I have same issue with Linux agents, not sure where is the problem - Agent, MC server or Nginx reverse proxy.
Still trying to figure it out.

**Comment by ryanblenis** [comment] 2020-10-06 00:24
Ok, so that shows the agent is installed and is running. Are you getting the "Unable to open database" errors in the log file, or when trying to run it manually. If the latter, then you need to stop the service first with `sudo launchctl stop meshagent`

As for not connecting without ignoreagenthashcheck, that's a different problem I'm unfamiliar with, but I believe there are many issues listed here with the fixes for that particular problem.

**Comment by si458** [comment] 2024-03-03 01:39
closing as stale,
please download the latest version 1.1.21 and use node 18 or above,
if issue perists, please report back

**Closed by si458** 2024-03-03 01:39 UTC
Labels: bug
