### ISSUE TITLE
7 Day Power State wrong

### ISSUE THREAD

**Issue by adsgreen** [Ylianst/MeshCentral#705] opened 2019-12-04 11:16 UTC
We had a machine that was accidentally turned off last night around 22:00 and wasn't powered on until 06:00 this morning. 
However for the mesh service is saying there was no interruption and that it was online the whole time.
Is there a away to debug this?
Running mesh 0.4.5.b

**Comment by ryanblenis** [comment] 2019-12-04 15:30
I see similar results as well with Surfaces when they go into sleep mode, though I don't pay attention to that feature so I haven't looked into it myself.

**Comment by Ylianst** [comment] 2019-12-04 18:50
One thing that can help a lot with this is to take a look at the data log and see if the data is ok and it's just the graph that is bad, or if the data is the problem. You can download the raw timeline data using the small icon on the upper right of the timeline graph. Feedback on this would be appreciated.

![x](https://user-images.githubusercontent.com/1319013/70171572-d6e3c680-1683-11ea-9715-d9e2c4cd4028.png)

**Comment by ryanblenis** [comment] 2019-12-04 20:05
Oddly enough, I just downloaded that export for a machine that has been consistently on all week and it seems to "flicker" for several seconds every now and then. Perhaps when I restart the MeshCentral server? But that doesn't make sense as it should not affect the actual power state of the machine. (Changed .csv to .log for GitHub compat)
[powerevents.log](https://github.com/Ylianst/MeshCentral/files/3923746/powerevents.log)

A small side question: why is the power state generated as black bars instead of a pretty graph like in the server tab using charts.js?

**Comment by Ylianst** [comment] 2019-12-04 20:13
The power state is data shows the server's knowledge of the device's state, not the actual device state. So, if you reset the server, you do get a gap in the data. If the gap is small, it's not going to be shown in the graphs, but it will be in the data. So, if the server is shutdown for an hour, all devices will have an hour gap. Also, if a device does not have network connectivity for an hour, you also get a gap.

As for the charts looking nice... this is something I can look at at some point. This graph format is a really simple HTML table and can be displayed quickly on all browsers. That said, something I lot more fancy could be built.

**Comment by ryanblenis** [comment] 2019-12-04 20:22
That makes sense. So this isn't so much about being a "power state" versus being an an "online and able to communicate with the server" state. E.g. the computer could be on, but not connected to the internet, thus would have a gap in the graph. Correct?

**Comment by Ylianst** [comment] 2019-12-04 21:28
Exactly. I guess we could have the agent send the computers uptime when it connects to the server and correct the data. Of course, you would have to trust that the agent information is correct.

**Comment by ryanblenis** [comment] 2019-12-04 21:33
I actually like online state better. I don't care about when a computer is powered on, I care when it is online. I do, however care about the uptime- but that can be seen pretty easily with a "Last Rebooted" timestamp versus the black bar graph that only spans 7 days.

**Comment by adsgreen** [comment] 2019-12-05 09:25
Got the data and it's not right:
Thu Nov 28 2019   09:39:26 GMT+0000 (Coordinated Universal Time) | 1
Fri Nov 29 2019 09:22:17 GMT+0000   (Coordinated Universal Time) | 0
Fri Nov 29 2019 09:22:22 GMT+0000   (Coordinated Universal Time) | 1

Where as the windows event logs for the machine show the power went off at 22:00 and was restored at 06:00

**Comment by Ylianst** [comment] 2019-12-05 18:38
Ok, that helps. I may not have recorded that the agent disconnected. I will have to take a look at this.

**Comment by PathfinderNetworks** [comment] 2019-12-05 22:50
I believe you are on the right track.  It appears it's not recording when the agent goes offline.  Below is the screen grab from the power state download for a device I installed MeshAgent on this afternoon.  (at 1:45pm EST).  But I then shut that same device down at about 3pm EST.  The power state is not recording when the device was powered off.  
![time](https://user-images.githubusercontent.com/48607498/70280954-ad13c800-1787-11ea-9d7d-fd2c2620acdc.JPG)

**Comment by pczolee** [comment] 2019-12-15 10:07
I had a bugreport regarding this issue before. Unfortunately this part of MC still not working :(, I hope we can have an update soon...

**Comment by MailYouLater** [comment] 2019-12-17 19:32
"I had a bugreport regarding this issue before"?  I don't see an issue about this posted by you, but I do see that you posted a comment on another issue that someone else opened about this.

Anyway, this is a duplicate of #460.

**Comment by JunHyunPark1210** [comment] 2020-03-02 08:39
So, was this issue still not improved?

I also faced with that power state shows powered on even when PC is shut down or when agent process is terminate

**Comment by PathfinderNetworks** [comment] 2020-03-02 17:46
I don't believe it's been resolved.  The 7 day power state and Last Seen times still don't seem to match up with what the device is actually experiencing for power state.  I have one device I'm looking at now that reports the last seen time as 2;28;20 at 2:03 pm (which may or may not be correct) but the 7 day power state shows it as being connected until 4:29pm on 2/29/20 (which likely is not correct).

**Comment by Ylianst** [comment] 2020-05-08 02:40
This is now fixed. I will close this one, but please open again if needed.

**Closed by Ylianst** 2020-05-08 02:40 UTC
Labels: bug
