### ISSUE TITLE
Manually-defined battery status data for display in MeshCentral

### ISSUE THREAD

**Issue by DaveTSG** [Ylianst/MeshCentral#1761] opened 2020-08-27 08:48 UTC
As per [this Reddit post](https://www.reddit.com/r/MeshCentral/comments/igt2x6/prepare_device_battery_data_for_meshcentral/), I would like to propose a new feature that allows people with custom battery situations to provide battery data to MeshCentral, e.g. via a plain-text file that the user can update through the user's own scripts.

I have a fleet of Raspberry Pi systems that all have [a battery system for power](https://lifepo4wered.com/lifepo4wered-pi+.html). This system provides an easy BASH command that can access battery charge data, i.e. the voltage currently being output to the Raspberry Pi, and the voltage being applied to the battery itself.

Using this information, I can tell if the battery is being charged or discharged, and (based on known minimum and maximum battery output voltage) a rough idea as to what the battery charge level might be. (To find out a more exact charge percentage, I would have to look at the battery's charge/discharge curve, and then figure out the voltages for specific percentages, e.g. what is the output voltage at 10% remaining battery charge?).

It would be useful to be able for the user to put this data into a plain text file in e.g. /home/<user directory>/ 

For instance, the plain text file could contain the following:

`Charging=yes` (or alternatively `no`)
`MaximumOutputVoltage=xxx.yyy` (a float value of voltage in millivolts)
`MinimumOutputVoltage=xxx.yyy` (a float value of voltage in millivolts)
`CurrentOutputVoltage=xxx.yy` (a float value of voltage in millivolts)

These four parameters would be the minimum required. If only these are provided by the user, then MeshCentral would ideally show the charging status (either "charging" or "not charging"), along with the three voltage values (minimum, maximum, and current voltage).

Even better would be if the user could optionally provide the following lines as well in the same file:

`100=xxx.yyy` (a float value of voltage that would be expected if the battery is at 100% charge. This should be identical to MaximumOutputVoltage)
`90=xxx.yyy` (a float value of voltage that would be expected if the battery is at 90% charge.)
`80=xxx.yyy` (a float value of voltage that would be expected if the battery is at 80% charge.)
`70=xxx.yyy` (a float value of voltage that would be expected if the battery is at 70% charge.)

...and so on, so that there are voltage values for every 10% from 0% to 100%.
That would allow MeshCentral to then know (even if it's a vague ballpark idea) what the actual charge percentage is.

(or even better again, instead of having only values for every 10% increment, the user could just specify any percentage e.g. 2.5% and a voltage value, and MeshCentral would then display the appropriate percentage instead of the CurrentOutputVoltage)

The reason this percentage section needs to be optional, though, is because the user will need to test their battery (a battery-specific thing) and determine an appropriate discharge curve for the battery; this isn't an easy thing to do so some users might not want to bother with this. I certainly intend to use it, though, if it's implemented.

Hope this all makes sense...

Thanks for considering this.
David

**Comment by Ylianst** [comment] 2020-08-29 03:06
Interesting request, I did a first attempt at adding this feature but will need Bryan's help on a few things. I only had it working on Windows so far.

Basically, you create a file called "batterystate.txt" in the agent folder that contains:

```
ac,75
```

or

```
dc,25
```

Where AC is charging or plugged-in and DC is discharging and the number is from 0 to 100 the state of charge. When you change the file, the battery state is updated to the server. It does not work yet, but that is the idea. Your going to have to map the voltage and state yourself and write that file when you want.

**Comment by DaveTSG** [comment] 2020-08-30 02:49
Brilliant, thanks for this, looks like it'll be flexible enough for either use-case I mentioned. 👍 
Could you please clarify where the agent folder is, though?

Thanks again!
Dave

**Comment by Ylianst** [comment] 2020-08-30 13:50
It's not currently implemented, but will let you know when it is.

**Comment by DaveTSG** [comment] 2020-08-30 22:07
Thanks!

**Comment by Ylianst** [comment] 2020-09-03 23:47
Just published MeshCentral 0.6.28 with support for manual battery state and tested it on Raspberry Pi. You should be able to do this:

```
sudo echo "dc,90" > /usr/local/mesh/batterystate.txt
```

Then restart the agent and you should see the battery state on the web page. Once the agent starts tracking this file, you can edit it and should see the server update a second later. Valid values are `ac` or `dc` followed by a comma and a value from 0 to 100.

Let me know if this works.

**Comment by DaveTSG** [comment] 2020-09-04 10:25
Ok, thanks. I have updated MC server to v0.6.28, waited about 15 minutes to let the agent update propagate to the device. I then added the ran the above command and checked using nano to ensure the file /usr/local/mesh/batterystate.txt contains only "dc,90" (without quotes).

I then rebooted the RPi as I can't remember how to restart the MC agent and I figured a reboot would be easier.

I don't know if the agent on the RPi has been updated yet or not, but at this point I'm not seeing any battery indicator in the MC server.

Could you please advise where this would appear? e.g. on the "My Devices" page? Or on the "general" tab of the specific device?

I have looked through all the tabs for this device but can't see anything relating to battery charge status or charge percentage.

Thanks,
Dave

P.S.: awesome GitHub profile pic. Is that the booster in Hawthorne or some other one? One day I will make the _holy pilgrimage_ from here (Australia) to see it in person... hopefully...

**Comment by Ylianst** [comment] 2020-09-04 17:38
A few things, first for restarting the agent:

```
sudo systemctl restart meshagent
```

Next, go in /usr/local/mesh and take a look at the file ownership. Make sure 'batterystate.txt` is the same owner and group as the MeshAgent. Use `chown` and `chgrp` to change if needed.

You will see the battery icon on the devices page and on the device, you can't miss it once there.

PS: Yes, it's the SpaceX Hawthorne booster, the first one to have successfully landed. I watched it on the live stream so it was nice to also see it in person.

**Comment by DaveTSG** [comment] 2020-09-05 01:29
Thanks, I restarted the agent with that code, but still no luck with the indicators...

It looks like the file has the right ownership...

<img width="721" alt="Screen Shot 2020-09-05 at 11 27 40 am" src="https://user-images.githubusercontent.com/10595542/92293961-e376b180-ef6a-11ea-947b-320e6df12497.png">

**Comment by Ylianst** [comment] 2020-09-10 21:23
Ok, I know what the problem is. You need to re-install your agent. Just run the install script again and it should work. The problem is that the old install script did not set the agent working directly and so, the "batterystate.txt" file can't be found. An alternative that may work is to put "batterystate.txt" in the root folder of the Raspberry Pi. That may work until you run the agent install script again.

I just tested it and my older Raspberry Pi run into the same problem, the new ones that I installed later work. Let me know if this helps.

**Comment by DaveTSG** [comment] 2020-09-10 22:51
Uhhh, that seems to have made things worse...

I got the installer script via the MC server's "My Devices" page, by clicking the "add agent" link and choosing Linux installer command.

I then entered the terminal view for this Pi and pasted the installer command into the terminal. I wasn't paying close attention so I'm not sure of the exact timing, but either mid-way through pasting the command, or instantly after finishing pasting the command, the terminal (in MC) disconnected from the device (as you'd expect if it was reinstalling the agent).

Ten minutes later and the Pi is still showing as disconnected in MC and I have no way of controlling it...

**Comment by Ylianst** [comment] 2020-09-11 06:44
So, running the MeshAgent install script within the agent's own terminal session is really playing with fire. That case has not been tested and as one could imagine... once you start the script and it uninstalls the current agent, the terminal session will close killing the install script. The new again will never get a chance to install. So, your likely toast. You need to SSH back into that device and run the install script properly.

**Comment by DaveTSG** [comment] 2020-09-11 07:00
Ah.

Ok, let me see if I can set up the uninstall and reinstall via a cron job (I have no way of SSHing into the Pi, but I can alter its cron jobs as I have it set up to get updates off my AWS S3 every five minutes just in case)...

**Comment by DaveTSG** [comment] 2020-09-11 07:21
Ok, managed to get it uninstalled and then reinstalled and I can now use MC to access the Pi's terminal. I have also recreated the batterystate.txt file and checked the ownership and it's all ok, but the status indicators still aren't showing in MC server...

**Comment by DaveTSG** [comment] 2020-09-25 01:37
Hi @Ylianst, just wondering if you had any further ideas on this please? Thanks.

**Comment by DaveTSG** [comment] 2020-09-25 01:38
Ah, never-mind. I just opened MC server and the battery indicator is there now. Not sure why it took two weeks to appear but it's there now! 

Thanks heaps for implementing this. It's very much appreciated!

**Comment by DaveTSG** [comment] 2020-10-03 05:36
Hi @Ylianst, unfortunately I have noticed that the MC server does not show the battery indicator on my RPi in the "My Devices" screen of the MC server.

It works if I log into the Pi's terminal via MC, and then run the command e.g.
"echo "ac,100" > /usr/local/mesh/batterystate.txt"

If I then immediately go back to the MC My devices screen, the battery indicator appears.
However, if the system later reboots (or if I manually reboot it), the battery status indicator does not appear after reboot. 

Do you have any thought on what may be causing this please? Thanks.

**Closed** 2021-04-30 18:08 UTC
Labels: Fixed - Confirm & Close, enhancement

**Comment by DaveTSG** [comment] 2021-05-02 05:13
Hi @Ylianst. I'm not sure why this was closed... the issue is still occurring as per my last message dated 3rd October 2020 (server v0.7.89, the latest stable version).
Thanks, 
Dave
