### ISSUE TITLE
Improve Touch interface for remote desktop

### ISSUE THREAD

**Issue by meichthys** [Ylianst/MeshCentral#4644] opened 2022-10-18 15:00 UTC
**Is your feature request related to a problem? Please describe.**
The Remote Desktop Feature isn’t very usable with a touch screen because touch is not precise enough to select small check boxes and or buttons. In testing it probably worked well when using developer tools on a desktop machine because you can click very precisely with the mouse, but in reality it is very difficult on a small screen to make a precise click using touch.

**Describe the solution you'd like**
It would be really nice to be able to change from touch mode to trackpad mode like is possible in the Microsoft Remote Desktop App. Great work on MeshCentral!

**Describe alternatives you've considered**
I've tried using a larger touch screen like an iPad and it helps, but it's still very difficult to click precisely.

**Comment by si458** [comment] 2022-10-24 14:49
duplicate of #3816

**Closed** 2023-09-30 05:40 UTC
Labels: enhancement
