### ISSUE TITLE
Agent

### ISSUE THREAD

**Issue by Ronnyhe96** [Ylianst/MeshCentral#5247] opened 2023-07-18 13:51 UTC
It takes a long time to see a newly configured device in windows and linux.
It does not appear to download mobile agent.
And I also can't see the screen of linux,ubuntu,fedora devices.

**Comment by si458** [comment] 2023-07-18 15:09
duplicate of #3211 #2998

**Comment by Ronnyhe96** [comment] 2023-07-18 15:11
Thanks!

**Comment by si458** [comment] 2023-07-18 15:12
plz close the issue if it has been fixed 👍

**Closed** 2023-07-18 15:16 UTC
Labels: question
