### ISSUE TITLE
Web-RDP link disappear after v1.0.13

### ISSUE THREAD

**Issue by smartekIT** [Ylianst/MeshCentral#3924] opened 2022-04-30 10:06 UTC
![image](https://user-images.githubusercontent.com/70715469/166101087-06db20ec-84c5-44f4-a2a4-bd60e1c31436.png)

**Comment by smartekIT** [comment] 2022-04-30 10:26
my config.js:
<pre>
  "domains": {
    "": {
      "deviceMeshRouterLinks": {
         "rdp": true,
         "ssh": true,
         "scp": true,
      },
      "mstsc": true,
      "novnc": true,
      "ssh": true
   }
}
</pre>

**Comment by Mfinadmin** [comment] 2022-04-30 10:30
+1 same issue.

**Comment by VINISHVV** [comment] 2022-04-30 11:04
+1 same problem.

Tried remove the "mstsc": true from configuration. But its not working.

**Comment by Ylianst** [comment] 2022-04-30 17:26
Oh! Looking into it today.

**Comment by prononext** [comment] 2022-04-30 18:13
same also.

**Comment by LPJon** [comment] 2022-05-01 00:33
+1 Same Issue.....I really want to try this new feature out. This is awesome! Thanks for the hard work.

**Comment by Ylianst** [comment] 2022-05-01 03:11
Just published v1.0.14 with a fix for this. Let me know if it works.

**Comment by prononext** [comment] 2022-05-01 03:22
It is working like a charm, with NLA integrated nicely. Thank you very much Ylianst !

**Comment by LPJon** [comment] 2022-05-01 03:28
I also confirm this is working! This is so nice.....thank you so much for implementing this. Very much appreciated!

**Comment by Ylianst** [comment] 2022-05-01 05:00
Nice! I am so glad to hear that. I am going to try integrating RDP into the Desktop tab, that should be really cool and looks like I can offer more configuration options.

**Comment by LPJon** [comment] 2022-05-01 05:22
I think that would be really nice. I also really like that it routes the RDP session through the MeshCentral Server. Very nicely done! I notice some lag compared to the MeshCentral "Desktop" tab interface but still very useful. A+ I can't wait to see what other configuration options you can make available. This is a feature we will use A LOT.

**Comment by smartekIT** [comment] 2022-05-01 07:36
each time I try the Web-RDP, and after typing the credentials then clicking Connect it crashes the server.

here is error log attached 
<pre>
Node.js v17.8.0


-------- 5/1/2022, 5:30:08 PM ---- 1.0.14 --------

node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:135:10)
    at md4 (/home/node/meshcentral/node_modules/meshcentral/rdp/protocol/nla.js:276:35)
    at ntowfv2 (/home/node/meshcentral/node_modules/meshcentral/rdp/protocol/nla.js:279:60)
    at new NLA (/home/node/meshcentral/node_modules/meshcentral/rdp/protocol/nla.js:19:28)
    at /home/node/meshcentral/node_modules/meshcentral/rdp/protocol/x224.js:245:24
    at TLSSocket.<anonymous> (/home/node/meshcentral/node_modules/meshcentral/rdp/core/layer.js:161:3)
    at Object.onceWrapper (node:events:641:28)
    at TLSSocket.emit (node:events:527:28)
    at TLSSocket.onConnectSecure (node:_tls_wrap:1565:10)
    at TLSSocket.emit (node:events:527:28)
    at TLSSocket._finishInit (node:_tls_wrap:946:8)
    at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:727:12) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
</pre>

**Comment by Ylianst** [comment] 2022-05-01 08:03
I get the same `digital envelope routines::unsupported` with NodeJS 17, but it work on NodeJS 16. Seems like the removed MD4 support in NodeJS 17 and so, I will need to work around this.

**Comment by smartekIT** [comment] 2022-05-01 08:05
@Ylianst should i revert back to NodeJS 16 for time been ? if yes, then how and what exact version i should be using?
Thanks

**Comment by smartekIT** [comment] 2022-05-01 08:15
@Ylianst 
ok I did:
<pre>
nvm install 16.15.0
</pre>

now node -v showing 16.15.0. will try it again.

**Comment by smartekIT** [comment] 2022-05-01 08:22
still doing the same thing with:
nvm v0.39.1
npm v8.5.5
node v16.15.0

**Comment by Ylianst** [comment] 2022-05-01 09:04
Turns out MD4 and RC4 are both missing from NodeJS v17. I just added alternatives for both of them. Hold on a minute, I will release a new version.

**Comment by Ylianst** [comment] 2022-05-01 09:08
MeshCentral v1.0.15 is out, let me know if it works for you on NodeJS v17.

**Comment by smartekIT** [comment] 2022-05-01 09:34
> Turns out MD4 and RC4 are both missing from NodeJS v17. I just added alternatives for both of them. Hold on a minute, I will release a new version.

sorry, i was too quick. i already downgraded to v16.15.0 and then i edited the meshcentral service to use the 16.15.0 then i reinstalled meshcentral 1.0.14.

now testing v1.0.14 on node 16.15.0  if success then i will upgrade the node and test it for you on node v17.8.0

**Comment by smartekIT** [comment] 2022-05-01 10:00
@Ylianst 
MC v1.0.15 on Node v16.15.0 >> Working
MC v1.0.15 on Node v17.8.0 >> Working

MC doesn't use the saved credentials for Web-RDP on the second connection even though in the device page it shows that RDP credentials are saved !

**Comment by PetieM** [comment] 2022-05-02 05:11
I can confirm this is working on Node 17 with NLA as well - thanks for making this happen! As an aside though, my saved credentials do not appear to be working for web RDP sessions despite showing as saved.

**Comment by JTrotta** [comment] 2022-05-02 12:34
Hello, I can only install these ones:
```
Name                                  Stream                                  Profiles                                                            Summary
nodejs                                10 [d][e]                               common [d], development, minimal, s2i                               Javascript runtime
nodejs                                12                                      common [d], development, minimal, s2i                               Javascript runtime
nodejs                                14                                      common [d], development, minimal, s2i                               Javascript runtime
nodejs                                16                                      common [d], development, minimal, s2i                               Javascript runtime
```
Now i'm using 10, would it work with 16?

**Comment by smartekIT** [comment] 2022-05-02 12:53
it should be working on Node v16.15.0. I already tested it.

**Comment by smartekIT** [comment] 2022-05-02 15:25
it happened to me before.
just stop MC service:
systemctl stop meshcentral.service

edit MC service, pointing it to use node v16.15.0 by doing the following:
sudo pico /etc/systemd/system/meshcentral.service

now change the version of the node in ExecStart line, mine looks like this:
ExecStart=/root/.nvm/versions/node/v17.8.0/bin/node /home/node/meshcentral/node_modules/meshcentral

save it and close,

now reload daemon services:
systemctl daemon-reload

now restart MC service:
sudo systemctl restart meshcentral.service

once it's up again, login and go to the console tab, type "info" in the command filed. now it should say it's using Node v16.15.0

**Comment by smartekIT** [comment] 2022-05-02 15:49
here is the full process how I've done mine, I'm on ubuntu 20.04 and using NVM while meshcentral in my home folder. I had Node v17.8.0 installed but I needed to downgrade to Node v16.15.0

<pre>
cd /root
nvm list  # this will show all nodes versions installed, let's clean them all and start fresh on v16.15.0

nvm deactivate
nvm uninstall 17.8.0
nvm uninstall 16.15.0  #do this if you already installed v16.15.0 before but you want to start clean and fresh.
nvm unload
rm -Rf ~/.nvm

apt-get install build-essential libssl-dev
wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
source ~/.profile
nvm --version
node -v
nvm install 16.15.0

nvm list #This show currently installed

cd /home/node/meshcentral
npm install meshcentral@1.0.15   # This will re-install MC v1.0.15. don't worry you won't lose your settings if you have folder "meshcentral-data" there.

# now let's edit the meshcentral service so it can use the new node version:
sudo pico /etc/systemd/system/meshcentral.service

change the version node in the path from 17.8.0 to 16.15.0 . save and close.

#now reload the daemon:
systemctl daemon-reload

#now restart MC service
sudo systemctl restart meshcentral.service
</pre>

**Closed** 2022-05-31 03:28 UTC
Labels: bug, Fixed - Please Verify & Close
