### ISSUE TITLE
MeshCentral 0.8.63~0.8.65 . [issue]  [sessionRecording Index Not working sometimes]

### ISSUE THREAD

**Issue by Jacky0400143** [Ylianst/MeshCentral#2794] opened 2021-06-18 05:29 UTC
Hi ,
#2793 Although I submitted an issue yesterday, I will make a separate issue for the convenience of tracking
Sorry for my usage problem, I will separate my problems

> MeshCentral version 0.8.63~0.8.65 , all agents are up to date
Server : Raspberry Pi 4 2GB RAM , Linux raspberrypi 5.10.17-v7l+ #"1421 SMP Thu May 27 14:00:13 BST 2021 armv7l GNU/Linux
> Using Firefox 64bit 89.0 and Edge based on Chromium 64bit 91.0.864.48

> [sessionRecording] ,

index Sometimes not working,but some Recodings works,
Causes some too long videos to be unable to skip,

Config.json below

`"sessionRecording": {
        "onlySelectedDeviceGroups": true,
        "filepath": "/home/XX/meshcentral/meshcentral-recordings",
        "index": true,
        "maxRecordings": 64,
        "_maxRecordingSizeMegabytes": 64,
        "__protocols__": "Is an array: 1 = Terminal, 2 = Desktop, 5 = Files, 100 = Intel AMT WSMAN, 101 = Intel AMT Redirection, 200 = Messenger",
        "protocols": [ 1, 2, 101 ]`
;

**Comment by Ylianst** [comment] 2021-06-18 16:00
Indexing only works for remote desktop sessions. Currently no indexing possible for terminal or Intel AMT KVM. If the indexing does not work for remote desktop session, it would be great to have a sample file that is not indexed and I will try it.

**Comment by Jacky0400143** [comment] 2021-06-19 01:48
@Ylianst

I use it on remote desktop session. Attached is a screenshot of sample.
At the same time, the time on the session recroding screen is displayed, and a garbled message appears.

![圖片](https://user-images.githubusercontent.com/75102529/122627639-cd963f80-d0eb-11eb-8f22-c5e1cdd66e29.png)

also I will email you same sample file for reference .
Many Thanks.

**Comment by Jacky0400143** [comment] 2021-06-19 02:31
@Ylianst 
I have provided three sample files and sent them to the hotmail provided on your github
Thank you

**Comment by Ylianst** [comment] 2021-06-22 15:33
Duplicate of #2795.

**Closed by Ylianst** 2021-06-22 15:33 UTC
Labels: bug
