### ISSUE TITLE
Add agent: link to exe is wrong

### ISSUE THREAD

**Issue by hunter-nl** [Ylianst/MeshCentral#288] opened 2019-06-08 12:38 UTC
With Add Agent dialog: For type Windows and Windows Uninstall, the link (32 & 64 bits) points to blob:https://server.domain.com:443/randomstring
The part of blob is wrong. And the rest of the url is not found when copy paste it manually into browser.
The url's are correct with copy url to clipboard.

**Comment by Ylianst** [comment] 2019-06-09 04:45
So, what browser are you using? The "links" used to be real links, however they would over a different tab in the browser and it was annoying. The new links make a java script call that loads the agents from the server and opens the save dialog box. So, they are not really correct links. When you click on them, the links are fixed up and used to load the agent.

You should not be able to use the link's URL. However, if you can show me what you do, I will work on a fix. Thanks.

**Comment by hunter-nl** [comment] 2019-06-09 09:04
I'm using Safari. I've read that the response type Blob (xdr.responseType = "blob";) is not supported in Safari.
In Chrome, no Save As dialog appears, it starts downloading immediately.
Firefox and Edge present Save As Dialog.

**Comment by Ylianst** [comment] 2019-06-10 02:53
Ok, this is a Safari issue. I will need to check into it.

**Comment by Ylianst** [comment] 2019-06-11 18:05
I got a Mac with Safari v12.0.3 and all the download links work just fine. What version are you using?

**Comment by hunter-nl** [comment] 2019-06-11 18:29
I have Safari v12.1 On OSX 10.14.5

**Comment by Ylianst** [comment] 2019-06-11 18:46
I can't make this happen. I click on the link and it works. Can you send any additional screen shots or step-by-step details of what you see. I don't understand the problem.

**Comment by hunter-nl** [comment] 2019-06-11 18:57
For example, go to Agents View
![image](https://user-images.githubusercontent.com/5203309/59298281-7eaaa980-8c8a-11e9-8667-b6bbccf62b3f.png)
Click Add Agent
![image](https://user-images.githubusercontent.com/5203309/59298324-97b35a80-8c8a-11e9-83cc-7db6201907b8.png)
Click on the link (32 or 64bits) (not on the Copy to Clipboard icon)
It opens a new tab in Safari:
![image](https://user-images.githubusercontent.com/5203309/59298404-c3cedb80-8c8a-11e9-95f3-9fc08d5d6453.png)
With reason:
![image](https://user-images.githubusercontent.com/5203309/59298544-0bedfe00-8c8b-11e9-9b4a-90f89d8badda.png)

It happens with ALL links anywhere in MeshCentral where ```xdr.responseType = "blob";``` javascript code has been used.

**Comment by Ylianst** [comment] 2019-06-11 22:47
Just tried with Safari 12.1.1 and it also works for me.

**Comment by Ylianst** [comment] 2019-06-18 00:29
Ok. I just realized that if you are on the MeshCentral main page and you have some arguments in the URL like "?trace=1", the download links don't work anymore on any browsers. I just fixed that in MeshCentral v0.3.6-q that I just published.

Also, you can how add "?filedownloadtab=1" at the end of the URL to make the file downloads use a new tab instead of the current method.

Hopefully, one of these will fix this problem. If you can try and report back, that would be appreciated.

**Comment by hunter-nl** [comment] 2019-06-20 08:58
Yes, With ?filedownloadtab=1 it is working. Without it gives still the blob error. I do not like the solution to add the parameter to the url to get a workaround.

**Comment by hunter-nl** [comment] 2019-06-22 12:17
With version 0.3.6-v the links are now working without the use of ?filedownloadtab=1. That's great!

Except for the links:
On Console tab of an agent or My server console to download the console text. That's still using blob method...
And with My server Stats downloading data points.
And both types of My Events Exports and Users Information export

**Comment by Ilia1** [comment] 2019-06-24 14:57
after last update (0.3.6-v) unable to download agent, if the group name contains Cyrillic characters. before that, downloading was normal. If you create a group with an English name, add an agent, then move it to a group with a Cyrillic name, then everything works well.

**Comment by Ylianst** [comment] 2019-06-25 01:03
I will have the mesh agent download with Cyrillic characters fixed in the next version.

For all the links that use "blobs", the problem is that these links are actually local information being saved, there is no download from the server so, I would have to see that is the problem with the blob download. I use [FileSaver](https://github.com/eligrey/FileSaver.js/). I did notice they have a problem with Safari I could maybe take a look at.

**Comment by Ylianst** [comment] 2019-06-25 02:24
FYI. Published MeshCentral v0.3.6-w with a workaround for the Cyrillic characters.

**Comment by Ilia1** [comment] 2019-06-25 04:28
Thank you very much! it works well

**Comment by Ylianst** [comment] 2019-07-14 17:15
Closing this one as it seems fixed.

**Closed by Ylianst** 2019-07-14 17:15 UTC
Labels: Fixed - Please Confirm, bug
