### ISSUE TITLE
not open on windows 11 24h2

### ISSUE THREAD

**Issue by Raxiel1987** [Ylianst/MeshCentral#6457] opened 2024-10-17 09:25 UTC
**Describe the bug**
not working on windows 11 24h2, the program try to start with the dos window but close immediatly, 

on windows 10 and windows 11 23h2 works 

i'm on the latest docker image of meshcentral and the latest agents

**Comment by si458** [comment] 2024-10-17 09:27
Please do ur research of closed issues before opening issues

Duplicate of many issues 

Fix is here https://github.com/Ylianst/MeshCentral/issues/6162#issuecomment-2168031763

You MUST install the wmic client

**Closed** 2024-10-17 09:27 UTC
Labels: bug, duplicate

**Comment by si458** [comment] 2024-11-07 08:24
i have an updated agent for people to test if they want!i have a new agent for people to try if they want!
fully compiled with all the bug fixes in the repo including replacing wmic with the `win-wmi` we already had

1. download zip and extract zip [MeshService64.exe.zip](https://github.com/user-attachments/files/17649745/MeshService64.exe.zip)
2. backup the `MeshService64.exe` from inside `node_modules/meshcentral/agents/` (or rename to something else)
3. place the new `MeshService64.exe` back in `node_modules/meshcentral/agents/`
4. stop meshcentral
5. **IMPORTANT: DISABLE AUTO AGENT UPDATE OTHERWISE ALL AGENTS WILL GET AUTO UPDATED!!!**
set `"noAgentUpdate": 1` inside of `settings` in your `config.json`
7. start meshcentral
8. **IMPORTANT: LET MESHCENTRAL RESIGN/RECUSTOMISE THE SINGLE FILE!**
9. **skip this step if you dont code-sign yourself** 
copy the new signed agent from inside `signed-agents` located inside of `meshcentral-data` to your machine,
code-sign the exe however you want/do it,
put the new code-signed exe back into `agents` replacing the old `MeshService64.exe`
(backing up the old code-signed version of yours first),
restart meshcentral
10. pick a device and go into its `Console` tab and run `agentupdate`
11. you should see the device go offline and then back online, and in theory the date/version will of changed!

edit: you can also then download a new meshagent from the 'addagent' tab and it should work on 24h2 machines for install/run

**Comment by chdodier** [comment] 2025-01-13 19:30
I just tested your proposed agent on a fresh install of windows server 2025 and Windows 11 24H2. My Meshagent server is running on Ubuntu. The new client installation installs and runs fine. Thank You.
