### ISSUE TITLE
Mouse pointer not where it shows

### ISSUE THREAD

**Issue by FilGov** [Ylianst/MeshCentral#191] opened 2019-04-18 16:35 UTC
When using meshcentral.com to desktop connect to Windows 10 computers, the mouse pointer on the connected client is sometimes not where it actually shows, but rather above to the left, making clicking buttons a guessing game.

**Comment by krayon007** [comment] 2019-04-18 16:41
By any chance do you have multi monitors where each monitor has a different DPI setting? I noticed this particular issue a few weeks ago, but haven't had time to look at it deeply yet.

**Comment by FilGov** [comment] 2019-04-18 16:45
Possibly. We do connect to computers with multiple monitors and I do think at least some of them use different resolutions on each monitor.

**Comment by PathfinderNetworks** [comment] 2019-04-19 21:42
I've been noticing this recently as well.  Yesterday I was using MeshCentral to work on a device that has three monitors connected. Two are the same resolution but the third is different.  The mouse pointer was working properly when I was viewing all the displays in the same window. But, as soon as I switched to one of the two monitors that have matching resolutions the mouse pointer was no longer coinciding with the pointer icon on my end.  No matter what I did allowed me to get the mouse pointer to work correctly (including disconnecting and reconnecting, viewing all the displays at once, etc).  I had to end up using a different remote tool to do what I needed to do.  I had noticed something similar a month or so ago on another device.  Also, even since MeshCentral1, the mouse pointer isn't 100% accurate.  You can tell this the most when you are wanting to drag a window larger.  If you try to click on the edge of a window you actually have to move a couple mm to the right or bottom of the edge to actually be able to select the true edge.  Hope that makes sense.  
The second issue I can (and have) deal with.  But this particular issue, with the pointer being dramatically out of sync, is something I can't seem to work around.

**Comment by krayon007** [comment] 2019-04-24 20:54
I root caused and fixed this. It will be released in an upcoming release. It was caused by exactly what I suspected. The DPI awareness API I was using doesn't support when multiple monitors have different DPI settings. So I fixed it so it detects if per-monitor DPI is supported, and if so, uses that. This fix requires an agent update, so it will be released in an upcoming server release.

**Comment by Ylianst** [comment] 2019-04-25 07:17
Bryan showed me a demonstration of the upcoming fix for this. Very impressive. Should be coming next time we release an new Mesh Agent.

**Comment by FilGov** [comment] 2019-04-25 08:57
Thank you. How will we know when it is released? Is there a notification service?

**Comment by Ylianst** [comment] 2019-04-26 17:51
Hopefully next week. You can monitor NPM for server updates, however there is no notification service for when a release has a new agent. If I think about it, i will post here when a release is made.

**Comment by FilGov** [comment] 2019-04-26 17:52
What's NPM?

**Comment by Ylianst** [comment] 2019-04-26 17:54
[Node package Manager](https://www.npmjs.com/package/meshcentral). This is for people that run their own server. If you are using [MeshCentral.com](MeshCentral.com), there is no notification. I will update the server when I get a chance.

**Comment by joshabts** [comment] 2019-12-27 20:28
Just curious if this ever was deployed?  I would presume it has, but I am seeing a similar issue where with a single monitor in the base case, the mouse pointer seems to be "upper right" of the actual mouse pointer showing in the remote desktop.  If you were to draw a rectangle that encapsulates the whole arrow pointer, it seems it is using perhaps the upper right of that rectangle as the point of the cursor rather than the upper left? 

Not certain this is the same issue, I can open a new one if this one was meant to have been closed already or is unrelated.

**Comment by krayon007** [comment] 2019-12-27 20:37
What version/build of Windows are you running? The original issue was caused by different DPI settings on each monitor. The fix was to set the DPI aware flag so that the OS wouldn't try to scale. Not sure what is going on in your case, but I can certainly try to reproduce/diagnose it.

Bryan

**Comment by joshabts** [comment] 2019-12-27 20:44
The computer running the agent is Windows 10 1903.  The windows setting for
scaling is greyed out but the greyed out value is 175% and says custom
value is set, but when I go to advanced it shows it is scaling at 100 in
the value box.  Scaling for apps is turned on for that computer.  Also
1920x1080.  Only a single monitor on this system.

The computer I am connecting from is Windows 10 1803.  No scaling and fix
scaling for apps is turned off, 100%, 1920x1080 on dual monitors.

Running Google Chrome v71 on the computer I am connecting from.

Wondering if the "custom" scaling factor is throwing it off or the "allow
windows to fix blurry apps" setting is messing with something.  I can try
turning those off tonight.

**Comment by joshabts** [comment] 2019-12-27 21:01
I have tried turning off the allow windows to fix blurry apps setting, and
turned off custom scaling.  It is defaulting to 150% scaling.

It does seem to be closer to correct now.

Thinking if I go to no scaling or the same 100% if it would be back to spot
on.

**Comment by ryanblenis** [comment] 2019-12-27 21:03
Can confirm the same thing, however the actual cursor on the remote screen in to the bottom of the actual mouse pointer. Video below.
Destination machine is Win10 1903, 2160x1440 @ 150% scale. Controlling computer is OS X 10.13.6 High Sierra, Chrome 78 browser.

![mcgif](https://user-images.githubusercontent.com/1929277/71532656-631f8d00-28c2-11ea-999e-3dbf4d3268a5.gif)

**Comment by joshabts** [comment] 2019-12-27 21:18
Even at 100% I am noticing it being slightly off still.

**Comment by MailYouLater** [comment] 2019-12-28 01:00
I have a feeling there may be multiple issues here, but they do all seem to be related to some variety of scaling.  I've noticed that on my computers the mouse cursor seems to be in the right spot when MeshCentral's remote desktop is at 100%, 50% or 25% scaling, but all the other scaling factors seem to be off by varying amounts.  I've also noticed that the right and/or bottom edges get cut off in varying amounts at all scales other than 100% which may be related.

In case there's any confusion, this is the scale setting I'm referring to:
![image](https://user-images.githubusercontent.com/1279475/71536616-e8587100-28c5-11ea-9a2f-c827dad0d273.png)

**Comment by MailYouLater** [comment] 2019-12-30 22:04
For diagnosing this, is it possible that an option could be added to not hide the remote cursor?  Then we could directly see the positional difference between the local and remote cursors.

**Comment by krayon007** [comment] 2019-12-30 22:16
That's an excellent idea. I'll look into that when I get back from the holidays.

**Comment by tradexsrl** [comment] 2020-03-22 10:38
i have seen the problem also on computer with open xt os.
open xt is an opensource software derivated from citrix xenclient which enable you to have baremetal virtual machine on desktop. i use it in my company pc so i'm not tie the os to the hardware.
as already written: mouse pointer on the connected client is sometimes not where it actually shows, but rather above to the left, making clicking buttons a guessing game. or impossible for far right object

**Comment by krayon007** [comment] 2020-04-07 15:47
If this issue still persists, you can now set "remoteMouseRender" in the msh file, and restart the agent... This will make it so when you connect KVM, the remote mouse cursor is always rendered. This will take all the guessing out of where the cursor actually is...

**Comment by FilGov** [comment] 2020-04-07 15:52
And if we're using meshcentral.com?

**Comment by tradexsrl** [comment] 2020-04-07 16:10
@krayon007 : i need to explain better because i see this problem also with meshcommander when i'm connected in remote desktop (KVM) and in this case is not a problem of the agent.
mouse pointer is not where it actually shows, but rather above to the left, making clicking buttons a guessing game. or impossible for far right object.
instead if i start a windows vm on top of openxt , until i'm inside the vm everythings is ok , when i switch to gui of the openxt it comes out again the same problem , so is not possible to do remote assistance in this case

**Comment by krayon007** [comment] 2020-04-07 16:17
So if I understand this correctly... You have the agent installed on the host OS, not the guest OS in your case? And you only see the cursor issue, when you are KVM'ed into the host, and you move the cursor over the guest OS area, and are wanting to click a UI element in the guest, but the pointer does not align with where the cursor appears to be in the bitmap?

**Comment by tradexsrl** [comment] 2020-04-07 16:30
no the agent is installed in the guest os because there is no possibility to install the agent in the host os because is a hardened linux
when the user have windows vm at full screen , when i'm connected in this situation everythings is ok but if i ask user to press CTRL+0 to switch to gui of the host os (i think is called dom0) when i move the mouse , the real host pointer is shifted to the upper left so is not possible to make remote assistance.
the same situation happend if i try to use meshcommander to rdp in kvm , since these pc have amt enabled....i was trying meshcommander to bypass the problem but it is still present.

**Comment by krayon007** [comment] 2020-04-07 17:37
ok, so you are saying the agent is in the guest OS... And when the user is controlling the host, everything is fine, when you control remotely... But if the user moves the mouse to try to locally control the guest, remote control of the guest is misaligned?

**Comment by krayon007** [comment] 2020-04-07 17:56
Does this issue happen when you connect KVM after the user already pressed CTRL+0, or does it only occur if the KVM is already connected, and the user presses CTRL+0?

**Comment by tradexsrl** [comment] 2020-04-07 18:57
when the user move the mouse inside windows vm is ok and also for me connected to their windows desktop via Meshcentral.
When they hit CTRL+0 to switch from VM to the gui of the host os , also my view switch to the gui of the host os , the user mouse is still ok , for me no more as explained before...to be honest i don't know how this could work because agent is inside the vm... i'm expecting that my view will be limited to the desktop of the windows vm but hey this is a huge plus :-)

**Comment by tradexsrl** [comment] 2020-04-07 19:07
if i kvm with meshcommander and on user pc there is full screen windows vm (at pc boot so user has done nothing) everythings is fine because i see the windows vm desktop and no problem with the mouse.
if i kvm and on the user pc there is at full screen host os with vm running in background , i have that problem.in this case the user have already pressed CTRL+0 because there is no way for the user to power up pc and get only host os running and vm shutdown.
with kvm i'm expecting to be able to see the host os gui because is an out of the band connection via the intel amt

**Comment by johnnyq** [comment] 2022-02-16 21:21
@FilGov This seems to have been resolved but I dont have the ability to close it can you please close this @FilGov

**Closed** 2022-02-16 21:46 UTC
Labels: bug
