### ISSUE TITLE
Special symbols not being forwarded correctly

### ISSUE THREAD

**Issue by GnaXi** [Ylianst/MeshCentral#630] opened 2019-11-02 22:15 UTC
Hi,

I think that this issue is keyboard language specific.
Let's say that I with a danish keyboard hold down right-alt and press 1234567890, it will look like this:
@£$€{[]}
alt+1 and alt+6 does not have any symbol attached to them on a danish keyboard
When I type these into the type field and forward it to the device, it shows up as:
1"¤6`´åÅ

A completely different set of symbols is pasted to the environment.

A screenshot demonstrating:
![image](https://user-images.githubusercontent.com/1616448/68077597-a8de3e80-fdc6-11e9-8cf9-f3d4f20d1f15.png)

**Comment by GnaXi** [comment] 2019-11-02 22:18
Interesting. When I change to US keyboard on the device that I'm connected to, the symbols are sent correctly:
![image](https://user-images.githubusercontent.com/1616448/68077627-230ec300-fdc7-11e9-8e64-6fa3491da16a.png)

**Comment by MailYouLater** [comment] 2019-11-03 04:24
This is a duplicate of #469, but includes information not preset there.

**Comment by GnaXi** [comment] 2019-11-03 12:28
I read through #469 and was not able to duplicate their issue.
If I hold down AltGr and press 1, 2, 3, 4 etc. I do get the correct symbols.
My issue only occurs when using the "Type" feature.

**Comment by Ylianst** [comment] 2019-11-03 22:25
This is a problem that @krayon007 needs to look it. We need to be able to send keys to the remote agent that will not be remapped by the remotely set language keyboard. I think this should be possible. Right now, it only works best if the remote keyboard is set to US-EN.

**Comment by GnaXi** [comment] 2019-11-23 11:38
I've made another discovery. Not sure if it's going to be helpful, but I'll mention it anyway!
If I instead of using the "Type" feature use the "Clipboard" feature and copy something to the remote machines clipboard and paste it directly on the remote system, it does show it correctly.
So a working workaround at least for me, until a fix is found for the "Type" feature and maybe others having the same issue! :)

**Comment by si458** [comment] 2024-11-27 12:00
you can try using the 'use remote keyboard map' under settings

**Closed by si458** 2024-11-27 12:00 UTC
Labels: bug
