### ISSUE TITLE
Working with LE certificates

### ISSUE THREAD

**Issue by D4V3M0NK** [Ylianst/MeshCentral#5296] opened 2023-08-18 20:24 UTC
**Describe your issue**
MC2 overwrites LE issued web-server-cert-[private|public].[key|crt] wildcard with "default"?

<details>
<summary>Server Software</summary>

 - OS: Ubunt 18.04 ESM
 - Network: MC2 sites behind SSL Proxy (nginx)
 - Version: 0.9.52
 - Node: 16.14.2

</details>

<details>
<summary>config.json</summary>

```
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "settings": {
    "cert": "mc2.my.domain.com",
    "WANonly": true,
    "trustedproxy": ["CIDR_A/24","CIDR_B/24"],
    "cookieIpCheck": false
  },
  "domains": {
    "": {
      "title": "mc2",
      "title2": "Remote Support Services",
      "welcomeText": "blah blah blah.",
      "passwordRequirements": {
              "force2factor": true,
              "min": 12,
              "upper": 1,
              "lower": 1,
              "numeric": 1,
              "nonalpha": 1,
              "oldPasswordBan": 24
      },
      "autocomplete": false,
      "certUrl": "https://local.ip.address:443"
    }
  }
}
```

</details>

Greetings everyone - it's been a while since I've needed to post to this forum, but I hope that you're all well and healthy. (Ylian / Brian, none more so than the two of you fine chaps...)

I've been using MC2 for years. I also appreciate that I don't have the latest version, but I don't believe that I need to at this point in time. I also have extensive notes made on using public certificates in the past and this has always proven to be accurate, but for some reason, it doesn't appear to be working now. So, here goes:

My MC2 server doesn't have access to the internet. It can accept incoming connections of course and has been working perfectly for some years supporting a number of remote clients. Historically, we have used GoDaddy certificates on our (nginx) Proxy servers and, according to my notes, the GoDaddy full chain certificate and key needed to be copied to the MC2 server, and named them as `webserver-cert-public.crt` and `webserver-cert-private.key` respectfully.

The GoDaddy certs don't have wildcards, but `mc2.my.domain.com` along with localhost etc.

We've now transitioned over to using Lets Encrypt. The generation of those LE certs (which **are** wildcards) are handled on a separate system (that does have access to the internet, DNS etc) and so what I have done today, is to take LE fullchain.pem and private.key files from LE and copied them to my MC2 server, in a backup folder. When I inspect those files in the backup folder using (for example) `openssl x509 -in le-full.crt -noout -dates -ext subjectAltName` I get all the information, all the wildcards that I was expecting, including the expiration date of mid October.

I stop MC2. I rename copy the LE files from the backup folder to `webserver-cert-public.crt` and `webserver-cert-private.key` in the `meshcentral-data` folder and then start up MC2 again. The web UI comes up and upon inspection, I see the LE certificate is the one it's using and has the mid October expiration date.

However, none of my remote agents are able to connect. 

I check the certificates in the `meshcentral-data` folder, expecting to see the LE information (I had just copied and renamed them there), but I'm now seeing a certificate issued by MeshCentralRoot, with an expiration date of Dec 31st, 2049. It has the specific hostname of my server and none of the wildcards.

Obviously I'm a little baffled by this ... can anyone shed any light on what's going on and furthermore, how to get past this??

**Comment by si458** [comment] 2023-08-19 07:07
You are running an old version to begin with.
Have u simply tried updating the software to the latest version?

**Comment by Ylianst** [comment] 2023-08-19 18:39
Hi. I will send you a private email to fix this. In general, if you config "cert" is set to "mc2.my.domain.com", then if you have a cert that is "mc2.my.domain.com" or "*.my.domain.com", MeshCentral should keep it. However, if the certificate wildcard does not include the domain set in "cert" MeshCentral will generate a new self-signed cert.

So, you can check that. If you are ok with it, you can send me the public only portion of your cert and the name in the config.json and I will try it out.

In detail, the function [compareCertificateNames()](https://github.com/Ylianst/MeshCentral/blob/3e57d2dfa4da0b3212fb9bc2676d855ddfb5943f/certoperations.js#L744) should match your LE cert with your DNA name and find that it does match, but it's probably saying it does not match.

**Comment by Ylianst** [comment] 2023-08-21 00:27
Ok. it turned out the problem is that the certificate being loaded into MeshCentral is not a RSA cert, but a ECDSA cert. MeshCentral does not support ECDSA cert expect if loaded in the reverse proxy in front of the server.

I researched this a bit and with NodeJS v16 and higher, I should be able to support ECDSA. At some point, I may be have MeshCentral only support NodeJS v16+ and get rid of the node-forge dependency which is getting old.

Ylian

**Comment by si458** [comment] 2024-07-21 16:55
closing in favour of #6266

**Closed by si458** 2024-07-21 16:55 UTC
Labels: question
