### ISSUE TITLE
uncaughtException1: Error: tls.socket.OnError():  => TypeError: [object Object] not callable

### ISSUE THREAD

**Issue by tahanjokunimi** [Ylianst/MeshCentral#113] opened 2019-02-27 13:26 UTC
After updating to the 0.2.9-h version          (similar problem was with older also, but was working on some version  in the middle. )

- UI is working fine,  and I am able to connec to the devices,   but some devices fail,   
              like if  also installing the agent to the  device, with is running the MeshCenral.service
- All devices are Ubuntu 16.04.   servers,   with  Mate  desktop.

- When trying to take  remote, or fileshare, or terminal,   getting this  error to the Console:
  uncaughtException1: Error: tls.socket.OnError():  => TypeError: [object Object] not callable

 If I remove the device  agent and  try to add it again got this to the linux root terminal;
    Failed to execute operation: Too many levels of symbolic links
    Warning: meshagent.service changed on disk. Run 'systemctl daemon-reload' to reload units.
    Mesh agent started.

Have been trying to  restart the  daemons; 
   sudo systemctl stop meshagent
   sudo systemctl stop meshcentral.service
   sudo systemctl daemon-reload
   sudo systemctl start meshagent
   sudo systemctl start meshcentral.service
   sudo systemctl status meshcentral.service
   sudo systemctl status meshagent
Looking good,  if checking  status.   And Webserver is running fine.

Device  is   showing up at the UI,  My Devices,  and it says  "Agent, Powered",
     but when trying to remote,    al ways get this  error;    
          uncaughtException1: Error: tls.socket.OnError():  => TypeError: [object Object] not callable

      and at remote page,    is the  message,     " Setup... "

So some devices  are  good to go,  working nicely.  Can remote and see files and terminal.
But  just  some  devices,  al ways  got this  error.  and can not remote.

**Comment by Ylianst** [comment] 2019-02-27 18:47
Thanks for reporting this. Can you send a screen shot of the error? I want to know where you see the error message. - Thanks.

**Comment by tahanjokunimi** [comment] 2019-02-28 08:23
![screenshot at 2019-02-28 10-21-22](https://user-images.githubusercontent.com/28250130/53551836-d8a3bb00-3b42-11e9-9168-0b4ec6be47b7.png)

**Comment by tahanjokunimi** [comment] 2019-02-28 08:31
I don't  know,   if   update  process  from the web ui,    is the  cause of this?
Because if I  run the  update from here,
   - after update,  UI hangs,  so I need to  SSH  to the server, and manually give commands;
         sudo systemctl stop meshcentral.service   and  sudo systemctl stop meshcentral.service
   - after that,   web server  starts again,  and I am able to see, that the release number has changed to the latest version.
![screenshot at 2019-02-28 10-27-02](https://user-images.githubusercontent.com/28250130/53552451-05a49d80-3b44-11e9-9ff7-055135ce641f.png)

**Comment by tahanjokunimi** [comment] 2019-02-28 08:37
But  other   devices,       in the  Mesh,   is  okay,    and I am able  to  remote, and see files and use terminal;                        (on working agents/devices,   nothing is been written to the Console, when it works.)

![screenshot at 2019-02-28 10-35-21](https://user-images.githubusercontent.com/28250130/53552775-ce82bc00-3b44-11e9-82bb-73e2c092710a.png)

**Comment by tahanjokunimi** [comment] 2019-02-28 08:43
Here,   seen  better,        so  This HP server  is running the service,
      - previously,  I was able to   connect also  there. (before updating the latest version.)
              just says   "Setup..."
      - but now,     I can only  connect  to the  ThinkPad  laptop.

![screenshot at 2019-02-28 10-41-31](https://user-images.githubusercontent.com/28250130/53553174-af385e80-3b45-11e9-8d50-045f00f55140.png)

**Comment by krayon007** [comment] 2019-02-28 08:48
By any chance do the effected clients use a proxy to access the internet? (Regardless of where the mesh server is).

If so, the client could be trying to use a proxy for the remote tunnels... I'll try to investigate when I get back in the office.

**Comment by tahanjokunimi** [comment] 2019-02-28 08:55
It is just a Closed LAN,    using inside  the office.      (Server is another room,  laptops another..)
                                        All the machines  are under same network switch.
                                        Or some use cases, few switches are connected as bigger LAN.
    Not yet accessing from Internet.       Just  testing  in local network,  from several PC:s in the network.

**Comment by krayon007** [comment] 2019-02-28 09:01
So none of the machines have a proxy setting configured in the OS or environment variables?

**Comment by krayon007** [comment] 2019-02-28 09:02
Are all the failed clients running the same OS and version?

**Comment by tahanjokunimi** [comment] 2019-02-28 09:22
yes,  no proxy  settings used.         tested both,   Ubuntu 16.04   and 18.04    server,  running service.
       tried  several times  to  uninstall the  agent,   and  install again.  but still no success to connect to the  
      server client agent. (even tought it is saying,  "Agent, Powered")
      just says  Setup...     and console error;  uncaughtException1: Error: tls.socket.OnError():  => TypeError: [object Object] not callable

**Comment by Ylianst** [comment] 2019-02-28 09:30
The fact the the URL to the server includes an IPv6 address may be of interest. I don't think I did much testing with this situation.

**Comment by krayon007** [comment] 2019-02-28 09:30
Interesting. I'll investigate tomorrow. Those are the same versions of Ubuntu I use...

**Comment by Ylianst** [comment] 2019-03-01 04:08
I tested it myself and I can confirm that IPv6 on Linux is causing this. Works on Windows.

**Comment by tahanjokunimi** [comment] 2019-03-01 08:46
Yes,      confirmed.             
             If I   send  command;   " cat /proc/sys/net/ipv6/conf/all/disable_ipv6  "
             and  restart the service,
                  systemctl stop meshcentral.service
                  systemctl start meshcentral.service

  After  that   I am able to take remote connection also to the  "Master server", 
                          which is running the  meshcentral.service.       Good!   Thanx.

**Comment by tahanjokunimi** [comment] 2019-03-01 09:01
But,             then after  that,         I updated  the  latest  version..    0.2.9-k   via the web UI,
                    now again same problem;
             uncaughtException1: Error: tls.socket.OnError():  => TypeError: [object Object] not callable
                  eventought   the ipv6 should be disabled.

**Comment by Ylianst** [comment] 2019-03-02 02:11
Published MeshCentral v0.2.9-o with Bryan's (krayon007) fix for IPv6 on Linux. Can you give it a try and confirm it works? - Thanks.

**Comment by tahanjokunimi** [comment] 2019-03-02 16:10
Updated,      now got this new problem,  that can not add any linux agents to the mesh.
                        - tried to uninstall the who thing (cleared the databases),    
                            and reinstalled   "npm install meshcentral", but same problem.

**Comment by Ylianst** [comment] 2019-03-02 19:10
Oh dear! Can you run the mesh agent manually. First stop the service "systemctl stop meshagent" than "cd /usr/local/mesh" and run "suco meshagent". Then post a screenshot of the result. Thanks.

**Comment by Ylianst** [comment] 2019-03-03 01:43
I found the problem, it's my fault and it's dumb. The .msh file has a missing carriage return at the end of the line "MeshServer=local" and before "ignoreProxyFile=1". So, the agent is trying to connect to "MeshServer=localignoreProxyFile=1". Just add a carriage return at the right place and the agent will work fine. I will go fix this and publish a new version ASAP.

**Comment by Ylianst** [comment] 2019-03-03 02:03
Just published MeshCentral v0.2.9-p with a fix for this. It affected all agents (Windows & Linux) when the server did not have a fixed name or IP address.

**Comment by Ylianst** [comment] 2019-03-05 17:23
Confirmation that this bug is fixed would be appreciated. The next MeshCentral publication will have a fix for server discovery when the server has multiple network interfaces.

**Comment by tahanjokunimi** [comment] 2019-03-09 09:38
Yes,   0.2.9-z   version,     just  installed again, with  command  npm install meshcentral,
       Works great!     Thank you very much, for fixing this!

**Comment by Ylianst** [comment] 2019-03-09 22:34
Nice! Going to close this issue since I am pretty sure it's fixed.

**Closed by Ylianst** 2019-03-09 22:34 UTC
