### ISSUE TITLE
Black screen on remote desktop on Mac OS X 10.13.6

### ISSUE THREAD

**Issue by rroseselavy42** [Ylianst/MeshCentral#228] opened 2019-05-08 18:23 UTC
Hey there,

I have the Mac OS X agent running on a Mac (10.13.6) and when trying to enter terminal or remote desktop mode it will say "connected" but only give a black screen. 

I can collect more data for this if you want.

The console agent gives me this output 
```
UncaughtException1: Error: timers.onElapsed() callback handler on 'sendNetworkUpdate()'  => TypeError: cannot write property 'action' of null
Spawning User Process for KVM
```

**Comment by rroseselavy42** [comment] 2019-05-08 19:29
update: It looks like if we move the device to another group, it begins to connect properly.

**Comment by Ylianst** [comment] 2019-05-08 23:02
You are right! I just saw the same problem with a Raspberry Pi. I get a blank screen unless I switch the device to a different group. Investigating this now.

**Comment by Ylianst** [comment] 2019-05-08 23:20
Just Published MeshCentral v0.3.3-x with a fix for this. I got lucky and found that cause. If a device group has user notification turned on and a remote desktop/terminal session is started to a agent that does not yet support user notifications, the session would fail and go black.

I fixed it so that session continues, but we will need to add user notification on the MacOS and Linux agents.

**Comment by Ylianst** [comment] 2019-05-09 20:55
Ok, I will close this one as I am pretty sure the issue is solved. Please re-open if needed.

**Closed by Ylianst** 2019-05-09 20:55 UTC
Labels: bug

**Comment by rogalskij13** [comment] 2020-05-06 17:40
I seem to be getting this even on groups that have no notification.  Is there something else that might be causing this problem?  My issue is the exact same as mentioned above.
