### ISSUE TITLE
Lock machine after disconnect

### ISSUE THREAD

**Issue by alesribic73** [Ylianst/MeshCentral#663] opened 2019-11-18 23:13 UTC
Hi
Im looking for a feature to automaticaly lock machine after i disconnect desktop session.

Thanks

**Comment by MailYouLater** [comment] 2019-11-19 01:28
Duplicate of #270 & #649.

**Comment by Ylianst** [comment] 2019-11-19 01:41
Seems like a frequently asked feature. I think other commercial solutions have this.

**Comment by alesribic73** [comment] 2019-11-19 05:47
Not implemented yet? Plans?

**Comment by MailYouLater** [comment] 2019-11-19 20:11
As [stated](https://github.com/Ylianst/MeshCentral/issues/649#issuecomment-553620783) by ryanblenis in #649, a hook to allow plugins to perform an action when disconnecting from a KVM session is in his fork, and assuming Ylianst accepts his next pull request when he makes it, MeshCentral will support the ability to make a small plugin that adds this ability, or a more complex one that could do more (like asking if you want to lock the computer and/or log a custom event when you disconnect).

**Comment by alesribic73** [comment] 2019-11-19 20:17
Thanks for clearing this out.

**Comment by alesribic73** [comment] 2019-11-19 20:18
CLosing

**Closed** 2019-11-19 20:17 UTC
