### ISSUE TITLE
Dual monitors - Dual Tabs

### ISSUE THREAD

**Issue by coolwormgit** [Ylianst/MeshCentral#1068] opened 2020-03-25 18:19 UTC
hello,
when i connect to a client with dual monitor , i open in one tab -Monitor 1- i reconnect with second tab and select -Monitor 2- then the screen going crazy in both tabs.... 

thanks

**Comment by Ylianst** [comment] 2020-03-25 20:25
Can you open the browser console and see if anything show up? (CTRL-SHIFT-i on Chrome). If there is anything, can you post a screen shot? Thanks.

**Comment by Ylianst** [comment] 2020-03-25 23:09
Confirmed. I see this exact problem. I will fix this.

**Comment by Ylianst** [comment] 2020-03-25 23:20
Thanks for the report. Checked in the fix for this, will be in MeshCentral v0.5.0-u when I next published it.

**Comment by Ylianst** [comment] 2020-03-26 03:48
Published MeshCentral v0.5.0-u with the fix. Let me know if it works.

**Comment by asasin114** [comment] 2020-03-26 05:59
Display switching seems to be working for me on 0.5.0-u. It wasn't working properly back on 0.5.0-s earlier this afternoon.

**Comment by coolwormgit** [comment] 2020-03-26 07:13
its not fixed, now when i change the first tab just change and second what the first got, tested chrome and firefox

**Comment by krayon007** [comment] 2020-03-26 07:34
That's currently the intended behavior, because the kvm session is actually a singleton, all the tabs are connected to the same session.

**Comment by Ylianst** [comment] 2020-03-26 07:49
Yes, the agent can only capture one screen, so you can't have two different tabs showing two different screens. However, I did fix it so it does not flip between the two screens.

**Comment by asasin114** [comment] 2020-03-26 07:49
Dear Ylianst/MeshCentral,

Your support ticket "Re: [Ylianst/MeshCentral] Dual monitors - Dual Tabs (#1068)" has been submitted.

We reply to all tickets as soon as possible, within 24 to 48 hours. If we expect your ticket will take additional time, we will update you by sending you an email.

Ticket tracking ID: JA2-SN8-EJ18

You can view the status of your ticket here:
https://support.yxetech.ca/ticket.php?track=JA2-SN8-EJ18&e=reply%2BAADFZ3U3D3OSRDMAPRNFFS54RA3SJEVBNHHCGCUWNE%40reply.github.com&Refresh=57510

You will receive an email notification when our staff replies to your ticket.


Sincerely,

YXE Tech Help Desk
https://support.yxetech.ca

**Comment by asasin114** [comment] 2020-03-26 07:49
Dear Ylianst/MeshCentral,

Your support ticket "Re: [Ylianst/MeshCentral] Dual monitors - Dual Tabs (#1068)" has been submitted.

We reply to all tickets as soon as possible, within 24 to 48 hours. If we expect your ticket will take additional time, we will update you by sending you an email.

Ticket tracking ID: BD3-D1Y-ATPJ

You can view the status of your ticket here:
https://support.yxetech.ca/ticket.php?track=BD3-D1Y-ATPJ&e=reply%2BAADFZ3RAQHCNGBHTNYX4GJN4RA6CXEVBNHHCGCUWNE%40reply.github.com&Refresh=54967

You will receive an email notification when our staff replies to your ticket.


Sincerely,

YXE Tech Help Desk
https://support.yxetech.ca

**Comment by tradexsrl** [comment] 2020-03-26 08:02
one question: you bug fixed the agent also?
if i upgrade the server from 0.5.0-s to 0.5.0-u and agent are upgraded also , what happend to the agent already installed on the client?

**Comment by krayon007** [comment] 2020-03-26 08:06
The bug fix was server side. The agent was not updated.

**Comment by krayon007** [comment] 2020-03-26 08:07
But to answer your question, if a server update includes an agent update, all the connected agents will automatically update to the version of the agent included in the server update.

**Comment by coolwormgit** [comment] 2020-03-26 09:13
so its not possible to have two tabs??

**Closed** 2020-03-26 12:19 UTC
Labels: Fixed - Confirm & Close, bug

**Comment by Ylianst** [comment] 2020-03-26 19:29
Note that agents automatically get updated if needed when the server gets updated. This takes a few minutes to hours depending on how many devices you have. You never have to update agents manually.

It's not possible to get two tabs showing two different screens of the same computer right now. i don't imagine we would do this in the future, it would be a lot of work and fundamental changes.

**Comment by andreapx** [comment] 2022-10-07 08:20
> Note that agents automatically get updated if needed when the server gets updated. This takes a few minutes to hours depending on how many devices you have. You never have to update agents manually.
> 
> It's not possible to get two tabs showing two different screens of the same computer right now. i don't imagine we would do this in the future, it would be a lot of work and fundamental changes.

Hi @Ylianst do you still think that you'll never implement the possibility to view 2 screens on different tabs or....?
