### ISSUE TITLE
Shared link management

### ISSUE THREAD

**Issue by laboiteajb** [Ylianst/MeshCentral#1932] opened 2020-10-30 14:36 UTC
Hello,

Is there a place to manage shared sessions?

This could allow me to cut a link with too great a time.
I also test the rights, I can not prohibit the session sharing only.

thank you

**Comment by Ylianst** [comment] 2020-10-30 18:05
This is probably a duplicate of #1891.

**Closed** 2020-11-02 20:24 UTC
Labels: duplicate
