### ISSUE TITLE
Question: Possible to Set Local Port With Custom MeshCentral Router Links?

### ISSUE THREAD

**Issue by MatinatorX** [Ylianst/MeshCentral#2617] opened 2021-05-11 00:00 UTC
Checked the advanced-config.json example, but didn't see a way to set the local port, only the remote port:

```        "extralinks": [
          {
            "name": "HTTP",
            "protocol": "http",
            "port": 80,
            "_ip": "192.168.1.100",
            "_filter": [ "mesh//xxxx", "node//xxxx" ]
          },
```
Is it possible to set the local port too, for the admittedly small number of times it's needed?

**Comment by Ylianst** [comment] 2021-05-11 14:41
Well, I guess I could add that... but since you only have one local port, you can't make that route work multiple times. I would also have to deal with the local port already being in use, etc. Are you sure this is really needed?

**Comment by Ylianst** [comment] 2021-05-11 18:11
To answer @baikal question. Right now, MeshCentral Router will launch the SSH/Putty/RDP/WinSCP client and pass in the random local port along with "127.0.0.1" using command line arguments. So, you just click on a device, select "Putty" and it works. Having a fixed local port is useful when MeshCentral Router is not launch the application.

@MatinatorX. Ok, I will work on adding local port. May need an update to MeshCentral Router to do it.

**Comment by Ylianst** [comment] 2021-05-12 18:32
Working on this now.

**Comment by Ylianst** [comment] 2021-05-12 19:20
I just added localport support. It will be in upcoming MeshCentral v0.8.37. You will need to update MeshCentral Router. I kept the version number of MeshCentral Router that same, but you need to get the new one that will come with MeshCentral v0.8.37 for this to work. In the config, there is a new optional "localport".

```
      "deviceMeshRouterLinks": {
        "rdp": true,
        "ssh": true,
        "scp": true,
        "extralinks": [
          {
            "name": "xxHTTPS",
            "protocol": "https",
            "port": 443,
            "localPort": 12345                 <---------
          }
        ]
      }
```

Once published, let me know if it works.

**Comment by MatinatorX** [comment] 2021-05-16 06:47
Just tested this with MeshCentral 0.8.38 and the version of MeshCentral Router it includes (1.7.7802). Does not seem to work, clicking the MCRouter link from the webpage still assigning a random local port when MeshCentral Router opens. Here is my config excerpt:
```
      "deviceMeshRouterLinks": {
        "rdp": true,
        "ssh": true,
        "scp": false,
        "extralinks": [
          {
            "name": "TAP",
            "port": 47800,
            "localPort": 47800,
            "filter": [ "node//[removed]",
                        "node//[removed]",
                        "node//[removed]",
                        "node//[removed]",
                        "node//[removed]",
                        "node//[removed]",
                        "node//[removed]" ]
          },```

**Comment by MatinatorX** [comment] 2021-05-29 15:07
Just checked again with the latest version of MeshCentral (0.8.49) and MeshCentral Router (1.7.7811), unfortunately still does not work, still just assigns a random local port to the map.

**Comment by Ylianst** [comment] 2021-06-04 22:03
Ok, checking this now.

**Comment by Ylianst** [comment] 2021-06-04 22:14
I just tested it and it worked for me. Are you sure you updated MeshCentral Router to the latest version?

![image](https://user-images.githubusercontent.com/1319013/120867682-48d1f000-c547-11eb-84c3-a9f3f770f6c5.png)

This is my current config. So far, every time I put "localport" it works. The older MeshCentral Router will ignore the local port, you need the new one. You can need to click on the web list link. Make sure that when you click on the link, the correct MeshCentral Router executable is invoked.

```
      "deviceMeshRouterLinks": {
        "rdp": true,
        "ssh": true,
        "scp": true,
        "extralinks": [
          {
            "name": "TAP",
            "port": 443,
            "localPort": 47800
          },
          {
            "name": "xxHTTPS",
            "protocol": "https",
            "port": 443,
            "localPort": 12345,
            "ip": "192.168.2.147",
            "__filter": [ "tag:abc" ],
            "_filter": [ "mesh//7b4b43cdad850135f36ab31124b52e47c167fba055ce800267a4dc89fe0e581c", "node//Uqr1kHG7hV22kjOGQULZaoCde93GcAIk6fnwsYZyXAx8hjJlwbubn@$M$FxLPxPh" ]
          },
          {
            "name": "HTTPS",
            "protocol": "https",
            "_ip": "192.168.2.147",
            "localPort": 12346,
            "port": 443
          },
          {
            "name": "MCRDesk",
            "protocol": "mcrdesktop"
          },
          {
            "name": "MCRFiles",
            "protocol": "mcrfiles"
          }
        ]
      },
```

**Comment by MatinatorX** [comment] 2021-06-04 23:55
Just updated from MeshCentral v0.8.49 to v0.8.56 and with it MeshCentral Router v1.7.7811 to v1.7.7823, but still had no success. I then backed up my "deviceMeshRouterLinks" section and replaced it exactly with your example above, then restarted MeshCentral. I can see the changed links, but still not taking the custom local port.

I also completely removed the router executable from my PC and deleted the HKCU\SOFTWARE\Open Source\MeshCentral Router folder in registry. I then downloaded the latest router again, opened it, and verified no stored server or username. Tried the link again, still does not work. Confirmed port 47800 is not in use on the local machine. Then I tried the above steps again on 2 different computers with no luck.

I really have no idea what I'm doing wrong. Here is my entire config.json with identifying information removed:

```
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "settings": {
    "Cert": "subdomain.website.com",
    "_ignoreagenthashcheck": true,
    "AgentInviteCodes": true,
    "MongoDb": "mongodb://127.0.0.1:27017/meshcentral",
    "_WANonly": true,
    "desktopMultiplex": true,
    "WsCompression": true,
    "AgentWsCompression": true,
    "Log": "/home/user/meshlogs/log.log",
    "SysLog": "/home/user/meshlogs/syslog.log",
    "AuthLog": "/home/user/meshlogs/auth.log",
    "MeshErrorLogPath": "/home/user/meshlogs",
    "Minify": true,
    "webRTC": true,
    "nice404": true,
    "clickOnce": false,
    "publicPushNotifications": true,
    "allowHighQualityDesktop": true,
    "plugins": { "enabled": true },
    "_ManageCrossDomain": [ "user@domain.com" ],
    "_ManageAllDeviceGroups": [ "user@domain.com" ],
    "Compression": true,
    "maxInvalidLogin": {
      "time": 10,
      "count": 5,
      "coolofftime": 30
    },
    "_AutoBackup": {
      "backupIntervalHours": 24,
      "keepLastDaysBackup": 10,
      "zipPassword": "password",
      "backupPath": "/home/user/meshbackups"
    }
  },
  "domains": {
    "": {
      "SiteStyle": 2,
      "LoginPicture": "images/domain/login.png",
      "WelcomePicture": "images/domain/welcome.png",
      "TitlePicture": "images/domain/logo.png",
      "Title": "Domain Remote Access Portal",
      "Title2": "",
      "UserSessionIdleTimeout": 15,
      "novnc": false,
      "desktopPrivacyBarText": "Domain Remote Access: {0}",
      "WebEmailsPath": "/home/user/meshcentral-data/emailtemplates/domain/",
      "notificationMessages": {
        "Title": "Domain Remote Access",
        "Desktop": "{0} is requesting a remote desktop session. Allow?",
        "Terminal": "{0} is requesting a remote terminal session. Allow?",
        "Files": "{0} is requesting a remote filesharing session. Allow?"
      },
      "consentMessages": {
        "Title": "Domain Remote Access",
        "Desktop": "{0} has started a remote desktop session.",
        "Terminal": "{0} has started a remote terminal session.",
        "Files": "{0} has started a remote filesharing session."
      },
      "deviceMeshRouterLinks": {
        "rdp": true,
        "ssh": true,
        "scp": true,
        "extralinks": [
          {
            "name": "TAP",
            "port": 443,
            "localPort": 47800
          },
          {
            "name": "xxHTTPS",
            "protocol": "https",
            "port": 443,
            "localPort": 12345,
            "ip": "192.168.2.147",
            "__filter": [ "tag:abc" ],
            "_filter": [ "mesh//meshID", "node//nodeID" ]
          },
          {
            "name": "HTTPS",
            "protocol": "https",
            "_ip": "192.168.2.147",
            "localPort": 12346,
            "port": 443
          },
          {
            "name": "MCRDesk",
            "protocol": "mcrdesktop"
          },
          {
            "name": "MCRFiles",
            "protocol": "mcrfiles"
          }
        ]
      },
      "agentCustomization": {
        "displayName": "Domain Remote Agent",
        "description": "Allows remote assistance and service by Domain staff.",
        "companyName": "Domain Remote Access Utilities",
        "serviceName": "domainagent",
        "fileName": "domainagent"
      },
      "maxGuestSessionSharingTime": 5760,
      "NewAccounts": true,
      "newAccountsUserGroups": [ "ugrp//ugrpID" ],
      "UserNameIsEmail": true,
      "geoLocation": true,
      "meshMessengerTitle": "Domain Messenger",
      "NewAccountEmailDomains": [ "domain.com" ],
      "WelcomeText": "<p style='font-size:36px; color:#EEEEFFCC;'>Welcome to the Domain remote access portal.</p><p style='font-size:18px; color:#EEEEFFAA;'>Log in or create an account using your Domain email address to get started.</p>",
      "Footer": "<style>#footer { overflow: hidden; }</style><a href='https://subdomain.domain.com/userfiles/user@domain.com/Remote_Access_Utilities.exe?download=1'><img src='images/download.png' onmouseover='this.src=&quot;images/download_hover.png&quot;' onmouseout='this.src=&quot;images/download.png&quot;' alt='Download Remote Access Utilities'></a>",
      "passwordRequirements": {
        "min": 10,
        "max": 128,
        "upper": 1,
        "lower": 1,
        "numeric": 1,
        "nonalpha": 0,
        "force2factor": true,
        "banCommonPasswords": true
      },
      "SessionRecording": {
        "onlySelectedDeviceGroups": true,
        "filepath": "/home/user/meshsessions/domain/",
        "index": true,
        "protocols": [ 1, 2, 5, 100, 101 ]
      },
      "amtAcmActivation": {
        "log": "/home/user/meshlogs/amt.log",
        "_certs": {
         "_certfiles": "/home/user/meshcentral-data/mpsserver-cert-public.crt",
         "_keyfile": "/home/user/meshcentral-data/mpsserver-cert-private.key"
        }
      }
    },
    "domain2": {
      "dns": "subdomain2.domain.com",
      "GuestDeviceSharing" : false,
      "SiteStyle": 2,
      "LoginPicture": "images/domain2/login.png",
      "WelcomePicture": "images/domain2/welcome.png",
      "TitlePicture": "images/domain2/logo.png",
      "Title": Domain2 Remote Access Portal",
      "Title2": "",
      "UserSessionIdleTimeout": 15,
      "novnc": false,
      "desktopPrivacyBarText": "Domain2 Remote Access: {0}",
      "WebEmailsPath": "/home/user/meshcentral-data/emailtemplates/domain2/",
      "userConsentFlags": {
        "desktopnotify": true,
        "terminalnotify": true,
        "filenotify": true,
        "desktopprompt": false,
        "terminalprompt": false,
        "fileprompt": false,
        "desktopprivacybar": true
      },
      "notificationMessages": {
        "Title": "Domain2 Remote Access",
        "Desktop": "{0} is requesting a remote desktop session. Allow?",
        "Terminal": "{0} is requesting a remote terminal session. Allow?",
        "Files": "{0} is requesting a remote filesharing session. Allow?"
      },
      "consentMessages": {
        "Title": "Domain2 Remote Access",
        "Desktop": "{0} has started a remote desktop session.",
        "Terminal": "{0} has started a remote terminal session.",
        "Files": "{0} has started a remote filesharing session."
      },
      "deviceMeshRouterLinks": {
        "rdp": true,
        "ssh": false,
        "scp": false,
        "_extralinks": [
          {
            "name": "HTTP",
            "protocol": "http",
            "port": 80
          },
          {
            "name": "HTTPS",
            "protocol": "https",
            "port": 443
          }
        ]
      },
      "agentCustomization": {
        "displayName": "Domain2 Remote Agent",
        "description": "Allows remote access by Domain2 staff.",
        "companyName": "Domain2 Remote Access Utilities",
        "serviceName": "domain2agent",
        "fileName": "domain2agent"
      },
      "maxGuestSessionSharingTime": 5760,
      "NewAccounts": false,
      "UserNameIsEmail": true,
      "geoLocation": true,
      "meshMessengerTitle": "Domain2 Messenger",
      "WelcomeText": "<p style='font-size:36px; color:#EEEEFFCC;'>Log in to your account to access sites remotely.</p><p style='font-size:18px; color:#EEEEFFAA;'>To request an account, please ask your project manager or contact Staff.</p>",
      "Footer": "<a href='https://domain2.com/'>Domain2 Homepage</a>",
      "passwordRequirements": {
        "min": 10,
        "max": 128,
        "upper": 1,
        "lower": 1,
        "numeric": 1,
        "nonalpha": 0,
        "force2factor": true,
        "banCommonPasswords": true
      },
      "SessionRecording": {
        "filepath": "/home/user/meshsessions/domain2/",
        "index": true,
        "protocols": [ 1, 2, 5, 100, 101 ]
      }
    }
  },
  "letsencrypt": {
    "email": "user@domain.com",
    "names": "subdomain.domain.com,subdomain2.domain.com",
    "production": true
  },
  "smtp": {
    "host": "smtp.domiain.com",
    "port": 123,
    "from": "user@domain.com",
    "user": "user@domain.com",
    "pass": "password",
    "tls": false
  },
  "sms": {
    "provider": "twilio",
    "sid": "sid",
    "auth": "auth",
    "from": "+1-111-111-1111"
  }
}
```

**Comment by Ylianst** [comment] 2021-06-05 18:14
If your server is public facing, could you create a dummy account and send me a user/pass? [My contact info is here](https://www.meshcommander.com/contact-information). No need for any server rights. If you want to be good with security, use my PGP key to encrypt your server URL and dummy user/pass. I will put a device the account and give it a try. I should be able to find out if the problem is server-side or router-side.

**Comment by baikal** [comment] 2021-06-06 21:12
I can confirm that I tested it shortly after @Ylianst added that feature (so probably on v0.8.37 or v0.8.38) and it worked well.
According to on of my users, it worked all the time since then ... I do frequently update MeshCentral (v0.8.55 now), but the MCRouter binary almost certainly did not get updated on that users machine since then.

**Comment by MatinatorX** [comment] 2021-06-06 23:42
@Ylianst I've emailed you the link and login information, thank you for the help. I poked at the site in developer mode in Chrome, and the TAP link shows up like this (nodeID removed):
`<a href="#" onclick="p10MCRouter(&quot;node//nodeID&quot;,0,443)">TAP</a>`

I am still using your exact "deviceMeshRouterLinks" example config. Seems to me the local port number is not a part of the link on my server for some reason. Currently I'm one revision behind at MeshCentral v0.8.56. I'm not sure what other information might help, but I'm running Node v14.16.1, NPM v7.11.2, Ubuntu 18.04.5 LTS and MongoDB v4.4.5.

**Comment by MatinatorX** [comment] 2021-06-07 19:43
I think I figured it out. The local port feature _does_ work, but **only** on the device general page. From the main page list view, it does not work, which is where all our tests were performed from. I can confirm this looking at the source in Chrome.

Main page "Links" column:
<a href="#" onclick="p10MCRouter(&quot;node//nodeID&quot;,0,443)">TAP</a>

Device General page:
<a href="#" onclick="p10MCRouter(&quot;node//nodeID&quot;,0,443,null,47800)" title="Requires installation of MeshCentral Router.">TAP</a>

@Ylianst Can you confirm if the above is the case for you?

**Comment by MatinatorX** [comment] 2021-07-01 21:27
Just checked and the issue still exists in 0.8.69.

**Comment by MatinatorX** [comment] 2022-02-16 00:04
Issue still exists in 0.9.81. Specifying the local port works from the device General page, but not from the router links column on the My Devices main page. I had a peek at the links using the chrome console and the local port argument is definitely not present, so I'm thinking (hoping) it's a simple fix.
![Untitled-1](https://user-images.githubusercontent.com/42086791/154170530-8b34ede7-4696-48df-8217-5ff3706a7fca.png)
.

**Closed** 2022-02-16 00:11 UTC
Labels: enhancement

**Comment by ocsnetworks** [comment] 2024-04-15 19:12
I seem to be having an issue myself with the local port.
I have the most current version of Mesh Central as well as meshrouter.
When I click the link in mesh central, it still randomizes the port.
Port 80 is not in use..... I can connect via meshrouter manually.

{
            "name": "RemoteCam",
            "protocol": "http",
            "port": 80,
            "localPort": 80,
            "ip": "10.0.0.100",
            "_filter": [ "mesh/(domainid)/(meshid)", "node/(domainid)/(nodeid)" ]
          }

**Comment by MatinatorX** [comment] 2024-04-15 20:14
Specifying the local port is still working well for me. From my experience, even if the local port you specify is already in use, it will still try to map it. You'll end up an entry in the Mappings tab like normal, just with a "cannot bind to local port" message underneath it.

Your config entry also looks good. The only thing I notice is you're trying to make a relay map - specifying both a local port and remote IP. There's no reason that shouldn't work, but I haven't specifically tested specifying a local port with a relay map, so perhaps there's an issue there. It'd be interesting to see if it maps correctly without the IP specified (I know this wouldn't help with your current issue but at least the exact problem scenario could be narrowed down).

The only other suggestion I'd have is to make sure you're restarting meshcentral after saving any config.json changes, but I'm sure you're already doing that.

**Comment by ocsnetworks** [comment] 2024-04-15 21:33
I just noticed somewhere maybe in the registry or browser that something is cached..... I am checking this out.
I installed on another workstation and directs to local port 80 with no issues.
