### ISSUE TITLE
MeshAgent is taking lots of memory/ram Consumption.

### ISSUE THREAD

**Issue by Shivangraj** [Ylianst/MeshCentral#5983] opened 2024-04-02 11:57 UTC
**Describe the bug**
MeshAgent is taking lots of memory/ram Consumption.

**Screenshots**
![meshagent](https://github.com/Ylianst/MeshCentral/assets/38600280/38ee3420-c032-4189-aaaa-0017300e99a0)

**Server Software (please complete the following information):**
 - OS: [Ubuntu]
 - Virtualization: [Docker]

**Client Device (please complete the following information):**
 - Device: [PC]
 - OS: [Ubuntu and Gentoo]
 - Network: [Local to Meshcentral]

**Comment by si458** [comment] 2024-04-02 11:58
Duplicate of several others like #5855

**Closed by si458** 2024-04-02 11:58 UTC
Labels: bug

**Comment by Shivangraj** [comment] 2024-04-02 12:29
> Duplicate of several others like #5855
> 
> Simple fix is restart the meshagent on the remote device or use 'service restart' from the console tab of the device

for ubuntu getting this error:

![image](https://github.com/Ylianst/MeshCentral/assets/38600280/43772694-e9f7-46dc-9de9-de35e2e223a6)
