### ISSUE TITLE
Feature Request: shift + home / shift + end buttons does not select the line/word.

### ISSUE THREAD

**Issue by senolkehya** [Ylianst/MeshCentral#385] opened 2019-07-29 05:58 UTC
Hi Ylianst,
When i connect Desktop if i make the combination shift + home or shift + end the cursor does not select the line/word.
For example when i try ctrl + home or ctrl + end it works.
Is it possible to develop shift + home and shift + end functions?
Thanks

**Comment by Ylianst** [comment] 2019-07-29 17:39
I will check when I get a chance.

**Comment by MailYouLater** [comment] 2019-08-06 18:38
This is a duplicate of #169.

**Comment by dinger1986** [comment] 2023-11-12 16:07
@si458 duplicate please close

**Closed** 2023-11-12 16:28 UTC
Labels: bug, duplicate
