### ISSUE TITLE
User Terminal seems to be broken on 0.3.7-l version of mesh

### ISSUE THREAD

**Issue by UnP1u9** [Ylianst/MeshCentral#346] opened 2019-07-10 06:07 UTC
User Terminal seems to be broken on 0.3.7-l version of mesh, connecting it just shows black screen nothing else.

**Comment by Ylianst** [comment] 2019-07-10 21:41
Tested the terminal on a few servers and it works for me. Probably not a version specific problem.

**Comment by UnP1u9** [comment] 2019-07-11 07:41
facing it after an update so thought that might be the issue, it says connected but you can't type any command, same works fine for Linux.

**Comment by Ylianst** [comment] 2019-07-14 16:15
Your original issue is to vague. You updated the server and the terminal is a black screen on Windows computers only? Does the same happen for remote desktop? More details appreciated. Thanks.

**Comment by UnP1u9** [comment] 2019-07-14 19:34
Yep, on windows only. I am able to take remote access and files access but while taking remote terminal, I am getting black screen only, it says connected but nothing is in the terminal, action button at right corner also doesn't shows popup.

**Comment by UnP1u9** [comment] 2019-07-14 20:10
My bad, my question seems live it broke the terminal on the user end😁. It is at the server end from where i can't take remote terminal access.

**Comment by UnP1u9** [comment] 2019-07-15 07:53
like this. 

![image](https://user-images.githubusercontent.com/19772335/61201945-c1d1bf80-a703-11e9-8f0b-373b0ce10d6f.png)

**Comment by UnP1u9** [comment] 2019-07-19 10:59
Hi, did you got time to check this, still not working, unable to take remote access to terminal.

**Comment by MailYouLater** [comment] 2019-07-19 18:15
Is this happening for _all_ Windows devices? or only one/some?
I would recommend that you try opening the device's "Console" screen, use the Agent Action dialog to first "Clear the core", then use it to "Upload default server core", and see if that fixes it.

**Comment by UnP1u9** [comment] 2019-07-19 18:19
It's happening with all windows devices,sure will try core cleaning options tomorrow and will let you know.

Thnx.

**Comment by krayon007** [comment] 2019-07-20 15:59
What version of the server are you using? That error about win-terminal not being found suggests you are using an old server as the agent binary is out of date.

**Comment by krayon007** [comment] 2019-07-20 16:02
Essentially the issue is that the agent binary is not updated, which is probably the underlying issue, if you didn't specifically disable auto-update.

**Comment by UnP1u9** [comment] 2019-07-20 16:04
Just updated the server,.

As per the suggestion by Ylianst, I copied meshcore file in meshchentral config folder besides node modules folder to save configuration after an update, could that be the issue.

Will also check after changing it back to normal on Monday.

**Comment by UnP1u9** [comment] 2019-07-20 16:06
Haven't disabled any settings specifically.

Might be issue with meshcore file, will check same too once.

**Comment by UnP1u9** [comment] 2019-07-21 04:16
Hi, 

https://github.com/Ylianst/MeshCentral/issues/325#issuecomment-505977689

I was using this but forgot to merge the files time to time hence got the issue which is fixed now. Deleted meshcore files from config folder and updated the server, all working fine now.

Thnx

**Comment by MailYouLater** [comment] 2019-07-22 17:10
Yeah, if you have your own meshcore in the meshcentral-data folder, then it uses that instead of whatever version of meshcore meshcentral included by default. If you're going to do that, then you have to be aware that you're effectively using an old version of the meshcore until/unless you manually update it, and you either have to merge your changes into the new file, every update, or at least every time an update breaks backward compatibility with the old meshcore that you're still using.

**Comment by MailYouLater** [comment] 2019-07-22 17:35
If you're not familiar with how to merge files, I'd recommend you to try WinMerge.

**Comment by Ylianst** [comment] 2019-07-22 22:55
I guess we can close this one. If there is an interesting feature that we should add to the MeshCore.js, please let us know. Certainly something we would consider for addition.

**Closed by Ylianst** 2019-07-22 22:55 UTC
Labels: bug
