### ISSUE TITLE
Clipboard transfer very slow

### ISSUE THREAD

**Issue by jacotec** [Ylianst/MeshCentral#3729] opened 2022-03-02 18:55 UTC
I'm experiencing with all clients that the clipboard transfer is pretty slow. You can see it best when using the "Clipboard" tab. Inserting just a short line of text and then click on "Send clipboard" it usually takes between 3-5 seconds before I get the "success" feedback.

I don't see a real reason why it takes that time to transfer around 40 Bytes of clipboard to the remote side. Should be a thing of below 100ms ...

**Comment by krayon007** [comment] 2022-03-03 23:33
What OS are your agents running?

**Comment by jacotec** [comment] 2022-03-04 23:52
Mostly Windows 10 and Server 2012R2. No differences between these though.

**Comment by krayon007** [comment] 2022-03-08 19:58
The delay was caused by how the agent was enumerating and spawning a child process in the user's desktop session. I already had written a module a while back to use native COM API to spawn this type of session instead of relying on SCHTASKS and Powershell... I switched the dispatcher in the agent to use this, and noticed a considerable speed up in sending the clipboard...  I have some more tests to validate this change, but it will be incorporated in an upcoming agent update.

**Comment by jacotec** [comment] 2022-03-08 20:16
@krayon007 Sounds pretty good!
Will the clipboard be able to transfer files then as well, like Teamviewer?

**Comment by krayon007** [comment] 2022-03-08 20:34
That's a feature I'll have to look into. Currently the only profile I implemented was text.

**Comment by si458** [comment] 2024-02-23 11:57
closing as stale,
please update to latest version 1.1.21 and use node 18 or above,
if issue persists, please reply back

**Closed by si458** 2024-02-23 11:57 UTC
Labels: question
