### ISSUE TITLE
"KVM Child process has unexpectedly exited" when a putty connection has established

### ISSUE THREAD

**Issue by elpibedeoro** [Ylianst/MeshCentral#3554] opened 2022-01-27 14:00 UTC
Hi,

I've noticed that when I establish a ssh connection through Putty with a client, the message "KVM Child process has unexpectedly exited" appears when I want to use the MC2 desktop service.
Have to close putty to get the service working as expected.

The client is on Debian 10 and have proprietary Nvidia graphic driver 470.94 installed. 
GDM3 is in use but Wayland is deactivated.
Meshagent current core is Jan 7 2022, 3588883981.

In the log I can find 
```
[2022-01-27 02:30:54 PM] [84BA4A8508C03921] microstack/ILibParsers.c:2824 (0,0) ** CRASH ** /lib/x86_64-linux-gnu/libc.so.6(+0x37840) [0x7fcfec84c840]
[0xcbf188]
```
Do not have this on Debian 9 but I've tested only 1 computer.

MC2 version is 0.9.74

Thanks

**Comment by krayon007** [comment] 2022-01-27 17:46
I'll setup a system with GDM.. My Debian 10 system is running Cinnamon, and KVM seems to work fine while putty is connected to it.

**Comment by elpibedeoro** [comment] 2022-01-28 07:59
> So to clarify, in your setup, you only see this issue when you have an ssh session connection to your debian 10 system, but not on your debian 9 system?

I have this issue from my Windows 10 machine to a Debian 10 client but I don't have it from my Windows 10 machine to a Debian 9 client.

**Comment by krayon007** [comment] 2022-01-28 19:06
Ok, I setup Debian 11 with Gnome, and was able to reproduce this if I connected SSH while the system was sitting at the login screen... Looking into it now...

**Comment by krayon007** [comment] 2022-01-28 20:08
Ok, I fixed it. It will be in the next agent update. The bug was caused by user-session not parsing out pseudo terminals when using loginctl to find the logged in user session.

**Comment by elpibedeoro** [comment] 2022-01-31 07:17
Wow that's amazing !!! Thank you for your reactivity and efficiency as usual !

**Comment by NiceGuyIT** [comment] 2023-11-26 08:32
@si458 Please close. Fix was in Jan 2022.

**Closed** 2023-11-26 10:05 UTC
