### ISSUE TITLE
Crash on startup with userallowedip config option

### ISSUE THREAD

**Issue by pmoncho99** [Ylianst/MeshCentral#72] opened 2019-01-07 14:55 UTC
I believe you fixed the error for UserAllowedIP (Issue #69) when using the domain section of the file but not when in the global settings section.

My Config. 

```
tt
{
  "settings": {
    "WANonly": true,
    "_Minify": 1,
    "SessionTime": 30,
    "Port": 443,
    "RedirPort": 80,
    "SelfUpdate": true,
    "UserAllowedIP": "MYEXTERNALIP",
    "_WebRtConfig": { "iceServers": [ { "urls": "stun:stun.services.mozilla.com"
 }, { "urls": "stun:stun.l.google.com:19302" } ] }
}`
```

Here is the error.

```
-------- 1/7/2019, 2:20:44 PM ---- 0.2.5-w --------

/home/user99/mc/node_modules/meshcentral/meshcentral.js:255

if (typeof obj.args.userallowedip == 'string') { if (obj.args.userallowedip == '') { obj.args.userallowedip = null; } else { obj.args.userallowedip = obj.userallowedip.split(','); } }

TypeError: Cannot read property 'split' of undefined
    at Object.CreateMeshCentralServer.obj.StartEx (/home/user99/mc/node_modules/meshcentral/meshcentral.js:255:177)
    at Object.CreateMeshCentralServer.obj.Start (/home/user99/mc/node_modules/meshcentral/meshcentral.js:140:17)
    at /home/user99/mc/node_modules/meshcentral/meshcentral.js:1340:110
    at InstallModules (/home/user99/mc/node_modules/meshcentral/meshcentral.js:1290:103)
    at InstallModule (/home/user99/mc/node_modules/meshcentral/meshcentral.js:1307:5)
    at InstallModules (/home/user99/mc/node_modules/meshcentral/meshcentral.js:1290:31)
    at InstallModule (/home/user99/mc/node_modules/meshcentral/meshcentral.js:1307:5)
    at InstallModules (/home/user99/mc/node_modules/meshcentral/meshcentral.js:1290:31)
    at InstallModule (/home/user99/mc/node_modules/meshcentral/meshcentral.js:1307:5)
    at InstallModules (/home/user99/mc/node_modules/meshcentral/meshcentral.js:1290:31)
```
`

**Comment by Ylianst** [comment] 2019-01-07 21:22
Thanks for the report. Fixed in MeshCentral 0.2.5-x. Please re-open if the issue is still present.

**Closed by Ylianst** 2019-01-07 21:22 UTC
