### ISSUE TITLE
After version 0.6.89 connection in some cases not working

### ISSUE THREAD

**Issue by pczolee** [Ylianst/MeshCentral#2141] opened 2021-01-04 11:38 UTC
Hello

Well, I'm updating always to the recent version of the MeshCentral. But today I faced that some of my remote system (and some is working!) is not working as it should. The agent looks online, but I can't connect to the terminal or files or etc. It showing connecting, than setup, but nothing else. If I try to talk with the agent, so type to the console for example "info", there is no response. So I tried to revert to the old version, and I found, that the last version is 0.6.89 which was working fine. After that this is broken.

Please have a look why is the new versions broken. If I can help, let me know how can I do it.

Thanks

**Comment by Ylianst** [comment] 2021-01-04 18:27
This could be a duplicate of #2128 and so, v0.7.36 would fix it. Apologies, but since you don't provide exact version, no way to replicate the problem.

**Closed by Ylianst** 2021-01-04 18:27 UTC

**Comment by pczolee** [comment] 2021-01-05 08:20
Well, as I wrote, I tried the latest version 0.7.37, but the issue was the same. Please let me know how can I give you more information, because this is different issue than #2128 . The 0.6.89 working fine, the 0.6.90 - 0.7.37 is not working in some cases...
