### ISSUE TITLE
NPM 6.8 to NPM 6.9 causing random server disconnections

### ISSUE THREAD

**Issue by SomeGuru** [Ylianst/MeshCentral#122] opened 2019-03-09 21:20 UTC
Hi Ylian,

I seem to have done an update on both the NPM and MeshCentral server yesterday to 0.2.6-z and the server keeps crashing down even with the enable of the recovery after 15 seconds. Have you seen the same?

Thanks,
SomeGuru

**Comment by Ylianst** [comment] 2019-03-09 21:58
Can you go in "meshcentral-data" and post the content of "mesherrors.txt". Any server exceptions should be there. You can also go in the "My Server" tab, click "Show server error log". Thanks.

**Comment by SomeGuru** [comment] 2019-03-10 07:16
GNU nano 2.9.3                   mesherrors.txt

-------- 3/9/2019, 6:05:28 PM ---- 0.2.9-z --------

ERROR: MeshCentral Intel(R) AMT server port 4433 is not available.


-------- 3/9/2019, 9:44:47 PM ---- 0.2.9-z --------

ERROR: MeshCentral Intel(R) AMT server port 4433 is not available.


-------- 3/10/2019, 12:44:54 AM ---- 0.2.9-z --------

sh: 0:


-------- 3/10/2019, 12:44:54 AM ---- 0.2.9-z --------

getcwd() failed: No such file or directory

**Comment by Ylianst** [comment] 2019-03-10 18:07
I have no idea what is going on. It's unlikely NPM is the cause of the server problem since it's the install tool. The mesherrors.txt file makes no sense to me. Does the server crash match the entries and times in the mesherrors.txt file? You could try renaming "node_modules" to "node_modules_bak" and doing "npm install meshcentral" again to get a fresh install. If you have any more information, let me know.

**Comment by Ylianst** [comment] 2019-03-28 03:59
Any more information on this one? I would suggest backing up the "meshcentral-data" folder and doing a server re-install. If any the problem still occurs, any more information would be appreciated.

**Comment by Ylianst** [comment] 2019-04-05 22:57
I am going to close this one as I am pretty sure NPM is not the cause of the problem. Please re-open if needed.

**Closed by Ylianst** 2019-04-05 22:57 UTC
