### ISSUE TITLE
Meshcentral Assistant hangs

### ISSUE THREAD

**Issue by Bintelons** [Ylianst/MeshCentral#3113] opened 2021-09-08 15:02 UTC
The latest Meshcentral assistant application is pretty powerful while compare with message features.
But while updating my server to the latest one I found that the Assistant application is not responding properly. It's taking more time to respond also sometimes the system gets hangs.

I am using aws ec 2 linux server.
Meshcentral version - 0.9.20

**Comment by pggsadmin** [comment] 2021-09-08 16:32
Duplicate of #3072, #3018,  #2961 etc
Hope this will fix soon

**Comment by Ylianst** [comment] 2021-11-06 05:44
Hopefully I just fixed this MeshCentral v0.9.45. #3212

**Closed** 2021-11-06 05:44 UTC
