### ISSUE TITLE
1.0.85 Mesh agent not installing

### ISSUE THREAD

**Issue by knkumar93** [Ylianst/MeshCentral#4600] opened 2022-10-04 10:08 UTC
**Describe the bug**

Mesh agent not getting installed in Ubuntu 16.04 (i686) device.

**To Reproduce**
1. In Mesh portal, click on Add Agent.
2. Choose Operating System - Linux/BSC/macOS Binary Installer
3. Choose System Type as 'Linux x86-32'
4. Choose Installation Type as 'Background & Interactive'
5. Copy the Command box value and paste it in Ubuntu 16.04 32bit machine.
6. Once file downloaded, convert to executable with chmod +x ./meshagent
7. Launch it with ./meshagent -install

**Expected behavior**
It should install the mesh agent, but it is not happening, instead it gives the command usage itself.

**Screenshots**
![image](https://user-images.githubusercontent.com/10217409/193792659-56be86a4-e733-419a-a3d1-0af5e4569e1d.png)

![image](https://user-images.githubusercontent.com/10217409/193792215-213a3fc5-026c-4f6c-baa0-b0c574257170.png)

**Server Software (please complete the following information):**
 - OS: Windows 10
 - Virtualization: No
 - Network: LAN
 - Version: 1.0.85
 - Node: v16.17.0

**Client Device (please complete the following information):**
 - Device: VM
 - OS: Ubuntu 16.04
 - Network: LAN

**Your config.json file**
```
{
	"$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
	"settings": {
		"cert": "10.81.234.42",
		"port": 8443,
		"browserPong": 60,
		"agentPong": 60,
		"noAgentUpdate":1
	},
	"domains": {
		"": {
			"title": "RemoteControl",
			"title2": "Remote Control",
			"minify": true,
			"welcomeText": "Remote control Tool",
			"welcomePicture": "mainwelcome.jpg",
			"consentMessages": {
				"title": "RemoteControl  Request",
				"desktop": "{0} requesting remote desktop access. Grant access?",
				"terminal": "{0} requesting remote terminal access. Grant access?",
				"files": "{0} requesting remote files access. Grant access?"
			},
			"notificationMessages": {
				"title": "RemoteControl  Request",
				"desktop": "{0} started a remote desktop session.",
				"terminal": "{0} started a remote terminal session.",
				"files": "{0} started a remote files session."
			}
		}
	}
}
```

**Comment by si458** [comment] 2022-10-04 11:51
duplicate of #4565, please follow this issue

**Closed** 2023-03-21 16:43 UTC
Labels: bug
