### ISSUE TITLE
access problems. login as a different user

### ISSUE THREAD

**Issue by nitmanby** [Ylianst/MeshCentral#5209] opened 2023-06-22 08:39 UTC
We use the mesh by several users. Sometimes when I open a mesh I see another user's groups, another user's profile opens. At the top where the username is, another user's name is listed.

**Comment by silversword411** [comment] 2023-09-10 00:54
You can log me in and replicate it. Let me know so I can see where the issue is.

**Comment by si458** [comment] 2023-09-22 19:56
closing issue as no real details about issue

**Closed by si458** 2023-09-22 19:56 UTC
Labels: question
