### ISSUE TITLE
Feature suggestion- password protect the Mesh Agent for uninstallation

### ISSUE THREAD

**Issue by PathfinderNetworks** [Ylianst/MeshCentral#655] opened 2019-11-14 02:11 UTC
This is in relation to #648.  I'd like to be able to password protect (as an option) the Mesh Agent such that a password has to be entered before it can be uninstalled from a device.  This is to prevent end users from uninstalling the MeshAgent when they aren't authorized to do so.  
Definitely not a critical request- but would be nice.  I can do this currently with Avast CloudCare and it's prevented quite a few end users from uninstalling the antivirus on their device (which they like to do when Avast stops them from running malware or visiting a site they insist on trying to visit, for example).

**Comment by Ylianst** [comment] 2019-11-16 05:00
This is kinda weird, because if you are administrator on the system, there are many ways you could disable the MeshAgent. One thing we could add is an option so that when you download and install the agent, it would not show up in the Control Panel uninstall list, we could also add a password, but understand that it's not going to be super effective at stopping someone from uninstalling it.

**Comment by PathfinderNetworks** [comment] 2019-11-18 01:22
It's really just about making it not obvious for a typical (read that as as 'non-technical) user to have access to uninstall MeshCentral.  If it's not in the Add/Remove programs list then that would work too.  Kind of like how it was with MeshCentral 1.  I'm not too concerned about users that have enough technical knowledge to be able to stop it/uninstall it outside the Add/Remove programs listing.  I'd rather have the uninstall be password protected though - even if it not's fool proof.  Just enough of something to make a non-technical user stop what they are doing.  There is one other thing that would need to be an option if the uninstall were able to be password protected- that would be being able to add/update/remove the password via the MeshCentral portal.  I realize that would probably quite a bit more involved though.   So if that's not all that feasible then just an option to not add MeshCentral to the Add/Remove programs list would be sufficient for my needs.

**Comment by MailYouLater** [comment] 2019-11-18 20:49
I would also really like an option to not add the agent to the Add/Remove Programs list.  It's probably best if it does get added for most people, but in an environment where you may have some users who require a local administrator account, it would be nice to not give them the option of removing your remote support and administration software.

**Comment by alialpsln** [comment] 2022-01-21 09:15
Hello, 

Any upcoming update for this feature?

**Comment by JSuenram** [comment] 2022-01-24 18:15
Duplicate of #3511 and there marked as invalid. See explanation from @Ylianst there. The risk to get Agent banned by AV-Software is far to high.

**Comment by cgb** [comment] 2022-01-25 04:25
Yeah, taking over from other MSP's, it is a major pain being unable to quickly remove agents that do this kind of thing (Antivirus!).  I don't think this should be implemented.

**Comment by si458** [comment] 2023-11-12 12:55
CLOSING ISSUE as this wont be implemented, sorry

**Closed by si458** 2023-11-12 12:55 UTC
Labels: enhancement
