### ISSUE TITLE
Users Permissions Dissapearing

### ISSUE THREAD

**Issue by matt-cylanda** [Ylianst/MeshCentral#2127] opened 2020-12-30 18:20 UTC
Morning,

I have a strange one. One of our users this morning complained they were unable to use remote access. I took a look and found even though their list of permissions were correct, when I went to edit them, all of the checks were blank. I just recently enabled force 2fa and password length & complexity requirements, I'm not sure if that might have done it or not. I'm also running the server in a docker container, not that it should matter.

![image](https://user-images.githubusercontent.com/65490814/103372997-c87b0080-4a77-11eb-90b3-53928e7814dc.png)

As far as I can tell, all of my non-admin users permissions look like this now with their permissions listed, but the edit area is blank.

**Comment by Ylianst** [comment] 2020-12-31 00:27
This is weird. I can't replicate this. Can you open the browser debug console and see if any errors are displayed? On FireFox it's "Ctrl-Shift-K" on Chrome it's "Ctrl-Shift-I". On FireFox the console looks like this:

![image](https://user-images.githubusercontent.com/1319013/103388000-b02cd500-4abb-11eb-97de-1688d853be27.png)

If you see any errors, that is good news. Cut & paste the error back. Thanks.

**Comment by LPJon** [comment] 2020-12-31 00:41
Duplicate of #2124 
@matt-cylanda 
@Ylianst Please look at the issue above. This seems to be related to some database issues, possibly with MongoDB. During the upgrade to 0.7.33 it seems the account used for the upgrade has its permissions removed for agents that were assigned to it. There aren't any errors in the "inspect element" window. It seems the original admin account (created during initial setup) will allow access to the agents as long as it was assigned access rights **before** the update.

**Comment by Ylianst** [comment] 2020-12-31 01:00
I wish I would replicate this issue on my servers. Looking into it now but I have to start looking in the dark since I don't have much information to go on. The screenshot above looks like it's for permissions to a user group.

**Comment by matt-cylanda** [comment] 2020-12-31 01:05
Hi @Ylianst, you are correct, the above is for a users permissions in a usergroup. I did find a user for another user group that had their permissions intact, so this wasn't a global issue. It would possibly make sense that coincides with a database upgrade since the user that had their permissions in tact was onboarded within the first week of starting our server. The other users were only added recently.

Also, the console in chrome is not reporting any errors.

**Comment by LPJon** [comment] 2020-12-31 01:22
To add to @matt-cylanda comment. In my case the user group that my user was in was completely removed from the device groups if that helps.

**Comment by Ylianst** [comment] 2020-12-31 01:23
Ok. Publsihed MeshCentral v0.7.34 that does not mess up the database anymore. Looking into the root cause now.

**Comment by Ylianst** [comment] 2020-12-31 01:34
Ok. I have a working theory as to what is going on. The problem will only occur for accounts with any of these 3 special chars: dot (.), dollar ($) and parentage (%) in the name. So, accounts with an email addresses as the name, etc. These accounts need special escaping since MongoDB and NeDB don't allow a dot in the field name.

This is also good because I can work on reversing the issue, so a server update will fix it.

**Comment by asasin114** [comment] 2020-12-31 01:36
I seem to have access to everything again after building a new user group. The ticket that was closed by @LPJon a bit ago also had a mention from me of the following error I am receiving on my MeshCentral instance running on Windows Server 2019 DC Edition:

![image](https://user-images.githubusercontent.com/417006/103389725-41a94080-4ad6-11eb-9be6-d770af29e945.png)

**Comment by Ylianst** [comment] 2020-12-31 01:36
Working on a fix, will take a few hours to validate.

**Comment by Ylianst** [comment] 2020-12-31 01:40
For the database "mongodump.exe" warning. If you are not using the MeshCentral built-in backup system, you can ignore that. I will fix it so that if you turned off auto-backup, that warning will no show.

If you want to use the built-in auto backup, you can fix the problem by specifying the path to "mongodump.exe" like this:

```
    "AutoBackup": {
      "mongodumppath": "C:\\Program Files\\MongoDB\\Tools\\100\\bin\\mongodump.exe",
      "backupIntervalHours": 24,
      "keepLastDaysBackup": 3,
      "zipPassword": "test",
      "backupPath": "C:\\temp",
    }
```

Let me know if that helps.

**Comment by Ylianst** [comment] 2020-12-31 01:42
To be clear, I am working on a fix for the permission issue so that if the database is not right, the new version will fix it without having to restore a backup or do any changes.

**Comment by Ylianst** [comment] 2020-12-31 02:57
Published MeshCentral v0.7.35 with a fix for this. Exactly replicated the problem and this should fix it. Let me know if it works.

**Comment by matt-cylanda** [comment] 2020-12-31 02:59
You guys are so awesome! We'll update our docker container tonight

**Comment by LPJon** [comment] 2020-12-31 03:33
I can confirm that upgrade from 0.7.32 to 0.7.35 works. Will report shortly with 0.7.33 to 0.7.35 results.
I can also confirm that upgrading from 0.7.33(with confirmed permission issue) to 0.7.35 corrects this issue. It works!....thank you Sir.

**Comment by Ylianst** [comment] 2020-12-31 03:53
Nice! Thanks for reporting back.

**Closed** 2021-01-02 20:44 UTC
Labels: Fixed - Confirm & Close, bug
