### ISSUE TITLE
MeshMessenger Branding? 

### ISSUE THREAD

**Issue by SomeGuru** [Ylianst/MeshCentral#2301] opened 2021-02-16 23:17 UTC
Hi Ylian,    @Ylianst 

For the MeshMessenger, it doesn't seem to follow the same branding as that of the agent/sites? Can this be easily implemented to follow those sites brand logos and such? Just wondering as users click but then hang up because they think they are going to the wrong chat folks.

Thanks,
SomeGuru

**Comment by Ylianst** [comment] 2021-02-17 00:43
This is a duplicate of #2199 and already fixed. If that does not work, open a new issue. Thanks.

**Closed by Ylianst** 2021-02-17 00:43 UTC
Labels: enhancement
