### ISSUE TITLE
FEATURE REQUEST : Agent version number shown

### ISSUE THREAD

**Issue by GRIFFCOMMca** [Ylianst/MeshCentral#2218] opened 2021-01-26 15:01 UTC
Hi

Are we able to have the agent version number to be shown in the tab "Details > Mesh Agent (section)", it tells the Mesh agent bit level (32/64), connection time and IP address, however the version would be nice here to make sure they are updated.

**Comment by Ylianst** [comment] 2021-01-26 19:50
Working on it.

**Comment by Ylianst** [comment] 2021-01-26 20:17
Added agent compile time to the details tab. This will be in MeshCentral v0.7.53.

![MC2-AgentVersion](https://user-images.githubusercontent.com/1319013/105900149-8094be00-5fd0-11eb-993a-cfc2cb9991b1.png)

**Comment by GRIFFCOMMca** [comment] 2021-01-26 20:42
Cool, thanks :)

**Comment by petervanv** [comment] 2021-01-26 22:10
I get an messag: invalid date, server version 0.7.54
![image](https://user-images.githubusercontent.com/58996467/105912302-8c619e00-602b-11eb-82c3-7cb6a7482f8c.png)

**Comment by Ylianst** [comment] 2021-01-26 22:32
@petervanv can you go in the agent console, type "versions" and report back when you get? I will work on a fix for this.

![image](https://user-images.githubusercontent.com/1319013/105914447-3ff27000-5fe3-11eb-969c-b9c4a1e3b5c7.png)

**Comment by petervanv** [comment] 2021-01-26 22:32
![image](https://user-images.githubusercontent.com/58996467/105914546-caac8c80-602e-11eb-93e1-4d8cf575d94c.png)

**Comment by Ylianst** [comment] 2021-01-26 22:33
Perfect, thanks. Working on it now.

**Comment by Ylianst** [comment] 2021-01-26 22:40
For now, I can display the US formatted date on the web page, but this is not idea. I need to find a way to parse the US date and display the date in the correct local format.

**Comment by petervanv** [comment] 2021-01-28 10:29
Confirmed fix: compile date and time is working now
![image](https://user-images.githubusercontent.com/58996467/106124952-f0837f80-615b-11eb-9381-22601dd6ed2c.png)![image](https://user-images.githubusercontent.com/58996467/106124911-e497bd80-615b-11eb-8577-3aa4160a9aa6.png)

**Comment by vitko-bg** [comment] 2021-01-28 11:26
0.7.56 - working for me fine! Thanks.

**Comment by GRIFFCOMMca** [comment] 2021-01-28 15:27
v0.7.55 works for me... :)

**Closed** 2021-01-28 18:37 UTC
Labels: Fixed - Confirm & Close, enhancement

**Comment by petervanv** [comment] 2021-02-03 14:38
Hi @Ylianst ,

Mesh Central Server version: v0.7.61, VM ubuntu server 20.04.2 LTS 

i noticed that on the raspberry pi (buster) no compile information is displayed on the details page
![image](https://user-images.githubusercontent.com/58996467/106761005-ad7e4c00-6634-11eb-9389-694d368a02b7.png)![image](https://user-images.githubusercontent.com/58996467/106761103-c850c080-6634-11eb-8272-f287f559c7bc.png)
while the command in the console does provide that information
![image](https://user-images.githubusercontent.com/58996467/106761447-2087c280-6635-11eb-9a53-ac5dd57fd41d.png)
is this by design? the other raspberry pi (2 and 3) running buster does not report any compile info at the details page

**Comment by drnikcuk** [comment] 2021-02-03 15:13
I'm seeing the same on my PIs.
