### ISSUE TITLE
Meshcentral Desktop Sharing Link

### ISSUE THREAD

**Issue by mctchirag** [Ylianst/MeshCentral#5559] opened 2023-11-16 07:30 UTC
*Hello when we share the remote session with another user by generating sharing link then the user is getting blue bar on the top that your machine is shared
how we can hide that. Please help me

**Comment by dinger1986** [comment] 2023-11-16 07:51
It's a prompt for confirmation or a bar if you give someone the link, those are the options, I'm sure you can work around it in the code but really not smart from a security point of view

**Comment by mctchirag** [comment] 2023-11-16 07:55
its a Blue Colour  bar on the top center of the screen when we give the link to someone
i want to hide that

Please help

**Comment by dinger1986** [comment] 2023-11-16 08:01
Yeah I just answered this, I know what bar it is

**Comment by mctchirag** [comment] 2023-11-16 08:02
so how to Hide that?
i have see someone using it and he has hidden that part

**Comment by mctchirag** [comment] 2023-11-16 08:09
i have closed it in discussion so it is open only here

**Comment by dinger1986** [comment] 2023-11-16 08:09
Probably not when it's being used with a sharing link, I'm sure whoever showed you can show you it being changed in the code but not something that should be supported here

**Comment by mctchirag** [comment] 2023-11-16 08:10
so its not possible ?

**Comment by dinger1986** [comment] 2023-11-16 08:17
Everything's possible but would need a change in code, due to the cyber risks etc I doubt it will be implemented officially

**Comment by mctchirag** [comment] 2023-11-16 08:44
ok i understand that it want be implemented officially
but do you know how we can achieve this by changing what part of the code and in which file

**Comment by si458** [comment] 2023-11-16 09:37
Sadly @Ylianst has designed the guest shating stuff so the end user must be show the notification bar so they are aware someone is connected to there computer (security)

It currently isn't possible to do this without physically changing the code itself 

It is inside a few different files but can't remember which ones?

The is already other issues about this, so I'm going to close this as a duplicate

Will update my message when I find the other issues for you

**Closed by si458** 2023-11-16 09:37 UTC
Labels: bug
