### ISSUE TITLE
Bug: In agent-mode no typing into website forms shown in Edge (0.4.1-v)

### ISSUE THREAD

**Issue by veitw** [Ylianst/MeshCentral#536] opened 2019-10-07 10:22 UTC
When using the remote desktop in agent mode and opening an Edge window, it is not possible to type into any forms shown in the window; when pressing a key, you see the cursor react, but to characters show up. The "Type" feature is affected by this bug, too. 

Typing on the local keyboard works flawlessly, as well as typing into e.g. the browser's address bar. Also using other browsers such as Firefox works as expected.

At first I thought this was a chat-related feature that prevents the MC user from impersonating as the managed machine's local user in the chat window, but it affects all forms inside Edge, not just the chat.
Then I thought it might be related to the "limited input" permission (which I found no further documentation on), but it even occurs for Full Administrator (server and group) users.

**Comment by MailYouLater** [comment] 2019-10-07 19:20
This is a duplicate of #454.

**Comment by Ylianst** [comment] 2019-10-07 20:08
Bryan and I may do some testing on this. If Edge works when the agent is running in temporary mode (just hit "Connect" on install dialog) we may be some possible solution for the future.

**Comment by MailYouLater** [comment] 2019-10-07 22:01
Doesn't work in temporary mode for me. 😞

**Comment by Ylianst** [comment] 2019-10-08 00:34
Arg! Ok. We need to close one of these since it's a dup. I will close this one and continue on #454. Bryan will need to look into this.

**Closed by Ylianst** 2019-10-08 00:34 UTC
Labels: bug
