### ISSUE TITLE
MeshCentral server shuts down when SSH session is closed

### ISSUE THREAD

**Issue by eagle856** [Ylianst/MeshCentral#4184] opened 2022-06-27 12:49 UTC
**Describe the bug**
I log in to my server via SSH and start Meshcentral. When the SSH session times out and closes, so does the MeshCentral Server.

**Server Software (please complete the following information):**
 - OS: Oracle-Linux
 - Virtualization: OCI
 - Network: WAN
 - Version: 8.6
  - Browser: Google Chrome

**Remote Device (please complete the following information):**
 - Device: Desktop
 - OS: Windows 10
 - Version: 21H1

**Additional context**
I followed the directions in the server install guide to set it so the MC starts automatically, but even though I don't get any errors, it doesn't start up when the server is restarted.

**Comment by eagle856** [comment] 2022-06-27 15:23
Disregard this post. I'm going to start from scratch with Ubuntu.

**Comment by LPJon** [comment] 2022-06-27 18:08
Have you tried starting MeshCentral from the console instead of an SSH connection? Most SSH sessions are close everything that was open in them when they are closed unless it's a system service. Did you setup a system service for MeshCentral?

**Comment by Ylianst** [comment] 2022-06-27 20:51
I think @ryanblenis is correct, this is not a bug. When you close a SSH session the shell closes and any commands you where running including MeshCentral will stop. You can run `node meshcentral --help` to see at the `install/uninstall/start/stop` arguments you can use to install MeshCentral as a background service:

![image](https://user-images.githubusercontent.com/1319013/176033303-f31e1a34-94e9-4bb0-9873-a8bb3ef443e5.png)

**Comment by eagle856** [comment] 2022-06-27 20:53
I've been using node ./node_modules/meshcentral, so apparently that's my problem. If I enter systemctl meshcentral start, it says Unknown operation meshcentral. If I enter systemctl start meshcentral it wants the root password. If I enter sudo systemctl start meshcentral, it just returns me to the system prompt without starting the server. If I put in /etc/init.d/meshcentral start it gives me No such file or directory. The only things in the init.d directory are: functions, mongod, network, and readme.

I really appreciate your help on this. I've been doing IT work for over 30 years, but never got in Linux until now.

**Comment by LPJon** [comment] 2022-06-27 20:59
Once the service starts it could take up to 30 seconds for the web UI to be available. If it is available then you need to enable the service on startup using the command `sudo systemctl enable meshcentral`. This will cause meshcentral service to automatically start on each boot.

**Comment by eagle856** [comment] 2022-06-27 21:01
If I'm reading it right, it closed. 

● meshcentral.service - MeshCentral Server
   Loaded: loaded (/etc/systemd/system/meshcentral.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Mon 2022-06-27 20:59:03 GMT; 5s ago
  Process: 138119 ExecStart=/usr/bin/node /home/opc/node_modules/meshcentral (code=exited, status=203/EXEC)
 Main PID: 138119 (code=exited, status=203/EXEC)
Jun 27 20:59:03 medar-meshcentral systemd[1]: meshcentral.service: Main process exited, code=exited, status=203/EXEC
Jun 27 20:59:03 medar-meshcentral systemd[1]: meshcentral.service: Failed with result 'exit-code'.

**Comment by LPJon** [comment] 2022-06-27 21:04
Please note that @Ylianst is talking about the Windows Installation. You sort of have an issue there. You can't really install MeshCentral into a `home` directory. There is too much security over permissions that OS uses there. It really needs to be installed into `/opt/` or a different folder of your choosing off of the root `/` directory. This is currently why you are having issues.

To fix this you are going to have to save your `config.json` file and reinstall MeshCentral into a different directory.

**Comment by eagle856** [comment] 2022-06-27 21:06
I thought that looked like it was for Windows (that's what I'm used to looking at. LOL) Ok. I'll give that a shot and see what happens. Thank you so much for your time!!

**Comment by LPJon** [comment] 2022-06-27 21:07
If you are open to a video conference I may be able to help you a little faster. It's just a link no special software.

**Comment by eagle856** [comment] 2022-06-27 21:11
Thanks! I'm actually about to leave the office shortly. I was going to play with it in the morning. How can I tell it to install in a different directory. The instructions say run npm install meshcentral. Would I just do npm install /opt/meshcentral. or npm install meshcentral /opt/, or just change to the directory first and run npm install meshcentral?

**Comment by LPJon** [comment] 2022-06-27 21:15
Run the npm command inside of the `/opt/` directory. The directory where you run the command is where the install will occur. So your last statement is the correct way.

**Comment by eagle856** [comment] 2022-06-27 21:16
Ok. Thank you so much!!

**Comment by ryanblenis** [comment] 2022-06-27 21:16
You mentioned:
> I followed the directions in the server install guide to set it so the MC starts automatically

I'm unfamiliar with Oracle Linux (I'll look it up later), but if `systemctl start meshcentral` worked, but with no output, it sounds like it has systemd (a linux service manager). What does `systemctl status meshcentral` output? My best guess would be that you may need to add permissions for the user you're set to run meshcentral as to allow it use of ports 443/80. 

Take a look and see if you have a file `/etc/systemd/system/meshcentral.service` (or do a search for meshcentral.service, as it may be placed elsewhere on other disctributions) and post the contents here. My first guess would be that you're missing this line:
`AmbientCapabilities=cap_net_bind_service`


Here's my full file, as an example:

```
[Unit]
Description=MeshCentral Server
[Service]
Type=simple
LimitNOFILE=1000000
ExecStart=/usr/bin/node /opt/meshcentral/node_modules/meshcentral
WorkingDirectory=/opt/meshcentral
Environment=NODE_ENV=production
User=meshcentral
Group=meshcentral
Restart=always
# Restart service after 10 seconds if node service crashes
RestartSec=10
# Set port permissions capability
AmbientCapabilities=cap_net_bind_service
[Install]
WantedBy=multi-user.target

```

**Comment by Ylianst** [comment] 2022-06-27 22:21
Note that these commands should work on both Linux and Windows, but obviously are implemented in very different ways:

```
node node_modules/meshcentral --install
node node_modules/meshcentral --uninstall
node node_modules/meshcentral --start
node node_modules/meshcentral --stop
node node_modules/meshcentral --restart
```

On Linux, `--install` should create the service file and get things started from the right path. This said, the Linux specifics like permissions can change things.

**Comment by eagle856** [comment] 2022-06-28 12:44
Here's the output of the meshcentral.service file:

[Unit]
Description=MeshCentral Server

[Service]
Type=simple
LimitNOFILE=1000000
ExecStart=/home/opc/.nvm/versions/node/v16.15.1/bin/node /home/opc/node_modules/meshcentral/meshcentral
WorkingDirectory=/home/opc
Environment=NODE_ENV=production
User=opc
Group=opc
Restart=always
# Restart service after 10 seconds if node service crashes
RestartSec=10
# Set port permissions capability
AmbientCapabilities=cap_net_bind_service

[Install]
WantedBy=multi-user.target

I tried doing an install from the /opt/ directory, but I get permission errors when it tries to create directories. I tried doing a sudo mkdir, but then the install fails again when it tries to rename the existing folder. I can't win for losing. LOL

**Comment by LPJon** [comment] 2022-06-28 14:35
Okay, so you might need to consider switching your Linux distro to one supported in the [Docs](https://info.meshcentral.com/downloads/MeshCentral2/MeshCentral2InstallGuide.pdf). I would choose [Debian's net-install](https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/debian-11.3.0-amd64-netinst.iso) and install it with the minimum tools. Basically, nothing but the "Standard System Utilities" and "SSH Server" options. Then follow the Ubuntu instructions in the Docs. 

Oracle Linux is much like Red-Hat and therefore you are going to run into lots of permission and SELinux (Security) issues that require you to have serious knowledge and skills about Linux in general. It would be better to switch to a more user friendly Linux Distro that is not built around technical knowledge. 

If you wish to continue with Oracle Linux that is fine but I will have to spin up a VM and test run the install/setup so that I can give you a step by step for that Linux Distro. However, maintaining it might prove to be difficult and cumbersome in the future. So it could be like shooting yourself in the foot.

**Comment by LPJon** [comment] 2022-06-28 14:47
You can join a meeting I've setup for help if you would like at the link below.
[https://meets.laptop-pitstop.net/MeshCentralGitHubHelp](https://meets.laptop-pitstop.net/MeshCentralGitHubHelp)
I can use that help provide you live support. You should know I'm not a DEV and am only trying to help as a major user of MeshCentral Server.

**Comment by eagle856** [comment] 2022-06-28 14:55
Yeah, I'm kind of in a box as to what versions I can use. The only non-Oracle ones they offer are CentOS (7 or 8 Stream) or Canonical Ubuntu (18, 20, and 22). I think I'll try to start up a new OCI with  Ubuntu 18.04 and see how it goes. 

By the way, I joined the meeting, but I guess you were away. I really do appreciate all your help! I'll give this a shot and see what happens.

**Comment by LPJon** [comment] 2022-06-28 14:58
LOL....I stepped out to get a cup of coffee. Come on back! lets see if we can't get this rolling for you.

**Comment by eagle856** [comment] 2022-06-28 15:08
Ok. Coming back in.

**Comment by LPJon** [comment] 2022-06-30 19:41
@eagle856 Were you able to get this up and rolling?

**Comment by eagle856** [comment] 2022-06-30 19:57
Sorry, I should have responded already.  Yes, I was able to get my original config up and running. I guess I missed the section on starting the server in the background with ./mcstart. Still fuddling with let's encrypt, but other than that, all is good. I appreciate all your help!

**Comment by LPJon** [comment] 2022-06-30 21:17
You are welcome! Feel free to close the issue if you think you have this issue resolved. If you have new questions about the install just start a new issue or re-open this one.

**Closed** 2022-07-01 13:06 UTC
Labels: question, Fixed - Please Verify & Close
