### ISSUE TITLE
ERROR NEW UPDATE 1.1.23

### ISSUE THREAD

**Issue by pieer3991** [Ylianst/MeshCentral#6118] opened 2024-05-24 00:37 UTC
Node.js v18.14.2

-------- 23/5/2024, 19:35:58 ---- 1.1.23 --------

/opt/meshcentral/node_modules/telegram/errors/index.js:25
            return new Cls({ request: request, capture: capture });
                   ^

FloodWaitError: A wait of 3247 seconds is required (caused by auth.ImportBotAuthorization)
    at RPCMessageToError (/opt/meshcentral/node_modules/telegram/errors/index.js:25:20)
    at MTProtoSender._handleRPCResult (/opt/meshcentral/node_modules/telegram/network/MTProtoSender.js:537:58)
    at MTProtoSender._processMessage (/opt/meshcentral/node_modules/telegram/network/MTProtoSender.js:467:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async MTProtoSender._recvLoop (/opt/meshcentral/node_modules/telegram/network/MTProtoSender.js:418:17) {
  code: 420,
  errorMessage: 'FLOOD',
  seconds: 3247
}

Node.js v18.14.2

**Comment by pieer3991** [comment] 2024-05-24 01:07
-------- 23/5/2024, 20:06:36 ---- 1.1.23 --------

/opt/meshcentral/node_modules/meshcentral/meshuser.js:821
                                    if (parent.users[a].realname) { docs[i].links[a].name = parent.users[a].realname; }
                                                        ^

TypeError: Cannot read properties of undefined (reading 'realname')
    at /opt/meshcentral/node_modules/meshcentral/meshuser.js:821:57
    at /opt/meshcentral/node_modules/meshcentral/db.js:2571:54
    at /opt/meshcentral/node_modules/mongodb/lib/utils.js:349:28
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.14.2

**Comment by pieer3991** [comment] 2024-05-24 01:19
I used MongoDB

**Comment by si458** [comment] 2024-05-24 05:49
The telegram flood bug is a duplicate of https://github.com/Ylianst/MeshCentral/issues/5127

Will look at the realname when I get into office

**Comment by si458** [comment] 2024-05-24 09:49
@pieer3991 ok ive replicated the error
can u just patch `meshuser.js` lines 821 and 822 with the below and restart, should fix ur issue temp
```
if (parent.users[a] && parent.users[a].realname) { docs[i].links[a].name = parent.users[a].realname; }
else if (parent.users[a] && parent.users[a].name) { docs[i].links[a].name = parent.users[a].name; }
```

**Closed** 2024-05-24 09:55 UTC
Labels: bug
