### ISSUE TITLE
no download button only upload

### ISSUE THREAD

**Issue by mathias1xxX** [Ylianst/MeshCentral#782] opened 2020-01-03 01:07 UTC
I'm relativity new to meshcentral2 but in the file manger there is only an upload button and no download button, i need a folder containing 7154 files so clicking one by one isn't an option.. and there is no access rights to install an FTP on it or another program ( the current admin forgot the password and cannot reset it.. as the Laptop is 1200 Miles away i could realy use that button xD

**Comment by ryanblenis** [comment] 2020-01-03 01:29
Just a thought, but if you have an agent on there already this means it is installed as an admin, and you can reset the admin password via command line (`net user administrator password`) or simply create a new admin account. Once you have that settled you can install whatever you'd like. 
Second, you can also use powershell (5+) and the `Compress-Archive` command to create a zip that you can then download with a single click... plus smaller size because it is compressed.

**Comment by MailYouLater** [comment] 2020-01-03 02:17
Basically you're asking for the same thing as #525/#323/#50, which was also discussed in some detail in #503 and should be possible without _too much_ work since @krayon007 [added a `.tar` encoder to the agent](https://github.com/Ylianst/MeshAgent/commit/b54087783629de2c649bad95d9921c8fbe7be85d), but will still require some work on the server side of things before it'll be usable. (Also the ability to convert it to a `.zip` before downloading it was suggested to make it easier for Windows/Mac users who aren't familiar with how to extract a `.tar` file.)

**Comment by dinger1986** [comment] 2023-11-12 16:53
@si458 duplicate of one closed,

**Comment by si458** [comment] 2024-01-15 18:16
Duplicate please follow #1390

**Closed by si458** 2024-01-15 18:16 UTC
Labels: enhancement
