### ISSUE TITLE
cores are not functioning properly on 0.6.82

### ISSUE THREAD

**Issue by vtacquet** [Ylianst/MeshCentral#1972] opened 2020-11-10 14:37 UTC
all agents stay connected but you can't do Desktop/Terminal/Files, clearing the core and uploading recovery core has no effect either, rolled back from 0.6.82 to 0.5.81, everything works fine on 0.5.81

error in console is "TLS handshake error"

**Comment by Ylianst** [comment] 2020-11-10 16:50
This is likely because of a new security measure we added. How are you configuring your TLS certificate for HTTPS port 443?

**Comment by vtacquet** [comment] 2020-11-10 17:03
I use Caddy as frontend with LetsEncrypt certificates and configured TlsOffload to the internal ip of my Caddy and the CertUrl to the external dns of my MeshCentral URL. It still works in 0.6.80.

**Comment by southeasterntech** [comment] 2020-11-10 17:40
Ylian, I'm also having what seems to be this issue.... also using Caddy as a front end.  My previous post on Desktops not showing up, is probably more related to this issue here.
Shane #1971

**Comment by Ylianst** [comment] 2020-11-10 20:41
Are you guys using `"ignoreAgentHashCheck": true` in settings section of config.json? If so, I have a fix coming shortly.

**Comment by GoodComputerGuy** [comment] 2020-11-10 21:07
> Are you guys using `"ignoreAgentHashCheck": true` in settings section of config.json? If so, I have a fix coming shortly.

No... But we could if that will fix the issue (at least Shane and I can.)

**Comment by Ylianst** [comment] 2020-11-10 21:11
MeshCentral v0.6.83 is published. `"ignoreAgentHashCheck": true` in settings will fix the issue (but you get less security), but now I am going to test again with my reverse proxies.

**Comment by GoodComputerGuy** [comment] 2020-11-10 21:13
Thanks! Confirmed working again, at least with ignoreagenthashcheck true.

**Comment by Ylianst** [comment] 2020-11-10 21:18
Ok! Seeing the same problem with my reverse proxy!! Debugging this now.

**Comment by Ylianst** [comment] 2020-11-10 21:29
Uploading MeshCentral 0.6.84 where I am reversing the added TLS checking until I get something better. Should be up in a few minutes and you don't need to use `ignoreagenthashcheck ` anymore.

**Comment by Ylianst** [comment] 2020-11-10 21:37
ok, MeshCentral 0.6.84 is out. Remove the `ignoreagenthashcheck` if you just added that in. I will be working on this security feature again for future release.

**Comment by southeasterntech** [comment] 2020-11-10 21:39
Yep All good now on .4 thanks Ylian!

**Comment by Ylianst** [comment] 2020-11-10 22:08
Ok, the root cause was use of ECC (Epileptic Curve Certificate) in the reverse proxy. Working on fixing this.

**Comment by Ylianst** [comment] 2020-11-13 07:07
Pretty sure this in fixed now. Thanks for the reports.

**Closed by Ylianst** 2020-11-13 07:07 UTC
Labels: Fixed - Confirm & Close, bug
