### ISSUE TITLE
Sort Group in "Grouped Action" list

### ISSUE THREAD

**Issue by Tomatoschewps** [Ylianst/MeshCentral#1669] opened 2020-07-31 14:03 UTC
Hi,

Is it possible to sort groups alphabeticaly for the dropdown menu in "Grouped Action" --> "Move to group" :
![image](https://user-images.githubusercontent.com/10291238/89042380-1ebc0a00-d347-11ea-9e3d-6eb3f31b63ff.png)

**Comment by Ylianst** [comment] 2020-07-31 18:54
Just published MeshCentral v0.5.99 with a fix for this. Should be sorted now. Let me know if it works.

**Comment by Tomatoschewps** [comment] 2020-08-03 10:02
All right for me !
Thanks :)

**Comment by PetieM** [comment] 2020-08-13 15:28
I feel like this is related enough to re-open but if it would be better to create a new issue instead, let me know.

Can we also get groups on the "My Account" page sorted alphabetically? Or maybe add a sort-order field so we can optionally choose a sort order?

**Comment by Ylianst** [comment] 2020-08-16 06:42
Added device group sorting in "My Account" tab, It will be in MeshCentral v0.6.10.

**Comment by PetieM** [comment] 2020-08-16 20:33
Confirmed - groups are sorting correctly on the My Account tab now. Thanks.

**Comment by Tomatoschewps** [comment] 2020-08-17 07:40
Hi Ylian,
Another places that needs filing is "Device Group" dropdown menu in "Add Relay Map..." and "Add Map..." button from MeshCentral Router :)
D.

**Comment by PetieM** [comment] 2020-08-17 15:03
It looks like it's also not sorting on the My Account page on the mobile version of the site.

**Closed** 2021-02-15 06:33 UTC
Labels: Fixed - Confirm & Close, enhancement
