### ISSUE TITLE
wol and amt activated: wol doesn't work anymore

### ISSUE THREAD

**Issue by tradexsrl** [Ylianst/MeshCentral#1079] opened 2020-03-27 14:49 UTC
Hi , have you ever seen if wol and amt are activated on a pc , wol magic packet are now ignored and the only way to power up the pc is login into amt webpage of that pc or use meshcommander ?

**Comment by tradexsrl** [comment] 2020-03-27 16:15
i have found this thread:
https://www.google.com/search?client=firefox-b-d&ei=vxp-XqqXGtSFk74PmtSjqA4&q=wol+not+working+when+amt+enabled&oq=wol+not+working+when+amt+enabled&gs_lcp=CgZwc3ktYWIQAzoECCEQClDaeFjQnwFgnKUBaAFwAHgAgAFoiAGoEJIBBDIyLjKYAQCgAQGqAQdnd3Mtd2l6&sclient=psy-ab&ved=0ahUKEwjq8o2d-7roAhXUwsQBHRrqCOUQ4dUDCAo&uact=5

in this someone say to disable the ping on AMT , i have done it via meshcommander but again wol doesn't work anymore...they only way to have it back is to disable amt...
if wol doesn't work with amt enables is it possible to schedule an amt power up action on all computer each work day?

**Comment by tradexsrl** [comment] 2020-03-27 16:40
i found also this thread that say in intel amt sdk there is a remotecontrol.exe that can be scripted but i'm not able to find it inside the sdk:
https://community.broadcom.com/groups/communities/community-home/librarydocuments/viewdocument?DocumentKey=44fcb45a-4c35-4c50-88f3-62205de94f06&CommunityKey=2e7731d2-88b7-41f8-b095-7828c53aaa71&tab=librarydocuments

http://software.intel.com/en-us/articles/download-the-latest-intel-amt-software-development-kit-sdk

**Comment by Ylianst** [comment] 2020-03-27 16:51
Closing this since it's a duplicate of #1078 and MeshCentral generates UDP WOL packets that work fine with Intel AMT enabled.

**Closed by Ylianst** 2020-03-27 16:51 UTC
