### ISSUE TITLE
Missing Desktop Session Icon

### ISSUE THREAD

**Issue by K-O-K** [Ylianst/MeshCentral#3271] opened 2021-11-11 17:09 UTC
Hi,

I've the following issue with the UI:

My default browser is Firefox and today, while showing a user the MC Platform in a call, I saw something in his screen I haven't seen before, he had an icon I don't.

I realized that, since he was using Chrome and I use Firefox the problem had to be there, so a launched Chrome, signed in with my administrator credentials and there it was, the Icon is shown in Chrome but not in Firefox.

The missing Icon in Firefox is the "Upload local clipboard to remote device". 

The "Download remote clipboard to local clipboard" does show up in Firefox.

Chrome:
![image](https://user-images.githubusercontent.com/25281984/141337825-0509ac1a-f1bc-4dac-8072-2f68564e577b.png)

Firefox:
![image](https://user-images.githubusercontent.com/25281984/141338880-eb40d675-079a-462d-a3a0-641f881893f9.png)

(BTW, I replaced the default icons with Google Material ones using the trick explained here: #3240)

Any way I can help to check this issue?

Thanks!

**Comment by Ylianst** [comment] 2021-11-11 18:01
I will take a look again, but I test to see if the browser allows the web page to read from the clipboard and only show this option if the browser allows it. Due to security concerns, FireFox does not, but I am need to ask use permission. In general, this is expected behavior... but maybe I can work around it.

Also, if you have better icons, send them over. I can make them the default ones.

**Comment by K-O-K** [comment] 2021-11-12 21:09
Hi Ylian, thanks!

Since I use Firefox as my daily browser, I thought there was only one Clipboard Icon so I didn't bother to have the arrow in it (as you can see in the snips of my last post).

So, even tho I'm far from being good at editing images and using imaging software (I'm using GIMP), I'm working now in those two icons (the Download and Upload Clipboard) because I couldn't find anything appropriate in Material Google Icons.

I'm not sure what looks best because how small they are.

![image](https://user-images.githubusercontent.com/25281984/141534265-752ac9c9-4526-4eda-8498-aaae186694da.png)
this one looks o.k. in Dark mode but in Light mode the arrow can't be distinguished:

![image](https://user-images.githubusercontent.com/25281984/141534446-b99d35ab-2ffb-49a2-b9ad-09d12693c69e.png)
![image](https://user-images.githubusercontent.com/25281984/141534453-cbad3bdb-0646-43f1-915b-ce67ca0d1472.png)

Your input its appreciated.

Thanks!

**Comment by K-O-K** [comment] 2021-11-17 02:36
Hi @Ylianst ,

I just emailed you the Icons I have so far, I hope you like them.

Thanks!

**Comment by si458** [comment] 2023-11-11 21:54
im going to close this for the moment,
currently the upload clipboard its implemented as intended for edge and chrome
HOWEVER firefox is a law into its own, so doesnt work correctly because you cant read ur clipboard in Javascript
https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/readText

**Closed by si458** 2023-11-11 21:54 UTC
Labels: bug
