### ISSUE TITLE
Chat doesn't work

### ISSUE THREAD

**Issue by ZENAdmin-Ops** [Ylianst/MeshCentral#6286] opened 2024-07-29 09:47 UTC
**Describe the bug**
Chat doesn't work. Click on the chat button in the General tab and a tab opens in my browser, but no chat window opens on the remote system.

**To Reproduce**
1. Click on the chat button in the General tab
2. A new tab opens in my browser (Chrome)
3. Says 'Waiting for other user'
4. No chat window opens on the remote system
5. Message appears in the new tab: 'connection closed'

**Expected behavior**
A chat window should open on the remote system

**Screenshots**

<img width="286" alt="MeshCentral_chat_tab_on_my_browser" src="https://github.com/user-attachments/assets/57cc8c90-27e9-45e4-bc66-961ecc1539b0">
**Server Software (please complete the following information):**
 - OS: Windows 10 Pro
 - Virtualization: HyperV VM
 - Network: WAN
 - Version: 1.1.24
 - Node: 20.15.0

**Client Device (please complete the following information):**
 - Device: Dell OptiPlex 7070
 - OS: Windows Server 2019 Standard
 - Network: [Remote over WAN
 - Browser: [Google Chrome is installed] - No browser opened
 - MeshCentralRouter Version: [N/A]

**Remote Device (please complete the following information):**
 - Device: [e.g. Dell Latitude 7410]
 - OS: [Windows 10 22H2
 - Network: [Remote over WAN
 - Current Core Version (if known): [**HINT**: Go to a device then `console` Tab then type `info`]

**Additional context**

**Your config.json file**
```
{
  "$schema": "https://raw.githubusercontent.com/Ylianst/MeshCentral/master/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "cert": "mc1.zen.net.au",
    "WANonly": true,
	"_LANonly": true,
    "sessionKey": "### have changed ###",
    "_port": 443,
    "aliasPort": 5443,
	"MpsAliasPort": 54433,
    "_redirPort": 80,
    "_redirAliasPort": 80,	
	"mongodb": "mongodb://127.0.0.1:27017/meshcentral",
    "mongodbcol": "meshcentral",
	"autoBackup": {
	"mongoDumpPath": "C:/Program Files/MongoDB/Server/7.0/bin/mongodump.exe",
	"backupIntervalHours": 24,
	"keepLastDaysBackup": 10,
	"zipPassword": "#### have changed ####",
	"backupPath": "C:/MeshCentral/meshcentral-backups",
	"maxFiles": 10
	}
  },
  "domains": {
    "": {
      "_title": "MyServer",
      "_title2": "Servername",
      "_minify": true,
      "_newAccounts": true,
      "_userNameIsEmail": true
    }
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "info@zen.net.au",
    "names": "mc1.zen.net.au",
    "skipChallengeVerification": true,
    "production": false
  }
}
```

**Comment by si458** [comment] 2024-07-29 09:57
is the remote user thats logged onto the remote device connected to the `console` RDP session?
or is it a normal desktop control session?

we are aware of a bug where the chat window doesnt open IF the remote user on the device is using an RDP session,
rather than the console session (or physical desktop) https://github.com/Ylianst/MeshCentral/issues/4372

the is already a few issues open about chat not opening the default web browser correctly
https://github.com/Ylianst/MeshCentral/issues/4884
https://github.com/Ylianst/MeshCentral/discussions/5645

one thing to also check is IF you can open a web page using the open web page `globe` button,
AND also check using the `openurl` in the console tab to
`openurl https://www.bbc.co.uk`

**Comment by ZENAdmin-Ops** [comment] 2024-07-29 22:52
> is the remote user thats logged onto the remote device connected to the `console` RDP session? or is it a normal desktop control session?

I believe I'm connected to the 'console' RDP session.

I'm connected to the session, which I would be using if I were physically in front of the computer.

> one thing to also check is IF you can open a web page using the open web page `globe` button, AND also check using the `openurl` in the console tab to `openurl https://www.bbc.co.uk`

The globe button doesn't open a browser on the client device.

The console tab says 'success'. No browser opens on the client device.

I then tried opening a browser on the client device (Chrome) and re-entered the openurl command into the console. Same behaviour. The console tab says 'success'. But no change to Chrome on the client device.

**Comment by si458** [comment] 2024-07-30 08:20
@ZENAdmin-Ops ok so your device have the issue where the meshagent CANT create the windows tasks needed to launch a web browser!
i cant remember where the issue is (will tag here when i find it)
but try opening up the `task scheduler` on the remote device and see if you get any errors,
but basically it cant create a task in the scheduler for some reason, weather its a corrupt task or corrupt system

**Comment by ZENAdmin-Ops** [comment] 2024-07-30 08:25
Hello 

I don't know what I should be looking for exactly, but Task Manager itself opens fine.

And the first task is list is running daily. I'm not aware of any issues with Task Manager on this system.
<img width="605" alt="Task_Scheduler_MeshAgent_device" src="https://github.com/user-attachments/assets/57d43730-75b7-4a0b-a805-6c5236b879cf">

**Comment by si458** [comment] 2024-07-30 08:28
@ZENAdmin-Ops can you try running this command in powershell or cmd?
` C:\Windows\system32\cmd.exe /C START https://www.google.com`
does it open up your default browser and load up google?

**Comment by ZENAdmin-Ops** [comment] 2024-07-30 08:33
> @ZENAdmin-Ops can you try running this command in powershell or cmd? ` C:\Windows\system32\cmd.exe /C START https://www.google.com` does it open up your default browser and load up google?

That works in cmd.

**Comment by ZENAdmin-Ops** [comment] 2024-07-30 08:37
> @ZENAdmin-Ops just a random one, cau try this issue/post too? [#1146 (comment)](https://github.com/Ylianst/MeshCentral/issues/1146#issuecomment-612671532) it might be because the remote machine is on DOMAIN mode and its missing the domain name if present, just wanted to verify this!

WARNING: Task may not run because /ST is earlier than current time.
SUCCESS: The scheduled task "TestTask" has successfully been created.

**Comment by si458** [comment] 2024-07-30 08:39
does it show as created in the task scheduler itself?
and what happens if you RUN the task ` SCHTASKS /RUN /TN TestTask` ?

**Comment by ZENAdmin-Ops** [comment] 2024-07-30 08:41
Task appears in Task Scheduler
<img width="572" alt="Task_in_Task_scheduler" src="https://github.com/user-attachments/assets/5c2b5d2e-2be0-4917-a5d8-5da9219bd2ed">

If I run the task, it does work

**Comment by si458** [comment] 2024-07-30 08:42
@ZENAdmin-Ops what did you put the user/domain as ?
was it a domain user by any chance?
i think this is the issue, its creating the task as a non domain user,
just looking now

**Comment by ZENAdmin-Ops** [comment] 2024-07-30 08:42
> @ZENAdmin-Ops what did you put the user/domain as ? was it a domain user by any chance? i think this is the issue, its creating the task as a non domain user, just looking now

I specified the domain\user cyberx1\zen

**Comment by si458** [comment] 2024-07-30 08:47
are you comfortable with editing javascript to do some testing for me?
might be easier to email me and ill explain

**Comment by ZENAdmin-Ops** [comment] 2024-07-30 09:05
> are you comfortable with editing javascript to do some testing for me? might be easier to email me and ill explain

Yes, I'm happy to assist in any way that I can on both of my issues.

Also interested to learn more about MC too.

**Comment by si458** [comment] 2024-07-30 09:06
@ZENAdmin-Ops please email me then (check my github profile 👍 )

**Comment by ZENAdmin-Ops** [comment] 2024-07-30 09:07
Do you want me to reply?

Regards,
Vaughan

**Comment by si458** [comment] 2024-08-02 12:20
ok this issue has been fixed by https://github.com/Ylianst/MeshAgent/commit/90f730c3d49555e5c16106a7c8dd0219818edad6
the is a bug in the windows registry code,
it checks local users first then domain users,
but sadly if the same exists exists both locally AND in the domain,
it was always returning the local user deatils which would stop the task schedular from running as the correect user!
a temp fix until a new agent is built is to download the fixed win-registry.js and place it next to meshagent.exe on every machine
https://github.com/Ylianst/MeshAgent/raw/master/modules/win-registry.js

**Closed by si458** 2024-08-02 12:20 UTC
Labels: bug
