### ISSUE TITLE
Mesh Agent no longer installs

### ISSUE THREAD

**Issue by rowds15** [Ylianst/MeshCentral#296] opened 2019-06-10 23:13 UTC
Hi After the weekend I have noticed that the Mesh Agent installed onto most of my computer network about 40 nodes, is no longer installed. Not sure why. can someone please explain why this might be happening. This has happened in the past but i put it down to a version update, but over the weekend I had not performed any update.

**Comment by PathfinderNetworks** [comment] 2019-06-10 23:19
I have a feeling it's because antivirus applications are starting to tag the MeshCentral agent (especially the 32bit version) as a trojan.  Which it absolutely is not!  But it, somehow, got listed as such recently and more engines are tagging it that way.  I had Windows Defender blow away the 32bit version just this past weekend one of the few devices I don't have Avast CloudCare installed on.  If Avast starts viewing it as a virus then I'm going to be royally screwed as I have over 300 devices in MeshCentral for management.

**Comment by Ylianst** [comment] 2019-06-11 17:04
Yes, this is a big problem. It's much better to install the 64bit agent right now since anti-virus software don't see it as bad. I am going to do some testing to see if it's better to have the agent self-signed or not signed at all. If anyone has suggestions on this, that would be appreciated.

**Comment by Ylianst** [comment] 2019-06-11 17:05
FYI. This is a duplicate of #279.

**Comment by Ylianst** [comment] 2019-06-13 06:44
FYI. Just published MeshCentral v0.3.6-m with a new 32bit MeshAgent that passes all virustotal.com tests. So now, both 32bit and 64bit MeshCentral agents should not have a problem anymore.

I am going to close this one since I think this solves it. If there are any issues, please over an issue or post on #279. Thanks.

**Closed by Ylianst** 2019-06-13 06:44 UTC
Labels: duplicate
