### ISSUE TITLE
clipboard on remote and admin panel cause black screen

### ISSUE THREAD

**Issue by kpetrow** [Ylianst/MeshCentral#5307] opened 2023-08-23 13:50 UTC
**Describe the bug**
I am trying to get the clipboard to work using a remote link in the browser.  I notice first that the clipboard functions are commented out in sharing.handlebars. Does that mean remote links cant use the clipboard?  

Second i notice if i use the clipboard int he admin panel it sets the remote machine into black screen and requires computer reboot.

**To Reproduce**
function showDeskClip(),function showDeskClipGet(),  function showDeskClipSet() are commented out in sharing.handlebars
remote view into machine from mesh central control panel. Use clipboard set. remote session becomes unresponsive and on reconnect is black screened

**Expected behavior**
clip board to work in link on browser and in admin panel.

**Screenshots**

**Server Software (please complete the following information):**
 - OS: windows server 2019
 - Virtualization: Amazon EC2 instance
 - Network: LAN
 - Version: "0.9.99",
 - Node:v18.12.1

**Client Device (please complete the following information):**
 - Device: desktop
 - OS: windows 11 home
 - Network: remote
 - Browser: chrome
 - MeshCentralRouter Version: [if applicable]

**Remote Device (please complete the following information):**
 - Device: desktop
 - OS: windows 10 pro
 - Network: remote
 - Current Core Version (if known): [**HINT**: Go to a device then `console` Tab then type `info`]

**Additional context**
thanks this ahs been game changer.

**Comment by si458** [comment] 2023-08-23 16:12
I noticed this issue recently, too, and it's weird?

If you 'set clipboard' and the content includes a url,

The minute you try to paste inside the remote machine,
The screen is disconnected, and you have to reconnect.

**Comment by kpetrow** [comment] 2023-08-23 19:50
Ideally get rid of the weird clipboard panel and use hot keys and copy/paste context menu.  Have it work in the remote link and admin panel.  Has there been any investigation into using navigator.clipboard ? Seems like a lot of the original hurdles were around Linux.  So forget Linux and just make work for windows.

**Comment by si458** [comment] 2024-11-30 16:08
duplicate of #5323

**Closed by si458** 2024-11-30 16:08 UTC
Labels: bug
