### ISSUE TITLE
Can't type any symbol in a web site open by Microsoft Edge

### ISSUE THREAD

**Issue by GusevVictor** [Ylianst/MeshCentral#892] opened 2020-01-30 21:10 UTC
Step to reproduce:

- Client OS: Windows 10 1809 or 1511
- Remote OS: Windows 10 1809
- Browser: Firefox 68 ESR
- Server: 0.4.7-s / 0.4.8-f

- Connect to Remote OS
- Run Microsoft Edge
- Go go any web site
- try to input any text field in site: for example: type login/pass and so on 
- you can't (for example proxmox or alfresco)

![изображение](https://user-images.githubusercontent.com/7081357/73490910-8d330600-43be-11ea-8a9b-70d25907ac0c.png)

**Comment by Ylianst** [comment] 2020-01-30 22:20
So, we know about this and I am not sure there is anything we can do about it. I think this is a security feature of Edge? But not sure. It's not accepting keyboard input. Maybe Bryan can comment on this.

**Comment by Ylianst** [comment] 2020-01-30 22:21
Duplicate of #454.

**Comment by PathfinderNetworks** [comment] 2020-01-31 02:50
But what's odd about this is that I can type in to Edge using other remote tools- such as Premium Remote that is included with Avast CloudCare.  It only seems to be MeshCentral (from my experience with various remote tools) that is experiencing this behavior.

**Comment by krayon007** [comment] 2020-01-31 02:55
I remember someone said that once you load the MeshCentral page, and it stops working, it stops working for other tools too, as if edge went into some mode where rejects everything.

**Comment by ryanblenis** [comment] 2020-01-31 04:34
Just tested with Kaseya on a machine and was able to type, whereas with MeshCentral I could not. So there is a way. Maybe I'll set up a Remotely instance and test that as well, since it is open source.

**Comment by GusevVictor** [comment] 2020-01-31 06:21
> 
> 
> Duplicate of #454.

Oh... I'm so sorry about that... :( I will more search in a next time before create a issue.

**Closed** 2020-05-08 02:39 UTC
Labels: bug, duplicate
