### ISSUE TITLE
connect to a terminalserver user session - or switch between sessions...

### ISSUE THREAD

**Issue by wvt-adm** [Ylianst/MeshCentral#544] opened 2019-10-08 16:27 UTC
question - it is possible to access on a terminalserver to a user session? or switch from one to an other session?

thanks and best regards

am

**Comment by krayon007** [comment] 2019-10-08 17:11
Which OS are you referring to?

**Comment by wvt-adm** [comment] 2019-10-08 17:14
the meshcentral server is a windows 2019 server with german language pack…

the machine that i will remote is a windows 10 prof 64bit machine

best regards and thanks for your help

(need access to the server – let me know!)


Von: Bryan Roe [mailto:notifications@github.com]
Gesendet: Dienstag, 8. Oktober 2019 19:12
An: Ylianst/MeshCentral <MeshCentral@noreply.github.com>
Cc: wvt-adm <fws@wvtnet.ch>; Author <author@noreply.github.com>
Betreff: Re: [Ylianst/MeshCentral] connect to a terminalserver user session - or switch between sessions... (#544)


Which OS are you referring to?

**Comment by MailYouLater** [comment] 2019-10-09 17:17
This is a duplicate of #38.

**Comment by krayon007** [comment] 2019-10-10 01:48
Oh wait, so you guys are referring to terminal services sessions, as in Microsoft Terminal Services, and not about the terminal console (command prompt) being connected as a user session as opposed to LocalSystem?

**Comment by wvt-adm** [comment] 2019-10-11 22:19
yes exactly, the point is that you can also help customers who work on a terminal server. but you also have to be able to access their session. at splashtop i personally find the implementation to be the most successful - i can access each session via dropdown menu and even if there are several monitors that change with a click... ect. ect.

**Comment by d1m3ch** [comment] 2019-12-04 02:41
+1.

You can run multiple meshagents as a logon script.  Each time a user logs in it will connect to the server and show their session.  

I have not figured out how to change the display name in the server though.  Any ideas?

**Comment by Ylianst** [comment] 2019-12-04 05:24
@krayon007 is hard at work on a way to get sessions as the currently logged in user. No need for running many agents.

**Comment by d1m3ch** [comment] 2019-12-04 19:33
kewl!  Happen to have an ETA on this feature?  

Thanks! : )

**Comment by Ylianst** [comment] 2019-12-04 19:52
If all goes well, next week we will have the the ability to open a terminal session under the currently logged in user for Windows. This is already available on Linux, you right click the terminal "Connect" button and select "User Shell".

**Comment by d1m3ch** [comment] 2019-12-12 21:38
Hi, i wonder, will this issue be closed when it is available for us to start using?  Also, how should i deploy it?

**Comment by krayon007** [comment] 2019-12-12 22:25
This feature is already live for both Windows and Linux :)  You right click on the connect button, and you'll see a menu item for User Shell.

**Comment by krayon007** [comment] 2019-12-12 22:26
If you are referring to KVM sessions as particular users, we just need to update the UI to allow user selection, but the feature is working.

**Comment by Ylianst** [comment] 2019-12-12 22:29
As indicated by @krayon007, you can now right click on the Terminal "Connect" button to see different connection options. We added this for Linux a month back, but just added this for Windows in the last few days so you need the latest MeshCentral server to do this for Windows.

![MC2-UserTerminal](https://user-images.githubusercontent.com/1319013/70754320-c5399900-1ceb-11ea-90d5-001267e3d1a0.png)

**Comment by d1m3ch** [comment] 2019-12-13 16:45
this is so cool!  You guys are RAD!!!  Thanks!

**Comment by dinger1986** [comment] 2023-11-12 17:03
this works @si458

**Comment by si458** [comment] 2023-11-12 20:30
this is indeed now possible,
when you have multiple users logged in on terminal server, when you click connect
you will get a list of users logged in and you select which one you want, then it connects to that user

**Closed by si458** 2023-11-12 20:30 UTC
Labels: enhancement
