### ISSUE TITLE
MeshCentral-Service Crash when logging on with 2FA in enabled LDAP (Active Directory)

### ISSUE THREAD

**Issue by JSuenram** [Ylianst/MeshCentral#3467] opened 2022-01-16 13:44 UTC
When we try to logon with 2FA, after entering Username and Pasword, site is reloading for 2FA and Service Crashes... waiting until service restart and Logon again, crashed the service again on third try Logon with 2FA is possible.... this happens every time when 2FA is requested.... 

config:

```
      "auth": "ldap",
      "ldapUserName": "sAMAccountName",
      "ldapUserBinaryKey": "objectSid",
      "ldapOptions": {
        "url": [ "ldaps://SERVERA:636", "ldaps://SERVERB:636" ],
        "bindDN": "CN=XXX,OU=XXX,DC=XXX,DC=XXX,DC=XXX",
        "bindCredentials": "*************",
        "searchBase": "DC=XXXDC=XXX,DC=XXX",
        "searchFilter": "(&(sAMAccountName={{username}})(objectClass=organizationalPerson))",
        "tlsOptions": { "rejectUnauthorized": false },
        "reconnect":true
      }
```

```
-------- 16.1.2022, 14:12:51 ---- 0.9.68 --------

events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:209:20)
Emitted 'error' event on LdapAuth instance at:
    at LdapAuth._handleError (/etc/meshcentral/node_modules/ldapauth-fork/lib/ldapauth.js:204:8)
    at Client.emit (events.js:314:20)
    at TLSSocket.onSocketError (/etc/meshcentral/node_modules/ldapjs/lib/client/client.js:968:12)
    at TLSSocket.emit (events.js:314:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read'
}


-------- 16.1.2022, 14:14:00 ---- 0.9.68 --------

events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:209:20)
Emitted 'error' event on LdapAuth instance at:
    at LdapAuth._handleError (/etc/meshcentral/node_modules/ldapauth-fork/lib/ldapauth.js:204:8)
    at Client.emit (events.js:314:20)
    at TLSSocket.onSocketError (/etc/meshcentral/node_modules/ldapjs/lib/client/client.js:968:12)
    at TLSSocket.emit (events.js:314:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read'
}

```

**Comment by nzalev** [comment] 2022-01-16 18:03
I set up TLS on my ldap server and reconfigured it like yours. I enabled 2FA on an account (google authenticator), but I am not able to reproduce your error.

Have you tried creating a new user in your directory without 2FA enabled and seeing if this error continues?

Something I want to note, the error is being generated from within `ldapjs`. The error `ECONNRESET` means the LDAP server abruptly closed its connection on meshcentral, so you should check your ldap server log files for errors as well.

**Comment by JSuenram** [comment] 2022-01-16 19:49
> I set up TLS on my ldap server and reconfigured it like yours. I enabled 2FA on an account (google authenticator), but I am not able to reproduce your error.
> 
> Have you tried creating a new user in your directory without 2FA enabled and seeing if this error continues?
> 
> Something I want to note, the error is being generated from within `ldapjs`. The error `ECONNRESET` means the LDAP server abruptly closed its connection on meshcentral, so you should check your ldap server log files for errors as well.

I am sorry, but there is "nothing" in the LDAP-Server logs. Maybe the issue is related to https://github.com/ldapjs/node-ldapjs/issues/318 ? Maybe the LDAP-Connection should have some sort of "timeout" or "do it again one more time, if it fails"-Setting? Crashing the whole server makes it hard to use 2FA.... disabled 2FA for the user and the problem does not exist anymore.....

**Comment by nzalev** [comment] 2022-01-16 20:21
I have put in an error handler for the ldap connection. What server are you using for LDAP? I was testing with OpenLDAP 2.4.49.

**Comment by JSuenram** [comment] 2022-01-17 07:38
> I have put in an error handler for the ldap connection. What server are you using for LDAP? I was testing with OpenLDAP 2.4.49.

We connect to Windows Active Directory Servers (2019).

**Comment by JSuenram** [comment] 2022-01-17 07:48
Updates to 0.9.71 and enabled 2FA again. So far looks good. No server-crash on first login after update with 2FA enabled...

**Closed** 2022-01-17 09:09 UTC
Labels: bug
