### ISSUE TITLE
Device Last Seen timeline 

### ISSUE THREAD

**Issue by PathfinderNetworks** [Ylianst/MeshCentral#132] opened 2019-03-16 00:00 UTC
The timeline for the 'device online' data for devices is not working correctly.  As you can see in the screen grab this particular device is offline and has been offline since 5:21:33pm.  However, the graphical 7 Day Power State data shows PC as still being online.  
![LastSeen Data](https://user-images.githubusercontent.com/48607498/54467646-dfdee180-475c-11e9-9f65-4b19db3064b9.JPG)

**Comment by Ylianst** [comment] 2019-03-16 01:53
Thanks for the report. I can confirm the timelines never did work correctly. It's low priority, but I will get around to fixing it.

**Comment by mschubeck** [comment] 2019-03-19 20:23
It's never worked properly for me either since V. 1.  Although the "Last seen" time is convenient, it wouldn't bother me if the timeline was dropped completely from the program.

**Comment by PathfinderNetworks** [comment] 2019-03-20 00:38
I do use the timeline feature (it seems to be fairly accurate on MeshCentral1).  It's a tool I use to do very basic monitoring of uptime of systems and, more importantly, can use it to see when a system has gone offline (such as during a power outage, Internet outage, etc).  Not an urgent thing to fix- but definitely something I want to see remain and working at some point down the road.

**Comment by Ylianst** [comment] 2019-03-20 19:42
Just published MeshCentral v0.3.0-s with fixes for the device timeline. I also added a way to download the power state of a device on the upper right of the device timeline.

![MC2-PowerStateDownload](https://user-images.githubusercontent.com/1319013/54714147-8a645500-4b0d-11e9-8863-d94d938fd566.png)

**Comment by mschubeck** [comment] 2019-03-20 20:30
Looks good, but only goes back to my last server update in both the timeline and the spreadsheet:
![image](https://user-images.githubusercontent.com/48728727/54716975-76c8e680-4b2d-11e9-940d-d5515df7c499.png)

**Comment by PathfinderNetworks** [comment] 2019-03-20 22:52
Thank you Ylian, I just updated to 3.0-s and see it does appear to be working correctly now (but will continue to monitor it). The ability to download the power state as a csv file- that is greatly appreciated!  Thank you for that.

**Comment by mschubeck** [comment] 2019-03-21 15:06
So, does the black bar indicate when it was powered on?

**Comment by mschubeck** [comment] 2019-03-21 17:59
That's exactly what I'm seeing as well.  I used the wrong machines to test with, but today I looked at some machines that I know were powered off and the black bar indicated they were on.  I also turned on a machine that is normally off, left it on for more than 1 hour, and the black bar never appeared.

**Comment by Ylianst** [comment] 2019-03-21 18:21
Looks like I need to work on this one a bit more :) If by chance you can download the power state .csv file and take a quick look to see if the data is correct and it's the UI displaying it wrong, that would be great. If the download data is not right, that would be super important to know.

**Comment by mschubeck** [comment] 2019-03-22 12:24
Negative, it appears that all 3 indicators are wrong now - the graph, the last seen time, and the CSV file.  Here are my screenshots:
![image](https://user-images.githubusercontent.com/48728727/54822287-12b43880-4c7b-11e9-82d1-b65b32d02cd1.png)
![image](https://user-images.githubusercontent.com/48728727/54822363-30819d80-4c7b-11e9-9ea0-92a4d7db2097.png)
The computer above was powered on from about 8:30 AM to roughly 5:00 PM yesterday (it's right outside my own office).  The CSV also appears to show almost identical data to most other machines, regardless of their own power state:
![image](https://user-images.githubusercontent.com/48728727/54822736-f5339e80-4c7b-11e9-998d-34bf47a235b1.png)

**Comment by Ylianst** [comment] 2019-03-23 12:54
Ok thanks for the data. I will take another look into it. Interesting that the "last seen" does not also have a power state event.

**Comment by Ylianst** [comment] 2019-06-18 16:30
FYI. Just published MeshCentral v0.3.6-r with device timeline improvements. Should be a lot better now.

**Comment by Ylianst** [comment] 2019-07-14 17:13
Closing this as the timelines have been improved. Please open a new issue if you see problems in this area.

**Closed by Ylianst** 2019-07-14 17:13 UTC
Labels: Fixed - Please Confirm, bug
