### ISSUE TITLE
After update some clients do not reconnect

### ISSUE THREAD

**Issue by nicrame** [Ylianst/MeshCentral#77] opened 2019-01-21 09:55 UTC
Hello. I have noticed, that after server update, some Windows clients (usually 6.1.7601) do not reconnect.
For example today i have updated from 0.2.6-n into 0.2.6-o, and after that some random computers do not appear as Powered.
In the Mesh Agent directory of such computer there is no any log files (Program Files\Mesh Agent).
In the "My Events" there is also no any information.
Maybe it may have something to do, with the fact that many computers are connecting from the same IP (NAT).
To say the truth, what i believe is lacking about Mesh Agents now, is the any kind of log, that show what is happening with connection (when it starts, when it's lost, when try to reconnect and why it fail, or when it's completed). Is there any way to make it show? So i will always know what is happening under the hood.

What i noticed on that specific computers, that Mesh Agent service is stopped, and the Mesh Agent process isn't running. Like it would crash, but without any LOG.

Of course computers are online, and i can use them using different software for outside management (i use it for backup in situations like that).

Little Update: it may have something to do with Kaspersky AV. I always knew it's the worst AV out there, but i believe enough is enough, time to delete this malware from computers.

**Comment by Ylianst** [comment] 2019-01-22 02:43
Hi. The AV could very well be the problem, when updating the AV will see a new .exe file and probably halt it's execution. I did ask Kaspersky AV to white list the MeshAgent, but will give it another go at it. If you happen to see any Kaspersky AV errors about the MeshAgent, please post a screenshot here along with the AV version number. It helps a lot with the process.

On a different note, stop the mesh agent service, open a shell to "C:\Program Files\MeshAgent" and type "MeshAgent run" to run the agent manually. You will see everything the agent does on the screen which can help with debugging.

Lastly, in the Windows Server manager, you could check that it's set to auto-restart the mesh agent on crash. Should not be needed, but just in case. That should automatically be setup when the agent is installed, but good to make sure.

**Comment by nicrame** [comment] 2019-01-22 07:00
I find Kaspersky one of the worst AV software, so i will try to remove it first. The problem was, it deleted .exe files (but .db file and mesh config were still there). I made a script, that is try to restart service, checking for .exe file existence, and if it fails then it just install mesh agent again (interesting is, that it installing without problems when Kaspersky is enabled, it's just remove it when it's updating itself i believe).

Sadly, there is no Windows Server manager (because, there is no AD environment).

**Comment by whalehub** [comment] 2019-03-10 20:41
@nicrame @Ylianst Did you manage to fix the issue by uninstalling Kaspersky?

**Comment by nicrame** [comment] 2019-03-10 21:35
Firstly i must say, that the PC's that were affected by this problem had Kaspersky Internet Security. My 1 try was adding Mesh Agent to trusted apps. But that didn't help, so removing it was the only solution. And it did help.

**Comment by Ylianst** [comment] 2019-03-11 15:56
I don't run Kaspersky myself. There seems to be a way to add to the whitelist locally: https://support.kaspersky.com/11444. If someone sends me a screen shot of the Kaspersky report for the Mesh Agent, I can ask for a global whitelist here: https://whitelist.kaspersky.com/

**Comment by mschubeck** [comment] 2019-03-19 20:45
Ylian, sent via private email.

Interestingly, this only happens during the agent upgrade process - not during the installation, or from a weekly file scan.  Therefore, it must be some specific action that's triggering it, not the file contents themselves.

Yes, it can be whitelisted on machines individually, or within the applied policies from the Kaspersky Management Console.

**Comment by nicrame** [comment] 2019-03-20 00:17
In my case, whitelisting didn't help. The app was still removed. But maybe it was some older version of KIS.

**Comment by mschubeck** [comment] 2019-03-21 13:01
After adding this to both the "Scan exclusions" and the "Trusted applications" setting under the various policy properties, and then running a MeshCentral version update yesterday, the MeshCentral agent **did not** get quarantined this time.

Running on Kaspersky Security Center 10.2.434, and KES 10.2.6.3733 mr4.
![image](https://user-images.githubusercontent.com/48728727/54753605-d66bd400-4bb7-11e9-828a-1a71687d4619.png)

**Comment by Ylianst** [comment] 2019-05-09 21:31
This is a duplicate of #57. As indicated in that page, the 64bit version of the MeshAgent shows up clear on [TotalVirus.com](https://www.virustotal.com) so that is the easiest way to fix this issue. If there are any suggestions for other actions I can take, take a look at #57 first and please open a new issue. Thanks.

**Closed by Ylianst** 2019-05-09 21:31 UTC
