### ISSUE TITLE
User management issues

### ISSUE THREAD

**Issue by amenolo** [Ylianst/MeshCentral#1116] opened 2020-04-06 00:36 UTC
1. when trying as administrator to create user account with empty or incomplete email address field (i.e. without trailing domain) or else with duplicated username, confirmation is successful without creating user nor returning any warning/error.

2. devices/users group creation allows duplicated names...maybe by design?

3. what's the purpose of user checkbox column?
![flag](https://user-images.githubusercontent.com/29974944/78512463-037c2c00-77a5-11ea-98c6-b80fbdcde3f0.png)
At first sight I thought it was related to `broadcast/import/export` operations...which is not...maybe at this point could be added commands like for instance `select all/select none/group actions` (as well as in My Devices section)?

 4. trying to add - both as administrator and as user - a non-existent user to a device group, it cause a forced log-out and a brief service disruption (the latter is an educated guess since Apache proxy returns `Service Unavailable` error but MC systemd unit isn't restarting)
![PMbeUVvHDX](https://user-images.githubusercontent.com/29974944/78513578-f95e2b80-77ac-11ea-923e-af2a0ebc8628.gif)

BTW I guess could be useful to have the option to deny registering more than 1 account with same email address.

Thanks

**Comment by Ylianst** [comment] 2020-04-06 00:41
1. Let me check on that.
2. By design, internally device groups have a unique identifier and on some servers many users will create al sorts of device groups with duplicate names.
3. Check boxes where added a few days ago, I am working on account batch operations. Hopefully with have these working in the next weeks.
4. Checking on this.

**Comment by Ylianst** [comment] 2020-04-06 00:45
FYI. Just checked in the fix for 4, will be in next published release.

**Comment by amenolo** [comment] 2020-04-06 00:53
1. 👍 
 2. copy that
 3. sorry my fault...I didn't noticed the W.I.P. status :sweat_smile:
 4. 👍 

Quick and accurate as always!

**Comment by amenolo** [comment] 2020-04-06 00:54
1. 👍 
 2. copy that
 3. sorry my fault...I didn't notice the W.I.P. status :sweat_smile:
 4. 👍 

Quick and accurate as always!

**Comment by Ylianst** [comment] 2020-04-06 01:15
Just checked in fix for 1, server will correctly notify when a problem occurs and web page now checks email address is in correct format. Will be in next published version.

**Comment by Ylianst** [comment] 2020-04-11 07:26
FYI. In MeshCentral v0.5.1-m, the check boxes in "My Users" tab are now used for group actions on accounts.

![MC2-BatchAccountOperations](https://user-images.githubusercontent.com/1319013/79038020-e4a5dd00-7b8a-11ea-8296-a5cf5b41ae4b.png)

**Closed** 2020-04-19 03:00 UTC
Labels: Fixed - Confirm & Close, bug
