### ISSUE TITLE
MeshCentral Windows Service detected as Trojan

### ISSUE THREAD

**Issue by avidtran** [Ylianst/MeshCentral#293] opened 2019-06-10 02:47 UTC
![meshcentral](https://user-images.githubusercontent.com/6099882/59169468-67838480-8aef-11e9-91f2-efd9bc480719.png)

**Comment by Ylianst** [comment] 2019-06-10 02:51
Yes, this is a know issue. The 32 bit version of the agent will trigger a lot of virus warnings, you can upload the executable to [https://www.virustotal.com](https://www.virustotal.com) and see. One way we could get around this is to simply remove the 32bit version of the MeshAgent.

This is a duplicate of #279.

**Closed by Ylianst** 2019-06-10 02:51 UTC
