### ISSUE TITLE
Consent box not showing in macOS agent

### ISSUE THREAD

**Issue by Brocky453** [Ylianst/MeshCentral#4287] opened 2022-07-19 09:51 UTC
Hello,

I've stumbled into a weird issue with the macOS meshagent, 

When I tried to take control with remote desktop over one of our Macbooks with the latest agent, our mesh central just waits for the  acknowledgment of the consent of the client.
With a yellow "Waiting for user access authorization..."

In the Client side, absolutely nothing shows up.

PS : The meshagent is correctly installed, others functionalities of the agent are working perfectly fine (like the power state)
PS2 : The 2 needed authorization from the client is given for the meshagent (Accesibility and Screen recording) 

### Further analysis

When I was looking of the history of my terminal on the macOS client, I've stumbled into one of the commands that the meshagent executes : 

`
/usr/local/mesh_services/meshagent/meshagent_osx64 -b64exec Y29uc29sZS5sb2coJ3RlbGwgY3VycmVudCBhcHBsaWNhdGlvbiB0byBkaXNwbGF5IGRpYWxvZyAiYWRtaW4gcmVxdWVzdGluZyByZW1vdGUgZGVza3RvcCBhY2Nlc3MuIEdyYW50IGFjY2Vzcz8iIHdpdGggdGl0bGUgIk1lc2hDZW50cmFsIiB3aXRoIGljb24gY2F1dGlvbiBidXR0b25zIHsiWWVzIiwiTm8ifSBkZWZhdWx0IGJ1dHRvbiAiTm8iIGdpdmluZyB1cCBhZnRlciB1bmRlZmluZWQnKTsgcHJvY2Vzcy5leGl0KCk7 | osascript 2>/dev/null | awk '{ printf "\x1e"; c=split($0, tokens, ","); split(tokens[1], val, ":"); if(c==1) { print val[2] } else { split(tokens[2], gu, ":"); if(gu[2]=="true") { print "_TIMEOUT_" } else { print val[2]  }  } printf "\x1e"; }'
`

If we analyse this command, we see that the meshagent execute an Apple script for what is suppose to be the consent box :
`tell current application to display dialog "admin requesting remote desktop access. Grant access?" with title "MeshCentral" with icon caution buttons {"Yes","No"} default button "No" giving up after undefined`

But this Apple Script returns an error which is "The variable undefined is not defined"

**Comment by Ylianst** [comment] 2022-07-28 22:41
This is an issue for Bryan.

**Comment by krayon007** [comment] 2022-07-28 23:03
What os version is your macros running?

**Comment by Brocky453** [comment] 2022-07-29 09:21
These tests have been done on OSX 12.4 and OSX 11.6

**Comment by deltademibro** [comment] 2022-08-22 12:32
Any update on this?

**Comment by krayon007** [comment] 2022-08-22 16:12
I think I found where the issue is coming from.. Working on it now... I think it may only need a server update...

**Comment by deltademibro** [comment] 2022-09-14 17:50
Any update on this?

**Comment by krayon007** [comment] 2022-09-14 17:59
The fix for this was pushed with v1.0.75. Can you verify if you are still having this issue with the current release?

**Comment by dinger1986** [comment] 2023-11-26 12:27
@si458 fixed can close

**Closed** 2023-11-26 14:46 UTC
Labels: bug, Fixed - Please Verify & Close
