### ISSUE TITLE
Missing info by RAM 0.5.13

### ISSUE THREAD

**Issue by vyacheslav25** [Ylianst/MeshCentral#1240] opened 2020-04-25 12:05 UTC
After update Meshcentral to 0.5.13  agents missing info by RAM in Details.
But agents who have not yet received the update show information

**Comment by krayon007** [comment] 2020-04-25 15:11
If you type sysinfo on the console tab, does it still shows the ram info there?

**Comment by PathfinderNetworks** [comment] 2020-04-25 17:34
I'm seeing the same issue.  
This is what I see when using sysinfo.  I removed the hash. 
> sysinfo
{
 "hardware": {
  "windows": {
   "memory": [],
   "partitions": []
  },
  "identifiers": {}
 },
 "pendingReboot": null,
 "hash": "xxxremovedxxx"
}

**Comment by amenolo** [comment] 2020-04-25 17:45
BTW in MC 0.5.14 seems fine with Windows agent and missing with Linux Agent.

**Comment by krayon007** [comment] 2020-04-25 22:33
Linux never had this information displayed... But for windows, are you saying this issue is not present in  0.5.14?

**Comment by amenolo** [comment] 2020-04-25 22:47
> Linux never had this information displayed...

Doh! I swear I saw it in the past releases...sometimes I can be really absent-minded, sorry.

> But for windows, are you saying this issue is not present in 0.5.14?

If I'm not mistaken...

https://pastebin.com/iPPxbSYR

**Comment by PathfinderNetworks** [comment] 2020-04-25 23:19
I'm on version 0.5.13 but am going to upgrade to 0.5.14 in a few minutes.  I'll report back if the device info is correct in that version after the upgrade.

**Comment by PathfinderNetworks** [comment] 2020-04-25 23:36
I can confirm, this issue is not present in 0.5.14.  This is what I get with sysinfo on the same device as before.

> sysinfo
{
 "hardware": {
  "windows": {
   "memory": [
    {
     "BankLabel": "P0_Node0_Channel0_Dimm0",
     "Capacity": "8589934592",
     "DataWidth": "64",
     "Description": "Physical Memory",
     "DeviceLocator": "DIMMA1",
     "FormFactor": "8",
     "Manufacturer": "Micron Technology",
     "MemoryType": "0",
     "Name": "Physical Memory",
     "PartNumber": "9ASF1G72PZ-2G6D1",
     "SerialNumber": "1FE277A2",
     "Speed": "2667",
     "Tag": "Physical Memory 0",
     "TotalWidth": "72",
     "TypeDetail": "8320"
    },
    {
     "BankLabel": "P0_Node0_Channel1_Dimm0",
     "Capacity": "8589934592",
     "DataWidth": "64",
     "Description": "Physical Memory",
     "DeviceLocator": "DIMMB1",
     "FormFactor": "8",
     "Manufacturer": "Micron Technology",
     "MemoryType": "0",
     "Name": "Physical Memory",
     "PartNumber": "9ASF1G72PZ-2G6D1",
     "SerialNumber": "1FE27761",
     "Speed": "2667",
     "Tag": "Physical Memory 1",
     "TotalWidth": "72",
     "TypeDetail": "8320"
    },
    {
     "BankLabel": "P0_Node0_Channel2_Dimm0",
     "Capacity": "8589934592",
     "DataWidth": "64",
     "Description": "Physical Memory",
     "DeviceLocator": "DIMMC1",
     "FormFactor": "8",
     "Manufacturer": "Micron Technology",
     "MemoryType": "0",
     "Name": "Physical Memory",
     "PartNumber": "9ASF1G72PZ-2G6D1",
     "SerialNumber": "1FE2773F",
     "Speed": "2667",
     "Tag": "Physical Memory 2",
     "TotalWidth": "72",
     "TypeDetail": "8320"
    },
    {
     "BankLabel": "P0_Node0_Channel3_Dimm0",
     "Capacity": "8589934592",
     "DataWidth": "64",
     "Description": "Physical Memory",
     "DeviceLocator": "DIMMD1",
     "FormFactor": "8",
     "InterleaveDataDepth": "0",
     "InterleavePosition": "0",
     "Manufacturer": "Micron Technology",
     "MemoryType": "0",
     "Name": "Physical Memory",
     "PartNumber": "9ASF1G72PZ-2G6D1",
     "SerialNumber": "1FE2776D",
     "Speed": "2667",
     "Tag": "Physical Memory 3",
     "TotalWidth": "72",
     "TypeDetail": "8320"
    },
    {
     "BankLabel": "P0_Node0_Channel4_Dimm0",
     "Capacity": "8589934592",
     "DataWidth": "64",
     "Description": "Physical Memory",
     "DeviceLocator": "DIMME1",
     "FormFactor": "8",
     "Manufacturer": "Micron Technology",
     "MemoryType": "0",
     "Name": "Physical Memory",
     "PartNumber": "9ASF1G72PZ-2G6D1",
     "SerialNumber": "1FE277A4",
     "Speed": "2667",
     "Tag": "Physical Memory 4",
     "TotalWidth": "72",
     "TypeDetail": "8320"
    },
    {
     "BankLabel": "P0_Node0_Channel5_Dimm0",
     "Capacity": "8589934592",
     "DataWidth": "64",
     "Description": "Physical Memory",
     "DeviceLocator": "DIMMF1",
     "FormFactor": "8",
     "Manufacturer": "Micron Technology",
     "MemoryType": "0",
     "Name": "Physical Memory",
     "PartNumber": "9ASF1G72PZ-2G6D1",
     "SerialNumber": "1FE2777E",
     "Speed": "2667",
     "Tag": "Physical Memory 5",
     "TotalWidth": "72",
     "TypeDetail": "8320"
    },
    {
     "BankLabel": "P0_Node0_Channel6_Dimm0",
     "Capacity": "8589934592",
     "DataWidth": "64",
     "Description": "Physical Memory",
     "DeviceLocator": "DIMMG1",
     "FormFactor": "8",
     "Manufacturer": "Micron Technology",
     "MemoryType": "0",
     "Name": "Physical Memory",
     "PartNumber": "9ASF1G72PZ-2G6D1",
     "SerialNumber": "1FE27810",
     "Speed": "2667",
     "Tag": "Physical Memory 6",
     "TotalWidth": "72",
     "TypeDetail": "8320"
    },
    {
     "BankLabel": "P0_Node0_Channel7_Dimm0",
     "Capacity": "8589934592",
     "DataWidth": "64",
     "Description": "Physical Memory",
     "DeviceLocator": "DIMMH1",
     "FormFactor": "8",
     "Manufacturer": "Micron Technology",
     "MemoryType": "0",
     "Name": "Physical Memory",
     "PartNumber": "9ASF1G72PZ-2G6D1",
     "SerialNumber": "1FE27787",
     "Speed": "2667",
     "Tag": "Physical Memory 7",
     "TotalWidth": "72",
     "TypeDetail": "8320"
    }
   ],
   "osinfo": {
    "BootDevice": "\\Device\\HarddiskVolume2",
    "BuildNumber": "17763",
    "BuildType": "Multiprocessor Free",
    "Caption": "Microsoft Windows Server 2019 Datacenter",
    "CodeSet": "1252",
    "CountryCode": "1",
    "CreationClassName": "Win32_OperatingSystem",
    "CSCreationClassName": "Win32_ComputerSystem",
    "CSName": "xxxxxx",
    "CurrentTimeZone": "-240",
    "DataExecutionPrevention_32BitApplications": "TRUE",
    "DataExecutionPrevention_Available": "TRUE",
    "DataExecutionPrevention_Drivers": "TRUE",
    "DataExecutionPrevention_SupportPolicy": "3",
    "Debug": "FALSE",
    "Distributed": "FALSE",
    "EncryptionLevel": "256",
    "ForegroundApplicationBoost": "2",
    "InstallDate": "20190128183307.000000-240",
    "LastBootUpTime": "20200423182543.500000-240",
    "Locale": "0409",
    "Manufacturer": "Microsoft Corporation",
    "MaxNumberOfProcesses": "4294967295",
    "MUILanguages": "{en-US}",
    "Name": "Microsoft Windows Server 2019 Datacenter|C:\\Windows|\\Device\\Harddisk0\\Partition4",
    "NumberOfLicensedUsers": "0",
    "NumberOfProcesses": "153",
    "NumberOfUsers": "14",
    "OperatingSystemSKU": "8",
    "OSArchitecture": "64-bit",
    "OSLanguage": "1033",
    "OSProductSuite": "400",
    "OSType": "18",
    "PortableOperatingSystem": "FALSE",
    "Primary": "TRUE",
    "ProductType": "2",
    "RegisteredUser": "Windows User",
    "SerialNumber": "00430-70311-xxxxx-xxxxx",
    "ServicePackMajorVersion": "0",
    "ServicePackMinorVersion": "0",
    "SizeStoredInPagingFiles": "19922944",
    "Status": "OK",
    "SuiteMask": "400",
    "SystemDevice": "\\Device\\HarddiskVolume4",
    "SystemDirectory": "C:\\Windows\\system32",
    "SystemDrive": "C:",
    "Version": "10.0.17763",
    "WindowsDirectory": "C:\\Windows"
   },
   "partitions": [
    {
     "BlockSize": "512",
     "Bootable": "FALSE",
     "BootPartition": "FALSE",
     "Description": "GPT: Basic Data",
     "DeviceID": "Disk #1",
     "DiskIndex": "Partition #0",
     "ErrorCleared": "1",
     "InstallDate": "0",
     "NumberOfBlocks": "Disk #1",
     "PNPDeviceID": "Partition #0",
     "PowerManagementCapabilities": "3906994176",
     "RewritePartition": "TRUE",
     "Status": "2000381018112",
     "StatusInfo": "16777216"
    },
    {
     "BlockSize": "512",
     "Bootable": "FALSE",
     "BootPartition": "FALSE",
     "Description": "GPT: Unknown",
     "DeviceID": "Disk #0",
     "DiskIndex": "Partition #0",
     "ErrorCleared": "0",
     "InstallDate": "0",
     "NumberOfBlocks": "Disk #0",
     "PNPDeviceID": "Partition #0",
     "PowerManagementCapabilities": "1021952",
     "RewritePartition": "FALSE",
     "Status": "523239424",
     "StatusInfo": "1048576"
    },
    {
     "BlockSize": "512",
     "Bootable": "TRUE",
     "BootPartition": "TRUE",
     "Description": "GPT: System",
     "DeviceID": "Disk #0",
     "DiskIndex": "Partition #1",
     "ErrorCleared": "0",
     "InstallDate": "1",
     "NumberOfBlocks": "Disk #0",
     "PNPDeviceID": "Partition #1",
     "PowerManagementCapabilities": "202752",
     "RewritePartition": "TRUE",
     "Status": "103809024",
     "StatusInfo": "524288000"
    },
    {
     "BlockSize": "512",
     "Bootable": "FALSE",
     "BootPartition": "FALSE",
     "Description": "GPT: Basic Data",
     "DeviceID": "Disk #0",
     "DiskIndex": "Partition #2",
     "ErrorCleared": "0",
     "InstallDate": "2",
     "NumberOfBlocks": "Disk #0",
     "PNPDeviceID": "Partition #2",
     "PowerManagementCapabilities": "1947953152",
     "RewritePartition": "TRUE",
     "Status": "997352013824",
     "StatusInfo": "644874240"
    },
    {
     "BlockSize": "512",
     "Bootable": "FALSE",
     "BootPartition": "FALSE",
     "Description": "GPT: Basic Data",
     "DeviceID": "Disk #2",
     "DiskIndex": "Partition #0",
     "ErrorCleared": "2",
     "InstallDate": "0",
     "NumberOfBlocks": "Disk #2",
     "PNPDeviceID": "Partition #0",
     "PowerManagementCapabilities": "937666560",
     "RewritePartition": "TRUE",
     "Status": "480085278720",
     "StatusInfo": "16777216"
    },
    {
     "BlockSize": "512",
     "Bootable": "TRUE",
     "BootPartition": "TRUE",
     "Description": "Installable File System",
     "DeviceID": "Disk #3",
     "DiskIndex": "Partition #0",
     "ErrorCleared": "3",
     "InstallDate": "0",
     "NumberOfBlocks": "Disk #3",
     "PNPDeviceID": "Partition #0",
     "PowerManagementCapabilities": "1953520065",
     "RewritePartition": "TRUE",
     "Status": "1000202273280",
     "StatusInfo": "32768"
    }
   ]
  },
  "identifiers": {
   "bios_date": "20181004000000.000000+000",
   "bios_vendor": "American Megatrends Inc.",
   "bios_version": "1.0c",
   "board_name": "H11SSL-NC",
   "board_serial": "VM186S0xxxxx",
   "board_vendor": "Supermicro",
   "board_version": "1.01",
   "product_uuid": "00000000-0000-0000-0000-AC1F6BAD0218"
  }
 },
 "pendingReboot": null,
 "hash": =*** removed ***"

**Comment by PathfinderNetworks** [comment] 2020-04-25 23:38
One other question, is it possible to pull and display more system information?  Such as the CPU make/model, GPU make/model, hard drive/SSD make and model, etc?

**Comment by krayon007** [comment] 2020-04-26 00:38
@PathfinderNetworks, I will look into the info you mentioned. If I do, it will probably be on Windows only, as I wasn't able to get nearly as much info from Linux.

**Comment by krayon007** [comment] 2020-04-26 00:39
Thinking outloud, I think the easiest way to get the information is to do a bus enumeration, as I remember a while ago, I had some test code where I pulled information from the Windows Device manager... I'm pretty sure there's metadata in there about the CPU/HDD/GPU, etc...

**Comment by krayon007** [comment] 2020-04-26 00:40
If I do that, I may just expose a bunch of JSON for all the installed devices it finds...

**Comment by krayon007** [comment] 2020-04-26 04:58
Ok, I used the same method to grab the other data, to obtain information about GPU make/model and Storage device make/model... It will be in the next windows agent update... It'll be in the sysinfo console command... @Ylianst  will be able to modify the UI for the details tab, to reflect the pertinent info.

**Comment by krayon007** [comment] 2020-04-27 00:48
Changes are live in MeshCentral_v0.5.15 (at least for sysinfo), give it a whirl, and see if you see the extra fields. I got it working for both linux and windows... For linux, HDD enumeration requires lshw, which I found to be already present on many of my installations. If its not there, it will just omit the data for HDD. But I found the CPU and GPU data was available on everything I threw at it, except for Pi, because Pi doesn't dmi)

**Comment by PathfinderNetworks** [comment] 2020-04-27 02:17
I just updated to 0.5.15 and, once the agents updated, I can now see the additional CPU, drive, and GPU data.  Thanks!

 "cpu": [
    {
     "Caption": "AMD64 Family 23 Model 1 Stepping 2",
     "DeviceID": "CPU0",
     "Manufacturer": "AuthenticAMD",
     "MaxClockSpeed": "2400",
     "Name": "AMD EPYC 7351P 16-Core Processor",
     "SocketDesignation": "CPU"
    }
   ],
   "gpu": [
    {
     "CurrentHorizontalResolution": "1280",
     "CurrentVerticalResolution": "1024",
     "Name": "ASPEED Graphics Family(WDDM)"
    }
   ],
   "drives": [
    {
     "Caption": "LSI Logical Volume SCSI Disk Device",
     "DeviceID": "\\\\.\\PHYSICALDRIVE1",
     "Model": "LSI Logical Volume SCSI Disk Device",
     "Partitions": "1",
     "Size": "1990114721280"

**Comment by Ylianst** [comment] 2020-04-27 02:30
The CPU, GPU and Storage information will be in the "Details" tab in the next version. just checking that in now.

**Comment by amenolo** [comment] 2020-04-27 07:18
Working fine under VMs as well!

**Comment by PathfinderNetworks** [comment] 2020-04-29 04:20
I just updated to 0.5.17 and see this data is now in the Details tab. Thank you! This is very helpful.

**Closed** 2020-05-02 16:45 UTC
Labels: Fixed - Confirm & Close, bug
