### ISSUE TITLE
Agent on Windows Server 2016: BSOD after login

### ISSUE THREAD

**Issue by energywave** [Ylianst/MeshCentral#1949] opened 2020-11-04 16:01 UTC
Hello,
the problem happened last time with MeshCentral ver. 0.6.76 but happened other two time on that server with previous versions too.
I'm trying to streamline my actions to let you reproduce or at least undersand and guess what's the problem could be.

- I've connected to Desktop on a Windows Server 2016 with MeshCentral
- It presented me two sessions: a Console and an RDP session.
- I've clicked on Console.
- The login screen appeared.
- I've inserted the password and logon correctly.
- Then the desktop sharing of MeshAgent stops working (for the already known bug) and usually I disconnect and reconnect to view again the desktop.
- I disconnected but could not reconnect for some minutes.
- When I reconnected I could login correctly with same method as above.
- I inspected Windows events to understand what happened and I've seen that serve had a BSOD and restarted.

I cannot be sure that this issue is related to MeshAgent but I highly suspect it.

This is the data that BlueScreenView extracts from the MEMORY.DMP file:
![BlueScreenView](https://user-images.githubusercontent.com/2051567/98133963-8477df00-1ebe-11eb-8532-3a2d1709f2e5.PNG)

This is some info about the server (that's a virtual server, I believe on VMWARE):
![InkedSystem_LI](https://user-images.githubusercontent.com/2051567/98134256-db7db400-1ebe-11eb-8448-63157b1f92b7.jpg)

I hope that you have some hints. This is a customer production server and I cannot do what tests I want... But if you have something to test I can try to...

Thank you in advance 👍
Henrik

**Comment by krayon007** [comment] 2020-11-04 16:17
Are you able to send me or ylian that minidump file? I can try to load it and see if it tells me what the agent was doing at the time.

**Comment by energywave** [comment] 2020-11-04 16:54
Sure! Can you provide me a private address where to send it?

**Comment by krayon007** [comment] 2020-11-04 17:53
> Sure! Can you provide me a private address where to send it? (yeah, I guess the mail on your github profile, do you confirm?)

Sure, you can email it to the address in my git profile:
`git.bryan.roe@techsavvydude.com`

**Comment by krayon007** [comment] 2020-11-04 17:56
Also, if you are running the server on VMWare, do you happen to have the vmx configuration file you are using? I happen to use VMWare for most of my testing, so I can try to setup my VMWare configuration to match yours as closely as possible. (What version of VMWare are you running?)

**Comment by energywave** [comment] 2020-11-05 11:08
Here I am. I've sent you the mail with a wetransfer link to download a 7zipped file of the minidump.
Sorry, I cannot tell you VMWARE details as the server is not my property so I have no control on it. Furthermore my happy would not be so happy to know that the server crashed due to a software I'ìve installed there... So I cannot ask him the details you've asked, sorry.
If that can help you this is vmware tools screenshot with version numeber:
![image](https://user-images.githubusercontent.com/2051567/98233580-8e9dea00-1f5f-11eb-8969-62b52782d08a.png)

Thank you for your interest 👍

**Comment by si458** [comment] 2024-01-16 15:19
duplicate of #1597

**Closed by si458** 2024-01-16 15:19 UTC
Labels: bug
