### ISSUE TITLE
Avast and Windows UAC are detecting virus and block

### ISSUE THREAD

**Issue by postmanpoland** [Ylianst/MeshCentral#4773] opened 2022-11-16 20:12 UTC
Good Evening
Last week i tried to install both of applications: server and client on 12 machines. Avast and Windows UAC showed me a middle finger for Both of them. Avast placed the files in quarantine and did not allow them to be installed. Windows UAC showed the Smart Screen and additionally blocked the installation of files. Of course, I managed to solve the problem without any problems. The average computer user and corporate employee is not able to install the program. I can't email the program installer or download link to anyone because the customers won't install it on their computer.
I had a problems on:
-Windows 7 Home, Pro x32,x64
-Windows 10 Home, Pro x64
-Windows 11 Home, Pro x64
---
![mesh_avast1](https://user-images.githubusercontent.com/118392361/202284314-a4f83abc-304a-4c6e-b370-f709746e32d1.png)

![mesh_avast2](https://user-images.githubusercontent.com/118392361/202284351-05a669a6-bcc0-4eb0-af62-85c14ddfde1b.png)

tag:meshcentral avast, meshcentral antivirus uac, meshagent, meshcmd, meshservice, meshagent64, meshagent32

**Comment by mschubeck-redux** [comment] 2022-11-16 22:44
This is not exactly a bug.  Assuming you didn't download anything from a third party, you need to whitelist the executables and the directories where the agents are installed in Avast and Windows Defender.

**Comment by PathfinderNetworks** [comment] 2022-11-16 23:29
This is a known issue.  The only way I've been able to work around this is to purchase a code signing certificate and use that to sign my agents.  I also had to customize the agent using my own logo and branding.  Lastly, I also had to to contact Avast (I'm an Avast partner and use Avast CloudCare on all of my customers devices) and have them whitelist my signed and branded agent.  
After doing all of that it is no longer being detected as a virus or PUP.  At least for now...

**Comment by postmanpoland** [comment] 2022-11-17 09:37
> This is not exactly...

Thank You.
For many customers who expect remote assistance, who have to install the program themselves, this is a huge problem and they cannot cope with it. An example scenario: I have been working in a computer service for 25 years and it often happens that a client calls and asks for remote help, I tell him to install Meshcentral and there is an unsolvable problem :)

**Comment by postmanpoland** [comment] 2022-11-17 09:51
>The only way I've been able to work around this is to purchase a code signing certificate and use that to sign my agents<

Thank You. Of course, this is a solution, but the idea of ​​open source, free software makes no little sense :(
>Lastly, I also had to to contact Avast...<

Me too. I informed them about this fact, maybe they will find a solution. Thank you.

**Comment by vithusel** [comment] 2022-11-28 20:51
> 

Sorry for replying to a old topic. The issue is Antiviruses are not wrong to block MeshCentral. Its scans the capabilities of MeshCentral and can see it allows what it would think is a back door into peoples machines. The problem with MeshCentral in its raw uneditied client is that it can indeed be used for nefarious purposes. It doesnt take many people using MeshCentral for harmful uses before AV's start blocking it by default. As a admin i would definitely want users machines to block MeshCentral as if it didnt anyone could ask a end user to install it and gain a easy backdoor. In my deployments i either manually install it myself or i push it via GPO to save myself the hassle. Our AV systems are set to automatically trust the agent. When it comes to clients who's machines i dont manage i typically use Quick Assist which is a built in windows assist tool (very easy to use and built into Win 11 & 10 now) for the first connection. Then i set it up myself.

**Comment by postmanpoland** [comment] 2022-11-29 08:50
> > 
> 
> Sorry for ...>

Thank you very much for your detailed explanation and advice. Kind regards

**Comment by dinger1986** [comment] 2023-11-13 00:10
@si458 can close

**Comment by si458** [comment] 2023-11-13 00:20
closing as agreed, all AV ones will point to a discussion going forward, me thinks

**Closed by si458** 2023-11-13 00:20 UTC
Labels: bug
