### ISSUE TITLE
MeshCentral server crashing

### ISSUE THREAD

**Issue by PathfinderNetworks** [Ylianst/MeshCentral#292] opened 2019-06-10 01:09 UTC
I was out of town this weekend and just returned only to find that my MeshCentral (running 0.3.6-c) had crashed (not the Windows Server itself- just the MeshCentral server service).  I tried to restart the service and, while it started, I then got a certificate invalid error when loading the MeshCentral web page.  When viewing the certificate that is being loaded it says it's being issued by 'MeshCentralRoot-9822f3' but I am using LetsEncrypt for the SSL cert (which has been working since I implemented it about 6 months ago or so).  
 I had my web browser load the site anyway- and then get a 'Cannot GET /login' error message.  
When I view the mesherrors.txt file this is what I'm seeing:

-------- 6/8/2019, 1:08:04 AM ---- 0.3.6-c --------

C:\Program Files\Open Source\MeshCentral\node_modules\meshcentral\meshagent.js:750
                    parent.duplicateAgentsLog[obj.dbNodeKey] = { name: device.name, group: mesh.name, ip: [obj.remoteaddr], count: 1 };
                                                                                           ^

ReferenceError: mesh is not defined
    at completeAgentConnection3 (C:\Program Files\Open Source\MeshCentral\node_modules\meshcentral\meshagent.js:750:92)
    at C:\Program Files\Open Source\MeshCentral\node_modules\meshcentral\meshagent.js:699:13
    at newArguments.(anonymous function) (C:\Program Files\Open Source\MeshCentral\node_modules\nedb\lib\executor.js:29:17)
    at Cursor.execFn (C:\Program Files\Open Source\MeshCentral\node_modules\nedb\lib\datastore.js:484:12)
    at callback (C:\Program Files\Open Source\MeshCentral\node_modules\nedb\lib\cursor.js:126:19)
    at C:\Program Files\Open Source\MeshCentral\node_modules\nedb\lib\cursor.js:193:12
    at C:\Program Files\Open Source\MeshCentral\node_modules\nedb\lib\datastore.js:329:14
    at Object.async.eachSeries (C:\Program Files\Open Source\MeshCentral\node_modules\nedb\node_modules\async\lib\async.js:130:20)
    at C:\Program Files\Open Source\MeshCentral\node_modules\nedb\lib\datastore.js:323:11
    at fn (C:\Program Files\Open Source\MeshCentral\node_modules\nedb\node_modules\async\lib\async.js:582:34)
    at Immediate.<anonymous> (C:\Program Files\Open Source\MeshCentral\node_modules\nedb\node_modules\async\lib\async.js:498:34)
    at processImmediate (timers.js:637:19)

-------- 6/8/2019, 1:08:18 AM ---- 0.3.6-c --------

Unhandled rejection TypeError: Cannot read property 'CertificateTableAddress' of undefined
    at Object.module.exports.hashExecutableFile (C:\Program Files\Open Source\MeshCentral\node_modules\meshcentral\exeHandler.js:264:28)
    at Object.CreateMeshCentralServer.obj.updateMeshAgentsTable (C:\Program Files\Open Source\MeshCentral\node_modules\meshcentral\meshcentral.js:1470:32)
    at Object.CreateMeshCentralServer.obj.StartEx4 (C:\Program Files\Open Source\MeshCentral\node_modules\meshcentral\meshcentral.js:772:13)
    at CreateMeshCentralServer.obj.StartEx3 (C:\Program Files\Open Source\MeshCentral\node_modules\meshcentral\meshcentral.js:748:42)
    at C:\Program Files\Open Source\MeshCentral\node_modules\meshcentral\letsencrypt.js:101:21
    at tryCatcher (C:\Program Files\Open Source\MeshCentral\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Program Files\Open Source\MeshCentral\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Program Files\Open Source\MeshCentral\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Program Files\Open Source\MeshCentral\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Program Files\Open Source\MeshCentral\node_modules\bluebird\js\release\promise.js:694:18)
    at Promise._fulfill (C:\Program Files\Open Source\MeshCentral\node_modules\bluebird\js\release\promise.js:638:18)
    at Promise._resolveCallback (C:\Program Files\Open Source\MeshCentral\node_modules\bluebird\js\release\promise.js:432:57)
    at Promise._settlePromiseFromHandler (C:\Program Files\Open Source\MeshCentral\node_modules\bluebird\js\release\promise.js:524:17)
    at Promise._settlePromise (C:\Program Files\Open Source\MeshCentral\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Program Files\Open Source\MeshCentral\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Program Files\Open Source\MeshCentral\node_modules\bluebird\js\release\promise.js:694:18)

**Comment by PathfinderNetworks** [comment] 2019-06-10 01:25
I tried to restore a backup (created by autobackup) but cannot do so because one of the files, agentserver-cert-private.key is throwing a 'Error 0x80004005: Unspecified error' when trying to extract it from the zip file.  This is happening with every backup zip I'm trying.

**Comment by PathfinderNetworks** [comment] 2019-06-10 01:30
Fortunately I had a full copy of 0.3.5-x from my last server upgrade. I restored that entire folder. That allowed MeshCentral to run once again.  I then updated to 0.3.6-i and it's still running (for now).

**Comment by PathfinderNetworks** [comment] 2019-06-10 01:33
Interestingly enough, the zip files from autobackup running under 0.3.5-x (that were made when I was still running that version) extract correctly and without the error I mention above. The only difference, that I can see, is that these zip backups are in the default meshcentral-backup folder whereas the others I tried from 0.3.6-c were in a folder I had specified via the backup path statement in config.json.

**Comment by Ylianst** [comment] 2019-06-10 02:46
Arg! So the original exception reported above was fixed. As for the backup, not sure what happened, but I will test my backups this week, see if I can find a problem.

On a different note, I may want to give out what version I am using in MeshCentral.com, it's always quite a bit late, but it's a "stable" version.

**Comment by Ylianst** [comment] 2019-06-10 02:52
Duplicate of #280

**Closed by Ylianst** 2019-06-10 02:52 UTC
Labels: duplicate
