### ISSUE TITLE
Several of us getting black screens when connecting to desktops on 0.6.82

### ISSUE THREAD

**Issue by southeasterntech** [Ylianst/MeshCentral#1971] opened 2020-11-10 14:03 UTC
Several of us getting black screens when connecting to desktops on 0.8.82
Anyone else getting this?
![blackscreen](https://user-images.githubusercontent.com/45638572/98683921-97156c80-2333-11eb-973e-7cbccb9348f5.JPG)

**Comment by Ylianst** [comment] 2020-11-10 16:52
There is a possible fix for this that was added in version 0.6.80. The bug is that the first screen does not show, but changes to the display after that will show correctly.

**Comment by southeasterntech** [comment] 2020-11-10 17:12
Apologies Ylian, I mis-typed.  We're on version 0.6.8.2 with this issue, not 0.5.82
![image](https://user-images.githubusercontent.com/45638572/98707412-026c3800-234e-11eb-82bb-c7ad4c0b0a6e.png)

**Comment by Ylianst** [comment] 2020-11-10 21:14
If you update to 0.6.83 and add `"ignoreagenthashcheck": true` it should work around the problem. But working on root cause now. Everyone seeing this is likely using a reverse proxy.

**Comment by Ylianst** [comment] 2020-11-10 21:38
Published MeshCentral v0.6.84, update and let me know if that works.

**Comment by southeasterntech** [comment] 2020-11-11 17:59
All good! thanks!  you guy rock.

**Closed** 2020-11-12 06:54 UTC
Labels: Fixed - Confirm & Close, question
