### ISSUE TITLE
ANSI Escape codes flooding the terminal

### ISSUE THREAD

**Issue by phorcys420** [Ylianst/MeshCentral#4528] opened 2022-09-08 13:42 UTC
**Describe the bug**

**To Reproduce**
1. Go to an agent
2. Click on "Terminal"
3. Click on "Connect"
4. See unusable terminal window

**Expected behavior**
![image](https://user-images.githubusercontent.com/57866459/189135162-009c1a36-8c12-46b1-ba4c-3b433c9df2e9.png)

**Screenshots**

**Server Software (please complete the following information):**
- OS: Ubuntu 20.04
- Virtualization: Docker
- Network: LAN/WAN, reverse proxy (apache2 <-> caddy <-> meshcentral), ssl offload
- Version: 1.0.82
- Node: 18.8.0

**Client Device (please complete the following information):**
 - Device: Laptop
 - OS: Windows 10 21H2
 - Network: Local to Meshcentral
 - Browser: Firefox Developer Edition (105.0b8)

**Remote Device (please complete the following information):**
 - Device: Laptop
 - OS: Windows 10 10.0.17134.1304
 - Network: Local to Meshcentral
 - Current Core Version (if known): Aug 25 2022, 1360394467

**Additional context**
Same computer as in #4527

**Your config.json file**
```
{
   "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
   "settings": {
      "cert": "[...]",
      "sessionKey": "[...]",
      "port": 420,
      "aliasPort": 443,
      "redirPort": 80,
      "agentPong": 300,
      "tlsOffload": true,
      "selfUpdate": false,
      "allowFraming": false,
      "mongodb": "mongodb://mongodb:27017/mesh",
      "mongodbcol": "mesh",
      "webRTC": false,
      "desktopMultiplex": true,
      "mpsPort": 0,

      "maxInvalidLogin": {
         "time": 5,
         "count": 5,
         "cooloffTime": 10
      },

      "plugins": {
         "enabled": true
      }
   },
   "domains":{
      "": {
         "siteStyle": 2,

         "title":"[...]",
         "title2":"[...]",

         "auth":"ldap",
         "ldapUserName":"sAMAccountName",
         "ldapUserKey": "sAMAccountname",
         "ldapUserBinaryKey":"objectSid",
         "ldapUserEmail": "mail",
         "ldapUserRealname": "name",
         "ldapUserPhoneNumber": "ipPhone",
         "ldapOptions": {
            "url": "ldap://[...]",
            "bindDN": "[...]",
            "bindProperty": "userPrincipalName",
            "bindCredentials": "[...]",
            "reconnect": true,
            "searchBase": "[...]",
            "searchFilter":"(sAMAccountName={{username}})"
         },

         "certUrl": "https://[...]"
      }
   },
}
```

**Comment by krayon007** [comment] 2022-09-08 16:01
This is a duplicate of #4435

**Closed by krayon007** 2022-09-08 16:01 UTC
Labels: bug

**Comment by phorcys420** [comment] 2022-09-08 17:22
I didn't find that issue, sorry for the dupe !
