### ISSUE TITLE
Saved credentials not appearing between users

### ISSUE THREAD

**Issue by suiciety** [Ylianst/MeshCentral#6119] opened 2024-05-24 03:05 UTC
**Describe the bug**
This is another bug report around the issue fixed in #5994

While the credentials are now being saved they are still not available across users.

**To Reproduce**
1. Log in as one user
2. Click on for instance RDP connect
3. Enter in credentials and tick the 'save credentials' option
4. Log out and in as a different user

**Expected behavior**
Our config has the allowSavingDeviceCredentials set to true which should enable this function and allow all users to access saved credentials.

**Screenshots**

**Server Software (please complete the following information):**
 - OS: Ubuntu
 - Virtualization:  Azure
 - Network: p2p vpn
 - Version: 1.1.23
 - Node: 20.13.1

**Client Device (please complete the following information):**
 - Device: Any
 - OS: Any
 - Network: Any
 - Browser: Any

**Remote Device (please complete the following information):**
 - Device: Any
 - OS: Any
 - Network: Any
 - Current Core Version (if known): Any

**Your config.json file**
```
{
    "$schema": "https://raw.githubusercontent.com/Ylianst/MeshCentral/master/meshcentral-config-schema.json",
    "settings": {
        "cert": "***",
        "TLSOffload": "***",
        "trustedProxy": "***",
        "agentTimeStampServer": false,
        "webRTC": true,
        "selfUpdate": true,
        "amtManager": false,
        "wsCompression": true,
        "agentWsCompression": true,
        "compression": true,
        "MongoDb": "mongodb://127.0.0.1:27017/meshcentral",
        "_ignoreagenthashcheck": true
    },
    "domains": {
        "": {
            "title": "***",
            "loginPicture": "***",
            "titlePicture": "***",
            "trustedCert": true,
            "allowSavingDeviceCredentials": true,
            "loginfooter": "***",
            "nightMode": 1,
            "welcomePicture": "backgroundpeak.png",
            "_rootRedirect": "***",
            "unknownUserRootRedirect": "***",
            "_showPasswordLogin": false,
            "minify": true,
            "allowedOrigin": [
                "rmm.***",
                "*.***"
            ],
            "autoRemoveInactiveDevices": 190,
            "deviceSearchBarServerAndCilentName": true,
            "agentFileInfo": {
                "icon": "merici.ico",
                "fileDescription": "***",
                "productName": "***"
            },
            "agentCustomization": {
                "displayName": "***",
                "description": "***",
                "companyName": "***",
                "serviceName": "***",
                "image": "***",
                "installText": "***",
                "filename": "***",
                "backgroundColor": "#0e3468"
            },
            "ipkvm": true,
            "ssh": true,
            "userNameIsEmail": true,
            "newAccountEmailDomains": "***",
            "authStrategies": {
                "azure": {
                    "callbackurl": "https://***/auth-azure-callback",
                    "newAccounts": true,
                    "newAccountsUserGroups": [
                        "ugrp//***"
                    ],
                    "clientid": "***",
                    "clientsecret": "***",
                    "tenantid": "***"
                }
            },
            "meshMessengerTitle": "***t",
            "meshMessengerPicture": "***.png"
        }
    }
}
```

**Comment by si458** [comment] 2024-05-24 15:07
ok yes i can confirm this issue, will look into it over weekend as running out of time today

**Comment by si458** [comment] 2024-05-24 15:24
ok just had another quick look and this is not a bug but by design.

`allowSavingDeviceCredentials` should read `Allow users to save SSH, RDP, VNC device credentials on the server`

it is **not** used to share credentials between each user, but rather for each user to save there own credentials.

this is because the backend saves the credentials against the node and used the userid to identify which credentials to use

SO

if user1 saves generic creds,
then user2 saves his own creds,
when user3 says lets see creds,
which credentials would you use?

we would have to display a list of saved credentials, and by which user, then u select which creds to use and use them

so in theory what your asking for is actually a feature request, to allow another option like 
`allowSharingOfSavedCredentials: true`

that way when we see `allowSharingOfSavedCredentials == true` we can then display all credentials and u pick

rather than just displaying your own credentials

**Comment by si458** [comment] 2024-05-24 15:55
ive also spotted the `mstsc.html` page which is the Web-RDP should also pre-fill credentials but it doesnt.
this is because its using old code to look for `node.rdp.u` and `node.rdp.p` (user/pass)
but the new code saves data in `node.rdp[obj.userid].u` and `node.rdp[obj.userid].p` (user/pass)
**BUT it also clears legacy credentials**
```
delete node.rdp.u;
delete node.rdp.p;
```

**Comment by si458** [comment] 2024-06-03 11:21
duplicate feature request is here - https://github.com/Ylianst/MeshCentral/issues/5285
so will close this for now

**Closed by si458** 2024-06-03 11:21 UTC
Labels: enhancement
