### ISSUE TITLE
MeshCentral Assistant disappears in the system tray.

### ISSUE THREAD

**Issue by kuksabong** [Ylianst/MeshCentral#2694] opened 2021-05-26 11:41 UTC
When I download and run the MeshCentral Assistant file from the Invite page, the Assistant appears in the system tray for a while and then disappears.

OS version : Windows 10 Pro - 2004 [19041]
MeshCentral version: 0.8.48

![assistant](https://user-images.githubusercontent.com/6889244/119652581-3c6fd800-be61-11eb-95b8-98f84f043896.JPG)

**Comment by VINISHVV** [comment] 2021-05-26 12:40
@kuksabong - Can you post the debug log and OS version where the Assistant running.

**Comment by Ylianst** [comment] 2021-05-26 18:36
I am going to work now on adding a debug/crash log to MeshCentral Assistant. hopefully that will help debug issues in the future.

**Comment by Ylianst** [comment] 2021-05-26 20:21
If MeshCentral Assistant generated an "debug.log" file, please cut & paste the content of the file here so we can see the error.

The next version of MeshCentral Assistant will support running with `-debug` and will generate a detailed log like this:

```
13:15:PM.2334: ***** Starting MeshCentral Assistant *****
13:15:PM.3295: Starting built-in agent
13:15:PM.3545: MCAgent: LoadAgentCertificate() - Loaded existing certificate.
13:15:PM.3635: MCAgent: MSH MeshID: 0xEDBE1BE3771D69DF39D35DF97F7E9A6F7D75DB86F9D9EE3B735EBB7DB6B4E7971EF34D36EBB6B875CF3D7DED1EE7CD5C
13:15:PM.3645: MCAgent: MSH ServerID: D99362D5ED8BAEA8BF9E743B34B242256370C460FD66CB62373C6CFCB204D6D707403E396CF0EF6DC2B3A42F735135FD
13:15:PM.3645: MCAgent: MSH MeshServer: wss://central.mesh.meshcentral.com/agent.ashx
13:15:PM.3675: Found 2 background agent(s)
13:15:PM.3765: connectToAgent ~
13:15:PM.3814: MCAgent: Connecting to wss://central.mesh.meshcentral.com/agent.ashx
13:15:PM.3854: Mcagent_onStateChanged 1
13:15:PM.3854: WebSocket: Websocket Start, URL=wss://central.mesh.meshcentral.com/agent.ashx
13:15:PM.3954: WebSocket: Websocket noProxy
...
```

**Comment by rowds15** [comment] 2021-05-26 23:40
I have the same issue here is my debug.log
UnhandledExceptionEventSink: System.NullReferenceException: Object reference not set to an instance of an object.
   at MeshAssistant.MainForm..ctor(String[] args)
   at MeshAssistant.Program.Main(String[] args)
UnhandledExceptionEventSink: System.NullReferenceException: Object reference not set to an instance of an object.
   at MeshAssistant.MainForm..ctor(String[] args)
   at MeshAssistant.Program.Main(String[] args)
UnhandledExceptionEventSink: System.NullReferenceException: Object reference not set to an instance of an object.
   at MeshAssistant.MainForm..ctor(String[] args)
   at MeshAssistant.Program.Main(String[] args)
UnhandledExceptionEventSink: System.NullReferenceException: Object reference not set to an instance of an object.
   at MeshAssistant.MainForm..ctor(String[] args)
   at MeshAssistant.Program.Main(String[] args)
UnhandledExceptionEventSink: System.NullReferenceException: Object reference not set to an instance of an object.
   at MeshAssistant.MainForm..ctor(String[] args)
   at MeshAssistant.Program.Main(String[] args)
UnhandledExceptionEventSink: System.NullReferenceException: Object reference not set to an instance of an object.
   at MeshAssistant.MainForm..ctor(String[] args)
   at MeshAssistant.Program.Main(String[] args)

**Comment by kuksabong** [comment] 2021-05-27 10:04
I am also the same as the debug contents posted by rowds15.

**Comment by Ylianst** [comment] 2021-05-28 00:35
MeshCentral v0.8.49 is now published and has an improved MeshCentral Assistant. It includes a debug log, so if this problem still occurs, use -debug and send over the log. - Thanks.

![MC2-Assistant-DebugLog](https://user-images.githubusercontent.com/1319013/119913067-cd05f100-bf11-11eb-84d2-93188c466529.png)

**Comment by rowds15** [comment] 2021-05-28 00:50
Hi Ylianst,

updated to ver 0.8.49 and the issue still happening
debug log

10:48:AM.7132: ***** Starting MeshCentral Assistant *****
10:48:AM.7299: Checking for embedded MSH file
10:48:AM.7469: Set TLS 1.2
10:48:AM.7635: InitializeComponent()
10:48:AM.8135: Check for built-in agent
10:48:AM.8135: Starting built-in agent
10:48:AM.8634: MCAgent: LoadAgentCertificate() - Loaded existing certificate.
10:48:AM.8634: MCAgent: MSH MeshID: 0xF3179C79FF33EF5BF4A80588F08A06C21F91D616406ADF0E52A9C7E89E1F83AE7D1B6EC884370BFC1D4428AB9DEE1B98
10:48:AM.8634: MCAgent: MSH ServerID: 8D8ED7DC99FA1701D5CC03E206CDFFA3475CEBDA65496C01F22A57A877F68F2EA127DE0713DCBB65B9F17BED3DCA5A86
10:48:AM.8790: MCAgent: MSH MeshServer: wss://XXXXXXXXXX/agent.ashx
UnhandledExceptionEventSink: System.NullReferenceException: Object reference not set to an instance of an object.
   at MeshAssistant.MainForm..ctor(String[] args)
   at MeshAssistant.Program.Main(String[] args)

**Comment by Ylianst** [comment] 2021-05-28 04:58
Thank you. I see the problem, [it's faulting here](https://github.com/Ylianst/MeshCentralAssistant/blob/3c572e8b85fcc436b48be0cca7f41c0c23777195/MainForm.cs#L143). One workaround until I fix it is to run the basic MeshCentralAssistant.exe from `/node_modules/meshagent` once. Then, stop it and then run the MeshCentralAssistant.exe you downloaded that includes the device group.

I will have a fix for this in 2 days then I get back to work.

**Comment by energywave** [comment] 2021-05-28 09:58
I can confirm exact same behavior and content in debug.log on my installation too.

**Comment by Ylianst** [comment] 2021-05-30 17:22
Just published MeshCentral v0.8.50 with a fix for this. Let me know if it works.

**Comment by VINISHVV** [comment] 2021-05-30 17:56
Dear Ylian,

Getting below error while running latest Meshcentral Assistant.
_________________________________________________________________________________________
23:23:PM.6303: ***** Starting MeshCentral Assistant *****
23:23:PM.6771: Checking for embedded MSH file
23:23:PM.7863: Set TLS 1.2
23:23:PM.8019: InitializeComponent()
23:23:PM.8487: Check for built-in agent
23:23:PM.8487: Starting built-in agent
UnhandledExceptionEventSink: System.MissingMethodException: Method not found: 'System.Security.Cryptography.RSA System.Security.Cryptography.RSA.Create(Int32)'.
   at MeshAssistant.MeshCentralAgent.LoadAgentCertificate()
   at MeshAssistant.MeshCentralAgent..ctor(MainForm parent, String softwareName, String selfExecutableHashHex, Boolean debug)
   at MeshAssistant.MainForm..ctor(String[] args)
   at MeshAssistant.Program.Main(String[] args)

**Comment by Ylianst** [comment] 2021-05-30 18:06
The "RSA MissingMethodException" is going to be more complicated to fix. MeshCentral Assistant needs to create a self-signed certificate and this is not supported on older .NET frameworks. If you can update your computer to .NET 4.7, it should work. If not, I will need to find a way around this.

**Comment by VINISHVV** [comment] 2021-05-30 18:36
Thanks Ylian.
.Net 4.7 resolved my issues.

**Comment by Ylianst** [comment] 2021-05-30 22:47
I just checked in a new fix for MeshCentral Assistant that should allow it to work even if you don't have .NET 4.7. Will be in the next version of MeshCentral v0.8.51.

**Comment by paolor1965** [comment] 2021-05-31 12:59
H
[debug.log](https://github.com/Ylianst/MeshCentral/files/6570370/debug.log)
i, I have updated meshcentral to 0.8.50 but I still have the same behavior with meshcentralassistant. (when I click on remote control, crash)
 I specify that the agent installed works perfectly.
For the sake of completeness, always running the meshcentralassistant of another meshcentral test installation on the same station I do not encounter the problem when I take remote control

**Comment by Ylianst** [comment] 2021-05-31 17:47
@paolor1965 Thank you for posting the error log, this is very useful. It is a holiday today in the US, but I will work on fixing this tomorrow.

**Comment by paolor1965** [comment] 2021-05-31 17:58
thanks, i just try to be helpful

**Comment by Ylianst** [comment] 2021-06-01 09:43
Published MeshCentral v0.8.51 with a fix for @paolor1965 reported issue. Let me know if it works.

**Comment by paolor1965** [comment] 2021-06-01 11:40
hi, i just tested version 0.8.51 with meshcentralassistant and now it works.
I can select direct connection, or through the agent installed, and the nice thing that if I choose direct connection I can also use a different meshcentral server than the agent's one
Thank you again. I have a question: I started a while ago, in my spare time, to translate meshcentral into Italian, using a translate.json file which now refers to an old version. It is possible to import my translations into the current version automatically and continue the work
Thanks and bye

**Comment by energywave** [comment] 2021-06-01 13:35
> I started a while ago, in my spare time, to translate meshcentral into Italian

Hey Paolo, I'm also translating in Italian in my spare time!!! It would be better to coordinate ourselves. We can somehow merge the file and continue on that. One of us continue from the beginning and the other from the end. If it's ok for you.
At the end we can revise the translations by the other so to give Ylian a good quality translation.
If it's ok for you the problem is... how to merge the files?


> It is possible to import my translations into the current version automatically and continue the work

I think that using the included tool in my account - localization settings - help translate meshcentral the file is automatically updated to the last version, can you confirm that @Ylianst ?



> Published MeshCentral v0.8.51 with a fix for @paolor1965 reported issue. Let me know if it works.

All up and running here too! Good work!

**Comment by paolor1965** [comment] 2021-06-01 14:41
Hi, actually I've already gotten to the letter N. It shouldn't take long, time permitting. As soon as finished I can share the file for corrections.
I used google translator a lot

**Comment by Ylianst** [comment] 2021-06-01 17:52
For language translation of the web site, place your latest "translate.json" in "node_modules/meshcentral/translate" then from that folder run the following:

```
node translate.js translateall
```

Then, refresh the web page and your translation should be there. If you are running NodeJS in production mode, you may need to restart the server.

**Comment by paolor1965** [comment] 2021-06-01 19:25
ok and then can I send you my translate.js file by mail?

**Comment by Ylianst** [comment] 2021-06-01 20:31
Yes, send me the translate.json, [here is my contact info](https://www.meshcommander.com/contact-information). I will add it to the next version.

**Comment by Ylianst** [comment] 2021-06-03 02:54
By the way, I will gladly accept partial translations. I will close this issue since it's very likely fixed. Please don't hesitate to open a new issue if there are any issues with Assistant.

**Closed by Ylianst** 2021-06-03 02:54 UTC
Labels: Fixed - Confirm & Close, bug
