### ISSUE TITLE
Mesh agent not starting anymore

### ISSUE THREAD

**Issue by Allowee** [Ylianst/MeshCentral#1564] opened 2020-06-30 09:58 UTC
A few mesh agents stopped working after updating to the latest version (mainly windows server OS) 

Error in the event viewer
"The Mesh Agent background service service is marked as an interactive service.  However, the system is configured to not allow interactive services.  This service may not function properly."

 Although this is a Windows setting, it did not have this problem before.

**Comment by Allowee** [comment] 2020-06-30 14:33
Further investigation:

When I manually start the service again it will download the new meshagent (seen in the trace tab)
It will disconnect (assuming to update the client) and than the error about the interactive service can be seen in the event log and the service is stopped again.

When I replace the old agent with the new one (meshagent.update.exe) the error is instant and no connection is made.

The old agent is from 24 may 2020.

**Comment by krayon007** [comment] 2020-06-30 16:22
Which windows version are you seeing this with?

**Comment by Allowee** [comment] 2020-06-30 17:06
Seems 32bit agent related
Windows Server 2016 Standard - 1607 [Version 10.0.14393] 32bit agent
Windows Server 2016 Essentials - 1607 [Version 10.0.14393] 32bit agent
Windows Server 2012 R2 Foundation [Version 6.3.9600] 32bit agent
Windows Embedded Standard [Version 6.1.7601] 32bit agent

I tried to uninstall and fresh install the latest 64bit agent and it seems to work on the 64bit OS'es
On the same OS the 32bit agent does not install, only the error in the event log.

On the 32bit OS I tried the same uninstall and fresh install, not working.

Found an error message as well, hope this helps
![image](https://user-images.githubusercontent.com/55733884/86155477-c1912680-bb04-11ea-9292-54a4fa7f03c1.png)

**Comment by Ylianst** [comment] 2020-06-30 18:07
Just took down MeshCentral v0.5.76, working on new release now.

**Comment by krayon007** [comment] 2020-06-30 18:54
This is fixed with MeshCentral v0.5.77
It was caused by one of the validation checks failing on 32 bit.

**Comment by Allowee** [comment] 2020-06-30 18:54
Wow that was quick. The new 32bit agent is working as expected now.

**Closed** 2020-06-30 18:54 UTC
Labels: bug
