### ISSUE TITLE
CERT URL

### ISSUE THREAD

**Issue by blaine07** [Ylianst/MeshCentral#4891] opened 2022-12-31 15:47 UTC
Morning,

Is it possible to define more than one "certUrl"? I am doing some split horizon DNS and occasionally running into "Agent reported web cert hash:XXXX" issue depending on if accessing MeshCentral internally or externally. For now I have "ignoreagenthashcheck": true, but I feel like there should be a easier way to accomplish what I need without circumventing security?

Internally I have mesh.myDomain.net > Nginx Proxy Manager > MeshCentral
Externally I have Cloudflare Tunnel(Argo) pointing to a different Nginx Proxy Manager Manager > MeshCentral

I realize I could probably use the same Nginx Proxy Manager instance but the way I am routing things I would prefer keep the outside >in traffic on a different NPM. 

Also, in config.json I am defining certURL like ""certUrl": "https://192.168.1.3:443"" is that the correct syntax? I mean, as in having the 443 at the end?

Thanks You!

**Comment by silversword411** [comment] 2022-12-31 20:55
Why don't you just make sure both reverse proxies have valid certs?

**Comment by blaine07** [comment] 2022-12-31 21:32
> Why don't you just make sure both reverse proxies have valid certs?

They both do but since reverse proxies different certs the hash is different? When doing reverse proxy also not sure if TLS offload should be on or off?

Have another instance of MeshCentral I am not doing split dns with and it works fine. 

Whatever is wrong is undoubtedly my own idiocracy lol

**Comment by blaine07** [comment] 2022-12-31 21:41
![EC265034-0FAA-4D69-900F-3CA8A2B73FEA](https://user-images.githubusercontent.com/63940698/210156116-2566e1b4-d571-4390-b8a6-262c73a2b182.jpeg)

**Comment by PrplHaz4** [comment] 2022-12-31 22:35
> > Why don't you just make sure both reverse proxies have valid certs?
> 
> They both do but since2 different reverse proxies different certs the hash is different? When doing reverse proxy also not sure if TLS offload should be on or off? Or if I am using trustedproxies line correctly.
> 
> Have another instance of MeshCentral I am not doing split dns with and it works fine.
> 
> Whatever is wrong is undoubtedly my own idiocracy lol

As far as I know, your assessment is correct.  See my feature request here: https://github.com/Ylianst/MeshCentral/issues/3798#issue-1180080339

CF Proxy and Internal Proxy are returning different hashes, so the server will only have one valid hash per domain and agents can only connect to one or the other.

**Comment by blaine07** [comment] 2022-12-31 23:05
> > > Why don't you just make sure both reverse proxies have valid certs?
> > 
> > 
> > They both do but since2 different reverse proxies different certs the hash is different? When doing reverse proxy also not sure if TLS offload should be on or off? Or if I am using trustedproxies line correctly.
> > Have another instance of MeshCentral I am not doing split dns with and it works fine.
> > Whatever is wrong is undoubtedly my own idiocracy lol
> 
> As far as I know, your assessment is correct. See my feature request here: [#3798 (comment)](https://github.com/Ylianst/MeshCentral/issues/3798#issue-1180080339)
> 
> CF Proxy and Internal Proxy are returning different hashes, so the server will only have one valid hash per domain and agents can only connect to one or the other.

Solution proposed appears to be exactly what my issue is/would solve my issue. Guess we’ll see what happens there. 

Thanks.

**Comment by si458** [comment] 2024-01-15 22:12
closing as duplicate of #3798

**Closed by si458** 2024-01-15 22:12 UTC
Labels: question
