### ISSUE TITLE
Energy state and list see computer

### ISSUE THREAD

**Issue by desarrollocdb** [Ylianst/MeshCentral#1378] opened 2020-05-19 18:13 UTC
Hello, is this expected behavior? I thought it refers to the ignition timing. This computer has not been turned on today.

![image](https://user-images.githubusercontent.com/26174637/82362820-8dd5c380-99d2-11ea-9a9b-20f94466583a.png)

Is there a way to display a list of the last time the computers were seen and with their ip?

**Comment by Ylianst** [comment] 2020-05-20 18:54
Hi. For the last agent connection time and IP address, take a look here:

![image](https://user-images.githubusercontent.com/1319013/82485634-95f43880-9a90-11ea-9903-da474434f53b.png)

For the timeline, that is not good. What version of MeshCentral are you using?

**Comment by desarrollocdb** [comment] 2020-05-20 18:59
Hi. the version is: 0.4.9-k

is there a way to generate a report from various computers about the ip and the date of the last connection?

**Comment by Ylianst** [comment] 2020-05-20 20:48
This bug is a duplicate of #1088 and was fixed in MeshCentral v0.5.0-y.

**Closed by Ylianst** 2020-05-20 20:48 UTC
Labels: bug

**Comment by desarrollocdb** [comment] 2020-05-27 13:55
Hello, I still have problems with the power display even after updating.

![image](https://user-images.githubusercontent.com/26174637/83028880-9f812180-9ff7-11ea-8872-c64af20e534e.png)

![image](https://user-images.githubusercontent.com/26174637/83029024-c9d2df00-9ff7-11ea-8634-70334534270d.png)
