### ISSUE TITLE
Agent name does not update if comptuer renamed

### ISSUE THREAD

**Issue by sorvani** [Ylianst/MeshCentral#143] opened 2019-03-22 15:06 UTC
With my current solutoins , I install very early in the PC setup process. typically before it is known what name will be assigned to the device.

But once I rename the device and deploy it, it still shows the original name here. This should update, or at least be an option to update.
![image](https://user-images.githubusercontent.com/3302372/54832518-54001480-4c8a-11e9-9ede-17313a942817.png)

It obviously knows the new name.
![image](https://user-images.githubusercontent.com/3302372/54832642-89a4fd80-4c8a-11e9-8eeb-88c3c3ad5d26.png)

**Comment by mschubeck** [comment] 2019-03-22 15:40
To the bottom-right of the device name is an edit icon. Click that and you are able to change the device name anytime you wish.  Right now, there is no mechanism in place within the software to change it automatically, and I suspect it won't be included.  Since the name shown in bold and the hostname can be different depending on your needs, I think it will stay as an editable field that uses the hostname by default unless otherwise changed.

**Comment by sorvani** [comment] 2019-03-22 16:09
@mschubeck  That is a horrible method of control for hundreds or thousands of devices.
ScreenConnect has a solid method for this. They let you choose what you want to happen.
![image](https://user-images.githubusercontent.com/3302372/54836790-f0c6b000-4c92-11e9-8dbb-ebc15a7b0594.png)

**Comment by jsastriawan** [comment] 2019-03-22 16:12
I am just curious, MeshAgent typically send machine info early after successful connection. Would softdisconnect the agent updates the hostname?

**Comment by sorvani** [comment] 2019-03-22 16:22
The MeshCentral `Name` field in the detail is the hostname, and is updated on connection. No reason that the display name could not also be updated with an option such as ScreenConnect offers (per device, defaulting to use machine name).

**Comment by mschubeck** [comment] 2019-03-22 16:38
I'm sure the developers will add it as a feature request, or you could write a fix and submit it.  All I did was explain the current usage; the developers will respond as needed.

If you need an immediate workaround for your hundreds of thousands of machines, perhaps adjust your own workflow so that the agent is installed AFTER you perform the change to the hostname.  As I stated, right now this is by design so that the hostname and the display name can be kept different if required.  The feature request would be to allow the user to display the hostname instead.

Personally, I have some mesh groups that have multiple machines with the same name, so I don't particularly mind that they can be set differently.  However, I am used to most RMM platforms having the 2 tied together, so I understand where you are coming from as well.  Just remember that this isn't exactly a complete replacement for any RMM software package yet, if ever.

**Comment by Ylianst** [comment] 2019-03-23 12:43
Hi. In the "My Devices" screen, you can click the "OS Name" checkbox to display the operating system names instead of the server name for all devices. I could add a device group option that makes the server name sync with the client name, or make it so that for a given group, the client name it always used.

**Comment by Ylianst** [comment] 2019-03-29 17:49
I am on vacation now until next Wednesday, but next time I get a chance, I will add an feature in the device group to sync the device hostname with the server name.

**Comment by Ylianst** [comment] 2019-04-06 04:33
Just published MeshCentral v0.3.1-y with a new feature that allows you to opt to use the device hostname as the server name. Click on a group, click on the edit icon in the "Features" line and select "Sync server device name to hostname". After this, each time a device connects, it will update the device name. Let me know if that works for you.

![MC2-SyncHostName](https://user-images.githubusercontent.com/1319013/55664873-6a5db280-57ea-11e9-90f3-6ded74fae4d5.png)

**Comment by Ylianst** [comment] 2019-04-12 00:14
I am going to close this since I am pretty sure the issue is solved with the new sync feature. Please re-open if needed.

**Closed by Ylianst** 2019-04-12 00:14 UTC

**Comment by DaanSelen** [comment] 2024-10-11 21:46
Sorry to append to such an old issue, but can I also set this hostname-sync feature on as default?

**Comment by si458** [comment] 2024-10-11 22:21
@DaanSelen the hostname sync feature is set per group, so create a group then enable the feature, its not set globally
