### ISSUE TITLE
Error creating OSX Agent if the name of the mesh contains non-English letters

### ISSUE THREAD

**Issue by TitovLab** [Ylianst/MeshCentral#174] opened 2019-04-10 12:05 UTC
MeshCentral 0.3.2-b.
Error creating OSX Agent if the name of the mesh contains non-English letters: Internal Server Error

**Comment by Ylianst** [comment] 2019-04-25 07:28
Interesting bug. We will look into it.

**Comment by TitovLab** [comment] 2019-04-30 18:11
Bug details in mesherrors.txt:

-------- 4/30/2019, 9:08:33 PM ---- 0.3.3-k --------

TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Content-Disposition"]
    at ServerResponse.setHeader (_http_outgoing.js:473:3)
    at ServerResponse.header (/opt/meshcentral/node_modules/express/lib/response.js:767:10)
    at ServerResponse.header (/opt/meshcentral/node_modules/express/lib/response.js:770:12)
    at obj.handleMeshOsxAgentRequest (/opt/meshcentral/node_modules/meshcentral/webserver.js:2423:13)
    at Layer.handle [as handle_request] (/opt/meshcentral/node_modules/express/lib/router/layer.js:95:5)
    at next (/opt/meshcentral/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/opt/meshcentral/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/opt/meshcentral/node_modules/express/lib/router/layer.js:95:5)
    at /opt/meshcentral/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/opt/meshcentral/node_modules/express/lib/router/index.js:335:12)

**Comment by Ylianst** [comment] 2019-04-30 22:41
Thank you for the report. Just published MeshCentral v0.3.3-m with a fix for this. Please let me know if it works. Thanks.

**Comment by Ylianst** [comment] 2019-04-30 22:53
Note that I tried many different strings, but if there is a specific character that causes the problem, please let me know. Thanks.

**Comment by TitovLab** [comment] 2019-05-01 18:23
If the group name contains non-English letters, then the group name is no longer added to the zip file name and no error occurs. Is it correct behavior?

**Comment by Ylianst** [comment] 2019-05-09 21:05
So, I did a few fixes in the server but also added code to catch an invalid string exception and fallback to using the standard name, this way it would still work in this case. Anyway you can give me an example device group name that causes this issue? I will cut & paste into a new group and give it a try. Thanks.

**Comment by TitovLab** [comment] 2019-05-10 16:15
Example device group name: MeshAgent удивительный
Thanks.

**Comment by Ylianst** [comment] 2019-07-14 17:22
This has been fixed as I am closing the issue. The problem is that I can't put some names in the content-disposition HTTP header, so I fall back to not putting a name at all. If anyone has a solution for placing extended characters in a HTTP header, let me know.

**Closed by Ylianst** 2019-07-14 17:22 UTC
Labels: bug
