### ISSUE TITLE
Cannot read property 'DispatchMessage' of null

### ISSUE THREAD

**Issue by VM-2020** [Ylianst/MeshCentral#2008] opened 2020-11-21 13:49 UTC
Got the following server error log,..

 -------- 11/20/2020, 10:41:35 AM ---- 0.6.88 --------

TypeError: Cannot read property 'DispatchMessage' of null
    at performRelay (/var/www/html/mesh.mydomain.com/node_modules/meshcentral/meshdevicefile.js:205:47)
    at Object.module.exports.CreateMeshDeviceFile (/var/www/html/mesh.mydmain.com/node_modules/meshcentral/meshdevicefile.js:310:5)
    at handleDeviceFile (/var/www/html/mesh.mydomain.com/node_modules/meshcentral/webserver.js:2718:35)
    at Layer.handle [as handle_request] (/var/www/html/mesh.mydomain.com/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/www/html/mesh.mydomain.com/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/var/www/html/mesh.mydomain.com/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/var/www/html/mesh.mydomain.com/node_modules/express/lib/router/layer.js:95:5)
    at /var/www/html/mesh.mydomain.com/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/var/www/html/mesh.mydomain.com/node_modules/express/lib/router/index.js:335:12)
    at next (/var/www/html/mesh.mydomain.com/node_modules/express/lib/router/index.js:275:10)
    at /var/www/html/mesh.mydomain.com/node_modules/meshcentral/webserver.js:4840:24
    at Layer.handle [as handle_request] (/var/www/html/mesh.mydomain.com/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/www/html/mesh.mydomain.com/node_modules/express/lib/router/index.js:317:13)
    at /var/www/html/mesh.mydomain.com/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/www/html/mesh.mydomain.com/node_modules/express/lib/router/index.js:335:12)
    at next (/var/www/html/mesh.mydomain.com/node_modules/express/lib/router/index.js:275:10)

-------- 11/20/2020, 10:41:36 AM ---- 0.6.88 --------

_http_outgoing.js:526
    throw new ERR_HTTP_HEADERS_SENT('set');
    ^

Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:526:11)
    at ServerResponse.header (/var/www/html/mesh.mydomain.com/node_modules/express/lib/response.js:771:10)
    at ServerResponse.header (/var/www/html/mesh.mydomain.com/node_modules/express/lib/response.js:774:12)
    at setContentDispositionHeader (/var/www/html/mesh.mydomain.com/node_modules/meshcentral/meshdevicefile.js:305:17)
    at WebSocket.<anonymous> (/var/www/html/mesh.mydomain.com/node_modules/meshcentral/meshdevicefile.js:221:29)
    at WebSocket.emit (events.js:314:20)
    at Receiver.receiverOnMessage (/var/www/html/mesh.mydomain.com/node_modules/express-ws/node_modules/ws/lib/websocket.js:720:20)
    at Receiver.emit (events.js:314:20)
    at Receiver.dataMessage (/var/www/html/mesh.mydomain.com/node_modules/express-ws/node_modules/ws/lib/receiver.js:414:14)
    at Receiver.getData (/var/www/html/mesh.mydomain.com/node_modules/express-ws/node_modules/ws/lib/receiver.js:346:17)
    at Receiver.startLoop (/var/www/html/mesh.mydomain.com/node_modules/express-ws/node_modules/ws/lib/receiver.js:133:22)
    at Receiver._write (/var/www/html/mesh.mydomain.com/node_modules/express-ws/node_modules/ws/lib/receiver.js:69:10)
    at doWrite (_stream_writable.js:403:12)
    at writeOrBuffer (_stream_writable.js:387:5)
    at Receiver.Writable.write (_stream_writable.js:318:11)
    at TLSSocket.socketOnData (/var/www/html/mesh.mydomain.com/node_modules/express-ws/node_modules/ws/lib/websocket.js:795:35) {
  code: 'ERR_HTTP_HEADERS_SENT'
}

**Comment by Ylianst** [comment] 2020-11-21 18:59
Duplicate of #1986. This should have been fixed.

**Comment by VM-2020** [comment] 2020-11-22 14:47
Did search the issue tracker but couldn't find any related issues directly - its fixed we've updated to version 0.6.98

Downloading files - especially larger ones is working ok now, thanks..

**Closed** 2020-11-22 20:08 UTC
Labels: Fixed - Confirm & Close, duplicate
