### ISSUE TITLE
Fedora 34 - XWayland?

### ISSUE THREAD

**Issue by FATeknollogee** [Ylianst/MeshCentral#2998] opened 2021-08-06 21:12 UTC
![Desktop-wgahqxfinance-002-2021-08-06-14-11](https://user-images.githubusercontent.com/47568278/128571572-f025fca4-c45b-42f5-88e6-be2174bb01e6.png)

Any workarounds to the Wayland issue?

**Comment by FATeknollogee** [comment] 2021-08-06 21:14
![Screenshot from 2021-08-06 14-13-27](https://user-images.githubusercontent.com/47568278/128571690-263cd329-f135-4dfe-ae00-8ef520486e19.png)
attached pic.

**Comment by krayon007** [comment] 2021-08-06 22:48
You mean like this?
1. Open /etc/gdm/custom.conf or /etc/gdm3/custom.conf
2. Uncomment: WaylandEnable=false.
3. Add the following line to the [daemon] section: DefaultSession=gnome-xorg.desktop

It's not possible right now to get remote desktop to work with Wayland.

**Comment by si458** [comment] 2024-02-29 23:13
duplicate of #2719

**Closed** 2024-02-29 23:14 UTC
Labels: question
