### ISSUE TITLE
Version 0.9.46

### ISSUE THREAD

**Issue by lexisman** [Ylianst/MeshCentral#3262] opened 2021-11-08 16:56 UTC
I just updated the server to 0.9.46, which is the current version, it connects to the desktop of windows and ubuntu, but the mouse cursor is not showing up, basically the desktop can not be controlled.

**Comment by Ylianst** [comment] 2021-11-08 17:45
Putting "Version 0.9.46" is not a proper title for a bug report. I will close this.

For remote input, make sure the input check box is checked. Also, in the future, you should specify if the problem is only the mouse or mouse and keyboard.

![image](https://user-images.githubusercontent.com/1319013/140791779-5311b2bf-1fe2-4c99-878a-2791d011db8f.png)

**Closed by Ylianst** 2021-11-08 17:45 UTC
