### ISSUE TITLE
OSX Mojave MeshAgent Black Screen

### ISSUE THREAD

**Issue by fazakis** [Ylianst/MeshCentral#249] opened 2019-05-28 11:18 UTC
On OSX Mojave after installing MeshAgent i can not do remote desktop session. It seems to connect but the screen stays black.
![image](https://user-images.githubusercontent.com/3018314/58474104-f6d58300-8152-11e9-9fc3-2ff3c5eb1bff.png)

Further investigation reveals the following:
1. I can still push the open web browser button and will open a browser on remote machine if i'm logged in on the remote host
2. On an other Mojave remote machine i first open TeamViewer login on a mojave local user and then if i press Desktop->Connect on MeshCentral it starts to show the Mojave Remote Desktop.

Other details:
=> version: meshcentral@0.3.5-h
=> Accessibility permission is checked for meshagent_osx64 in Privacy settings menu of OSX
=> Console output:
![image](https://user-images.githubusercontent.com/3018314/58474625-6304b680-8154-11e9-980f-bdd3468127d4.png)

**Comment by krayon007** [comment] 2019-05-28 15:29
Mojave introduced some bee security features. When you connect KVM for the first time. Mojave pops a security dialog box saying that MeshCentral is requesting remote control access. You'll then have to modify the security settings on Mojave, and then reconnect KVM, and it should work normally.

**Comment by fazakis** [comment] 2019-05-28 15:42
@krayon007 Thanks for your response as i have stated this option is checked
![image](https://user-images.githubusercontent.com/3018314/58491797-52fece00-8178-11e9-9a2a-546e6d959aa8.png)

**Comment by krayon007** [comment] 2019-05-28 15:58
What version of Mojave are you running? (My machine is 10.14.3)

**Comment by fazakis** [comment] 2019-05-28 16:04
@krayon007 i have to mojave hosts one on 10.14.2 and one on 10.14.5

**Comment by fazakis** [comment] 2019-05-28 16:45
@krayon007 As i said mentioned on the first post and after further testing i can make it more clear:
1. on mojave 10.14.5 if the mojave is logged in (unlocked with screen active) it is possible to connect the remote desktop and control it fine
2. on mojave 10.14.2 even even when unlocked it keeps showing black screen
Thanks

**Comment by fazakis** [comment] 2019-05-30 18:28
@krayon007 i would like to ask if this issue is planned to get a fix or will be left as future request to deal with...?

**Comment by krayon007** [comment] 2019-05-30 18:40
I'll take a look at it after we release the user-consent agent update, which should be very soon.

**Comment by hunter-nl** [comment] 2019-06-07 07:21
I've a similar issue. I've two monitors. When primary monitor has the focus, then it is working. If second monitor has the focus, I get only a black screen.
And how can I switch between the two monitors? I do not see any option in MeshCentral to switch.

**Comment by barart** [comment] 2022-06-22 01:34
I have the same issue, is any way to "wake-up" the screen remotely? or prevent it the display-sleep? Im using this on multiple headless mac-mini's so im unable to control them and/or wake-up the display them as they dont have keyboard/mouse and display..

**Comment by krayon007** [comment] 2022-06-22 04:02
I'll start by doing some research to see if I can find a way to remotely wake the system.

**Comment by silversword411** [comment] 2022-06-23 00:14
> That part I noticed a while ago. The API I use for input injection don't wake the screen, and also dont seem to trigger the hover event on the dock.

Interesting...I wonder how many APIethods there are...

**Comment by barart** [comment] 2022-07-26 19:34
Does we have a update on this?

**Comment by barart** [comment] 2022-11-15 19:21
Again.. asking for update on this so this bug dont lose interest

**Comment by krayon007** [comment] 2022-11-15 19:41
How many monitors are on your system?

**Comment by barart** [comment] 2022-11-15 22:40
> How many monitors are on your system?

I have 4 systems, one M1 with two monitors, other M1 with one monitor, one i5 with one monitor and one old macpro xeon with one monitor too, all of them present the same problem

**Comment by barart** [comment] 2023-01-04 18:01
Bumping this again

**Comment by whlsxl** [comment] 2023-05-31 14:09
Same here

**Comment by barart** [comment] 2023-08-18 19:26
The problem is not sleeping, i have my macs to prevent sleeping also to prevent turn off the display and the problem persist, if i attach a monitor to the mac, it shows the login screen always and i can login, but meshcentral still seeing the blackscreen until i login directly on the mac, if i "lock" the mac, meshcentral is able to see the login screen and im able to login, but after few minutes meshcentral only shows the blackscreen and im unable to do anything (only login to terminal) the use of caffeinate dont do anything because the mac is actually waked-up, the problem is something else

**Comment by barart** [comment] 2023-10-07 18:03
Bumping again

**Comment by si458** [comment] 2023-10-07 18:40
> Bumping again

Please don't bump, 

Sadly I don't have a mac so I cannot have a look at it,
and @Ylianst works on it too from time to time, and I'm not sure if he has a Mac either?
If anybody has mac hardware we can connect into or donate, please email me and ill have a look at it

**Comment by dinger1986** [comment] 2023-11-12 16:50
fix was merged @si458 https://github.com/Ylianst/MeshAgent/pull/181

**Comment by barart** [comment] 2024-01-12 01:34
> fix was merged @si458 [Ylianst/MeshAgent#181](https://github.com/Ylianst/MeshAgent/pull/181)

I have not been able to test it because the fix hast not been pushed yet, however, the fix is about permissions or validate permissions on start, but this is not the case... permissions are there actually, but, the problem is that if nobody is using the mac for xxx time, there is no way to "see" the screen or "send" any commands from the meshcentral desktop, client is connected and you can connect to Desktop but only to see a black screen, but you can use files and terminal without any problem, however if you "move" the mouse that is physically connected to the mac and then you "re-connect" or "connect" to the desktop on meshcentral you can see the screen again and use it from meshcentral

I can confirm that this is not any type or sleep or suspend, the mac itself is actually "awaken" showing the screensaver on the attached display, my guess is some kind of protection to prevent remote access if nobody use it in xxx time? BUT there is a BUT and my "workaround"... TeamViewer is not affected by this: I have installed teamviewer on the macs, so, when i want to connect to them from meshcentral and it shows the blackscreen, i connect to it from TeamViewer, and do anything (open a folder for example) then connect it from meshcentral and i can see the desktop and use it again,

Another workaround is to reboot it from meshcentral, and as soon as it connect it to mescentral again, connect to it and login a soon as possible and i can use it from meshcentral, this not work always, it only gives some secs to "activate" the protection¿? idk

**Comment by si458** [comment] 2024-01-12 07:56
Sadly I only have an old 2012 macbook pro, so I can't get it to compile the source code for the agent correctly as the os is too old...

Anybody willing to donate access/post me a new M1 or above series device , I can look at getting the agent to compiled for you

**Comment by si458** [comment] 2024-01-15 17:58
with an M mac, i can compile the code for arm64 but also run Mac x64 as VM and compile mac on there!
hense the need for an M mac really as they are better, but prices are ridiculous!
but once i have a new(ish) mac of some form, i can compile the binarys for the agent and do more testing!
as explained above the PR was merged by @Ylianst into the repo to hopefully fix issues, but we cant compile the mac agents anymore without a mac

**Comment by AymanAnsari** [comment] 2024-02-06 15:58
Hey Guys, Any Update on the Mesh Blank screen issue?

**Comment by si458** [comment] 2024-03-12 19:46
@AymanAnsari what was your issue you was having with the black screen?
is it when the mac goes to sleep/lock screen, it then connects but its a blackscreen?

**Comment by AymanAnsari** [comment] 2024-03-13 03:48
@si458 It was showing blank screen when we restart the mac and also it's only happening when we are at login page. If we are logged in to an account. It will start showing the screen on Mesh.

**Comment by si458** [comment] 2024-03-13 07:52
@AymanAnsari ah right ok!
I haven't fixed the on startup login screen yet
However I think I've fixed the mac going to sleep/locking device then it showing the login prompt!
You need to run `caffeinate -u -d 2` when the screens blank, this wakes the screen up and allows u to see the login page!
But again that doesn't fix the login screen on startup, still looking into that

**Comment by AymanAnsari** [comment] 2024-03-13 08:00
@si458 Thanks! Please keep me posted when you get this issue solution.
Appreciate your help.

**Closed** 2024-03-15 12:13 UTC
Labels: bug
