### ISSUE TITLE
Clipboard broken

### ISSUE THREAD

**Issue by amenolo** [Ylianst/MeshCentral#1219] opened 2020-04-22 18:42 UTC
Both get and set clipboard actions seem to be out of order.

Anyhow dialog window still returns `Success` notice when `set` button pushed and on the other hand it doesn't display clipboard content when `get` button pushed (in this case console returns `uncaughtException1: promise.unhandledRejection: Error reading clipboard` error).

Tested with Windows and Linux agents.

**MC v0.5.12**

Thanks

**Comment by Ylianst** [comment] 2020-04-22 18:49
Your right, I can confirm this.

**Comment by Ylianst** [comment] 2020-04-22 19:01
FYI, I get the following in the agent console when trying to read the remote clipboard:

`uncaughtException1: promise.unhandledRejection: Error reading clipboard`

**Comment by Ylianst** [comment] 2020-04-23 00:03
FYI. Bryan found the issue and working on it.

**Comment by krayon007** [comment] 2020-04-23 16:25
I fixed the windows clipboard issue. The linux clipboard, actually still works. It is just a little different to get used to, becuase linux has multiple different "clipboards" that don't play nice with each other... MC uses the X11 Selection Buffer, because the agent normally runs as a non-user service, so access to user desktop data was done using X11. Some apps, like the terminal, typically don't use the X11 buffers for clipboard.

**Comment by krayon007** [comment] 2020-04-23 16:26
But I found if you use the middle mouse button in the terminal, you can paste the contents of the data MC places in the X11 buffer.

**Comment by Ylianst** [comment] 2020-04-23 19:26
MeshCentral v0.5.13 is out, should fix this.

**Comment by amenolo** [comment] 2020-04-23 19:40
Juste tested, I can confirm! 👍

**Comment by Ylianst** [comment] 2020-04-23 20:58
Thanks for the report and for the initial issue. Closing this one.

**Closed by Ylianst** 2020-04-23 20:58 UTC
Labels: Fixed - Confirm & Close, bug
