### ISSUE TITLE
UAC Prompt under RDP Disconnect

### ISSUE THREAD

**Issue by ryanblenis** [Ylianst/MeshCentral#1130] opened 2020-04-08 18:58 UTC
Scenario:
Computer A: Users computer (via console session) (Win 10x64 1909 tested)
Computer B: Users computer (RDP session from Computer A) (Win10x64 1909 tested)

In MeshCentral, if you connect to Computer B and select the RDP session to Remote Desktop into, if they are an unprivileged user and you require privilege elevation for a program (test in my case was opening the LAN1 network adapter to edit properties), the resulting UAC prompt disconnects the MeshCentral user from the interface and back to the login screen.

Note: I did not attempt to reconnect directly to Computer B to see if multiple sessions were available for the administrator, or if reconnecting would simply allow me to view the UAC prompt. I happened to have an agent natively on Computer A, so I just connected from there and continued working on Computer B via Computer A's already established RDP session.

**Comment by krayon007** [comment] 2020-04-08 22:25
Interesting. I did some testing, and can see what you'r seeing, however, I'm at a complete loss to figure out how to fix it...

For example, I found that if I minimize my RDP client, then I cannot scrape the RDP session, until the RDP client is visible. Once it's visible, I am able to scrape the session.  Likewise, when the UAC is visible in the RDP session, I am also unable to scrape the RDP session. I tried enumerating all the sessions on the machine while the UAC prompt is visible... I can't tell if the UAC prompt is on the TSID of the RDP client, but I no longer have permission to access the graphics object, or if the UAC is done by the RDP client itself with an out-of-band (to the UI) mechanism... But in any case, when the UAC is displayed in the RDP client, I'm unable to figure out how to access that UX.

**Comment by hellofaduck** [comment] 2020-05-12 14:50
Any progress on this problem?  This bug now(when all users on vpn-rdp) is critical in our environment, our tech support cant do they work, they cant do anything under admin credentials ((

**Comment by dnutan** [comment] 2020-05-12 21:13
Don't know if this can be of help:
[UAC settings when remote controlling Windows clients to prevent screen freezing](https://www.theexperienceblog.com/2014/04/13/uac-settings-when-remote-controlling-windows-clients-to-prevent-screen-freezing/)
>User Account Control: Switch to the secure desktop when prompting for elevation policy = Disabled
User Account Control: Allow UIAccess application to prompt for elevation without using the secure desktop policy = Enabled

More on the same:
[Remote Assistance and UAC prompts](https://docs.microsoft.com/en-us/archive/blogs/asklar/remote-assistance-and-uac-prompts)
[How to get access to UAC prompt when running remote desktop application?](https://stackoverflow.com/questions/18826248/how-to-get-access-to-uac-prompt-when-running-remote-desktop-application)
[Windows 10 – Disable UAC for Remote Assistance/Google Remote Desktop/QuickAssist](https://eddiejackson.net/wp/?p=16923)

How other software handle this (from a user's point of view):
[Is TeamViewer UAC compatible?](https://community.teamviewer.com/t5/Knowledge-Base/Is-TeamViewer-UAC-compatible/ta-p/4574#U4574)

**Comment by hellofaduck** [comment] 2020-05-13 07:56
Oh my God, you are my lifesaver today!! This settings works! Without secure desktop UAC promt works fine without any problem. I am jumping around my desk :)

**Comment by JSuenram** [comment] 2022-03-03 10:04
As this issue is only solved by "workaround" and the Agent is still not able to elevate when user has started it in Temp/Non-Admin-Mode this should be marked as duplicate of #1885

**Comment by si458** [comment] 2024-02-23 10:25
closing as duplicate

**Closed by si458** 2024-02-23 10:25 UTC
